"resource/BaseActionCDTrackStartDialog.res"
{
"DialogFrame"
{
"ItemNameLabel"
{
"ControlName""CExLabel"
"fieldName""ItemNameLabel"
"font""HudFontSmall"
"labelText""%itemname%"
"textAlignment""west"
"ypos""17"
"wide""230"
"tall""15"
////"autoResize""0"
"skip_autoresize""1"
//"pinCorner""0"
//"visible""1"
////"enabled""1"
"wrap""1"
}
}
}