
#base "base/filesv1/notifipresentpanel/main.res"
#base "base/filesv1/notifipresentpanel/content1.res"
#base "base/filesv1/sheet/main.res"
#base "base/filesv2/bgfooter/main.res"
#base "base/filesv2/bgfooter/zpos_1.res"
#base "base/filesv2/bgheader/main.res"
#base "base/filesv2/bgheader/tall_120.res"
	#base "base/filesv2/footerline/main.res"
	#base "base/filesv2/footerline/xpos0.res"
	#base "base/filesv2/footerline/ypos420.res"
	#base "base/filesv2/footerline/zpos2.res"

	#base "base/filesv1/backbutton/main.res"
	#base "base/filesv1/backbutton/c-295.res"
	#base "base/filesv1/backbutton/def1.res"
	#base "base/filesv1/backbutton/content1.res"
	#base "base/filesv1/backbutton/ypos437.res"
	#base "base/filesv1/backbutton/zpos2.res"
	#base "base/filesv1/backbutton/pin3.res"