#base "base/filesv1/armory_panel/main.res"
#base "base/filesv4-class/scout/main.res"
#base "base/filesv4-class/scout/sound.res"
#base "base/filesv4-class/scout/extra/tab0.res"
#base "base/filesv4-class/scout/extra/pin2.res"
#base "base/filesv4-class/scout/extra/south-west.res"
#base "base/filesv4-class/scout/extra/def0.res"
#base "base/filesv4-class/scout/extra/scale1.res"
#base "base/filesv2/classlabel/main.res"
#base "base/filesv2/classlabel/font/hudfontsmallbold.res"
#base "base/filesv2/classlabel/text/north.res"
#base "base/filesv2/classlabel/zpos1.res"

#base "base/filesv1/backpack_panel/main.res"
#base "base/filesv1/class_loadout_panel/main.res"

#base "base/filesv2/showexplanationbtn/main.res"
#base "base/filesv2/showexplanationbtn/def0.res"
#base "base/filesv2/showexplanationbtn/hudfontsmallbold.res"
#base "base/filesv2/showexplanationbtn/zpos100.res"
#base "base/filesv2/showexplanationbtn/wt20.res"