#base "base/filesv2/topline/main.res"
#base "base/filesv2/topline/content1.res"
#base "base/filesv2/caratlabel/main.res"
#base "base/filesv2/caratlabel/wide20.res"
#base "base/filesv2/caratlabel/auto1.res"
#base "base/filesv2/caratlabel/zpos1.res"
#base "base/filesv2/caratlabel/xpos_c.res"
#base "base/filesv2/caratlabel/ypos20.res"
#base "base/filesv2/caratlabel/vis1.res"
#base "base/filesv2/caratlabel/fgcolor_200.res"
#base "base/filesv2/caratlabel/font/hudfontsmallest.res"


#base "base/filesv2/classlabel/main.res"
#base "base/filesv2/classlabel/cex.res"
#base "base/filesv2/classlabel/font/mediumbold.res"
#base "base/filesv2/classlabel/text/west.res"
#base "base/filesv2/classlabel/zpos1.res"
#base "base/filesv2/classlabel/tall25.res"
#base "base/filesv2/classlabel/content1.res"
#base "base/filesv2/classlabel/vis1.res"

#base "../../#uni_base/filesv1/closebutton/main.res"
#base "../../#uni_base/filesv1/closebutton/vis1.res"
#base "../../#uni_base/filesv1/closebutton/text/center.res"
#base "../../#uni_base/filesv1/closebutton/enabled.res"
#base "../../#uni_base/filesv1/closebutton/ctrl/cex.res"
#base "../../#uni_base/filesv1/closebutton/auto.res"
#base "../../#uni_base/filesv1/closebutton/dull0.res"
#base "../../#uni_base/filesv1/closebutton/bright0.res"
#base "../../#uni_base/filesv1/closebutton/def1.res"
#base "../../#uni_base/filesv1/closebutton/cmd/vguicancel.res"