#base "../../#uni_base/filesv1/background/bg_main.res"
#base "../../#uni_base/filesv1/background/bg_vis1.res"
#base "../../#uni_base/filesv1/background/bg_enabled.res"
#base "../../#uni_base/filesv1/background/controlname/editable.res"
#base "../../#uni_base/filesv1/background/bg_auto.res"
#base "../../#uni_base/filesv1/background/bg_paintbg_2.res"