#base "base/filesv1/goallabel/main.res"
#base "base/filesv1/goallabel/is-label.res"
#base "base/filesv1/goallabel/zpos1.res"
#base "base/filesv1/goallabel/label-null.res"
#base "base/filesv1/goallabel/hudfontsmall.res"
#base "base/image/goalimage.res"
#base "base/image/hudtrainingmsg.res"