#base "base/filesv2/loadout_preset_panel/main.res"
#base "base/filesv2/loadout_preset_panel/main2.res"
#base "base/filesv2/topline/main.res"
#base "base/filesv2/caratlabel/main.res"
#base "base/filesv2/caratlabel/wide20.res"
#base "base/filesv2/caratlabel/auto1.res"
#base "base/filesv2/caratlabel/zpos1.res"
#base "base/filesv2/caratlabel/vis1.res"
#base "base/filesv2/caratlabel/fgcolor_200.res"
#base "base/filesv2/caratlabel/font/hudfontsmallest.res"


#base "base/filesv2/classlabel/main.res"
#base "base/filesv2/classlabel/cex.res"
#base "base/filesv2/classlabel/text/west.res"
#base "base/filesv2/classlabel/zpos1.res"
#base "base/filesv2/classlabel/tall15.res"
#base "base/filesv2/classlabel/vis1.res"
#base "base/filesv2/classlabel/label/equiped.res"