	#base "base/filesv5-exist/mainmenu.res"
//	#base "base/filesv1/rankpanel/main.res"
//	#base "base/filesv1/rankpanel/cpvp.res"
//	#base "base/filesv1/rankpanel/show_model0.res"
//	#base "base/filesv1/rankpanel/matchgroup_12.res"
