	#base "base/filesv5-exist/mainmenu.res"


	#base "base/filesv2/footerline/main.res"
	#base "base/filesv2/footerline/xpos0.res"
	#base "base/filesv2/footerline/ypos420.res"
	#base "base/filesv2/bgfooter/main.res"
	#base "base/filesv1/itemrename/mouseoveritem.res"
	#base "base/filesv1/ranktooltip/main.res"
//	#base "base/filesv1/rankpanel/main.res"
//	#base "base/filesv1/rankpanel/cpvp.res"
//	#base "base/filesv1/rankpanel/show_model0.res"
//	#base "base/filesv1/rankpanel/matchgroup_12.res"
	#base "base/filesv2/rankmodelpanel/main.res"
	#base "../../#uni_base/filesv1/background/bg_main.res"
	#base "../../#uni_base/filesv1/background/bg_vis0.res"
	#base "../../#uni_base/filesv1/background/bg_enabled.res"
	#base "../../#uni_base/filesv1/background/bg_scale.res"
	#base "../../#uni_base/filesv1/background/position/y_0.res"
	#base "../../#uni_base/filesv1/background/controlname/scalable.res"
	#base "base/filesv2/tooltippanel/main.res"
	#base "base/filesv2/tooltippanel/ctrl.res"
	#base "base/filesv2/tooltippanel/border.res"
	#base "base/filesv2/tooltippanel/position/ypos0.res"
	#base "base/filesv2/tooltippanel/position/zpos10k.res"
	#base "base/filesv2/tooltippanel/position/tall50.res"
	#base "base/filesv2/tooltippanel/position/wide150.res"

	#base "base/filesv2/tooltippanel/tiplabel/main.res"
	#base "base/filesv2/tooltippanel/tiplabel/fgcolor.res"
	#base "base/filesv2/tooltippanel/tiplabel/position/fontbold.res"
	#base "base/filesv2/tooltippanel/tiplabel/position/xpos20.res"
	#base "base/filesv2/tooltippanel/tiplabel/position/ypos5.res"
	#base "base/filesv2/tooltippanel/tiplabel/position/wide140.res"
	#base "base/filesv2/tooltippanel/tiplabel/position/tall30.res"
	#base "base/filesv2/tooltippanel/tiplabel/text/center.res"
	#base "base/filesv2/tooltippanel/tiplabel/text/auto_wide.res"