#base "base/filesv2/tooltippanel/main.res"
#base "base/filesv2/tooltippanel/border.res"
#base "base/filesv2/tooltippanel/position/ypos0.res"
#base "base/filesv2/tooltippanel/position/tall100.res"
#base "base/filesv2/tooltippanel/position/wide300.res"

#base "base/filesv2/tooltippanel/tiplabel/main.res"
#base "base/filesv2/tooltippanel/tiplabel/fgcolor.res"
#base "base/filesv2/tooltippanel/tiplabel/position/xpos10.res"
#base "base/filesv2/tooltippanel/tiplabel/position/ypos10.res"
#base "base/filesv2/tooltippanel/tiplabel/position/wide140.res"
#base "base/filesv2/tooltippanel/tiplabel/position/tall30.res"
#base "base/filesv2/tooltippanel/tiplabel/text/center.res"
#base "base/filesv2/tooltippanel/tiplabel/text/auto_wide.res"
#base "base/filesv2/tooltippanel/tiplabel/text/wrap1.res"