#base "res_base/selectplayer/statpanel2.res"
#base "res_base/selectplayer/content_a.res"
#base "res_base/selectplayer/cancelbtn/content_a.res"
#base "base/filesv1/playerlistscroller/main.res"
#base "base/filesv1/playerlistscroller/yp_80.res"