#base "../../#uni_base/filesv1/image/main.res"
#base "../../#uni_base/filesv1/image/main_vis1.res"
#base "../../#uni_base/filesv1/desc/main.res"

#base "../../#uni_base/filesv1/background/bg_main.res"
#base "../../#uni_base/filesv1/background/bg_vis1.res"
#base "../../#uni_base/filesv1/background/bg_enabled.res"
#base "../../#uni_base/filesv1/background/position/x_0.res"
#base "../../#uni_base/filesv1/background/position/y_0.res"
#base "../../#uni_base/filesv1/background/position/z_0.res"
#base "../../#uni_base/filesv1/background/bg_paintbgtype_0.res"
#base "../../#uni_base/filesv1/background/controlname/panel.res"