#base "base/filesv2/topline/main.res"
#base "base/filesv2/topline/content1.res"

#base "../../#uni_base/filesv1/okbutton/ctrl/cex.res"
#base "../../#uni_base/filesv1/okbutton/main.res"
#base "../../#uni_base/filesv1/okbutton/position/wide100.res"
#base "../../#uni_base/filesv1/okbutton/position/tall25.res"
#base "../../#uni_base/filesv1/okbutton/auto.res"
#base "../../#uni_base/filesv1/okbutton/vis1.res"
#base "../../#uni_base/filesv1/okbutton/enabled.res"
#base "../../#uni_base/filesv1/okbutton/tab0.res"
#base "../../#uni_base/filesv1/okbutton/cmd/ok.res"
#base "../../#uni_base/filesv1/okbutton/label/gameui_ok.res"
#base "../../#uni_base/filesv1/okbutton/text/center.res"
#base "../../#uni_base/filesv1/okbutton/def1.res"
#base "../../#uni_base/filesv1/okbutton/dull0.res"
#base "../../#uni_base/filesv1/okbutton/bright0.res"
#base "../../#uni_base/filesv1/okbutton/sound.res"


#base "../../#uni_base/filesv1/titlelabel/controlname/label.res"
#base "../../#uni_base/filesv1/titlelabel/main.res"
#base "../../#uni_base/filesv1/titlelabel/wrap0.res"
#base "../../#uni_base/filesv1/titlelabel/text/center.res"
#base "../../#uni_base/filesv1/titlelabel/text/centerwrap.res"
#base "../../#uni_base/filesv1/titlelabel/auto.res"
#base "../../#uni_base/filesv1/titlelabel/pin.res"
#base "../../#uni_base/filesv1/titlelabel/vis1.res"
#base "../../#uni_base/filesv1/titlelabel/enabled.res"