#base "base/filesv1/progressbar/main.res"
#base "base/filesv1/progressbar/more/scalable.res"

#base "../../#uni_base/filesv1/background/bg_main.res"
#base "../../#uni_base/filesv1/background/bg_vis1.res"
#base "../../#uni_base/filesv1/background/bg_enabled.res"
#base "../../#uni_base/filesv1/background/bg_auto.res"
#base "../../#uni_base/filesv1/background/bg_pincorner.res"
#base "../../#uni_base/filesv1/background/draw/content1.res"
#base "../../#uni_base/filesv1/background/controlname/scalable.res"