"Resource/EngineVGuiLayout.res"
{
"Advanced"
{
"ControlName""Button"
"fieldName""Advanced"
"tall""24"
//"autoResize""0"
//"pinCorner""0"
"visible""1"
////"enabled""1"
"tabPosition""5"
"textAlignment""west"
//"dulltext""0"
//"brighttext""0"
"Command""Advanced"
"Default""0"
}}