"Resource/obj_dispenser.res"
{
"MuteButton"
{
"ControlName""Button"
"fieldName""MuteButton"
//"autoResize""0"
"pinCorner""2"
"visible""1"
////"enabled""1"
"tabPosition""3"
"labelText""#GameUI_MuteIngameVoice"
"textAlignment""west"
//"dulltext""0"
//"brighttext""0"
"Command""Mute"
"Default""1"
}}