"resource/ui/hudplayerclass.res"
{
"NewNumberLabel"
{
"ControlName""CExLabel"
"fieldName""NumberLabel"
//"font""Default"
"fgcolor""Black"
"xpos""15"
"ypos""90"
//"zpos""0"
"wide""15"
"tall""15"
////"autoResize""0"
//"pinCorner""0"
"visible""0"
"textAlignment""Center"
"dulltext""1"
"brighttext""0"
}
}