"resource/ui/hudplayerclass.res"
{
"ItemNameLabel"
{
"ControlName""CExLabel"
"fieldName""ItemNameLabel"
//"font""Default"
"zpos""1"
////"autoResize""0"
//"pinCorner""0"
////"enabled""1"
//"dulltext""0"
"brighttext""0"
}
}