#base "base/filesv2/explanationlabel/main.res"
#base "base/filesv2/explanationlabel/font/hudfontsmall.res"
#base "base/filesv2/explanationlabel/text/north.res"
#base "base/filesv2/explanationlabel/vis1.res"
#base "base/filesv2/explanationlabel/auto0.res"
#base "base/filesv2/explanationlabel/pin0.res"
#base "base/filesv2/explanationlabel/wrap.res"
#base "base/filesv2/explanationlabel/position/xpos20.res"
#base "base/filesv2/explanationlabel/position/ypos35.res"
#base "base/filesv2/explanationlabel/position/wide290.res"
#base "base/filesv2/explanationlabel/position/tall85.res"

#base "../../#uni_base/filesv1/closebutton/main.res"
#base "../../#uni_base/filesv1/closebutton/vis1.res"
#base "../../#uni_base/filesv1/closebutton/text/center.res"
#base "../../#uni_base/filesv1/closebutton/enabled.res"
#base "../../#uni_base/filesv1/closebutton/ctrl/cex.res"
#base "../../#uni_base/filesv1/closebutton/position/wide100.res"
#base "../../#uni_base/filesv1/closebutton/position/tall25.res"
#base "../../#uni_base/filesv1/closebutton/auto.res"
#base "../../#uni_base/filesv1/closebutton/pin3.res"
#base "../../#uni_base/filesv1/closebutton/dull0.res"
#base "../../#uni_base/filesv1/closebutton/bright0.res"
#base "../../#uni_base/filesv1/closebutton/def1.res"
#base "../../#uni_base/filesv1/closebutton/zpos1.res"
#base "../../#uni_base/filesv1/closebutton/sound.res"

#base "../../#uni_base/filesv1/closebutton/label/gameui_ok.res"
#base "../../#uni_base/filesv1/closebutton/cmd/close.res"

#base "../../#uni_base/filesv1/titlelabel/controlname/label.res"
#base "../../#uni_base/filesv1/titlelabel/main.res"
#base "../../#uni_base/filesv1/titlelabel/auto.res"
#base "../../#uni_base/filesv1/titlelabel/pin.res"
#base "../../#uni_base/filesv1/titlelabel/vis1.res"
#base "../../#uni_base/filesv1/titlelabel/enabled.res"
#base "../../#uni_base/filesv1/titlelabel/text/north.res"
#base "../../#uni_base/filesv1/titlelabel/text/wrap0.res"