#base "base/filesv2/loadout_preset_panel/main.res"
#base "base/filesv2/loadout_preset_panel/main2.res"
#base "base/filesv2/topline/main.res"
#base "base/filesv2/topline/content1.res"
//#base "base/filesv1/itemrename/mouseoveritem.res"

#base "base/filesv2/caratlabel/main.res"
#base "base/filesv2/caratlabel/wide20.res"
#base "base/filesv2/caratlabel/auto1.res"
#base "base/filesv2/caratlabel/zpos1.res"
#base "base/filesv2/caratlabel/xpos_c.res"
#base "base/filesv2/caratlabel/ypos20.res"
#base "base/filesv2/caratlabel/vis1.res"
#base "base/filesv2/caratlabel/fgcolor_200.res"
#base "base/filesv2/caratlabel/font/hudfontsmallest.res"

#base "base/filesv2/classlabel/main.res"
#base "base/filesv2/classlabel/cex.res"
#base "base/filesv2/classlabel/font/mediumbold.res"
#base "base/filesv2/classlabel/text/west.res"
#base "base/filesv2/classlabel/zpos1.res"
#base "base/filesv2/classlabel/tall25.res"
#base "base/filesv2/classlabel/content1.res"
#base "base/filesv2/classlabel/vis1.res"
#base "base/filesv2/classlabel/label/equiped.res"

#base "base/filesv1/class_loadout_panel/main.res"

	#base "base/filesv2/classmodelpanel/main.res"
	#base "base/filesv2/classmodelpanel/position/vis1.res"
	#base "base/filesv2/classmodelpanel/enabled.res"
	#base "base/filesv2/classmodelpanel/position/auto0.res"
	#base "base/filesv2/classmodelpanel/position/pin0.res"	
	#base "base/filesv2/classmodelpanel/position/render0.res"	
	#base "base/filesv2/classmodelpanel/position/allow_rot.res"
	#base "base/filesv2/classmodelpanel/model/main.res"
