#base "base/filesv1/desclabel/main.res"
#base "base/filesv1/desclabel/content1.res"
#base "base/filesv1/desclabel/ext/vis1.res"
#base "base/filesv1/desclabel/ext/enabled1.res"
#base "base/filesv1/desclabel/ext/auto1.res"
#base "base/filesv1/desclabel/ext/pin0.res"

#base "../../#uni_base/filesv1/titlelabel/controlname/cex.res"
#base "../../#uni_base/filesv1/titlelabel/main.res"
#base "../../#uni_base/filesv1/titlelabel/auto.res"
#base "../../#uni_base/filesv1/titlelabel/pin.res"
#base "../../#uni_base/filesv1/titlelabel/vis1.res"
#base "../../#uni_base/filesv1/titlelabel/enabled.res"
#base "../../#uni_base/filesv1/titlelabel/text/north.res"