#base "res_base/hudmenutauntselection.res"
// #base "base/build-more/numberbg/main.res"
#base "base/build-more/cancellabel/main.res"
#base "base/build-more/cancellabel/ctrl/cex.res"
#base "base/build-more/cancellabel/autopin0.res"
#base "base/build-more/cancellabel/dullbright.res"
#base "base/build-more/cancellabel/visenabled1.res"
#base "base/build-more/cancellabel/position/zpos2.res"
#base "base/build-more/cancellabel/position/tall13.res"
#base "base/build-more/cancellabel/font/def.res"
#base "base/build-more/cancellabel/text/east.res"