#base "base/filesv2/playerstatushealthimage/main.res"
#base "base/filesv2/playerstatushealthimage/zpos4.res"
#base "base/filesv2/playerstatushealthimage/xypos_6.res"
#base "base/filesv2/playerstatushealthimage/wt20.res"

#base "base/filesv2/playerstatushealthimage/bg/main.res"
#base "base/filesv2/playerstatushealthimage/bg/zpos3.res"
#base "base/filesv2/playerstatushealthimage/bg/wt24.res"
#base "base/filesv2/playerstatushealthimage/bg/xypos_4.res"

#base "base/filesv2/playerstatushealthimage/bonus/main.res"
#base "base/filesv2/playerstatushealthimage/bonus/xypos_4.res"
#base "base/filesv2/playerstatushealthimage/bonus/wt24.res"
#base "base/filesv2/playerstatushealthimage/bonus/zpos3.res"

#base "base/filesv2/buildingstatushealthimagebg/main.res"
#base "base/filesv2/buildingstatushealthimagebg/zpos2.res"
#base "base/filesv2/buildingstatushealthimagebg/wt28.res"
#base "base/filesv2/buildingstatushealthimagebg/xpos0.res"
#base "base/filesv2/buildingstatushealthimagebg/ypos2.res"

#base "base/filesv2/playerstatushealthvalue/main.res"
#base "base/filesv2/playerstatushealthvalue/zpos5.res"
#base "base/filesv2/playerstatushealthvalue/font.res"
#base "base/filesv2/playerstatushealthvalue/wt20.res"
#base "base/filesv2/playerstatushealthvalue/xypos_6.res"