#base "base/filesv1/avatarimage/main.res"
#base "base/filesv1/avatarimage/enabled.res"
#base "base/filesv1/avatarimage/color.res"
#base "base/filesv1/specguihealth/main.res"
#base "base/filesv1/specguihealth/warning.res"
#base "base/filesv1/specguihealth/content1.res"
#base "base/filesv1/specguihealth/wide32.res"