#base "base/filesv5-exist/tfadvancedoptions.res"

#base "base/filesv1/panellistpanel/main.res"
#base "base/filesv1/panellistpanel/bg.res"
#base "base/filesv2/tooltippanel/main.res"
#base "base/filesv2/tooltippanel/ctrl.res"
#base "base/filesv2/tooltippanel/border.res"
#base "base/filesv2/tooltippanel/position/ypos0.res"
#base "base/filesv2/tooltippanel/position/zpos100.res"
#base "base/filesv2/tooltippanel/position/tall50.res"
#base "base/filesv2/tooltippanel/position/wide240.res"
#base "base/filesv2/tooltippanel/tiplabel/main.res"
#base "base/filesv2/tooltippanel/tiplabel/fgcolor.res"
#base "base/filesv2/tooltippanel/tiplabel/position/xpos20.res"
#base "base/filesv2/tooltippanel/tiplabel/position/ypos10.res"
#base "base/filesv2/tooltippanel/tiplabel/position/wide200.res"
#base "base/filesv2/tooltippanel/tiplabel/position/tall30.res"
#base "base/filesv2/tooltippanel/tiplabel/text/center.res"
#base "base/filesv2/tooltippanel/tiplabel/text/wrap1.res"


#base "../../#uni_base/filesv1/okbutton/position/wide100.res"
#base "../../#uni_base/filesv1/okbutton/position/tall25.res"


#base "../../#uni_base/filesv1/okbutton/auto.res"
#base "../../#uni_base/filesv1/okbutton/zpos1.res"
#base "../../#uni_base/filesv1/okbutton/vis1.res"
#base "../../#uni_base/filesv1/okbutton/enabled.res"
#base "../../#uni_base/filesv1/okbutton/tab0.res"
#base "../../#uni_base/filesv1/okbutton/cmd/ok.res"
#base "../../#uni_base/filesv1/okbutton/label/gameui_ok.res"
#base "../../#uni_base/filesv1/okbutton/text/center.res"
#base "../../#uni_base/filesv1/okbutton/def1.res"
#base "../../#uni_base/filesv1/okbutton/dull0.res"
#base "../../#uni_base/filesv1/okbutton/bright0.res"
#base "../../#uni_base/filesv1/okbutton/sound.res"


#base "../../#uni_base/filesv1/titlelabel/controlname/cex.res"
#base "../../#uni_base/filesv1/titlelabel/main.res"
#base "../../#uni_base/filesv1/titlelabel/text/center.res"
#base "../../#uni_base/filesv1/titlelabel/auto.res"
#base "../../#uni_base/filesv1/titlelabel/pin.res"
#base "../../#uni_base/filesv1/titlelabel/vis1.res"
#base "../../#uni_base/filesv1/titlelabel/enabled.res"

#base "../../#uni_base/filesv1/cancelbutton/ctrl/cex.res"
#base "../../#uni_base/filesv1/cancelbutton/main.res"
#base "../../#uni_base/filesv1/cancelbutton/position/x150.res"
#base "../../#uni_base/filesv1/cancelbutton/position/ypos310.res"
#base "../../#uni_base/filesv1/cancelbutton/position/zpos1.res"
#base "../../#uni_base/filesv1/cancelbutton/position/w100.res"
#base "../../#uni_base/filesv1/cancelbutton/position/t25.res"
#base "../../#uni_base/filesv1/cancelbutton/pin3.res"
#base "../../#uni_base/filesv1/cancelbutton/auto.res"
#base "../../#uni_base/filesv1/cancelbutton/vis1.res"
#base "../../#uni_base/filesv1/cancelbutton/enabled.res"
#base "../../#uni_base/filesv1/cancelbutton/tab0.res"
#base "../../#uni_base/filesv1/cancelbutton/label/cancel.res"
#base "../../#uni_base/filesv1/cancelbutton/text/center.res"
#base "../../#uni_base/filesv1/cancelbutton/dull0.res"
#base "../../#uni_base/filesv1/cancelbutton/bright0.res"
#base "../../#uni_base/filesv1/cancelbutton/def1.res"
#base "../../#uni_base/filesv1/cancelbutton/cmd/close.res"
#base "../../#uni_base/filesv1/cancelbutton/sound.res"
#base "../../#uni_base/filesv1/cancelbutton/font/hudfontsmallbold.res"