"resource/BaseActionCDTrackStartDialog.res"
{
"DialogFrame"
{
"FooterTopPanel"
{
"ControlName""EditablePanel"
"fieldName""FooterTopPanel"
"xpos""3"
"ypos""240"
"zpos""1"
"tall""10"
//"visible""1"
////"enabled""1"
"paintborder""0"
"PaintBackgroundType""0"
"paintbackground""1"
"bgcolor_override" "50 46 41 255"
}
}
}