"Resource/UI/HudArenaCapPointCountdown.res"
{
    "CapCountdownLabel"
    {
        "font""DamageText2"
        "xpos""2"
        "ypos""2"
        "zpos""-1"
        "wide""23"
        "tall""23"
        "textAlignment""center"
        "fgcolor""Black"
    }
}
