
"Resource/UI/HudDamageAccount.res"
{
	"CDamageAccountPanel"
	{
		"fieldName"				"CDamageAccountPanel"
		"text_x"				"0"
		"text_y"				"0"
		"delta_item_end_y"		"-10"
		"PositiveColor"			"46 255 83 150"
		"NegativeColor"			"255 215 0 150"
		"delta_item_font"		"Size 16 Uber"//Size 12"
		"delta_item_font_big"	"Size 16 Uber"//Size 18"		
		"alpha"	"255"
		"EventColor"			"35 195 255 255" //med drops n whatnots
//		"RedRobotScoreColor"	"255 255 255 255"
//		"BlueRobotScoreColor"	"255 255 255 255"
		
		"delta_lifetime"		"5.6"
		"alpha" "125"
		"Additive" "1"
	}	

	"DamageAccountLabel"
	{
		"ControlName"	"CExLabel"
		"fieldName"		"DamageAccountLabel"
		"font"			"HealthAndAmmo2"
		"fgcolor"		"Primary"
		"xpos"			"cs-0.5+152"
		"ypos"			"cs-0.5+99"
		"zpos"			"0"
		"wide"			"100"
		"tall"			"30"
		"visible"		"1"
		"auto_wide_tocontents"	"1"
		"textAlignment"	"west"	
		"bgcolor_override"	"blank"
		"labelText"		"%metal%"	
	}	
		"alert"
		{
			"ControlName"	"CExLabel"
			"fieldName"		"alert"
			"xpos"			"297"//"-1"
			"ypos"			"-5"
			"zpos"			"2"
			"wide"			"8"
			"tall"			"20"
			"font"			"Killfeed"
			"textAlignment"	"center"
			"labelText"	""
			"centerwrap"	"1"
			"fgcolor"		"White"
			"bgcolor_override"	"Yellow"
			"pin_to_sibling"	"DamageAccountLabel"
			"pin_corner_to_sibling"					"PIN_TOPLEFT"
			"pin_to_sibling_corner"					"PIN_TOPRIGHT"	
		}		
		"alert2"
		{
			"ControlName"	"CExLabel"
			"fieldName"		"alert2"
			"xpos"			"0"//"-1"
			"ypos"			"0"
			"zpos"			"2"
			"wide"			"8"
			"tall"			"20"
			"font"			"Killfeed"
			"textAlignment"	"center"
			"labelText"	"!"
			"centerwrap"	"1"
			"fgcolor"		"Neutral"
			"bgcolor_override"	"Red"
			"pin_to_sibling"	"alert"
			"pin_corner_to_sibling"					"PIN_TOPLEFT"
			"pin_to_sibling_corner"					"PIN_TOPRIGHT"	
		}		
}