"Resource/UI/HudItemEffectMeter_Demoman.res"
{
	HudItemEffectMeter
	{
		"fieldName"		"HudItemEffectMeter"
		"visible"		"1"
		"enabled"		"1"
		"xpos"			"0"
		"ypos"			"0"
		"wide"			"f0"
		"tall"			"f0"
		"MeterFG"		"White"
		"MeterBG"		"Gray"
	}
	"Spinner5"
	{
		"ControlName"	"RotatingProgressBar"
		"visible"		"1"
		"zpos"			"5"
		"xpos"			"0"
		"ypos"			"0"
		"wide"			"20"
		"tall"			"20"
		"image"			"replay/thumbnails/hud/ks/5"
		"rotating_x"			"-50"
		"rotating_y"			"-50"
		"start_degrees"			"0"
		"end_degrees"			"1800"
		"variable"				"progresscount"
		// "progress"				"0.0"
		"approach_speed"		"100"
		"rotating_wide"			"100"
		"rotating_tall"			"100"
		"rot_origin_x_percent"	"0.5"
		"rot_origin_y_percent"	"0.5"
	}

	"border1"
	{
		"ControlName"			"CTFImagePanel"
		"zpos"					"15"
		"ypos"					"0"
		"wide"					"44"
		"tall"					"22"
		"teambg_0"				"replay/thumbnails/hud/ks/border_red"
		"teambg_1"				"replay/thumbnails/hud/ks/border_red"
		"teambg_2"				"replay/thumbnails/hud/ks/border_red"
		"teambg_3"				"replay/thumbnails/hud/ks/border_blue"
		"alpha"					"255"
	}
	"border2"
	{
		"ControlName"			"CTFImagePanel"
		"zpos"					"15"
		"ypos"					"0"
		"wide"					"44"
		"tall"					"22"
		"image" "replay/thumbnails/hud/ks/refks"
		"alpha"					"255"
	}	
	"Spinner10"
	{
		"ControlName"	"RotatingProgressBar"
		"visible"		"1"
		"zpos"			"6"
		"xpos"			"0"
		"ypos"			"0"
		"wide"			"20"
		"tall"			"20"
		"image"			"replay/thumbnails/hud/ks/10"
		"rotating_x"			"-50"
		"rotating_y"			"-50"
		"start_degrees"			"0"
		"end_degrees"			"1800"
		"variable"				"progresscount"
		// "progress"				"0.1"
		"approach_speed"		"100"
		"rotating_wide"			"100"
		"rotating_tall"			"100"
		"rot_origin_x_percent"	"0.5"
		"rot_origin_y_percent"	"0.5"
	}

	"Spinner15"
	{
		"ControlName"	"RotatingProgressBar"
		"visible"		"1"
		"zpos"			"7"
		"xpos"			"0"
		"ypos"			"0"
		"wide"			"20"
		"tall"			"20"
		"image"			"replay/thumbnails/hud/ks/15"
		"rotating_x"			"-50"
		"rotating_y"			"-50"
		"start_degrees"			"0"
		"end_degrees"			"1800"
		"variable"				"progresscount"
		// "progress"				"0.15"
		"approach_speed"		"100"
		"rotating_wide"			"100"
		"rotating_tall"			"100"
		"rot_origin_x_percent"	"0.5"
		"rot_origin_y_percent"	"0.5"
	}

	"Spinner20"
	{
		"ControlName"	"RotatingProgressBar"
		"visible"		"1"
		"zpos"			"4"
		"xpos"			"0"
		"ypos"			"0"
		"wide"			"20"
		"tall"			"20"
		"image"			"replay/thumbnails/hud/ks/20"
		"rotating_x"			"-50"
		"rotating_y"			"-50"
		"start_degrees"			"0"
		"end_degrees"			"1350"
		"variable"				"progresscount"
		// "progress"				"0.2"
		"approach_speed"		"100"
		"rotating_wide"			"100"
		"rotating_tall"			"100"
		"rot_origin_x_percent"	"0.5"
		"rot_origin_y_percent"	"0.5"
	}

		"FixForHP"
		{
		"ControlName""CTFImagePanel"
		"fieldName""FixForHP"
		"xpos""0"
		"ypos" "0"
		"wide"	"100"
		"tall" "17"
		"zpos" "0"
		"ControlName""CTFImagePanel"
		"fieldName""FixForHP"
		"image"			"replay/thumbnails/hp/cover"
		"scaleImage"		"1"	
		"teambg_2"		"replay/thumbnails/hp/modulate_red"
		"teambg_3"		"replay/thumbnails/hp/modulate_blu"
		"pin_to_sibling"	"ItemEffectMeterBG"
		}
								
	"1_progress"
	{
					"ControlName""ContinuousProgressBar"
		"fieldName""1_progress"
		"xpos"			"0"
		"ypos"			"0"
		"zpos"			"-1"
		"wide"			"331"	// limit at 30
		"tall"			"17"
		"variable"		"progresscount"

		"fgcolor_override"	"White"
		"bgcolor_override" "0 0 0 0"
		"pin_to_sibling"	"ItemEffectMeterBG"
	}		
	"ItemEffectMeterBG"
	{
		"ControlName"	"ImagePanel"
		"fieldName"		"ItemEffectMeterBG"
		"xpos"			"rs1-10"
		"ypos"			"10"
		"zpos"			"0"
		"wide"			"100"
		"tall"			"17"
		"visible"		"1"
		"enabled"		"1"
		"image"			""
		"fillcolor"		"0 0 0 175"	
	}
	
	"ItemEffectMeterLabel"
	{
		"ControlName"			"CExLabel"
		"fieldName"				"ItemEffectMeterLabel"
		"xpos"					"-25"
		"ypos"					"-27"
		"zpos"					"2"
		"wide"					"41"
		"tall"					"15"
		"autoResize"			"1"
		"pinCorner"				"2"
		"visible"				"0"
		"enabled"				"0"
		"labelText"				"#TF_KillStreak"
		"textAlignment"			"center"
		"font"					"TFFontSmall"
		"pin_to_sibling" "ItemEffectMeterBG"
	}

	"ItemEffectMeter"
	{	
		"ControlName"			"ContinuousProgressBar"
		"fieldName"				"ItemEffectMeter"
		"font"					"Default"
		"xpos"					"25"
		"ypos"					"23"
		"ypos_minmode"			"0"
		"xpos_minmode"			"0"
		"zpos"					"2"
		"wide"					"40"
		"wide_minmode"			"50"
		"tall"					"6"				
		"visible"				"0"
		"enabled"				"0"
		"textAlignment"			"Left"
	}					
	
	"ItemEffectMeterCount"
	{
		"ControlName"			"CExLabel"
		"fieldName"				"ItemEffectMeterCount"
		"xpos"					"-70"
		"ypos"					"0"
		"zpos"					"3"
		"wide"					"50"
		"tall"					"16"
		"pinCorner"				"2"
		"visible"				"1"
		"enabled"				"1"
		"labelText"				"%progresscount%" // "killstreak_count_spaced"
		"textAlignment"			"west"
		"font"					"Killfeed"
		"fgcolor"				"245 245 245 255"
		"pin_to_sibling" "ItemEffectMeterBG"
	}
	"StreakLabel"
	{
		"ControlName"			"CExLabel"
		"fieldName"				"ItemEffectMeterCount"
		"xpos"					"-25"
		"ypos"					"0"
		"zpos"					"3"
		"wide"					"200"
		"tall"					"16"
		"pinCorner"				"2"
		"visible"				"1"
		"enabled"				"1"
		"labelText"				"Streak:"
		"textAlignment"			"west"
		"font"					"NotoBold16"
		"fgcolor"				"245 245 245 150"
		"pin_to_sibling" "ItemEffectMeterBG"
	}
	"StreakLabel2"
	{
		"ControlName"			"CExLabel"
		"fieldName"				"StreakLabel2"
		"xpos"					"-10"
		"ypos"					"0"
		"zpos"					"3"
		"wide"					"20"
		"tall"					"16"
		"labelText"				"H"
		"textAlignment"			"west"
		"font"					"NewIcons10"
		"fgcolor"				"245 245 245 150"
		"pin_to_sibling"	"ItemEffectMeterBG"
	}	
}
