"Resource/UI/HudObjectiveTimePanel.res"
{	
	"TimePanelBG"
	{
		"ControlName"		"ScalableImagePanel"
		"fieldName"		"TimePanelBG"
		"xpos"			"216"
		"ypos"			"9"
		"zpos"			"2"
		"wide"			"78"
		"tall"			"33"
		"visible"		"0"
		//"enabled"		"1"
		"image"			"replay/thumbnails/hp/timericon_bg_dx9"	
		"scaleImage"		"1"	
	}
	"TimePanelBGReal"
	{
		"ControlName"		"ScalableImagePanel"
		"fieldName"		"TimePanelBGReal"
		"xpos"			"220"
		"ypos"			"0"
		"zpos"			"2"
		"wide"			"72"
		"tall"			"24"
		"visible"		"1"
		//"enabled"		"1"
		"image"			"replay/thumbnails/hp/timericon_bg_dx9"	
		"scaleImage"		"1"	
	}
	"TimeCircleThingOverlay"
	{
		"ControlName"		"ImagePanel"
		"fieldName"		"TimeCircleThingOverlay"
		"xpos"			"222"
		"ypos"			"0"
		"zpos"			"100"
		"wide"			"20"
		"tall"			"20"
		"visible"		"1"
		//"enabled"		"1"
		"image"			"replay/thumbnails/hp/timericon_refract"
		"scaleimage"	"1"
	}
	"TimePanelProgressBar"
	{
		"ControlName"			"CTFProgressBar"
		"fieldName"			"TimePanelProgressBar"
		"xpos"				"220"
		"ypos"				"-4"
		"zpos"				"4"	
		"wide"				"25"
		"tall"				"26"
		"visible"			"1"
		"enabled"			"1"
		"scaleImage"			"1"
		"image"				"../hud/objectives_timepanel_progressbar"
		"color_active"			"236 240 241 255"
		"color_warning"			"236 240 241 255"
		"color_inactive"		"35 35 35 255"
		"percent_warning"		"0.75"
	}
	"WaitingForPlayersLabel"
	{
		"ControlName"		"CExLabel"
		"fieldName"		"WaitingForPlayersLabel"
		"xpos"			"200"
		"ypos"			"34"
		"zpos"			"5"
		"wide"			"110"
		"tall"			"19"
		"fgcolor"		"236 240 241 255"
		"visible"		"0"
		//"enabled"		"1"
		"labelText"		"#game_WaitingForPlayers"
		"textAlignment"		"center"
		"dulltext"		"0"
		"brighttext"		"0"
		"wrap"			"0"
		"font"			"Noto16"
	}			
	"WaitingForPlayersBG"
	{
		"ControlName"		"CTFImagePanel"
		"fieldName"		"WaitingForPlayersBG"
		"xpos"			"216"	[$WIN32]
		"xpos"			"211"	[$X360]
		"ypos"			"31"
		//"ypos_hidef"	"-100"	//off-screen
		//"ypos_lodef"	"-100"	//off-screen
		"zpos"			"1"
		"wide"			"78"
		"tall"			"0"
		"visible"		"0"
		//"enabled"		"1"
		"image"			"../hud/objectives_timepanel_suddendeath"	
		"scaleImage"		"1"	
	}
	"OvertimeLabel"
	{
		"ControlName"		"CExLabel"
		"fieldName"		"OvertimeLabel"
		"xpos"			"223"
		"ypos"			"-1"
		"zpos"			"5"
		"wide"			"20"
		"tall"			"20"
		"fgcolor"		"255 25 50 255"
		"visible"		"0"
		//"enabled"		"1"
		"textAlignment"		"center"
		"dulltext"		"0"
		"brighttext"		"0"
		"wrap"			"0"
		"font"			"Noto24"
	}			
	"OvertimeBG"
	{
		"ControlName"		"CTFImagePanel"
		"fieldName"		"OvertimeBG"
		"xpos"			"216"
		"ypos"			"31"
		//"ypos_hidef"	"-100"	//off-screen
		//"ypos_lodef"	"-100"	//off-screen
		"zpos"			"1"
		"wide"			"78"
		"tall"			"0"
		"visible"		"0"
		//"enabled"		"1"
		"image"			"../hud/objectives_timepanel_suddendeath"	
		"scaleImage"		"1"	
	}
	"SuddenDeathLabel"
	{
		"ControlName"		"CExLabel"
		"fieldName"		"SuddenDeathLabel"
		"xpos"			"200"
		"ypos"			"34"
		"zpos"			"5"
		"wide"			"110"
		"tall"			"19"
		"fgcolor"		"236 240 241 255"
		"visible"		"0"
		//"enabled"		"1"
		"labelText"		"#game_SuddenDeath"
		"textAlignment"		"center"
		"dulltext"		"0"
		"brighttext"		"0"
		"wrap"			"0"
		"font"			"Noto16"
	}			
	"SuddenDeathBG"
	{
		"ControlName"		"CTFImagePanel"
		"fieldName"		"SuddenDeathBG"
		"xpos"			"216"	[$WIN32]
		"xpos"			"11"	[$X360]
		"ypos"			"31"
		//"ypos_hidef"	"-100"	//off-screen
		//"ypos_lodef"	"-100"	//off-screen
		"zpos"			"1"
		"wide"			"78"
		"tall"			"0"
		"visible"		"0"
		//"enabled"		"1"
		"image"			"../hud/objectives_timepanel_suddendeath"	
		"scaleImage"		"1"	
	}	
	"SetupLabel"
	{
		"ControlName"	"CExLabel"
		"fieldName"		"SetupLabel"
		"xpos"			"200"
		"ypos"			"34"
		"zpos"			"5"
		"wide"			"110"
		"tall"			"19"
		"fgcolor"		"236 240 241 255"
		"visible"		"0"
		//"enabled"		"1"
		"labelText"		"#game_Setup"
		"textAlignment"		"center"
		"dulltext"		"0"
		"brighttext"		"0"
		"wrap"			"0"
		"font"			"Noto16"
	}	
	"SetupBG"
	{
		"ypos"			"r0"
	}
	"ServerTimeLimitLabel"
	{
		"ControlName"	"CExLabel"
		"fieldName"		"ServerTimeLimitLabel"
		"xpos"			"200"
		"ypos"			"34"
		"zpos"			"5"
		"wide"			"110"
		"tall"			"19"
		"fgcolor"		"236 240 241 255"
		"visible"		"0"
		//"enabled"		"1"
		"labelText"		"%servertimeleft%"
		"textAlignment"		"center"
		"dulltext"		"0"
		"brighttext"		"0"
		"wrap"			"0"
		"font"			"ClockSubText"
	}	
	"ServerTimeLimitLabelBG"
	{
		"ypos"			"r0"
	}
}
