//#base	"../ui_overrides/!res_health.res"
#base	"../ui_overrides/!res_health.res"
#base "../../../../../cfg/jp_custom_hp_speed.txt"
#base "../../../../../cfg/jp_custom_hp_progressbar.txt"
#base "../ui3/custom_hudplayerhealth.res"
