"Resource/UI/CharInfoPanel.res"
{
"Title"
{
"ControlName""Label"
"fieldName""Title"
"xpos""15"
"ypos""15"
"wide""250"
"tall""25"
//"autoResize""0"
//"pinCorner""0"
////"enabled""1"
"tabPosition""0"
"textAlignment""west"
//"dulltext""0"
//"brighttext""0"
"wrap""0"
"font""HudFontMediumSecondary"
}
}