"resource/ui/hudplayerclass.res"
{
"UnavailableLabel"
{
"ControlName""CExLabel"
"fieldName""UnavailableLabel"
//"font""Default"
"xpos""10"
"ypos""48"
"zpos""2"
"wide""80"
"tall""18"
////"autoResize""0"
//"pinCorner""0"
"visible""0"
////"enabled""1"
"labelText""#Hud_Menu_Build_Unavailable"
"textAlignment""Center"
//"dulltext""0"
"brighttext""0"
}
}