"j"
{
	"CustomizationMenu"
	{
		"MainPanel"
		{
			"MenuContainer"
			{
				
				"BGButtons"
				{
	
					"choosedef"
					{
						"ControlName"			"CExButton"
						"fieldName"				"choosedef"
						"xpos"					"0"
						"zpos"					"0"
						"wide"					"470"
						"tall"					"40"
						"proportionaltoparent"	"1"
						"labeltext"				"Keep Gray solid color one! (Removes bg)"
						"font"					"Noto20"
						"textalignment"			"center"
"command" "engine sixense_clear_bindings; sixense_write_bindings _jp_mm_bg.txt"
						"actionsignallevel"		"5" 
						"actionsignallevel"		"5" 
						"paintbackground"		"1"
							"defaultBgColor_override" 	"NotoBlack"
		"armedBgColor_override"		"Notowhite"
		"depressedBgColor_override" "0 0 0 0"
		"selectedBgColor_override" 	"NotoBlueSolid"
		
		"defaultFgColor_override" 	"NotoWhite"
		"armedFgColor_override"		"NotoBlack"
		"depressedFgColor_override" "NotoWhite"
		"selectedFgColor_override" 	"NotoBlack"			
						"border_default"		"FLAT_Black_4"
						"border_armed"			"FLAT_Black_2"
						"sound_depressed"		"UI/buttonclick.wav"
						"sound_released"		"UI/buttonclickrelease.wav"

					}	
					"choosecustom1"
					{
						"ControlName"			"CExButton"
						"fieldName"				"choosecustom1"
						"xpos"					"0"
						"ypos"					"40" 
						"wide"					"470"
						"tall"					"180"
						"textinsety"			"10"
						"labeltext"				"InsomniaHUD BG"
						"font"					"Regular12"
						"textalignment"			"north"
"command" "engine sixense_clear_bindings; sixense_write_bindings _jp_mm_bg.txt;con_logfile cfg/_jp_mm_bg.txt; echo #base ../custom/jofrehud-main/_jofrenew/new/ui_overrides/background/lead.res; con_logfile ."
						"actionsignallevel"		"5" 
						"paintbackground"		"0"
						"border_default"		"FLAT_Black_4"
						"border_armed"			"FLAT_Black_2"
						"sound_depressed"		"UI/buttonclick.wav"
						"sound_released"		"UI/buttonclickrelease.wav"

					}	
		"custombgshowcase"
		{
			"ControlName"							"ImagePanel"
			"fieldName"								"custombgshowcase"
			"xpos"									"80"
			"ypos"									"60"
			"wide"									"300"
			"tall"									"o0.5"
			"proportionaltoparent"					"1"
			"scaleImage"							"1"
			"mouseinputenabled"		"0"
			"drawcolor"	"Primary"
			"image"									replay/thumbnails/ui_effects/menu_glow
		}								
					"choosecustom2"
					{
						"textinsety"			"10"
						"ControlName"			"CExButton"
						"fieldName"				"choosecustom2"
						"xpos"					"0"
						"ypos"					"220"
						"wide"					"470"
						"tall"					"180"
						"proportionaltoparent"	"1"
						"labeltext"				"Gruvbox"
						"font"					"Regular12"
						"textalignment"			"north"
"command" "engine sixense_clear_bindings; sixense_write_bindings _jp_mm_bg.txt;con_logfile cfg/_jp_mm_bg.txt; echo #base ../custom/jofrehud-main/_jofrenew/new/ui_overrides/background/gruvbox1.res; con_logfile ."
						"actionsignallevel"		"5" 
						"actionsignallevel"		"5" 
						"paintbackground"		"0"
						"border_default"		"FLAT_Black_4"
						"border_armed"			"FLAT_Black_2"
						"sound_depressed"		"UI/buttonclick.wav"
						"sound_released"		"UI/buttonclickrelease.wav"

					}		
		"custombgshowcase2"
		{
			"ControlName"							"ImagePanel"
			"fieldName"								"custombgshowcase2"
			"xpos"									"80"
			"ypos"									"220+20"
			"wide"									"300"
			"tall"									"o0.5"
			"proportionaltoparent"					"1"
			"scaleImage"							"1"
			"mouseinputenabled"		"0"
			"image"									"replay/thumbnails/gruvbox"
		}	
							"choosecustom3"
					{
						"ControlName"			"CExButton"
						"fieldName"				"choosecustom3"
						"xpos"					"0"
						"ypos"					"400" 
						"wide"					"470"
						"tall"					"180"
						"textinsety"			"10"
						"labeltext"				"Danganronpa"
						"font"					"Regular12"
						"textalignment"			"north"
"command" "engine sixense_clear_bindings; sixense_write_bindings _jp_mm_bg.txt;con_logfile cfg/_jp_mm_bg.txt; echo #base ../custom/jofrehud-main/_jofrenew/new/ui_overrides/background/danganronpa.res; con_logfile ."
						"actionsignallevel"		"5" 
						"paintbackground"		"0"
						"border_default"		"FLAT_Black_4"
						"border_armed"			"FLAT_Black_2"
						"sound_depressed"		"UI/buttonclick.wav"
						"sound_released"		"UI/buttonclickrelease.wav"

					}	
		"custombgshowcase3"
		{
			"ControlName"							"ImagePanel"
			"fieldName"								"custombgshowcase3"
			"xpos"									"80"
			"ypos"									"400+20"
			"wide"									"300"
			"tall"									"o0.5"
			"proportionaltoparent"					"1"
			"scaleImage"							"1"
			"mouseinputenabled"		"0"
			"image"									"replay/thumbnails/danganronpa"
		}	
							"choosecustom4"
					{
						"ControlName"			"CExButton"
						"fieldName"				"choosecustom4"
						"xpos"					"0"
						"ypos"					"400+180" 
						"wide"					"470"
						"tall"					"180"
						"textinsety"			"10"
						"labeltext"				"Abstract"
						"font"					"Regular12"
						"textalignment"			"north"
"command" "engine sixense_clear_bindings; sixense_write_bindings _jp_mm_bg.txt;con_logfile cfg/_jp_mm_bg.txt; echo #base ../custom/jofrehud-main/_jofrenew/new/ui_overrides/background/abstract.res; con_logfile ."
						"actionsignallevel"		"5" 
						"paintbackground"		"0"
						"border_default"		"FLAT_Black_4"
						"border_armed"			"FLAT_Black_2"
						"sound_depressed"		"UI/buttonclick.wav"
						"sound_released"		"UI/buttonclickrelease.wav"

					}	
		"custombgshowcase4"
		{
			"ControlName"							"ImagePanel"
			"fieldName"								"custombgshowcase4"
			"xpos"									"80"
			"ypos"									"400+180+20"
			"wide"									"300"
			"tall"									"o0.5"
			"proportionaltoparent"					"1"
			"scaleImage"							"1"
			"mouseinputenabled"		"0"
			"image"									"replay/thumbnails/abstract"
		}			

							"choosecustom5"
					{
						"ControlName"			"CExButton"
						"fieldName"				"choosecustom5"
						"xpos"					"0"
						"ypos"					"400+180+180" 
						"wide"					"470"
						"tall"					"180"
						"textinsety"			"10"
						"labeltext"				"Beach"
						"font"					"Regular12"
						"textalignment"			"north"
"command" "engine sixense_clear_bindings; sixense_write_bindings _jp_mm_bg.txt;con_logfile cfg/_jp_mm_bg.txt; echo #base ../custom/jofrehud-main/_jofrenew/new/ui_overrides/background/beach.res; con_logfile ."
						"actionsignallevel"		"5" 
						"paintbackground"		"0"
						"border_default"		"FLAT_Black_4"
						"border_armed"			"FLAT_Black_2"
						"sound_depressed"		"UI/buttonclick.wav"
						"sound_released"		"UI/buttonclickrelease.wav"

					}	
		"custombgshowcase5"
		{
			"ControlName"							"ImagePanel"
			"fieldName"								"custombgshowcase5"
			"xpos"									"80"
			"ypos"									"400+180+180+20"
			"wide"									"300"
			"tall"									"o0.5"
			"proportionaltoparent"					"1"
			"scaleImage"							"1"
			"mouseinputenabled"		"0"
			"image"									"replay/thumbnails/beach"
		}			
		"choosecustom6"
{
	"ControlName"			"CExButton"
	"fieldName"				"choosecustom6"
	"xpos"					"0"
	"ypos"					"400+180+180+180" 
	"wide"					"470"
	"tall"					"180"
	"textinsety"			"10"
	"labeltext"				"Old1"
	"font"					"Regular12"
	"textalignment"			"north"
"command" "engine sixense_clear_bindings; sixense_write_bindings _jp_mm_bg.txt;con_logfile cfg/_jp_mm_bg.txt; echo #base ../custom/jofrehud-main/_jofrenew/new/ui_overrides/background/old1.res; con_logfile ."
	"actionsignallevel"		"5" 
	"paintbackground"		"0"
	"border_default"		"FLAT_Black_4"
	"border_armed"			"FLAT_Black_2"
	"sound_depressed"		"UI/buttonclick.wav"
	"sound_released"		"UI/buttonclickrelease.wav"

}	
"custombgshowcase6"
{
"ControlName"							"ImagePanel"
"fieldName"								"custombgshowcase6"
"xpos"									"80"
"ypos"									"400+180+180+20+180"
"wide"									"300"
"tall"									"o0.5"
"proportionaltoparent"					"1"
"scaleImage"							"1"
"mouseinputenabled"		"0"
"image"									"replay/thumbnails/old1"
}		
"choosecustom7"
{
	"ControlName"			"CExButton"
	"fieldName"				"choosecustom7"
	"xpos"					"0"
	"ypos"					"400+180+180+180+180" 
	"wide"					"470"
	"tall"					"180"
	"textinsety"			"10"
	"labeltext"				"Old2"
	"font"					"Regular12"
	"textalignment"			"north"
"command" "engine sixense_clear_bindings; sixense_write_bindings _jp_mm_bg.txt;con_logfile cfg/_jp_mm_bg.txt; echo #base ../custom/jofrehud-main/_jofrenew/new/ui_overrides/background/old2.res; con_logfile ."
	"actionsignallevel"		"5" 
	"paintbackground"		"0"
	"border_default"		"FLAT_Black_4"
	"border_armed"			"FLAT_Black_2"
	"sound_depressed"		"UI/buttonclick.wav"
	"sound_released"		"UI/buttonclickrelease.wav"

}	
"custombgshowcase7"
{
"ControlName"							"ImagePanel"
"fieldName"								"custombgshowcase7"
"xpos"									"80"
"ypos"									"400+180+180+20+180+180"
"wide"									"300"
"tall"									"o0.5"
"proportionaltoparent"					"1"
"scaleImage"							"1"
"mouseinputenabled"		"0"
"image"									"replay/thumbnails/old2"
}	
"choosecustom8"
{
	"ControlName"			"CExButton"
	"fieldName"				"choosecustom8"
	"xpos"					"0"
	"ypos"					"400+180+180+180+180+180" 
	"wide"					"470"
	"tall"					"180"
	"textinsety"			"10"
	"labeltext"				"No Man Sky"
	"font"					"Regular12"
	"textalignment"			"north"
"command" "engine sixense_clear_bindings; sixense_write_bindings _jp_mm_bg.txt;con_logfile cfg/_jp_mm_bg.txt; echo #base ../custom/jofrehud-main/_jofrenew/new/ui_overrides/background/nomansky.res; con_logfile ."
	"actionsignallevel"		"5" 
	"paintbackground"		"0"
	"border_default"		"FLAT_Black_4"
	"border_armed"			"FLAT_Black_2"
	"sound_depressed"		"UI/buttonclick.wav"
	"sound_released"		"UI/buttonclickrelease.wav"

}	
"custombgshowcase8"
{
"ControlName"							"ImagePanel"
"fieldName"								"custombgshowcase8"
"xpos"									"80"
"ypos"									"400+180+180+20+180+180+180"
"wide"									"300"
"tall"									"o0.5"
"proportionaltoparent"					"1"
"scaleImage"							"1"
"mouseinputenabled"		"0"
"image"									"replay/thumbnails/nomansky"
}	

"choosecustom9"
{
	"ControlName"			"CExButton"
	"fieldName"				"choosecustom9"
	"xpos"					"0"
	"ypos"					"400+180+180+180+180+180+180" 
	"wide"					"470"
	"tall"					"180"
	"textinsety"			"10"
	"labeltext"				"Pink"
	"font"					"Regular12"
	"textalignment"			"north"
"command" "engine sixense_clear_bindings; sixense_write_bindings _jp_mm_bg.txt;con_logfile cfg/_jp_mm_bg.txt; echo #base ../custom/jofrehud-main/_jofrenew/new/ui_overrides/background/pink.res; con_logfile ."
	"actionsignallevel"		"5" 
	"paintbackground"		"0"
	"border_default"		"FLAT_Black_4"
	"border_armed"			"FLAT_Black_2"
	"sound_depressed"		"UI/buttonclick.wav"
	"sound_released"		"UI/buttonclickrelease.wav"

}	
"custombgshowcase9"
{
"ControlName"							"ImagePanel"
"fieldName"								"custombgshowcase9"
"xpos"									"80"
"ypos"									"400+180+180+20+180+180+180+180"
"wide"									"300"
"tall"									"o0.5"
"proportionaltoparent"					"1"
"scaleImage"							"1"
"mouseinputenabled"		"0"
"image"									"replay/thumbnails/pink"
}
"choosecustom10"
{
	"ControlName"			"CExButton"
	"fieldName"				"choosecustom10"
	"xpos"					"0"
	"ypos"					"400+180+180+180+180+180+180+180" 
	"wide"					"470"
	"tall"					"180"
	"textinsety"			"10"
	"labeltext"				"-"
	"font"					"Regular12"
	"textalignment"			"north"
"command" "engine sixense_clear_bindings; sixense_write_bindings _jp_mm_bg.txt;con_logfile cfg/_jp_mm_bg.txt; echo #base ../custom/jofrehud-main/_jofrenew/new/ui_overrides/background/nsfw1.res; con_logfile ."
	"actionsignallevel"		"5" 
	"paintbackground"		"0"
	"border_default"		"FLAT_Black_4"
	"border_armed"			"FLAT_Black_2"
	"sound_depressed"		"UI/buttonclick.wav"
	"sound_released"		"UI/buttonclickrelease.wav"

}	
"custombgshowcase10"
{
"ControlName"							"ImagePanel"
"fieldName"								"custombgshowcase10"
"xpos"									"80"
"ypos"									"400+180+180+20+180+180+180+180+180"
"wide"									"300"
"tall"									"o0.5"
"proportionaltoparent"					"1"
"scaleImage"							"1"
"mouseinputenabled"		"0"
"image"									"replay/thumbnails/nsfw1"
}
"choosecustom11"
{
	"ControlName"			"CExButton"
	"fieldName"				"choosecustom11"
	"xpos"					"0"
	"ypos"					"400+180+180+180+180+180+180+180+180" 
	"wide"					"470"
	"tall"					"180"
	"textinsety"			"10"
	"labeltext"				"-"
	"font"					"Regular12"
	"textalignment"			"north"
"command" "engine sixense_clear_bindings; sixense_write_bindings _jp_mm_bg.txt;con_logfile cfg/_jp_mm_bg.txt; echo #base ../custom/jofrehud-main/_jofrenew/new/ui_overrides/background/nsfw2.res; con_logfile ."
	"actionsignallevel"		"5" 
	"paintbackground"		"0"
	"border_default"		"FLAT_Black_4"
	"border_armed"			"FLAT_Black_2"
	"sound_depressed"		"UI/buttonclick.wav"
	"sound_released"		"UI/buttonclickrelease.wav"

}	
"custombgshowcase11"
{
"ControlName"							"ImagePanel"
"fieldName"								"custombgshowcase11"
"xpos"									"80"
"ypos"									"400+180+180+20+180+180+180+180+180+180"
"wide"									"300"
"tall"									"o0.5"
"proportionaltoparent"					"1"
"scaleImage"							"1"
"mouseinputenabled"		"0"
"image"									"replay/thumbnails/nsfw2"
}
"choosecustom12"
{
	"ControlName"			"CExButton"
	"fieldName"				"choosecustom12"
	"xpos"					"0"
	"ypos"					"400+180+180+180+180+180+180+180+180+180" 
	"wide"					"470"
	"tall"					"180"
	"textinsety"			"10"
	"labeltext"				"-"
	"font"					"Regular12"
	"textalignment"			"north"
"command" "engine sixense_clear_bindings; sixense_write_bindings _jp_mm_bg.txt;con_logfile cfg/_jp_mm_bg.txt; echo #base ../custom/jofrehud-main/_jofrenew/new/ui_overrides/background/miku1.res; con_logfile ."
	"actionsignallevel"		"5" 
	"paintbackground"		"0"
	"border_default"		"FLAT_Black_4"
	"border_armed"			"FLAT_Black_2"
	"sound_depressed"		"UI/buttonclick.wav"
	"sound_released"		"UI/buttonclickrelease.wav"

}	
"custombgshowcase12"
{
"ControlName"							"ImagePanel"
"fieldName"								"custombgshowcase12"
"xpos"									"80"
"ypos"									"400+180+180+20+180+180+180+180+180+180+180"
"wide"									"300"
"tall"									"o0.5"
"proportionaltoparent"					"1"
"scaleImage"							"1"
"mouseinputenabled"		"0"
"image"									"replay/thumbnails/miku1"
}
"choosecustom13"
{
	"ControlName"			"CExButton"
	"fieldName"				"choosecustom13"
	"xpos"					"0"
	"ypos"					"400+180+180+180+180+180+180+180+180+180+180" 
	"wide"					"470"
	"tall"					"180"
	"textinsety"			"10"
	"labeltext"				"-"
	"font"					"Regular12"
	"textalignment"			"north"
"command" "engine sixense_clear_bindings; sixense_write_bindings _jp_mm_bg.txt;con_logfile cfg/_jp_mm_bg.txt; echo #base ../custom/jofrehud-main/_jofrenew/new/ui_overrides/background/whaven.res; con_logfile ."
	"actionsignallevel"		"5" 
	"paintbackground"		"0"
	"border_default"		"FLAT_Black_4"
	"border_armed"			"FLAT_Black_2"
	"sound_depressed"		"UI/buttonclick.wav"
	"sound_released"		"UI/buttonclickrelease.wav"

}	
"custombgshowcase13"
{
"ControlName"							"ImagePanel"
"fieldName"								"custombgshowcase13"
"xpos"									"80"
"ypos"									"400+180+180+20+180+180+180+180+180+180+180+180"
"wide"									"300"
"tall"									"o0.5"
"proportionaltoparent"					"1"
"scaleImage"							"1"
"mouseinputenabled"		"0"
"image"									"replay/thumbnails/whaven"
}
"choosecustom14"
{
	"ControlName"			"CExButton"
	"fieldName"				"choosecustom14"
	"xpos"					"0"
	"ypos"					"400+180+180+180+180+180+180+180+180+180+180+180" 
	"wide"					"470"
	"tall"					"180"
	"textinsety"			"10"
	"labeltext"				"-"
	"font"					"Regular12"
	"textalignment"			"north"
"command" "engine sixense_clear_bindings; sixense_write_bindings _jp_mm_bg.txt;con_logfile cfg/_jp_mm_bg.txt; echo #base ../custom/jofrehud-main/_jofrenew/new/ui_overrides/background/whaven2.res; con_logfile ."
	"actionsignallevel"		"5" 
	"paintbackground"		"0"
	"border_default"		"FLAT_Black_4"
	"border_armed"			"FLAT_Black_2"
	"sound_depressed"		"UI/buttonclick.wav"
	"sound_released"		"UI/buttonclickrelease.wav"

}	
"custombgshowcase14"
{
"ControlName"							"ImagePanel"
"fieldName"								"custombgshowcase14"
"xpos"									"80"
"ypos"									"400+180+180+20+180+180+180+180+180+180+180+180+180"
"wide"									"300"
"tall"									"o0.5"
"proportionaltoparent"					"1"
"scaleImage"							"1"
"mouseinputenabled"		"0"
"image"									"replay/thumbnails/whaven2"
}
"choosecustom15"
{
	"ControlName"			"CExButton"
	"fieldName"				"choosecustom15"
	"xpos"					"0"
	"ypos"					"400+180+180+180+180+180+180+180+180+180+180+180+180" 
	"wide"					"470"
	"tall"					"180"
	"textinsety"			"10"
	"labeltext"				"-"
	"font"					"Regular12"
	"textalignment"			"north"
"command" "engine sixense_clear_bindings; sixense_write_bindings _jp_mm_bg.txt;con_logfile cfg/_jp_mm_bg.txt; echo #base ../custom/jofrehud-main/_jofrenew/new/ui_overrides/background/whaven3.res; con_logfile ."
	"actionsignallevel"		"5" 
	"paintbackground"		"0"
	"border_default"		"FLAT_Black_4"
	"border_armed"			"FLAT_Black_2"
	"sound_depressed"		"UI/buttonclick.wav"
	"sound_released"		"UI/buttonclickrelease.wav"

}	
"custombgshowcase15"
{
"ControlName"							"ImagePanel"
"fieldName"								"custombgshowcase15"
"xpos"									"80"
"ypos"									"400+180+180+20+180+180+180+180+180+180+180+180+180+180"
"wide"									"300"
"tall"									"o0.5"
"proportionaltoparent"					"1"
"scaleImage"							"1"
"mouseinputenabled"		"0"
"image"									"replay/thumbnails/whaven3"
}


"choosecustom16"
{
	"ControlName"			"CExButton"
	"fieldName"				"choosecustom16"
	"xpos"					"0"
	"ypos"					"2740" 
	"wide"					"470"
	"tall"					"180"
	"textinsety"			"10"
	"labeltext"				"animegirl1"
	"font"					"Regular12"
	"textalignment"			"north"
"command" "engine sixense_clear_bindings; sixense_write_bindings _jp_mm_bg.txt;con_logfile cfg/_jp_mm_bg.txt; echo #base ../custom/jofrehud-main/_jofrenew/new/ui_overrides/background/animegirl1.res; con_logfile ."
	"actionsignallevel"		"5" 
	"paintbackground"		"0"
	"border_default"		"FLAT_Black_4"
	"border_armed"			"FLAT_Black_2"
	"sound_depressed"		"UI/buttonclick.wav"
	"sound_released"		"UI/buttonclickrelease.wav"

}	
"custombgshowcase16"
{
"ControlName"							"ImagePanel"
"fieldName"								"custombgshowcase16"
"xpos"									"80"
"ypos"									"2740+20"
"wide"									"300"
"tall"									"o0.5"
"proportionaltoparent"					"1"
"scaleImage"							"1"
"mouseinputenabled"		"0"
"image"									"replay/thumbnails/animegirl1"
}


"choosecustom17"
{
	"ControlName"			"CExButton"
	"fieldName"				"choosecustom17"
	"xpos"					"0"
	"ypos"					"2920" 
	"wide"					"470"
	"tall"					"180"
	"textinsety"			"10"
	"labeltext"				"animegirl2"
	"font"					"Regular12"
	"textalignment"			"north"
"command" "engine sixense_clear_bindings; sixense_write_bindings _jp_mm_bg.txt;con_logfile cfg/_jp_mm_bg.txt; echo #base ../custom/jofrehud-main/_jofrenew/new/ui_overrides/background/animegirl2.res; con_logfile ."
	"actionsignallevel"		"5" 
	"paintbackground"		"0"
	"border_default"		"FLAT_Black_4"
	"border_armed"			"FLAT_Black_2"
	"sound_depressed"		"UI/buttonclick.wav"
	"sound_released"		"UI/buttonclickrelease.wav"

}	
"custombgshowcase17"
{
"ControlName"							"ImagePanel"
"fieldName"								"custombgshowcase17"
"xpos"									"80"
"ypos"									"2940"
"wide"									"300"
"tall"									"o0.5"
"proportionaltoparent"					"1"
"scaleImage"							"1"
"mouseinputenabled"		"0"
"image"									"replay/thumbnails/animegirl2"
}


"choosecustom18"
{
	"ControlName"			"CExButton"
	"fieldName"				"choosecustom18"
	"xpos"					"0"
	"ypos"					"3100" 
	"wide"					"470"
	"tall"					"180"
	"textinsety"			"10"
	"labeltext"				"goofy2"
	"font"					"Regular12"
	"textalignment"			"north"
"command" "engine sixense_clear_bindings; sixense_write_bindings _jp_mm_bg.txt;con_logfile cfg/_jp_mm_bg.txt; echo #base ../custom/jofrehud-main/_jofrenew/new/ui_overrides/background/goofy2.res; con_logfile ."
	"actionsignallevel"		"5" 
	"paintbackground"		"0"
	"border_default"		"FLAT_Black_4"
	"border_armed"			"FLAT_Black_2"
	"sound_depressed"		"UI/buttonclick.wav"
	"sound_released"		"UI/buttonclickrelease.wav"

}	
"custombgshowcase18"
{
"ControlName"							"ImagePanel"
"fieldName"								"custombgshowcase18"
"xpos"									"80"
"ypos"									"3120"
"wide"									"300"
"tall"									"o0.5"
"proportionaltoparent"					"1"
"scaleImage"							"1"
"mouseinputenabled"		"0"
"image"									"replay/thumbnails/goofy2"
}





"choosecustom19"
{
	"ControlName"			"CExButton"
	"fieldName"				"choosecustom19"
	"xpos"					"0"
	"ypos"					"3280" 
	"wide"					"470"
	"tall"					"180"
	"textinsety"			"10"
	"labeltext"				"goofya1"
	"font"					"Regular12"
	"textalignment"			"north"
"command" "engine sixense_clear_bindings; sixense_write_bindings _jp_mm_bg.txt;con_logfile cfg/_jp_mm_bg.txt; echo #base ../custom/jofrehud-main/_jofrenew/new/ui_overrides/background/goofya1.res; con_logfile ."
	"actionsignallevel"		"5" 
	"paintbackground"		"0"
	"border_default"		"FLAT_Black_4"
	"border_armed"			"FLAT_Black_2"
	"sound_depressed"		"UI/buttonclick.wav"
	"sound_released"		"UI/buttonclickrelease.wav"

}	
"custombgshowcase19"
{
"ControlName"							"ImagePanel"
"fieldName"								"custombgshowcase19"
"xpos"									"80"
"ypos"									"3300"
"wide"									"300"
"tall"									"o0.5"
"proportionaltoparent"					"1"
"scaleImage"							"1"
"mouseinputenabled"		"0"
"image"									"replay/thumbnails/goofya1"
}


"new1"
{
	"ControlName"			"CExButton"
	"fieldName"				"new1"
	"xpos"					"0"
	"ypos"					"3460" 
	"wide"					"470"
	"tall"					"180"
	"textinsety"			"10"
	"labeltext"				"new1"
	"font"					"Regular12"
	"textalignment"			"north"
"command" "engine sixense_clear_bindings; sixense_write_bindings _jp_mm_bg.txt;con_logfile cfg/_jp_mm_bg.txt; echo #base ../custom/jofrehud-main/_jofrenew/new/ui_overrides/background/new1.res; con_logfile ."
	"actionsignallevel"		"5" 
	"paintbackground"		"0"
	"border_default"		"FLAT_Black_4"
	"border_armed"			"FLAT_Black_2"
	"sound_depressed"		"UI/buttonclick.wav"
	"sound_released"		"UI/buttonclickrelease.wav"

}	
"_new1"
{
"ControlName"							"ImagePanel"
"fieldName"								"_new1"
"xpos"									"80"
"ypos"									"3460+20"
"wide"									"300"
"tall"									"o0.5"
"proportionaltoparent"					"1"
"scaleImage"							"1"
"mouseinputenabled"		"0"
"image"									"replay/thumbnails/new1"
}


"new1a"
{
	"ControlName"			"CExButton"
	"fieldName"				"new1a"
	"xpos"					"0"
	"ypos"					"3640" 
	"wide"					"470"
	"tall"					"180"
	"textinsety"			"10"
	"labeltext"				"new1a"
	"font"					"Regular12"
	"textalignment"			"north"
"command" "engine sixense_clear_bindings; sixense_write_bindings _jp_mm_bg.txt;con_logfile cfg/_jp_mm_bg.txt; echo #base ../custom/jofrehud-main/_jofrenew/new/ui_overrides/background/new1a.res; con_logfile ."
	"actionsignallevel"		"5" 
	"paintbackground"		"0"
	"border_default"		"FLAT_Black_4"
	"border_armed"			"FLAT_Black_2"
	"sound_depressed"		"UI/buttonclick.wav"
	"sound_released"		"UI/buttonclickrelease.wav"

}	
"_new1a"
{
"ControlName"							"ImagePanel"
"fieldName"								"_new1a"
"xpos"									"80"
"ypos"									"3640+20"
"wide"									"300"
"tall"									"o0.5"
"proportionaltoparent"					"1"
"scaleImage"							"1"
"mouseinputenabled"		"0"
"image"									"replay/thumbnails/new1a"
}

"new1b"
{
	"ControlName"			"CExButton"
	"fieldName"				"new1b"
	"xpos"					"0"
	"ypos"					"3820"
	"wide"					"470"
	"tall"					"180"
	"textinsety"			"10"
	"labeltext"				"new1b"
	"font"					"Regular12"
	"textalignment"			"north"
"command" "engine sixense_clear_bindings; sixense_write_bindings _jp_mm_bg.txt;con_logfile cfg/_jp_mm_bg.txt; echo #base ../custom/jofrehud-main/_jofrenew/new/ui_overrides/background/new1b.res; con_logfile ."
	"actionsignallevel"		"5" 
	"paintbackground"		"0"
	"border_default"		"FLAT_Black_4"
	"border_armed"			"FLAT_Black_2"
	"sound_depressed"		"UI/buttonclick.wav"
	"sound_released"		"UI/buttonclickrelease.wav"

}	
"_new1b"
{
"ControlName"							"ImagePanel"
"fieldName"								"_new1b"
"xpos"									"80"
"ypos"									"3820+20"
"wide"									"300"
"tall"									"o0.5"
"proportionaltoparent"					"1"
"scaleImage"							"1"
"mouseinputenabled"		"0"
"image"									"replay/thumbnails/new1b"
}




"new2"
{
	"ControlName"			"CExButton"
	"fieldName"				"new2"
	"xpos"					"0"
	"ypos"					"4000" 
	"wide"					"470"
	"tall"					"180"
	"textinsety"			"10"
	"labeltext"				"new2"
	"font"					"Regular12"
	"textalignment"			"north"
"command" "engine sixense_clear_bindings; sixense_write_bindings _jp_mm_bg.txt;con_logfile cfg/_jp_mm_bg.txt; echo #base ../custom/jofrehud-main/_jofrenew/new/ui_overrides/background/new2.res; con_logfile ."
	"actionsignallevel"		"5" 
	"paintbackground"		"0"
	"border_default"		"FLAT_Black_4"
	"border_armed"			"FLAT_Black_2"
	"sound_depressed"		"UI/buttonclick.wav"
	"sound_released"		"UI/buttonclickrelease.wav"

}	
"_new2"
{
"ControlName"							"ImagePanel"
"fieldName"								"_new2"
"xpos"									"80"
"ypos"									"4020"
"wide"									"300"
"tall"									"o0.5"
"proportionaltoparent"					"1"
"scaleImage"							"1"
"mouseinputenabled"		"0"
"image"									"replay/thumbnails/new2"
}



"new3"
{
	"ControlName"			"CExButton"
	"fieldName"				"new3"
	"xpos"					"0"
	"ypos"					"4180" 
	"wide"					"470"
	"tall"					"180"
	"textinsety"			"10"
	"labeltext"				"new3"
	"font"					"Regular12"
	"textalignment"			"north"
"command" "engine sixense_clear_bindings; sixense_write_bindings _jp_mm_bg.txt;con_logfile cfg/_jp_mm_bg.txt; echo #base ../custom/jofrehud-main/_jofrenew/new/ui_overrides/background/new3.res; con_logfile ."
	"actionsignallevel"		"5" 
	"paintbackground"		"0"
	"border_default"		"FLAT_Black_4"
	"border_armed"			"FLAT_Black_2"
	"sound_depressed"		"UI/buttonclick.wav"
	"sound_released"		"UI/buttonclickrelease.wav"

}	
"_new3"
{
"ControlName"							"ImagePanel"
"fieldName"								"_new3"
"xpos"									"80"
"ypos"									"4180+20"
"wide"									"300"
"tall"									"o0.5"
"proportionaltoparent"					"1"
"scaleImage"							"1"
"mouseinputenabled"		"0"
"image"									"replay/thumbnails/new3"
}


"new4"
{
	"ControlName"			"CExButton"
	"fieldName"				"new4"
	"xpos"					"0"
	"ypos"					"4360" 
	"wide"					"470"
	"tall"					"180"
	"textinsety"			"10"
	"labeltext"				"new4"
	"font"					"Regular12"
	"textalignment"			"north"
"command" "engine sixense_clear_bindings; sixense_write_bindings _jp_mm_bg.txt;con_logfile cfg/_jp_mm_bg.txt; echo #base ../custom/jofrehud-main/_jofrenew/new/ui_overrides/background/new4.res; con_logfile ."
	"actionsignallevel"		"5" 
	"paintbackground"		"0"
	"border_default"		"FLAT_Black_4"
	"border_armed"			"FLAT_Black_2"
	"sound_depressed"		"UI/buttonclick.wav"
	"sound_released"		"UI/buttonclickrelease.wav"

}	
"_new4"
{
"ControlName"							"ImagePanel"
"fieldName"								"_new4"
"xpos"									"80"
"ypos"									"4360+20"
"wide"									"300"
"tall"									"o0.5"
"proportionaltoparent"					"1"
"scaleImage"							"1"
"mouseinputenabled"		"0"
"image"									"replay/thumbnails/new4"
}
"new5"
{
	"ControlName"			"CExButton"
	"fieldName"				"new5"
	"xpos"					"0"
	"ypos"					"4540" 
	"wide"					"470"
	"tall"					"180"
	"textinsety"			"10"
	"labeltext"				"new5"
	"font"					"Regular12"
	"textalignment"			"north"
"command" "engine sixense_clear_bindings; sixense_write_bindings _jp_mm_bg.txt;con_logfile cfg/_jp_mm_bg.txt; echo #base ../custom/jofrehud-main/_jofrenew/new/ui_overrides/background/new5.res; con_logfile ."
	"actionsignallevel"		"5" 
	"paintbackground"		"0"
	"border_default"		"FLAT_Black_4"
	"border_armed"			"FLAT_Black_2"
	"sound_depressed"		"UI/buttonclick.wav"
	"sound_released"		"UI/buttonclickrelease.wav"

}	
"_new5"
{
"ControlName"							"ImagePanel"
"fieldName"								"_new5"
"xpos"									"80"
"ypos"									"4540+20"
"wide"									"300"
"tall"									"o0.5"
"proportionaltoparent"					"1"
"scaleImage"							"1"
"mouseinputenabled"		"0"
"image"									"replay/thumbnails/new5"
}
"persona1"
{
	"ControlName"			"CExButton"
	"fieldName"				"persona1"
	"xpos"					"0"
	"ypos"					"4720" 
	"wide"					"470"
	"tall"					"180"
	"textinsety"			"10"
	"labeltext"				"persona1"
	"font"					"Regular12"
	"textalignment"			"north"
"command" "engine sixense_clear_bindings; sixense_write_bindings _jp_mm_bg.txt;con_logfile cfg/_jp_mm_bg.txt; echo #base ../custom/jofrehud-main/_jofrenew/new/ui_overrides/background/persona1.res; con_logfile ."
	"actionsignallevel"		"5" 
	"paintbackground"		"0"
	"border_default"		"FLAT_Black_4"
	"border_armed"			"FLAT_Black_2"
	"sound_depressed"		"UI/buttonclick.wav"
	"sound_released"		"UI/buttonclickrelease.wav"

}	
"_persona1"
{
"ControlName"							"ImagePanel"
"fieldName"								"_persona1"
"xpos"									"80"
"ypos"									"4720+20"
"wide"									"300"
"tall"									"o0.5"
"proportionaltoparent"					"1"
"scaleImage"							"1"
"mouseinputenabled"		"0"
"image"									"replay/thumbnails/persona1"
}
"persona2"
{
	"ControlName"			"CExButton"
	"fieldName"				"persona2"
	"xpos"					"0"
	"ypos"					"4900" 
	"wide"					"470"
	"tall"					"180"
	"textinsety"			"10"
	"labeltext"				"persona2"
	"font"					"Regular12"
	"textalignment"			"north"
"command" "engine sixense_clear_bindings; sixense_write_bindings _jp_mm_bg.txt;con_logfile cfg/_jp_mm_bg.txt; echo #base ../custom/jofrehud-main/_jofrenew/new/ui_overrides/background/persona2.res; con_logfile ."
	"actionsignallevel"		"5" 
	"paintbackground"		"0"
	"border_default"		"FLAT_Black_4"
	"border_armed"			"FLAT_Black_2"
	"sound_depressed"		"UI/buttonclick.wav"
	"sound_released"		"UI/buttonclickrelease.wav"

}	
"_persona2"
{
"ControlName"							"ImagePanel"
"fieldName"								"_persona2"
"xpos"									"80"
"ypos"									"4900+20"
"wide"									"300"
"tall"									"o0.5"
"proportionaltoparent"					"1"
"scaleImage"							"1"
"mouseinputenabled"		"0"
"image"									"replay/thumbnails/persona2"
}

"persona4"
{
	"ControlName"			"CExButton"
	"fieldName"				"persona4"
	"xpos"					"0"
	"ypos"					"4900+180" 
	"wide"					"470"
	"tall"					"180"
	"textinsety"			"10"
	"labeltext"				"persona4"
	"font"					"Regular12"
	"textalignment"			"north"
"command" "engine sixense_clear_bindings; sixense_write_bindings _jp_mm_bg.txt;con_logfile cfg/_jp_mm_bg.txt; echo #base ../custom/jofrehud-main/_jofrenew/new/ui_overrides/background/persona4.res; con_logfile ."
	"actionsignallevel"		"5" 
	"paintbackground"		"0"
	"border_default"		"FLAT_Black_4"
	"border_armed"			"FLAT_Black_2"
	"sound_depressed"		"UI/buttonclick.wav"
	"sound_released"		"UI/buttonclickrelease.wav"

}	
"_persona4"
{
"ControlName"							"ImagePanel"
"fieldName"								"_persona4"
"xpos"									"80"
"ypos"									"4900+20+180"
"wide"									"300"
"tall"									"o0.5"
"proportionaltoparent"					"1"
"scaleImage"							"1"
"mouseinputenabled"		"0"
"image"									"replay/thumbnails/persona4"
}
"persona3"
{
	"ControlName"			"CExButton"
	"fieldName"				"persona3"
	"xpos"					"0"
	"ypos"					"4900+360" 
	"wide"					"470"
	"tall"					"180"
	"textinsety"			"10"
	"labeltext"				"persona3"
	"font"					"Regular12"
	"textalignment"			"north"
"command" "engine sixense_clear_bindings; sixense_write_bindings _jp_mm_bg.txt;con_logfile cfg/_jp_mm_bg.txt; echo #base ../custom/jofrehud-main/_jofrenew/new/ui_overrides/background/persona3.res; con_logfile ."
	"actionsignallevel"		"5" 
	"paintbackground"		"0"
	"border_default"		"FLAT_Black_4"
	"border_armed"			"FLAT_Black_2"
	"sound_depressed"		"UI/buttonclick.wav"
	"sound_released"		"UI/buttonclickrelease.wav"

}	
"_persona3"
{
"ControlName"							"ImagePanel"
"fieldName"								"_persona3"
"xpos"									"80"
"ypos"									"4900+20+360"
"wide"									"300"
"tall"									"o0.5"
"proportionaltoparent"					"1"
"scaleImage"							"1"
"mouseinputenabled"		"0"
"image"									"replay/thumbnails/persona3"
}
"end"
{
	"ControlName"			"CExButton"
	"fieldName"				"end"
	"xpos"					"0"
	"ypos"					"9000" 
	"wide"					"470"
	"tall"					"1"
	"textinsety"			"10"
	"labeltext"				"Pink"
	"font"					"Regular12"
	"textalignment"			"north"
"command" "engine sixense_clear_bindings; sixense_write_bindings _jp_mm_bg.txt;con_logfile cfg/_jp_mm_bg.txt; echo #base ../custom/jofrehud-main/_jofrenew/new/ui_overrides/background/miku1.res; con_logfile ."
	"actionsignallevel"		"5" 
	"paintbackground"		"0"
	"border_default"		"FLAT_Black_4"
	"border_armed"			"FLAT_Black_2"
	"sound_depressed"		"UI/buttonclick.wav"
	"sound_released"		"UI/buttonclickrelease.wav"

}	
				}
			}
		}
	}
}