"j"
{
	"CustomizationMenu"
	{
		"MainPanel"
		{
			"MenuContainer"
			{
				"SourceschemeButtons"
				{
					"MainBorder"
					{
						"ControlName"	"CExLabel"
						"fieldName"		"MainBorder"
						"font"		"Regular16"
						"labelText"		"Main Border"
						"textAlignment"	"center"
						"xpos"		"0"
						"ypos"		"0"
						"zpos"		"20"
						"wide"		"p0.55"
						"tall"		"40"
						"border"		"FLAT_Black_4"
						"enabled"		"1"
						"fgcolor"		"white"
					}	
					"Modulate"
					{
						"ControlName"			"CExButton"
						"fieldName"				"Modulate"
						"xpos"					"0"
						"ypos"					"40"
						"wide"					"p0.2"
						"tall"					"40"
						"proportionaltoparent"	"1"
						"defaultfgcolor_override"	"Positive"
						"labeltext"				"Modulate"
						"font"					"Size 14"
						"textalignment"			"center"
"command"				"engine jp_srcescheme_border_clear; con_logfile cfg/jp_sourcescheme_border.txt; echo #base ../custom/jofrehud-main/new/ui_overrides/frame-border/modulate.res; con_logfile ."
						"actionsignallevel"		"5"
						"paintbackground"		"0"
						"border_default"		"FLAT_Black_4"
						"border_armed"			"FLAT_Black_2"
						"sound_depressed"		"UI/buttonclick.wav"
						"sound_released"		"UI/buttonclickrelease.wav"
					}	
					"ModulateBright"
					{
						"ControlName"			"CExButton"
						"fieldName"				"ModulateBright"
						"xpos"					"0+p0.2"
						"ypos"					"40"
						"wide"					"p0.2"
						"tall"					"40"
						"proportionaltoparent"	"1"
						"labeltext"				"Modulate Bright"
						"font"					"Size 14"
						"textalignment"			"center"
"command"				"engine jp_srcescheme_border_clear; con_logfile cfg/jp_sourcescheme_border.txt; echo #base ../custom/jofrehud-main/new/ui_overrides/frame-border/modulate_bright.res; con_logfile ."
						"actionsignallevel"		"5"
						"paintbackground"		"0"
						"border_default"		"FLAT_Black_4"
						"border_armed"			"FLAT_Black_2"
						"sound_depressed"		"UI/buttonclick.wav"
						"sound_released"		"UI/buttonclickrelease.wav"
					}		
					"ColorBorder"
					{
						"ControlName"			"CExButton"
						"fieldName"				"ColorBorder"
						"xpos"					"0+p0.4"
						"ypos"					"40"
						"wide"					"p0.2"
						"tall"					"40"
						"proportionaltoparent"	"1"
						"labeltext"				"Colored Border"
						"font"					"Size 14"
						"textalignment"			"center"
"command"				"engine jp_srcescheme_border_clear; con_logfile cfg/jp_sourcescheme_border.txt; echo #base ../custom/jofrehud-main/new/ui_overrides/frame-border/border.res; con_logfile ."
						"actionsignallevel"		"5"
						"paintbackground"		"0"
						"border_default"		"FLAT_Black_4"
						"border_armed"			"FLAT_Black_2"
						"sound_depressed"		"UI/buttonclick.wav"
						"sound_released"		"UI/buttonclickrelease.wav"
					}	
					"ImageBorder"
					{
						"ControlName"			"CExButton"
						"fieldName"				"ImageBorder"
						"xpos"					"0+p0.6"
						"ypos"					"40"
						"wide"					"p0.2"
						"tall"					"40"
						"proportionaltoparent"	"1"
						"labeltext"				"Image"
						"font"					"Size 14"
						"textalignment"			"center"
"command"				"engine jp_srcescheme_border_clear; con_logfile cfg/jp_sourcescheme_border.txt; echo #base ../custom/jofrehud-main/new/ui_overrides/frame-border/image1.res; con_logfile ."
						"actionsignallevel"		"5"
						"paintbackground"		"0"
						"border_default"		"FLAT_Black_4"
						"border_armed"			"FLAT_Black_2"
						"sound_depressed"		"UI/buttonclick.wav"
						"sound_released"		"UI/buttonclickrelease.wav"
					}	
					"Nullborder"
					{
						"ControlName"			"CExButton"
						"fieldName"				"Nullborder"
						"xpos"					"0+p0.8"
						"ypos"					"40"
						"wide"					"p0.2"
						"tall"					"40"
						"proportionaltoparent"	"1"
						"labeltext"				"Null"
						"font"					"Size 14"
						"textalignment"			"center"
"command"				"engine jp_srcescheme_border_clear"
						"actionsignallevel"		"5"
						"paintbackground"		"0"
						"border_default"		"FLAT_Black_4"
						"border_armed"			"FLAT_Black_2"
						"sound_depressed"		"UI/buttonclick.wav"
						"sound_released"		"UI/buttonclickrelease.wav"
					}		
					"ScrollbarWide"
					{
						"ControlName"	"CExLabel"
						"fieldName"		"ScrollbarWide"
						"font"		"Regular16"
						"labelText"		"Scrollbar Wide"
						"textAlignment"	"center"
						"xpos"		"0"
						"ypos"		"80"
						"zpos"		"20"
						"wide"		"p0.55"
						"tall"		"40"
						"border"		"FLAT_Black_4"
						"enabled"		"1"
						"fgcolor"		"white"
					}			
					"scroll60"
					{
						"ControlName"			"CExButton"
						"fieldName"				"scroll60"
						"xpos"					"0"
						"ypos"					"120"
						"wide"					"p0.1"
						"tall"					"20"
						"proportionaltoparent"	"1"
						"labeltext"				"60"
						"font"					"Size 14"
						"textalignment"			"center"
"command"				"engine jp_srcescheme_scroll_clear; con_logfile cfg/jp_sourcescheme_scrollbarwide.txt; echo Scheme{BaseSettings{Scrollbar.wide 60}}; con_logfile ."
						"actionsignallevel"		"5"
						"paintbackground"		"0"
						"defaultfgcolor_override"	"Positive"
						"border_default"		"FLAT_Black_4"
						"border_armed"			"FLAT_Black_2"
						"sound_depressed"		"UI/buttonclick.wav"
						"sound_released"		"UI/buttonclickrelease.wav"
					}	
					"scroll55"
					{
						"ControlName"			"CExButton"
						"fieldName"				"scroll55"
						"xpos"					"0+p0.1"
						"ypos"					"120"
						"wide"					"p0.1"
						"tall"					"20"
						"proportionaltoparent"	"1"
						"labeltext"				"55"
						"font"					"Size 14"
						"textalignment"			"center"
"command"				"engine jp_srcescheme_scroll_clear; con_logfile cfg/jp_sourcescheme_scrollbarwide.txt; echo Scheme{BaseSettings{Scrollbar.wide 55}}; con_logfile ."
						"actionsignallevel"		"5"
						"paintbackground"		"0"
						"border_default"		"FLAT_Black_4"
						"border_armed"			"FLAT_Black_2"
						"sound_depressed"		"UI/buttonclick.wav"
						"sound_released"		"UI/buttonclickrelease.wav"
					}	
					"scroll50"
					{
						"ControlName"			"CExButton"
						"fieldName"				"scroll50"
						"xpos"					"0+p0.2"
						"ypos"					"120"
						"wide"					"p0.1"
						"tall"					"20"
						"proportionaltoparent"	"1"
						"labeltext"				"50"
						"font"					"Size 14"
						"textalignment"			"center"
"command"				"engine jp_srcescheme_scroll_clear; con_logfile cfg/jp_sourcescheme_scrollbarwide.txt; echo Scheme{BaseSettings{Scrollbar.wide 50}}; con_logfile ."
						"actionsignallevel"		"5"
						"paintbackground"		"0"
						"border_default"		"FLAT_Black_4"
						"border_armed"			"FLAT_Black_2"
						"sound_depressed"		"UI/buttonclick.wav"
						"sound_released"		"UI/buttonclickrelease.wav"
					}		
					"scroll45"
					{
						"ControlName"			"CExButton"
						"fieldName"				"scroll45"
						"xpos"					"0+p0.3"
						"ypos"					"120"
						"wide"					"p0.1"
						"tall"					"20"
						"proportionaltoparent"	"1"
						"labeltext"				"45"
						"font"					"Size 14"
						"textalignment"			"center"
"command"				"engine jp_srcescheme_scroll_clear; con_logfile cfg/jp_sourcescheme_scrollbarwide.txt; echo Scheme{BaseSettings{Scrollbar.wide 45}}; con_logfile ."
						"actionsignallevel"		"5"
						"paintbackground"		"0"
						"border_default"		"FLAT_Black_4"
						"border_armed"			"FLAT_Black_2"
						"sound_depressed"		"UI/buttonclick.wav"
						"sound_released"		"UI/buttonclickrelease.wav"
					}		
					"scroll40"
					{
						"ControlName"			"CExButton"
						"fieldName"				"scroll40"
						"xpos"					"0+p0.4"
						"ypos"					"120"
						"wide"					"p0.1"
						"tall"					"20"
						"proportionaltoparent"	"1"
						"labeltext"				"40"
						"font"					"Size 14"
						"textalignment"			"center"
"command"				"engine jp_srcescheme_scroll_clear; con_logfile cfg/jp_sourcescheme_scrollbarwide.txt; echo Scheme{BaseSettings{Scrollbar.wide 40}}; con_logfile ."
						"actionsignallevel"		"5"
						"paintbackground"		"0"
						"border_default"		"FLAT_Black_4"
						"border_armed"			"FLAT_Black_2"
						"sound_depressed"		"UI/buttonclick.wav"
						"sound_released"		"UI/buttonclickrelease.wav"
					}		
					"scroll35"
					{
						"ControlName"			"CExButton"
						"fieldName"				"scroll35"
						"xpos"					"0+p0.5"
						"ypos"					"120"
						"wide"					"p0.1"
						"tall"					"20"
						"proportionaltoparent"	"1"
						"labeltext"				"35"
						"font"					"Size 14"
						"textalignment"			"center"
"command"				"engine jp_srcescheme_scroll_clear; con_logfile cfg/jp_sourcescheme_scrollbarwide.txt; echo Scheme{BaseSettings{Scrollbar.wide 35}}; con_logfile ."
						"actionsignallevel"		"5"
						"paintbackground"		"0"
						"border_default"		"FLAT_Black_4"
						"border_armed"			"FLAT_Black_2"
						"sound_depressed"		"UI/buttonclick.wav"
						"sound_released"		"UI/buttonclickrelease.wav"
					}	
					"scroll30"
					{
						"ControlName"			"CExButton"
						"fieldName"				"scroll30"
						"xpos"					"0+p0.6"
						"ypos"					"120"
						"wide"					"p0.1"
						"tall"					"20"
						"proportionaltoparent"	"1"
						"labeltext"				"30"
						"font"					"Size 14"
						"textalignment"			"center"
"command"				"engine jp_srcescheme_scroll_clear; con_logfile cfg/jp_sourcescheme_scrollbarwide.txt; echo Scheme{BaseSettings{Scrollbar.wide 30}}; con_logfile ."
						"actionsignallevel"		"5"
						"paintbackground"		"0"
						"border_default"		"FLAT_Black_4"
						"border_armed"			"FLAT_Black_2"
						"sound_depressed"		"UI/buttonclick.wav"
						"sound_released"		"UI/buttonclickrelease.wav"
					}	
					"scroll25"
					{
						"ControlName"			"CExButton"
						"fieldName"				"scroll25"
						"xpos"					"0+p0.7"
						"ypos"					"120"
						"wide"					"p0.1"
						"tall"					"20"
						"proportionaltoparent"	"1"
						"labeltext"				"25"
						"font"					"Size 14"
						"textalignment"			"center"
"command"				"engine jp_srcescheme_scroll_clear; con_logfile cfg/jp_sourcescheme_scrollbarwide.txt; echo Scheme{BaseSettings{Scrollbar.wide 25}}; con_logfile ."
						"actionsignallevel"		"5"
						"paintbackground"		"0"
						"border_default"		"FLAT_Black_4"
						"border_armed"			"FLAT_Black_2"
						"sound_depressed"		"UI/buttonclick.wav"
						"sound_released"		"UI/buttonclickrelease.wav"
					}				
					"scroll20"
					{
						"ControlName"			"CExButton"
						"fieldName"				"scroll20"
						"xpos"					"0+p0.8"
						"ypos"					"120"
						"wide"					"p0.1"
						"tall"					"20"
						"proportionaltoparent"	"1"
						"labeltext"				"20"
						"font"					"Size 14"
						"textalignment"			"center"
"command"				"engine jp_srcescheme_scroll_clear; con_logfile cfg/jp_sourcescheme_scrollbarwide.txt; echo Scheme{BaseSettings{Scrollbar.wide 20}}; con_logfile ."
						"actionsignallevel"		"5"
						"paintbackground"		"0"
						"border_default"		"FLAT_Black_4"
						"border_armed"			"FLAT_Black_2"
						"sound_depressed"		"UI/buttonclick.wav"
						"sound_released"		"UI/buttonclickrelease.wav"
					}	
					"scroll15"
					{
						"ControlName"			"CExButton"
						"fieldName"				"scroll15"
						"xpos"					"0+p0.9"
						"ypos"					"120"
						"wide"					"p0.1"
						"tall"					"20"
						"proportionaltoparent"	"1"
						"labeltext"				"15"
						"font"					"Size 14"
						"textalignment"			"center"
"command"				"engine jp_srcescheme_scroll_clear; con_logfile cfg/jp_sourcescheme_scrollbarwide.txt; echo Scheme{BaseSettings{Scrollbar.wide 15}}; con_logfile ."
						"actionsignallevel"		"5"
						"paintbackground"		"0"
						"border_default"		"FLAT_Black_4"
						"border_armed"			"FLAT_Black_2"
						"sound_depressed"		"UI/buttonclick.wav"
						"sound_released"		"UI/buttonclickrelease.wav"
					}																																																																										
				}
			}
		}
	}
}