"Resource/UI/CharInfoPanel.res"
{
"PlayerStatusHealthValue"
{
"ControlName""CExLabel"
"fieldName""PlayerStatusHealthValue"
//"visible""1"
////"enabled""1"
"labelText""%Health%"
"textAlignment""center"
"fgcolor""TanDark"
}
}