"Resource/UI/ItemRenameConfirmationDialog.res"
{
"LobbyPanel"
{
"ControlName""Frame"
"fieldName""LobbyPanel"
//"xpos""0"
"ypos""50"
"wide""f0"
"tall""f0"
////"autoResize""0"
//"pinCorner""0"
"visible""0"
////"enabled""1"
//"tabposition""0"
"settitlebarvisible""0"
"PaintBackgroundType""0"
"bgcolor_override""TanDarker"
"proportionaltoparent""1"
}
}
