	#base	"../../../custom/resource/ui/disguise_menu/hudmenuspydisguise.res"
	#base	"../../../_jofrenew/resource/ui/disguise_menu/hudmenuspydisguise.res"
	#base	"../../../_jofrehud/resource/ui/disguise_menu/hudmenuspydisguise.res"
	#base	"../../../_jofrehud/_tf2fix/resource/ui/disguise_menu/hudmenuspydisguise.res"
//	#base	"../../../_tf2hud/resource/ui/disguise_menu/hudmenuspydisguise.res"