"Resource/UI/CharInfoPanel.res"
{
"BackgroundFooter"
{
"ControlName""ImagePanel"
"fieldName""BackgroundFooter"
//"xpos""0"
"ypos""420"
"wide""f0"
"tall""60"
//"visible""1"
////"enabled""1"
"image""loadout_bottom_gradient"
"tileImage""1"
}
}
