"Resource/DialogHelpIngame.res"
{
	"HelpDialog"
	{
		"ControlName"		"Frame"
		"fieldName"		"HelpDialog"
		"xpos"		"154"
		"ypos"		"206"
		"wide"		"484"
		"tall"		"240"
		"visible"		"1"
		"enabled"		"1"
		//		"0"
	}
	"InfoText"
	{
		"ControlName"		"Label"
		"fieldName"		"InfoText"
		"xpos"		"18"
		"ypos"		"36"
		"wide"		"450"
		"tall"		"136"
		"visible"		"1"
		"enabled"		"1"
		//		"0"
		"textAlignment"		"center"
	}
	"CloseButton"
	{
		"ControlName"		"Button"
		"fieldName"		"CloseButton"
		"xpos"		"384"
		"ypos"		"188"
		"wide"		"64"
		"tall"		"24"
		"visible"		"1"
		"enabled"		"1"
		//		"1"
		"labelText"		"#TrackerUI_Close"
		"textAlignment"		"center"
		"command"		"Close"
	}
	"NeverShowButton"
	{
		"ControlName"		"CheckButton"
		"fieldName"		"NeverShowButton"
		"xpos"		"172"
		"ypos"		"186"
		"wide"		"194"
		"tall"		"24"
		"visible"		"1"
		"enabled"		"1"
		//		"2"
		"labelText"		"#TrackerUI_NeverShowThisDialogAgain"
		"textAlignment"		"center"
	}
}
