#base "../base/filesv2/explanationlabel/main.res"
#base "../base/filesv2/explanationlabel/font/hudfontsmall.res"
#base "../base/filesv2/explanationlabel/text/north.res"
#base "../base/filesv2/explanationlabel/text/centerwrap.res"
#base "../base/filesv2/explanationlabel/vis1.res"
#base "../base/filesv2/explanationlabel/auto0.res"
#base "../base/filesv2/explanationlabel/pin0.res"
#base "../base/filesv2/explanationlabel/position/xpos10.res"
#base "../base/filesv2/explanationlabel/position/ypos45.res"
#base "../base/filesv2/explanationlabel/position/wide300.res"
#base "../base/filesv2/explanationlabel/position/tall100.res"


#base "../../../#uni_base/filesv1/titlelabel/controlname/label.res"
#base "../../../#uni_base/filesv1/titlelabel/main.res"
#base "../../../#uni_base/filesv1/titlelabel/auto1.res"
#base "../../../#uni_base/filesv1/titlelabel/pin.res"
#base "../../../#uni_base/filesv1/titlelabel/vis1.res"
#base "../../../#uni_base/filesv1/titlelabel/enabled.res"
#base "../../../#uni_base/filesv1/titlelabel/text/north.res"