#base "../../../friends/base/namelabel_main_1.res"
#base "../../../friends/base/namelabel_autoresize0.res"
#base "../../../friends/base/namelabel_pincorner.res"
#base "../base/filesv1/verticalline/main.res"
#base "../base/filesv1/verticalline/ctrl_edit.res"
#base "../base/filesv1/verticalline/paintb.res"
#base "../base/filesv1/verticalline/wide1.res"