"Resource/EngineVGuiLayout.res"
{
"EmptyImage"
{
"ControlName""ImagePanel"
"fieldName""EmptyImage"
"xpos""1"
"ypos""1"
//"visible""1"
"proportionaltoparent""1"
"scaleImage""1"
"image""class_portraits/silhouette_alpha"
"mouseinputenabled""0"
}
}