"resource/BaseActionCDTrackStartDialog.res"
{
"DialogFrame"
{
"FootBottomPanel"
{
"ControlName""EditablePanel"
"fieldName""FootBottomPanel"
"xpos""3"
"ypos""240"
"zpos""1"
"tall""58"
//"visible""1"
////"enabled""1"
"paintborder""0"
"PaintBackgroundType""2"
"paintbackground""1"
"bgcolor_override" "50 46 41 255"
}
}
}