"Resource/baseaction_grip.res"
{
"LabelBlendFactor"
{
"ControlName""Label"
"fieldName""LabelBlendFactor"
"tall""34"
//"autoResize""0"
//"pinCorner""0"
"visible""1"
////"enabled""1"
"tabPosition""0"
"textAlignment""west"
//"dulltext""0"
//"brighttext""0"
}
}
