"Resource/UI/CharInfoPanel.res"
{
"BuildingStatusHealthImageBG"
{
"ControlName""ImagePanel"
"fieldName""BuildingStatusHealthImageBG"
"image""../hud/health_equip_bg"
//"visible""1"
////"enabled""1"
"scaleImage""1"
}
}