#base "../../../#uni_base/filesv1/closebutton/main.res"
#base "../../../#uni_base/filesv1/closebutton/vis1.res"
#base "../../../#uni_base/filesv1/closebutton/text/center.res"
#base "../../../#uni_base/filesv1/closebutton/enabled.res"
#base "../../../#uni_base/filesv1/closebutton/ctrl/ceximage.res"
#base "../../../#uni_base/filesv1/closebutton/def1.res"
#base "../../../#uni_base/filesv1/closebutton/tab.res"
#base "../../../#uni_base/filesv1/closebutton/dull0.res"
#base "../../../#uni_base/filesv1/closebutton/bright0.res"
#base "../../../#uni_base/filesv1/closebutton/sound.res"

#base "../../../#uni_base/filesv1/closebutton/font/hudfontsmallbold.res"
#base "../../../#uni_base/filesv1/closebutton/auto.res"
#base "../../../#uni_base/filesv1/closebutton/pin.res"

#base "../../../#uni_base/filesv1/closebutton/image/main.res"
#base "../../../#uni_base/filesv1/closebutton/image/wtf0.res"