"Resource/baseaction_sys.res"
{
"ShadedBar"
{
"ControlName""ImagePanel"
"fieldName""ShadedBar"
////"autoResize""0"
//"pinCorner""0"
//"visible""1"
////"enabled""1"
//"tabposition""0"
"PaintBackgroundType""0"
}
}
