"resource/ui/hudplayerclass.res"
{
"TitleLabelDropshadow"
{
"ControlName""CExLabel"
"fieldName""TitleLabelDropshadow"
"wide""300"
////"autoResize""0"
//"pinCorner""0"
//"visible""1"
////"enabled""1"
"brighttext""0"
}
}