"Resource/EngineVGuiLayout.res"
{
	"AvatarImage"
	{
		"ControlName"	"CAvatarImagePanel"
		"fieldName"		"AvatarImage"
		"xpos"			"260"
		"ypos"			"40"
		"wide"			"200"
		"tall"			"200"
		//"visible"		"1"
		////"enabled"		"1"
		"scaleImage"	"1"
	}
	"AvatarImage"
	{
		"ControlName"	"CAvatarImagePanel"
		"fieldName"		"AvatarImage"
		"xpos"			"6"
		"ypos"			"6"
		//"zpos"			"0"
		"wide"			"32"
		"tall"			"32"
		//"visible"		"1"
		////"enabled"		"1"
		//"image"			""
		"scaleImage"	"1"	
		"color_outline"	"52 48 45 255"
	}
	"AvatarImage"
	{
		// "ControlName"	"CAvatarImagePanel"
		"fieldName"		"AvatarImage"
		"xpos"			"1"
		"ypos"			"1"
		"zpos"			"101"
		"wide"			"26"
		"tall"			"o1"
		//"visible"		"1"
		"proportionaltoparent"	"1"
		"scaleImage"	"1"
	}
	"AvatarImage"
	{
		"ControlName"	"CAvatarImagePanel"
		"fieldName"		"AvatarImage"
		"xpos"			"10"
		"ypos"			"10"
		//"zpos"			"0"
		"wide"			"32"
		"tall"			"32"
		//"visible"		"1"
		////"enabled"		"1"
		//"image"			""
		"scaleImage"	"1"	
		"color_outline"	"52 48 45 255"
	}
	"AvatarImage"
	{
		"ControlName"	"CAvatarImagePanel"
		"fieldName"		"AvatarImage"
		"xpos"			"6"
		////"xpos_minmode"	"6"
		"ypos"			"6"
		"zpos"			"99"
		"wide"			"11"
		"tall"			"11"
		//"visible"		"1"
		////"enabled"		"1"
		//"image"			""
		"scaleImage"	"1"	
		"color_outline"	"52 48 45 255"
	}	
	"AvatarImage"
	{
		"ControlName"	"CAvatarImagePanel"
		"fieldName"		"AvatarImage"
		"xpos"			"9"
		"ypos"			"9"
		//"zpos"			"0"
		"wide"			"32"
		"tall"			"32"
		//"visible"		"1"
		////"enabled"		"1"
		//"image"			""
		"scaleImage"	"1"	
		"color_outline"	"52 48 45 255"
	}					
}	