"Resource/UI/build_menu/hudmenuengybuild.res"
{
"ModeLabel"
{
"ControlName""CExLabel"
"fieldName""ModeLabel"
"font""DefaultSmall"
"fgcolor""TanDark"
"xpos""33"
"ypos""17"
"zpos""1"
"wide""44"
"tall""13"
////"autoResize""0"
//"pinCorner""0"
"visible""0"
////"enabled""1"
"labelText" ""
"textAlignment""East"
}
}