#base "../#uni_base/filesv1/cancel/main.res"
#base "../#uni_base/filesv1/cancel/main2.res"
#base "../#uni_base/filesv1/cancel/def-is0.res"
#base "../#uni_base/filesv1/cancel/is-west.res"
#base "../#uni_base/filesv1/cancel/command/cancel.res"
#base "../#uni_base/filesv1/cancel/tall-is24.res"