#base "base/filesv1/keybindings/main.res"

#base "../#uni_base/filesv2/button1/main.res"

#base "../#uni_base/filesv2/button1/position/wide64.res"
#base "../#uni_base/filesv2/button1/position/tall24.res"
#base "../#uni_base/filesv2/button1/extra/auto0.res"
#base "../#uni_base/filesv2/button1/extra/pin2.res"
#base "../#uni_base/filesv2/button1/vis1.res"
#base "../#uni_base/filesv2/button1/enabled.res"
#base "../#uni_base/filesv2/button1/direccion/west.res"
#base "../#uni_base/filesv2/button1/extra/tab0.res"
#base "../#uni_base/filesv2/button1/extra/wrap0.res"
#base "../#uni_base/filesv2/button1/extra/dull0.res"
#base "../#uni_base/filesv2/button1/extra/bright0.res"
#base "../#uni_base/filesv2/button1/extra/cmd/close.res"
#base "../#uni_base/filesv2/button1/extra/def1.res"
#base "../#uni_base/filesv2/button1/label/vgui_close.res"