#base "../#uni_base/filesv1/loadinglabel/ctrl/frame.res"
#base "../#uni_base/filesv1/loadinglabel/main.res"
#base "../#uni_base/filesv1/loadinglabel/position/x322.res"
#base "../#uni_base/filesv1/loadinglabel/position/y249.res"
#base "../#uni_base/filesv1/loadinglabel/position/w300.res"
#base "../#uni_base/filesv1/loadinglabel/position/t180.res"

#base "../#uni_base/filesv1/infolabel/main.res"
#base "../#uni_base/filesv1/infolabel/ctrl/label.res"
#base "../#uni_base/filesv1/infolabel/auto.res"
#base "../#uni_base/filesv1/infolabel/pin.res"
#base "../#uni_base/filesv1/infolabel/vis1.res"
#base "../#uni_base/filesv1/infolabel/tab.res"
#base "../#uni_base/filesv1/infolabel/enabled.res"
#base "../#uni_base/filesv1/infolabel/bright0.res"
#base "../#uni_base/filesv1/infolabel/dull0.res"
#base "../#uni_base/filesv1/infolabel/text/west.res"
#base "../#uni_base/filesv1/infolabel/special/x20.res"
#base "../#uni_base/filesv1/infolabel/special/y34.res"
#base "../#uni_base/filesv1/infolabel/special/w340.res"
#base "../#uni_base/filesv1/infolabel/special/t24.res"
#base "../#uni_base/filesv1/infolabel/special/gameui_parse.res"

#base "base/filesv1/progress/main.res"
#base "base/filesv1/progress/tab0.res"
#base "base/filesv1/progress/vis1.res"
#base "base/filesv1/progress/controlname.res"
#base "base/filesv1/progress/position/x20.res"
#base "base/filesv1/progress/position/y64.res"
#base "base/filesv1/progress/position/w260.res"
#base "base/filesv1/progress/position/t24.res"

#base "../#uni_base/filesv1/cancelbutton/autoresize_pin.res"
#base "../#uni_base/filesv1/cancelbutton/ctrl/btn.res"
#base "../#uni_base/filesv1/cancelbutton/def0.res"
#base "../#uni_base/filesv1/cancelbutton/main.res"
#base "../#uni_base/filesv1/cancelbutton/vis1.res"
#base "../#uni_base/filesv1/cancelbutton/text/west.res"
#base "../#uni_base/filesv1/cancelbutton/enabled.res"
#base "../#uni_base/filesv1/cancelbutton/label/gameui_cancel.res"
#base "../#uni_base/filesv1/cancelbutton/bright0.res"
#base "../#uni_base/filesv1/cancelbutton/cmd/cancel.res"
#base "../#uni_base/filesv1/cancelbutton/dull0.res"
#base "../#uni_base/filesv1/cancelbutton/tab0.res"
#base "../#uni_base/filesv1/cancelbutton/position/x288.res"
#base "../#uni_base/filesv1/cancelbutton/position/y64.res"
#base "../#uni_base/filesv1/cancelbutton/position/w72.res"
#base "../#uni_base/filesv1/cancelbutton/position/t24.res"

//#base "../#uni_base/filesv1/timeremaininglabel/main.res"
//#base "../#uni_base/filesv1/timeremaininglabel/xpos20.res"
//#base "../#uni_base/filesv1/timeremaininglabel/ypos108.res"
//#base "../#uni_base/filesv1/timeremaininglabel/wide260.res"
//#base "../#uni_base/filesv1/timeremaininglabel/vis0.res"
//#base "../#uni_base/filesv1/timeremaininglabel/dull1.res"
//#base "../#uni_base/filesv1/timeremaininglabel/label/null.res"

#base "../#uni_base/filesv1/vac/main.res"