#base "../#uni_base/filesv1/button2/main.res"
#base "../#uni_base/filesv1/button2/wide_80.res"
#base "../#uni_base/filesv1/button2/label/gameui-cancel.res"
#base "../#uni_base/filesv1/button2/def/is-0.res"
#base "../#uni_base/filesv1/button2/def/command-close.res"

#base "../#uni_base/filesv2/button1/main.res"

#base "../#uni_base/filesv2/button1/position/wide80.res"
#base "../#uni_base/filesv2/button1/position/tall24.res"
#base "../#uni_base/filesv2/button1/extra/auto0.res"
#base "../#uni_base/filesv2/button1/extra/pin0.res"
#base "../#uni_base/filesv2/button1/vis1.res"
#base "../#uni_base/filesv2/button1/enabled.res"
#base "../#uni_base/filesv2/button1/direccion/west.res"
#base "../#uni_base/filesv2/button1/extra/tab3.res"
#base "../#uni_base/filesv2/button1/extra/wrap0.res"
#base "../#uni_base/filesv2/button1/extra/dull0.res"
#base "../#uni_base/filesv2/button1/extra/bright0.res"
#base "../#uni_base/filesv2/button1/extra/cmd/close.res"
#base "../#uni_base/filesv2/button1/extra/def1.res"
#base "../#uni_base/filesv2/button1/label/gameui_ok.res"