#base "../#uni_base/filesv1/imagepanel1/main.res"

#base "../#uni_base/filesv2/button1/main.res"

#base "../#uni_base/filesv2/button1/position/wide80.res"
#base "../#uni_base/filesv2/button1/position/tall24.res"
#base "../#uni_base/filesv2/button1/extra/auto0.res"
#base "../#uni_base/filesv2/button1/extra/pin0.res"
#base "../#uni_base/filesv2/button1/vis1.res"
#base "../#uni_base/filesv2/button1/enabled.res"
#base "../#uni_base/filesv2/button1/direccion/west.res"
#base "../#uni_base/filesv2/button1/extra/tab4.res"
#base "../#uni_base/filesv2/button1/extra/wrap0.res"
#base "../#uni_base/filesv2/button1/extra/dull0.res"
#base "../#uni_base/filesv2/button1/extra/bright0.res"
#base "../#uni_base/filesv2/button1/extra/cmd/close.res"
#base "../#uni_base/filesv2/button1/extra/def0.res"
#base "../#uni_base/filesv2/button1/label/vgui_cancel.res"

#base "../#uni_base/filesv1/label1/main.res"
#base "../#uni_base/filesv1/label1/auto.res"
#base "../#uni_base/filesv1/label1/pin.res"
#base "../#uni_base/filesv1/label1/enabled.res"
#base "../#uni_base/filesv1/label1/tab.res"
#base "../#uni_base/filesv1/label1/dull0.res"
#base "../#uni_base/filesv1/label1/bright0.res"
#base "../#uni_base/filesv1/label1/wrap1.res"
#base "../#uni_base/filesv1/label1/text/north-west.res"

#base "../#uni_base/filesv1/okbutton/ctrl/btn.res"
#base "../#uni_base/filesv1/okbutton/main.res"
#base "../#uni_base/filesv1/okbutton/position/wide80.res"
#base "../#uni_base/filesv1/okbutton/position/tall24.res"
#base "../#uni_base/filesv1/okbutton/auto.res"
#base "../#uni_base/filesv1/okbutton/pin.res"
#base "../#uni_base/filesv1/okbutton/vis1.res"
#base "../#uni_base/filesv1/okbutton/enabled.res"
#base "../#uni_base/filesv1/okbutton/text/west.res"
#base "../#uni_base/filesv1/okbutton/wrap0.res"
#base "../#uni_base/filesv1/okbutton/dull0.res"
#base "../#uni_base/filesv1/okbutton/bright0.res"
#base "../#uni_base/filesv1/okbutton/def1.res"
#base "../#uni_base/filesv1/okbutton/label/vgui_ok.res"