	#base 	"../../../_jofrehud/resource/#beta/menu_reloadbutton.res"
	#base	"../../../_stream/resource/ui/econ/backpackpanel.res"
	#base	"../../../_jofrenew/resource/ui/econ/backpackpanel.res"
	#base	"../../../_jofrehud/resource/ui/econ/backpackpanel.res"
	#base	"../../../z_tf2/resource/ui/econ/backpackpanel.res"