	#base 	"../../../_opt/resource/#beta/menu_reloadbutton.res"
	#base	"../../../_stream/resource/ui/econ/backpackpanel.res"
	#base	"../../../_jofrenew/resource/ui/econ/backpackpanel.res"
	#base	"../../../_opt/resource/ui/econ/backpackpanel.res"
	#base	"../../../z_tf2/resource/ui/econ/backpackpanel.res"