	#base	"../../../_mainstream/warpaint-seed/file.txt"
	#base	"../../../_stream/resource/ui/econ/inspectionpanel.res"
	#base	"../../../_jofrenew/resource/ui/econ/inspectionpanel.res"
	#base	"../../../_jofrehud/resource/ui/econ/inspectionpanel.res"
	#base	"../../../z_tf2/resource/ui/econ/inspectionpanel.res"