"//PLATFORM/resource/colorpicker.res"
{
	"ColorPicker"
	{
		"ControlName"	"CColorPicker"
		"fieldName"		"ColorPicker"
		"xpos"			"147"
		"ypos"			"128"
		"wide"			"640"
		"tall"			"480"
		//	"0"
		//		"0"
		"visible"		"1"
		"enabled"		"1"
		//	"0"
		"settitlebarvisible"	"1"
		"title"		"#Frame_Untitled"
		
		"ColorXYPreview"
		{
			"ControlName"	"CColorXYPreview"
			"fieldName"		"ColorXYPreview"
			"xpos"			"10"
			"ypos"			"10"
			"wide"			"256"
			"tall"			"256"
			//	"0"
			//		"0"
			"visible"		"1"
			"enabled"		"1"
			//	"0"
		}

		"ColorZPreview"
		{
			"ControlName"	"CColorZPreview"
			"fieldName"		"ColorZPreview"
			"xpos"			"274"
			"ypos"			"4"
			"wide"			"36"
			"tall"			"268"
			//	"0"
			//		"0"
			"visible"		"1"
			"enabled"		"1"
			//	"0"
		}
		
		"CurrentColor"
		{
			"ControlName"	"Panel"
			"fieldName"		"CurrentColor"
			"xpos"			"325"
			"ypos"			"10"
			"wide"			"100"
			"tall"			"50"
			//	"0"
			//		"0"
			"visible"		"1"
			"enabled"		"1"
			//	"0"
		}

		"InitialColor"
		{
			"ControlName"	"Panel"
			"fieldName"		"InitialColor"
			"xpos"			"325"
			"ypos"			"67"
			"wide"			"100"
			"tall"			"50"
			//	"0"
			//		"0"
			"visible"		"1"
			"enabled"		"1"
			//	"0"
		}

		"HueRadio"
		{
			"ControlName"		"RadioButton"
			"fieldName"		"HueRadio"
			"xpos"			"325"
			"ypos"			"125"
			"wide"			"48"
			"tall"			"24"
			//	"0"
			//		"0"
			"visible"		"1"
			"enabled"		"1"
			"selected"		"1"
			//		"8"
			"labelText"			"H"
			"wrap"				"0"
			"SubTabPosition"	"1"
		}
		
		"SaturationRadio"
		{
			"ControlName"		"RadioButton"
			"fieldName"		"SaturationRadio"
			"xpos"			"325"
			"ypos"			"150"
			"wide"			"48"
			"tall"			"24"
			//	"0"
			//		"0"
			"visible"		"1"
			"enabled"		"1"
			//		"8"
			"labelText"			"S"
			"wrap"				"0"
			"SubTabPosition"	"2"
		}
		
		"ValueRadio"
		{
			"ControlName"		"RadioButton"
			"fieldName"		"ValueRadio"
			"xpos"			"325"
			"ypos"			"175"
			"wide"			"48"
			"tall"			"24"
			//	"0"
			//		"0"
			"visible"		"1"
			"enabled"		"1"
			//		"8"
			"labelText"			"V"
			"wrap"				"0"
			"SubTabPosition"	"3"
		}
		
		"RedRadio"
		{
			"ControlName"		"RadioButton"
			"fieldName"		"RedRadio"
			"xpos"			"325"
			"ypos"			"200"
			"wide"			"48"
			"tall"			"24"
			//	"0"
			//		"0"
			"visible"		"1"
			"enabled"		"1"
			//		"8"
			"labelText"			"R"
			"wrap"				"0"
			"SubTabPosition"	"4"
		}
		
		"GreenRadio"
		{
			"ControlName"		"RadioButton"
			"fieldName"		"GreenRadio"
			"xpos"			"325"
			"ypos"			"225"
			"wide"			"48"
			"tall"			"24"
			//	"0"
			//		"0"
			"visible"		"1"
			"enabled"		"1"
			//		"8"
			"labelText"			"G"
			"wrap"				"0"
			"SubTabPosition"	"5"
		}
		
		"BlueRadio"
		{
			"ControlName"		"RadioButton"
			"fieldName"		"BlueRadio"
			"xpos"			"325"
			"ypos"			"250"
			"wide"			"48"
			"tall"			"24"
			//	"0"
			//		"0"
			"visible"		"1"
			"enabled"		"1"
			//		"8"
			"labelText"			"B"
			"wrap"				"0"
			"SubTabPosition"	"6"
		}
		
		"HueText"
		{
			"ControlName"		"TextEntry"
			"fieldName"		"HueText"
			"xpos"			"375"
			"ypos"			"125"
			"wide"			"48"
			"tall"			"24"
			//	"0"
			//		"0"
			"visible"		"1"
			"enabled"		"1"
			"NumericInputOnly" "1"
			//		"1"
			"labelText"			""
		}
		
		"SaturationText"
		{
			"ControlName"		"TextEntry"
			"fieldName"		"SaturationText"
			"xpos"			"375"
			"ypos"			"150"
			"wide"			"48"
			"tall"			"24"
			//	"0"
			//		"0"
			"visible"		"1"
			"enabled"		"1"
			"NumericInputOnly" "1"
			//		"2"
			"labelText"			""
		}

		"SaturationLabel"
		{
			"ControlName"		"Label"
			"fieldName"		"SaturationLabel"
			"xpos"			"425"
			"ypos"			"150"
			"wide"			"15"
			"tall"			"24"
			//	"0"
			//		"0"
			"visible"		"1"
			"enabled"		"1"
			"NumericInputOnly" "1"
			//		"0"
			"labelText"			"%"
		}

		"ValueText"
		{
			"ControlName"		"TextEntry"
			"fieldName"		"ValueText"
			"xpos"			"375"
			"ypos"			"175"
			"wide"			"48"
			"tall"			"24"
			//	"0"
			//		"0"
			"visible"		"1"
			"enabled"		"1"
			"NumericInputOnly" "1"
			//		"3"
			"labelText"			""
		}

		"ValueLabel"
		{
			"ControlName"		"Label"
			"fieldName"		"ValueLabel"
			"xpos"			"425"
			"ypos"			"175"
			"wide"			"15"
			"tall"			"24"
			//	"0"
			//		"0"
			"visible"		"1"
			"enabled"		"1"
			"NumericInputOnly" "1"
			//		"0"
			"labelText"			"%"
		}

		"RedText"
		{
			"ControlName"		"TextEntry"
			"fieldName"		"RedText"
			"xpos"			"375"
			"ypos"			"200"
			"wide"			"48"
			"tall"			"24"
			//	"0"
			//		"0"
			"visible"		"1"
			"enabled"		"1"
			"NumericInputOnly" "1"
			//		"4"
			"labelText"			""
		}

		"GreenText"
		{
			"ControlName"		"TextEntry"
			"fieldName"		"GreenText"
			"xpos"			"375"
			"ypos"			"225"
			"wide"			"48"
			"tall"			"24"
			//	"0"
			//		"0"
			"visible"		"1"
			"enabled"		"1"
			"NumericInputOnly" "1"
			//		"5"
			"labelText"			""
		}

		"BlueText"
		{
			"ControlName"		"TextEntry"
			"fieldName"		"BlueText"
			"xpos"			"375"
			"ypos"			"250"
			"wide"			"48"
			"tall"			"24"
			"NumericInputOnly" "1"
			//	"0"
			//		"0"
			"visible"		"1"
			"enabled"		"1"
			//		"6"
			"labelText"			""
		}		
			
		"AlphaText"
		{
			"ControlName"		"TextEntry"
			"fieldName"		"AlphaText"
			"xpos"			"375"
			"ypos"			"275"
			"wide"			"48"
			"tall"			"24"
			"NumericInputOnly" "1"
			//	"0"
			//		"0"
			"visible"		"1"
			"enabled"		"1"
			//		"7"
			"labelText"			""
		}	
		
		"AlphaLabel"
		{
			"ControlName"		"Label"
			"fieldName"		"AlphaLabel"
			"xpos"			"350"
			"ypos"			"275"
			"wide"			"15"
			"tall"			"24"
			//	"0"
			//		"0"
			"visible"		"1"
			"enabled"		"1"
			"NumericInputOnly" "1"
			//		"0"
			"labelText"			"A"
		}
	}
}
