"//PLATFORM/resource/mdlpickerfilter.res"
{
	"RenderPage"
	{
		"ControlName"	"PropertyPage"
		"fieldName"		"RenderPage"
		"xpos"			"6"
		"ypos"			"6"
		"wide"			"256"
		"tall"			"256"
		//	"0"
		//		"0"
		"visible"		"1"
		"enabled"		"1"
		//	"0"
	
		"Wireframe"
		{
			"ControlName"		"CheckButton"
			"fieldName"		"Wireframe"
			"xpos"		"6"
			"ypos"		"6"
			"wide"		"120"
			"tall"		"24"
			//		"0"
			//		"0"
			"visible"		"1"
			"enabled"		"1"
			//	"1"
			"labelText"		"Wireframe"
		}
		
		"Collision"
		{
			"ControlName"		"CheckButton"
			"fieldName"		"Collision"
			"xpos"		"6"
			"ypos"		"28"
			"wide"		"120"
			"tall"		"24"
			//		"0"
			//		"0"
			"visible"		"1"
			"enabled"		"1"
			//	"2"
			"labelText"		"Collision Model"
		}
		
		"NoGround"
		{
			"ControlName"		"CheckButton"
			"fieldName"		"NoGround"
			"xpos"		"6"
			"ypos"		"50"
			"wide"		"120"
			"tall"		"24"
			//		"0"
			//		"0"
			"visible"		"1"
			"enabled"		"1"
			//	"3"
			"labelText"		"No Ground"
		}
		
		"LockView"
		{
			"ControlName"		"CheckButton"
			"fieldName"		"LockView"
			"xpos"		"6"
			"ypos"		"72"
			"wide"		"120"
			"tall"		"24"
			//		"0"
			//		"0"
			"visible"		"1"
			"enabled"		"1"
			//	"4"
			"labelText"		"Lock View"
		}

		"ThumbnailSafeZone"
		{
			"ControlName"		"CheckButton"
			"fieldName"		"ThumbnailSafeZone"
			"xpos"		"6"
			"ypos"		"94"
			"wide"		"150"
			"tall"		"24"
			//		"0"
			//		"0"
			"visible"		"1"
			"enabled"		"1"
			//	"4"
			"labelText"		"Thumbnail Safe Zone"
		}
		
		"LookAtCamera"
		{
			"ControlName"		"CheckButton"
			"fieldName"		"LookAtCamera"
			"xpos"		"128"
			"ypos"		"6"
			"wide"		"216"
			"tall"		"24"
			//		"0"
			//		"0"
			"visible"		"1"
			"enabled"		"1"
			"selected"		"1"
			//	"5"
			"labelText"		"Look At Camera"
		}
		
		"ChooseLightProbe"
		{
			"ControlName"		"Button"
			"fieldName"		"ChooseLightProbe"
			"xpos"		"134"
			"ypos"		"34"
			"wide"		"100"
			"tall"		"24"
			//		"0"
			//		"0"
			"visible"		"1"
			"enabled"		"1"
			//		"6"
			"labelText"		"&Select Light Probe"
			"textAlignment"		"center"
			"command"		"ChooseLightProbe"
		}
	}
}