#base "../base/build-more/mainbg/main.res"
#base "../base/build-more/mainbg/position/wide450.res"
#base "../base/build-more/mainbg/position/xpos0.res"
#base "../base/build-more/mainbg/position/ypos10.res"
#base "../base/build-more/mainbg/position/tall170.res"
#base "../base/build-more/mainbg/ctrl_other.res"
#base "../base/build-more/mainbg/image/scale.res"
#base "../base/build-more/mainbg/image/color1.res"
#base "../base/build-more/mainbg/image/hud_menu_bg.res"
// hud_menu_item_bg
// hud_menu_item_bg
#base "../base/divider/main.res"
#base "../base/divider/main2.res"
#base "../base/divider/zpos1.res"
#base "../base/divider/xpos8.res"
#base "../base/divider/wide436.res"
// 4 14 0 98 105
//#base "../base/build-more/bgengineer/main.res"
//#base "../base/build-more/bgengineer/xpos405.res"

#base "../base/build-more/buildicon/main.res"
#base "../base/build-more/buildiconshadow/main.res"

#base "../base/build-more/titlelabel/main.res"
#base "../base/build-more/titlelabel/position/tall38.res"
#base "../base/build-more/titlelabel/text/left.res"
#base "../base/build-more/titlelabel/font/chalk.res"
#base "../base/build-more/cancellabel/main.res"
#base "../base/build-more/cancellabel/ctrl/cex.res"
#base "../base/build-more/cancellabel/autopin0.res"
#base "../base/build-more/cancellabel/dullbright.res"
#base "../base/build-more/cancellabel/visenabled1.res"
#base "../base/build-more/cancellabel/position/zpos1.res"
#base "../base/build-more/cancellabel/position/wide200.res"
#base "../base/build-more/cancellabel/position/tall13.res"
#base "../base/build-more/cancellabel/position/ypos35.res"
#base "../base/build-more/cancellabel/font/spec.res"
#base "../base/build-more/cancellabel/text/east.res"

#base "../base/build-more/active_item/1/ctrl_edit.res"
#base "../base/build-more/active_item/1/vis1.res"
#base "../base/build-more/active_item/1/main.res"
#base "../base/build-more/active_item/1/ypos47.res"

#base "../base/build-more/already_built/1/ctrl_edit.res"
#base "../base/build-more/already_built/1/vis0.res"
#base "../base/build-more/already_built/1/main.res"
#base "../base/build-more/already_built/1/ypos47.res"

#base "../base/build-more/cant_afford/1/ctrl_edit.res"
#base "../base/build-more/cant_afford/1/vis0.res"
#base "../base/build-more/cant_afford/1/main.res"
#base "../base/build-more/cant_afford/1/ypos47.res"

#base "../base/build-more/unavailable_item/1/ctrl_edit.res"
#base "../base/build-more/unavailable_item/1/vis0.res"
#base "../base/build-more/unavailable_item/1/main.res"
#base "../base/build-more/unavailable_item/1/ypos47.res"

