
#base "base/servernamelabel.res"
#base "base/label1_main.res"
#base "base/label1_tab.res"
#base "../#uni_base/filesv1/label4/main.res"
#base "../#uni_base/filesv1/label4/position/tall24.res"
#base "../#uni_base/filesv1/label4/text/east.res"
#base "../#uni_base/filesv1/label4/auto.res"
#base "../#uni_base/filesv1/label4/pin.res"
#base "../#uni_base/filesv1/label4/tab.res"
#base "../#uni_base/filesv1/label4/vis1.res"
#base "../#uni_base/filesv1/label4/enabled.res"
#base "../#uni_base/filesv1/label4/bright0.res"
#base "../#uni_base/filesv1/label4/dull1.res"

#base "../#uni_base/filesv3/startbutton/main.res"
#base "../#uni_base/filesv3/startbutton/ctrl/btn.res"
#base "../#uni_base/filesv3/startbutton/ctrl/position/tall24.res"
#base "../#uni_base/filesv3/startbutton/ctrl/position/wide90.res"
#base "../#uni_base/filesv3/startbutton/ctrl/auto0.res"
#base "../#uni_base/filesv3/startbutton/ctrl/pin.res"
#base "../#uni_base/filesv3/startbutton/ctrl/vis1.res"
#base "../#uni_base/filesv3/startbutton/ctrl/enabled.res"

#base "../#uni_base/filesv3/startbutton/ctrl/text/west.res"
#base "../#uni_base/filesv3/startbutton/ctrl/dull0.res"
#base "../#uni_base/filesv3/startbutton/ctrl/bright0.res"
#base "../#uni_base/filesv3/startbutton/ctrl/def1.res"

//#base "../resource/base/1sysmenu.res"

#base "../#uni_base/filesv1/cancelbutton/autoresize_pin.res"
#base "../#uni_base/filesv1/cancelbutton/ctrl/btn.res"
#base "../#uni_base/filesv1/cancelbutton/def0.res"
#base "../#uni_base/filesv1/cancelbutton/main.res"
#base "../#uni_base/filesv1/cancelbutton/vis1.res"
#base "../#uni_base/filesv1/cancelbutton/enabled.res"
#base "../#uni_base/filesv1/cancelbutton/text/west.res"
#base "../#uni_base/filesv1/cancelbutton/bright0.res"
#base "../#uni_base/filesv1/cancelbutton/tab10.res"
#base "../#uni_base/filesv1/cancelbutton/dull0.res"
#base "../#uni_base/filesv1/cancelbutton/cmd/cancel.res"
#base "../#uni_base/filesv1/cancelbutton/position/x214.res"
#base "../#uni_base/filesv1/cancelbutton/position/y318.res"
#base "../#uni_base/filesv1/cancelbutton/position/w64.res"
#base "../#uni_base/filesv1/cancelbutton/position/t24.res"