//#base "../resource/base/1sysmenu.res"
#base "base/okaybutton.res"
#base "base/okaybutton_label.res"
#base "base/label1_main.res"
#base "base/label1_tab.res"
#base "base/label1_west.res"
#base "base/label1_tallis16.res"

#base "../#uni_base/filesv1/label2/main.res"
#base "../#uni_base/filesv1/label2/auto.res"
#base "../#uni_base/filesv1/label2/pin.res"
#base "../#uni_base/filesv1/label2/tab.res"
#base "../#uni_base/filesv1/label2/vis1.res"
#base "../#uni_base/filesv1/label2/enabled.res"
#base "../#uni_base/filesv1/label2/bright0.res"
#base "../#uni_base/filesv1/label2/dull0.res"
#base "../#uni_base/filesv1/label2/text/west.res"


#base "../#uni_base/filesv1/cancelbutton/autoresize_pin.res"
#base "../#uni_base/filesv1/cancelbutton/ctrl/btn.res"
#base "../#uni_base/filesv1/cancelbutton/def0.res"
#base "../#uni_base/filesv1/cancelbutton/main.res"
#base "../#uni_base/filesv1/cancelbutton/vis1.res"
#base "../#uni_base/filesv1/cancelbutton/enabled.res"
#base "../#uni_base/filesv1/cancelbutton/text/west.res"
#base "../#uni_base/filesv1/cancelbutton/bright0.res"
#base "../#uni_base/filesv1/cancelbutton/tab7.res"
#base "../#uni_base/filesv1/cancelbutton/dull0.res"
#base "../#uni_base/filesv1/cancelbutton/cmd/close.res"
#base "../#uni_base/filesv1/cancelbutton/position/x226.res"
#base "../#uni_base/filesv1/cancelbutton/position/y246.res"
#base "../#uni_base/filesv1/cancelbutton/position/w80.res"
#base "../#uni_base/filesv1/cancelbutton/position/t24.res"