"Resource/PlayerListDialog.res"
{
"AnimationSetPicker"
{
"ControlName""CAnimationSetPicker"
"fieldName""AnimationSetPicker"
"xpos""5"
"ypos""29"
"autoResize""3"
//"pinCorner""0"
"visible""1"
////"enabled""1"
"tabPosition""0"
}
}
