"resource/ui/ReloadSchemeButton.res"
{
"ReloadSchemeButton"
{
"ControlName""CExButton"
"fieldName""ReloadSchemeButton"
"zpos""25"
"font""HudFontSmallest"
"textAlignment""center"
"textinsetx""50"
"tall""15"
"Command""reloadscheme"
//"sound_depressed""UI/buttonclick.wav"
//"sound_released""UI/buttonclickrelease.wav"
}
}