"resource/SFM_AnimationSetPicker.res"
{
"AnimationSetBrowser"
{
"ControlName""ListPanel"
"fieldName""AnimationSetBrowser"
//"pinCorner""0"
"visible""1"
////"enabled""1"
"tabPosition""0"
}
"FilterList"
{
"ControlName""TextEntry"
"fieldName""FilterList"
"tall""24"
"autoResize""1"
"visible""1"
////"enabled""1"
"tabPosition""0"
"textHidden""0"
"editable""1"
"maxchars""-1"
"NumericInputOnly""0"
"unicode""0"
}
}
