"resource/ui/hudplayerclass.res"
{

"NotBuiltLabel"
{
"ControlName""CExLabel"
"fieldName""NotBuiltLabel"
//"font""Default"
"xpos""10"
"ypos""48"
"zpos""2"
"wide""80"
"tall""18"
////"autoResize""0"
//"pinCorner""0"
//"visible""1"
////"enabled""1"
"labelText""#TF_NotBuilt"
"textAlignment""Center"
//"dulltext""0"
"brighttext""0"
}
}