"resource/BaseActionCDTrackStartDialog.res"
{
"DialogFrame"
{
"ControlName""EditablePanel"
"fieldName""DialogFrame"
//"zpos""0"
//"visible""1"
////"enabled""1"
"paintbackground""0"
"border""TFFatLineBorderOpaque"
"PaintBorder""1"
"PreviewViewportBg"
{
"ControlName""EditablePanel"
"fieldName""PreviewViewportBg"
"xpos""10"
"zpos""1"
//"visible""1"
////"enabled""1"
"paintborder""1"
"border""StoreInnerShadowBorder"
}
}
}