"classes/Default.res"
{
	"classNameLabel"
	{
		"ControlName"	"CExLabel"
		"fieldName"		"classNameLabel"
		"xpos"			"0"
		"ypos"			"0"
		"ypos_lodef"	"170"
		"zpos"			"5"	
		"wide"			"230"
		"tall"			"30"
		//	"0"
		//		"0"
		"visible"		"1"
		"enabled"		"1"
		//	"0"
		"textAlignment"	"north-west"
		"dulltext"		"0"
		"brighttext"	"1"
		"wrap"			"0"
		"font"			"ChalkboardTitleMedium"
		"fgcolor"		"White"
	}
}