#base "cs_global.res"
#base "global/bs_1.res"
#base "cs_border_1.res"
#base "bs/mainmenu_cons.res"
#base "bs/wizard.res"
#base "border/tabborder.res"
#base "border/tabactiveborder.res"
#base "border/titlebutton_2.res"
#base "border/combobox.res"
#base "border/baseborder.res"
#base "border/buttonborder.res"
#base "colors/red.res"
#base "colors/dullwhite.res"
#base "colors/offwhite.res"

//#base "colors/orange.res"