"Resource/UI/CharInfoPanel.res"
{
"PlayerStatusHealthBonusImage"
{
"ControlName""ImagePanel"
"fieldName""PlayerStatusHealthBonusImage"
"image""../hud/health_over_bg"
"visible""0"
////"enabled""1"
"scaleImage""1"
}
}