#base "../base/filesv1/zoombutton/main.res"
#base "../base/filesv1/zoombutton/content1.res"
#base "../base/filesv1/paintnamelabel/main.res"
#base "../base/filesv1/paintnamelabel/content2.res"
#base "../res_base/storepreviewitempanel.res"
#base "../../../base/filesv2/classusageimage/main.res"
#base "../../../base/filesv2/classusageimage/main2.res"