"Resource/baseaction_sys.res"
{
"CancelHintLabel"
{
"ControlName""CExLabel"
"fieldName""CancelHintLabel"
"font""ControllerHintText"
"zpos""1"
"wide""300"
"tall""39"
////"autoResize""0"
//"pinCorner""0"
//"visible""1"
////"enabled""1"
"labelText""#Cancel"
"textAlignment""Left"
//"dulltext""0"
"brighttext""0"
}
}
