"Resource/UI/HudStalemate.res"
{
	"HudStalemateBG"
	{
		"ControlName"		"CTFImagePanel"
		"fieldName"		"HudStalemateBG"
		"xpos"			"0"
		"ypos"			"0"
		"zpos"			"-1"
		"wide"			"320"
		"tall"			"150"
		//		"0"
		//		"0"
		"image"			"../hud/death_panel_black_bg"
		"scaleImage"		"1"
	}
	"StalemateLabel"
	{	
		"ControlName"		"Label"
		"fieldName"		"StalemateLabel"
		"xpos"			"25"
		"ypos"			"17"
		"zpos"			"1"
		"wide"			"280"
		"tall"			"35"
		//		"0"
		//		"0"
		"wrap"			"1"
		"labelText"		"#TF_teambalanced"
		"textAlignment"		"northwest"
	}
	"ReasonLabel"
	{	
		"ControlName"		"Label"
		"fieldName"		"ReasonLabel"
		"xpos"			"25"
		"ypos"			"34"
		"zpos"			"1"
		"wide"			"280"
		"tall"			"55"
		//		"0"
		//		"0"
		"wrap"			"1"
		"labelText"		""
		"textAlignment"		"northwest"
	}
}
