"Resource/UI/winpanel.res"
{
	"TFStatsSummary"
	{
		"ControlName"	"EditablePanel"
		"fieldName"	"TFStatsSummary"
		"xpos"		"0"
		"ypos"		"0"
		"wide"		"f0"
		"tall"		"480"
	}

	"MainBackground"
	{
		"ControlName"		"ImagePanel"
		"fieldName"		"MainBackground"
		"xpos"			"0"
		"ypos"			"0"
		"wide"			"f0"
		"tall"			"480"
		"image"			""
		"scaleImage"		"1"
	}	

	"MapInfo"
	{
		"ControlName"	"EditablePanel"
		"fieldName"	"MapInfo"
		"xpos"		"0"
		"ypos"		"0"
		"wide"		"f0"
		"tall"		"480"
		"visible"	"0"
		"bgcolor_override"	"46 43 42 255"
	
		"Background"
		{
			"ControlName"	"ImagePanel"
			"fieldName"		"Background"
			"xpos"			"0"
			"ypos"			"0"
			"wide"			"640"
			"tall"			"480"
			"image"			"stamp_background_map"
			"scaleImage"		"1"
		}

		"MapImage"
		{
			"ControlName"	"ImagePanel"
			"fieldName"		"MapImage"
			"xpos"			"30"
			"ypos"			"45"
			"zpos"			"2"
			"wide"			"300"
			"tall"			"300"
			"image"			""
			"scaleImage"	"1"		
		}
	
		"ContributedLabel"
		{
			"ControlName"	"EditablePanel"
			"fieldName"	"ContributedLabel"
			"xpos"			"30"
			"ypos"			"345"
			"zpos"			"40"
			"wide"			"300"
			"tall"			"100"
			"visible"		"0"
			"BG"
			{
				"ControlName"	"EditablePanel"
				"fieldName"		"BG"
				"xpos"			"0"
				"ypos"			"0"
				"wide"			"300"
				"tall"			"55"
				//		"0"
			}
	
			"ActualLabel"
			{
				"ControlName"		"CExLabel"
				"fieldName"		"ActualLabel"
				"labelText"		"#TF_Contributed"
				"textAlignment"		"center"
				"xpos"			"10"
				"ypos"			"0"
				"zpos"			"40"
				"wide"			"280"
				"tall"			"55"
				//		"0"
				"centerwrap"	"1"
				"wrap"			"1"
			}					
		}
	
		"InfoBG"
		{
			"ControlName"		"EditablePanel"
			"fieldName"		"InfoBG"
			"xpos"			"c+10"
			"ypos"			"120"
			"wide"			"285"
			"tall"			"280"
			//		"0"
		}

		"Title"
		{
			"ControlName"	"CExLabel"
			"fieldName"		"Title"
			"labelText"		"%title%"
			"textAlignment"	"north"
			"xpos"			"c20"
			"ypos"			"135"
			"zpos"			"2"
			"wide"			"275"
			"tall"			"30"
			//		"0"
			"fgcolor_override" "255 181 50 255"
		}
		"MapAuthors"
		{
			"ControlName"	"CExLabel"
			"fieldName"		"MapAuthors"
			"labelText"		"%authors%"
			"textAlignment"	"north"
			"xpos"			"c20"
			"ypos"			"155"
			"zpos"			"2"
			"wide"			"275"
			"tall"			"275"
			//		"0"
		}

		"MapLeaderboardTitle"
		{
			"ControlName"	"CExLabel"
			"fieldName"		"MapLeaderboardTitle"
			"labelText"		"%map_leaderboard_title%"
			"textAlignment"	"north"
			"xpos"			"c20"
			"ypos"			"230"
			"zpos"			"2"
			"wide"			"275"
			"tall"			"30"
			//		"0"
			"fgcolor_override" "137 191 60 255"
		}
	}

	"OnYourWayLabel"
	{
		"ControlName"		"CExLabel"
		"fieldName"		"OnYourWayLabel"
		"labelText"		"#LoadingMap"
		"textAlignment"		"center"
		"xpos"			"c+10"
		"ypos"			"30"
		"zpos"			"40"
		"wide"			"285"
		"tall"			"35"
		//		"0"
		"fgcolor_override" "173 168 148 255"
	}					
	"MapLabel"
	{
		"ControlName"		"CExLabel"
		"fieldName"		"MapLabel"
		"labelText"		"%maplabel%"
		"textAlignment"		"center"
		"xpos"			"c-25"
		"ypos"			"55"
		"zpos"			"50"
		"wide"			"350"
		"tall"			"35"
		//		"0"
	}
	"MapType"
	{
		"ControlName"	"CExLabel"
		"fieldName"		"MapType"
		"labelText"		"%maptype%"
		"textAlignment"	"center"
		"xpos"			"c-25"
		"ypos"			"80"
		"zpos"			"50"
		"wide"			"350"
		"tall"			"35"
		//		"0"
	}					
	"StatData"
	{
		"ControlName"	"EditablePanel"
		"fieldName"	"StatData"
		"xpos"		"0"
		"ypos"		"0"
		"zpos"		"1"
		"wide"		"f0"
		"tall"		"480"
		"NonInteractiveHeaders"
		{
			"ControlName"	"EditablePanel"
			"fieldName"	"NonInteractiveHeaders"
			"xpos"		"0"
			"ypos"		"0"
			"zpos"		"2"
			"wide"		"f0"
			"tall"		"480"
			"BarChartLabelA"
			{
				"ControlName"		"Label"
				"fieldName"		"BarChartLabelA"
				"labelText"		"#StatSummary_StatTitle_MostPoints"
				"textAlignment"		"east"
				"xpos"			"c-282"
				"ypos"			"212"
				"zpos"			"5"
				"wide"			"150" [$WIN32]
				"tall"			"20"
				//		"0"
			}
			"BarChartLabelB"
			{
				"ControlName"		"Label"
				"fieldName"		"BarChartLabelB"
				"labelText"		"#StatSummary_StatTitle_TotalPlaytime"
				"xpos"			"c-127"
				"ypos"			"212"
				"zpos"			"5"
				"wide"			"150"
				"tall"			"20"
				//		"0"
			}			
			"OverallRecordLabel"
			{
				"ControlName"		"Label"
				"fieldName"		"OverallRecordLabel"
				"labelText"		"#StatSummary_Label_AsAnyClass"
				"xpos"			"c+130"
				"ypos"			"200"
				"zpos"			"5"
				"wide"			"200"
				"tall"			"20"
				//		"0"
			}				
		}
		"InteractiveHeaders"	
		{
			"ControlName"	"EditablePanel"
			"fieldName"	"InteractiveHeaders"
			"xpos"		"0"
			"ypos"		"0"
			"zpos"		"2"
			"wide"		"f0"
			"tall"		"480"
			"BarChartComboA"
			{
				"ControlName"		"ComboBox"
				"fieldName"		"BarChartComboA"
				"xpos"		"c-285"
				"ypos"		"212"
				"zpos"		"10"
				"wide"		"154"
				"tall"		"14"
				//		"0"
				//		"1"
				"editable"		"0"
				"maxchars"		"-1"
			}
			"BarChartComboB"
			{
				"ControlName"		"ComboBox"
				"fieldName"		"BarChartComboB"
				"xpos"		"c-127"
				"ypos"		"212"
				"zpos"		"10"
				"wide"		"154"
				"tall"		"14"
				//		"0"
				//		"1"
				"editable"		"0"
				"maxchars"		"-1"
			}
			"ClassCombo"
			{
				"ControlName"		"ComboBox"
				"fieldName"		"ClassCombo"
				"xpos"		"c+124"
				"ypos"		"200"
				"zpos"		"10"
				"wide"		"167"
				"tall"		"14"
				//		"0"
				//		"1"
				"editable"		"0"
				"maxchars"		"-1"
			}
		}
		"AveragesBG"
		{
			"ControlName"		"EditablePanel"
			"fieldName"		"AveragesBG"
			"xpos"			"c-295"
			"ypos"			"165"
			"wide"			"406"
			"tall"			"300"
			//		"0"
		}
		"AveragesLabel"
		{
			"ControlName"		"Label"
			"fieldName"		"AveragesLabel"
			"labelText"		"#StatSummary_Label_PerformanceReport"
			"xpos"			"c-285"
			"wide"			"300"
			"tall"			"20"
			//		"0"
		}
		"ClassBarBG1A"
		{
			"ControlName"		"ImagePanel"
			"fieldName"		"ClassBarBG1A"
			"xpos"			"c-285"
			"ypos"			"230"
			"zpos"			"2"
			"wide"			"312"
			"tall"			"16"
			//		"0"
			//	"0"	
			"fillcolor"		"0 0 0 80"
		}	
		"ClassBarBG1B"
		{
			"ControlName"		"ImagePanel"
			"fieldName"		"ClassBarBG1B"
			"xpos"			"c+30"
			"ypos"			"230"
			"zpos"			"2"
			"wide"			"70"
			"tall"			"16"
			//		"0"
			//	"0"	
			"fillcolor"		"0 0 0 80"
		}
		"ClassBar1A"
		{
			"ControlName"		"ImagePanel"
			"fieldName"		"ClassBar1A"
			"xpos"			"c-282"
			"ypos"			"232"
			"zpos"			"3"
			"wide"			"151"
			"tall"			"12"
			//		"0"
			//	"0"	
			"fillcolor"		"162 148 135 255"
		}
		"ClassBar1B"
		{
			"ControlName"		"ImagePanel"
			"fieldName"		"ClassBar1B"
			"xpos"			"c-127"
			"ypos"			"232"
			"zpos"			"3"
			"wide"			"151"
			"tall"			"12"
			//		"0"
			//	"0"	
			"fillcolor"		"162 148 135 255"
		}	
		"ClassBarLabel1A"
		{
			"ControlName"		"Label"
			"fieldName"		"ClassBarLabel1A"
			"labelText"		"%classbarlabel1A%"
			"xpos"			"c-282"
			"ypos"			"228"
			"zpos"			"6"
			"wide"			"100"
			"tall"			"20"
			//		"0"
		}				
		"ClassBarLabel1B"
		{
			"ControlName"		"Label"
			"fieldName"		"ClassBarLabel1B"
			"labelText"		"%classbarlabel1B%"
			"xpos"			"c-127"
			"ypos"			"228"
			"zpos"			"6"
			"wide"			"100"
			"tall"			"20"
			//		"0"
		}				
		"ClassLabel1"
		{
			"ControlName"		"Label"
			"fieldName"		"ClassLabel1"
			"labelText"		"%class1%"
			"xpos"			"c+34"
			"ypos"			"228"
			"zpos"			"5"
			"wide"			"300"
			"tall"			"20"
			//		"0"
		}				
		"ClassBarBG2A"
		{
			"ControlName"		"ImagePanel"
			"fieldName"		"ClassBarBG2A"
			"xpos"			"c-285"
			"ypos"			"248"
			"zpos"			"2"
			"wide"			"312"
			"tall"			"16"
			//		"0"
			//	"0"	
			"fillcolor"		"0 0 0 80"
		}
		"ClassBarBG2B"
		{
			"ControlName"		"ImagePanel"
			"fieldName"		"ClassBarBG2B"
			"xpos"			"c+30"
			"ypos"			"248"
			"zpos"			"2"
			"wide"			"70"
			"tall"			"16"
			//		"0"
			//	"0"	
			"fillcolor"		"0 0 0 80"
		}
		"ClassBar2A"
		{
			"ControlName"		"ImagePanel"
			"fieldName"		"ClassBar2A"
			"xpos"			"c-282"
			"ypos"			"250"
			"zpos"			"3"
			"wide"			"151"
			"tall"			"12"
			//		"0"
			//	"0"	
			"fillcolor"		"93 60 27 255"
		}	
		"ClassBar2B"
		{
			"ControlName"		"ImagePanel"
			"fieldName"		"ClassBar2B"
			"xpos"			"c-127"
			"ypos"			"250"
			"zpos"			"3"
			"wide"			"151"
			"tall"			"12"
			//		"0"
			//	"0"	
			"fillcolor"		"93 60 27 255"
		}	
		"ClassBarLabel2A"
		{
			"ControlName"		"Label"
			"fieldName"		"ClassBarLabel2A"
			"labelText"		"%classbarlabel2A%"
			"xpos"			"c-282"
			"ypos"			"246"
			"zpos"			"6"
			"wide"			"100"
			"tall"			"20"
			//		"0"
		}				
		"ClassBarLabel2B"
		{
			"ControlName"		"Label"
			"fieldName"		"ClassBarLabel2B"
			"labelText"		"%classbarlabel2B%"
			"xpos"			"c-127"
			"ypos"			"246"
			"zpos"			"6"
			"wide"			"100"
			"tall"			"20"
			//		"0"
		}				
		"ClassLabel2"
		{
			"ControlName"		"Label"
			"fieldName"		"ClassLabel2"
			"labelText"		"%class2%"
			"xpos"			"c+34"
			"ypos"			"246"
			"zpos"			"5"
			"wide"			"300"
			"tall"			"20"
			//		"0"
		}				
		"ClassBarBG3A"
		{
			"ControlName"		"ImagePanel"
			"fieldName"		"ClassBarBG3A"
			"xpos"			"c-285"
			"ypos"			"266"
			"zpos"			"2"
			"wide"			"312"
			"tall"			"16"
			//		"0"
			//	"0"	
			"fillcolor"		"0 0 0 80"
		}
		"ClassBarBG3B"
		{
			"ControlName"		"ImagePanel"
			"fieldName"		"ClassBarBG3B"
			"xpos"			"c+30"
			"ypos"			"266"
			"zpos"			"2"
			"wide"			"70"
			"tall"			"16"
			//		"0"
			//	"0"	
			"fillcolor"		"0 0 0 80"
		}
		"ClassBar3A"
		{
			"ControlName"		"ImagePanel"
			"fieldName"		"ClassBar3A"
			"xpos"			"c-282"
			"ypos"			"268"
			"zpos"			"3"
			"wide"			"151"
			"tall"			"12"
			//		"0"
			//	"0"	
			"fillcolor"		"134 93 39 255"
		}	
		"ClassBar3B"
		{
			"ControlName"		"ImagePanel"
			"fieldName"		"ClassBar3B"
			"xpos"			"c-127"
			"ypos"			"268"
			"zpos"			"3"
			"wide"			"151"
			"tall"			"12"
			//		"0"
			//	"0"	
			"fillcolor"		"134 93 39 255"
		}	
		"ClassBarLabel3A"
		{
			"ControlName"		"Label"
			"fieldName"		"ClassBarLabel3A"
			"labelText"		"%classbarlabel3A%"
			"xpos"			"c-282"
			"ypos"			"264"
			"zpos"			"6"
			"wide"			"100"
			"tall"			"20"
			//		"0"
		}				
		"ClassBarLabel3B"
		{
			"ControlName"		"Label"
			"fieldName"		"ClassBarLabel3B"
			"labelText"		"%classbarlabel3B%"
			"xpos"			"c-127"
			"ypos"			"264"
			"zpos"			"6"
			"wide"			"100"
			"tall"			"20"
			//		"0"
		}				
		"ClassLabel3"
		{
			"ControlName"		"Label"
			"fieldName"		"ClassLabel3"
			"labelText"		"%class3%"
			"xpos"			"c+34"
			"ypos"			"264"
			"zpos"			"5"
			"wide"			"300"
			"tall"			"20"
			//		"0"
		}				
		"ClassBarBG4A"
		{
			"ControlName"		"ImagePanel"
			"fieldName"		"ClassBarBG4A"
			"xpos"			"c-285"
			"ypos"			"284"
			"zpos"			"2"
			"wide"			"312"
			"tall"			"16"
			//		"0"
			//	"0"	
			"fillcolor"		"0 0 0 80"
		}
		"ClassBarBG4B"
		{
			"ControlName"		"ImagePanel"
			"fieldName"		"ClassBarBG4B"
			"xpos"			"c+30"
			"ypos"			"284"
			"zpos"			"2"
			"wide"			"70"
			"tall"			"16"
			//		"0"
			//	"0"	
			"fillcolor"		"0 0 0 80"
		}
		"ClassBar4A"
		{
			"ControlName"		"ImagePanel"
			"fieldName"		"ClassBar4A"
			"xpos"			"c-282"
			"ypos"			"286"
			"zpos"			"3"
			"wide"			"151"
			"tall"			"12"
			//		"0"
			//	"0"	
			"fillcolor"		"207 147 95 255"
		}	
		"ClassBar4B"
		{
			"ControlName"		"ImagePanel"
			"fieldName"		"ClassBar4B"
			"xpos"			"c-127"
			"ypos"			"286"
			"zpos"			"3"
			"wide"			"151"
			"tall"			"12"
			//		"0"
			//	"0"	
			"fillcolor"		"207 147 95 255"
		}	
		"ClassBarLabel4A"
		{
			"ControlName"		"Label"
			"fieldName"		"ClassBarLabel4A"
			"labelText"		"%classbarlabel4A%"
			"xpos"			"c-282"
			"ypos"			"282"
			"zpos"			"6"
			"wide"			"100"
			"tall"			"20"
			//		"0"
		}				
		"ClassBarLabel4B"
		{
			"ControlName"		"Label"
			"fieldName"		"ClassBarLabel4B"
			"labelText"		"%classbarlabel4B%"
			"xpos"			"c-127"
			"ypos"			"282"
			"zpos"			"6"
			"wide"			"100"
			"tall"			"20"
			//		"0"
		}				
		"ClassLabel4"
		{
			"ControlName"		"Label"
			"fieldName"		"ClassLabel4"
			"labelText"		"%class4%"
			"xpos"			"c+34"
			"ypos"			"282"
			"zpos"			"5"
			"wide"			"300"
			"tall"			"20"
			//		"0"
		}				
		"ClassBarBG5A"
		{
			"ControlName"		"ImagePanel"
			"fieldName"		"ClassBarBG5A"
			"xpos"			"c-285"
			"ypos"			"302"
			"zpos"			"2"
			"wide"			"312"
			"tall"			"16"
			//		"0"
			//	"0"	
			"fillcolor"		"0 0 0 80"
		}
		"ClassBarBG5B"
		{
			"ControlName"		"ImagePanel"
			"fieldName"		"ClassBarBG5B"
			"xpos"			"c+30"
			"ypos"			"302"
			"zpos"			"2"
			"wide"			"70"
			"tall"			"16"
			//		"0"
			//	"0"	
			"fillcolor"		"0 0 0 80"
		}
		"ClassBar5A"
		{
			"ControlName"		"ImagePanel"
			"fieldName"		"ClassBar5A"
			"xpos"			"c-282"
			"ypos"			"304"
			"zpos"			"3"
			"wide"			"151"
			"tall"			"12"
			//		"0"
			//	"0"	
			"fillcolor"		"226 184 146 255"
		}	
		"ClassBar5B"
		{
			"ControlName"		"ImagePanel"
			"fieldName"		"ClassBar5B"
			"xpos"			"c-127"
			"ypos"			"304"
			"zpos"			"3"
			"wide"			"151"
			"tall"			"12"
			//		"0"
			//	"0"	
			"fillcolor"		"226 184 146 255"
		}	
		"ClassBarLabel5A"
		{
			"ControlName"		"Label"
			"fieldName"		"ClassBarLabel5A"
			"labelText"		"%classbarlabel5A%"
			"xpos"			"c-282"
			"ypos"			"300"
			"zpos"			"6"
			"wide"			"100"
			"tall"			"20"
			//		"0"
		}				
		"ClassBarLabel5B"
		{
			"ControlName"		"Label"
			"fieldName"		"ClassBarLabel5B"
			"labelText"		"%classbarlabel5B%"
			"xpos"			"c-127"
			"ypos"			"300"
			"zpos"			"6"
			"wide"			"100"
			"tall"			"20"
			//		"0"
		}				
		"ClassLabel5"
		{
			"ControlName"		"Label"
			"fieldName"		"ClassLabel5"
			"labelText"		"%class5%"
			"xpos"			"c+34"
			"ypos"			"300"
			"zpos"			"5"
			"wide"			"282"
			"tall"			"20"
			//		"0"
		}				
		"ClassBarBG6A"
		{
			"ControlName"		"ImagePanel"
			"fieldName"		"ClassBarBG6A"
			"xpos"			"c-285"
			"ypos"			"320"
			"zpos"			"2"
			"wide"			"312"
			"tall"			"16"
			//		"0"
			//	"0"	
			"fillcolor"		"0 0 0 80"
		}
		"ClassBarBG6B"
		{
			"ControlName"		"ImagePanel"
			"fieldName"		"ClassBarBG6B"
			"xpos"			"c+30"
			"ypos"			"320"
			"zpos"			"2"
			"wide"			"70"
			"tall"			"16"
			//		"0"
			//	"0"	
			"fillcolor"		"0 0 0 80"
		}
		"ClassBar6A"
		{
			"ControlName"		"ImagePanel"
			"fieldName"		"ClassBar6A"
			"xpos"			"c-282"
			"ypos"			"322"
			"zpos"			"3"
			"wide"			"151"
			"tall"			"12"
			//		"0"
			//	"0"	
			"fillcolor"		"162 148 135 255"
		}	
		"ClassBar6B"
		{
			"ControlName"		"ImagePanel"
			"fieldName"		"ClassBar6B"
			"xpos"			"c-127"
			"ypos"			"322"
			"zpos"			"3"
			"wide"			"151"
			"tall"			"12"
			//		"0"
			//	"0"	
			"fillcolor"		"162 148 135 255"
		}	
		"ClassBarLabel6A"
		{
			"ControlName"		"Label"
			"fieldName"		"ClassBarLabel6A"
			"labelText"		"%classbarlabel6A%"
			"xpos"			"c-282"
			"ypos"			"318"
			"zpos"			"6"
			"wide"			"100"
			"tall"			"20"
			//		"0"
		}				
		"ClassBarLabel6B"
		{
			"ControlName"		"Label"
			"fieldName"		"ClassBarLabel6B"
			"labelText"		"%classbarlabel6B%"
			"xpos"			"c-127"
			"ypos"			"318"
			"zpos"			"6"
			"wide"			"100"
			"tall"			"20"
			//		"0"
		}				
		"ClassLabel6"
		{
			"ControlName"		"Label"
			"fieldName"		"ClassLabel6"
			"labelText"		"%class6%"
			"xpos"			"c+34"
			"ypos"			"318"
			"zpos"			"5"
			"wide"			"300"
			"tall"			"20"
			//		"0"
		}				
		"ClassBarBG7A"
		{
			"ControlName"		"ImagePanel"
			"fieldName"		"ClassBarBG7A"
			"xpos"			"c-285"
			"ypos"			"338"
			"zpos"			"2"
			"wide"			"312"
			"tall"			"16"
			//		"0"
			//	"0"	
			"fillcolor"		"0 0 0 80"
		}
		"ClassBarBG7B"
		{
			"ControlName"		"ImagePanel"
			"fieldName"		"ClassBarBG7B"
			"xpos"			"c+30"
			"ypos"			"338"
			"zpos"			"2"
			"wide"			"70"
			"tall"			"16"
			//		"0"
			//	"0"	
			"fillcolor"		"0 0 0 80"
		}
		"ClassBar7A"
		{
			"ControlName"		"ImagePanel"
			"fieldName"		"ClassBar7A"
			"xpos"			"c-282"
			"ypos"			"340"
			"zpos"			"3"
			"wide"			"151"
			"tall"			"12"
			//		"0"
			//	"0"	
			"fillcolor"		"93 60 27 255"
		}	
		"ClassBar7B"
		{
			"ControlName"		"ImagePanel"
			"fieldName"		"ClassBar7B"
			"xpos"			"c-127"
			"ypos"			"340"
			"zpos"			"3"
			"wide"			"151"
			"tall"			"12"
			//		"0"
			//	"0"	
			"fillcolor"		"93 60 27 255"
		}	
		"ClassBarLabel7A"
		{
			"ControlName"		"Label"
			"fieldName"		"ClassBarLabel7A"
			"labelText"		"%classbarlabel7A%"
			"xpos"			"c-282"
			"ypos"			"336"
			"zpos"			"6"
			"wide"			"100"
			"tall"			"20"
			//		"0"
		}				
		"ClassBarLabel7B"
		{
			"ControlName"		"Label"
			"fieldName"		"ClassBarLabel7B"
			"labelText"		"%classbarlabel7B%"
			"xpos"			"c-127"
			"ypos"			"336"
			"zpos"			"6"
			"wide"			"100"
			"tall"			"20"
			//		"0"
		}				
		"ClassLabel7"
		{
			"ControlName"		"Label"
			"fieldName"		"ClassLabel7"
			"labelText"		"%class7%"
			"xpos"			"c+34"
			"ypos"			"336"
			"zpos"			"5"
			"wide"			"300"
			"tall"			"20"
			//		"0"
		}		
		"ClassBarBG8A"
		{
			"ControlName"		"ImagePanel"
			"fieldName"		"ClassBarBG8A"
			"xpos"			"c-285"
			"ypos"			"356"
			"zpos"			"2"
			"wide"			"312"
			"tall"			"16"
			//		"0"
			//	"0"	
			"fillcolor"		"0 0 0 80"
		}
		"ClassBarBG8B"
		{
			"ControlName"		"ImagePanel"
			"fieldName"		"ClassBarBG8B"
			"xpos"			"c+30"
			"ypos"			"356"
			"zpos"			"2"
			"wide"			"70"
			"tall"			"16"
			//		"0"
			//	"0"	
			"fillcolor"		"0 0 0 80"
		}
		"ClassBar8A"
		{
			"ControlName"		"ImagePanel"
			"fieldName"		"ClassBar8A"
			"xpos"			"c-282"
			"ypos"			"358"
			"zpos"			"3"
			"wide"			"151"
			"tall"			"12"
			//		"0"
			//	"0"	
			"fillcolor"		"134 93 39 255"
		}	
		"ClassBar8B"
		{
			"ControlName"		"ImagePanel"
			"fieldName"		"ClassBar8B"
			"xpos"			"c-127"
			"ypos"			"358"
			"zpos"			"3"
			"wide"			"151"
			"tall"			"12"
			//		"0"
			//	"0"	
			"fillcolor"		"134 93 39 255"
		}	
		"ClassBarLabel8A"
		{
			"ControlName"		"Label"
			"fieldName"		"ClassBarLabel8A"
			"labelText"		"%classbarlabel8A%"
			"xpos"			"c-282"
			"ypos"			"354"
			"zpos"			"6"
			"wide"			"100"
			"tall"			"20"
			//		"0"
		}				
		"ClassBarLabel8B"
		{
			"ControlName"		"Label"
			"fieldName"		"ClassBarLabel8B"
			"labelText"		"%classbarlabel8B%"
			"xpos"			"c-127"
			"ypos"			"354"
			"zpos"			"6"
			"wide"			"100"
			"tall"			"20"
			//		"0"
		}				
		"ClassLabel8"
		{
			"ControlName"		"Label"
			"fieldName"		"ClassLabel8"
			"labelText"		"%class8%"
			"xpos"			"c+34"
			"ypos"			"354"
			"zpos"			"5"
			"wide"			"300"
			"tall"			"20"
			//		"0"
		}		
		"ClassBarBG9A"
		{
			"ControlName"		"ImagePanel"
			"fieldName"		"ClassBarBG9A"
			"xpos"			"c-285"
			"ypos"			"374"
			"zpos"			"2"
			"wide"			"312"
			"tall"			"16"
			//		"0"
			//	"0"	
			"fillcolor"		"0 0 0 80"
		}
		"ClassBarBG9B"
		{
			"ControlName"		"ImagePanel"
			"fieldName"		"ClassBarBG9B"
			"xpos"			"c+30"
			"ypos"			"374"
			"zpos"			"2"
			"wide"			"70"
			"tall"			"16"
			//		"0"
			//	"0"	
			"fillcolor"		"0 0 0 80"
		}
		"ClassBar9A"
		{
			"ControlName"		"ImagePanel"
			"fieldName"		"ClassBar9A"
			"xpos"			"c-282"
			"ypos"			"376"
			"zpos"			"3"
			"wide"			"151"
			"tall"			"12"
			//		"0"
			//	"0"	
			"fillcolor"		"207 147 95 255"
		}	
		"ClassBar9B"
		{
			"ControlName"		"ImagePanel"
			"fieldName"		"ClassBar9B"
			"xpos"			"c-127"
			"ypos"			"376"
			"zpos"			"3"
			"wide"			"151"
			"tall"			"12"
			//		"0"
			//	"0"	
			"fillcolor"		"207 147 95 255"
		}	
		"ClassBarLabel9A"
		{
			"ControlName"		"Label"
			"fieldName"		"ClassBarLabel9A"
			"labelText"		"%classbarlabel9A%"
			"xpos"			"c-282"
			"ypos"			"372"
			"zpos"			"6"
			"wide"			"100"
			"tall"			"20"
			//		"0"
		}				
		"ClassBarLabel9B"
		{
			"ControlName"		"Label"
			"fieldName"		"ClassBarLabel9B"
			"labelText"		"%classbarlabel9B%"
			"xpos"			"c-127"
			"ypos"			"372"
			"zpos"			"6"
			"wide"			"100"
			"tall"			"20"
			//		"0"
		}				
		"ClassLabel9"
		{
			"ControlName"		"Label"
			"fieldName"		"ClassLabel9"
			"labelText"		"%class9%"
			"xpos"			"c+34"
			"ypos"			"372"
			"zpos"			"5"
			"wide"			"300"
			"tall"			"20"
			//		"0"
		}		
		"RecordsBG"
		{
			"ControlName"		"EditablePanel"
			"fieldName"		"RecordsBG"
			"xpos"			"c+115"
			"ypos"			"165"
			"wide"			"200"
			"tall"			"260"
			//		"0"
		}
		"RecordsLabel1"
		{
			"ControlName"		"Label"
			"fieldName"		"RecordsLabel1"
			"labelText"		"#StatSummary_Label_BestMoments"
			"xpos"			"c+124"
			"wide"			"300"
			"tall"			"20"
			//		"0"
			"visible"		"1"	[$WIN32]
		}							
		"RecordsSubBG1"
		{
			"ControlName"		"ImagePanel"
			"fieldName"		"RecordsSubBG1"
			"xpos"			"c+124"
			"ypos"			"217"
			"zpos"			"2"
			"wide"			"167"
			"tall"			"157"
			//		"0"
			//	"0"	
			"fillcolor"		"0 0 0 80"
		}
		"RecordsLabel"
		{
			"ControlName"		"Label"
			"fieldName"		"RecordsLabel"
			"labelText"		"#StatSummary_Records"
			"xpos"			"c-265"
			"ypos"			"232"
			"zpos"			"5"
			"wide"			"220"
			"tall"			"20"
			//		"0"
			"visible"		"0"	[$WIN32]
		}	
		"OverallRecord1Label"
		{
			"ControlName"		"Label"
			"fieldName"		"OverallRecord1Label"
			"labelText"		"%classrecord1label%"
			"xpos"			"c+128"
			"ypos"			"214"
			"zpos"			"5"
			"wide"			"200"
			"tall"			"20"
			//		"0"
		}							
		"OverallRecord1Value"
		{
			"ControlName"		"Label"
			"fieldName"		"OverallRecord1Value"
			"labelText"		"%classrecord1value%"
			"xpos"			"c+210"
			"ypos"			"214"
			"zpos"			"5"
			"wide"			"200"
			"tall"			"20"
			//		"0"
		}							
		"OverallRecord2Label"
		{
			"ControlName"		"Label"
			"fieldName"		"OverallRecord2Label"
			"labelText"		"%classrecord2label%"
			"xpos"			"c+128"
			"ypos"			"224"
			"zpos"			"5"
			"wide"			"200"
			"tall"			"20"
			//		"0"
		}							
		"OverallRecord2Value"
		{
			"ControlName"		"Label"
			"fieldName"		"OverallRecord2Value"
			"labelText"		"%classrecord2value%"
			"xpos"			"c+210"
			"ypos"			"224"
			"zpos"			"5"
			"wide"			"200"
			"tall"			"20"
			//		"0"
		}							
		"OverallRecord3Label"
		{
			"ControlName"		"Label"
			"fieldName"		"OverallRecord3Label"
			"labelText"		"%classrecord3label%"
			"xpos"			"c+128"
			"ypos"			"234"
			"zpos"			"5"
			"wide"			"200"
			"tall"			"20"
			//		"0"
		}							
		"OverallRecord3Value"
		{
			"ControlName"		"Label"
			"fieldName"		"OverallRecord3Value"
			"labelText"		"%classrecord3value%"
			"xpos"			"c+210"
			"ypos"			"234"
			"zpos"			"5"
			"wide"			"200"
			"tall"			"20"
			//		"0"
		}							
		"OverallRecord4Label"
		{
			"ControlName"		"Label"
			"fieldName"		"OverallRecord4Label"
			"labelText"		"%classrecord4label%"
			"xpos"			"c+128"
			"ypos"			"244"
			"zpos"			"5"
			"wide"			"200"
			"tall"			"20"
			//		"0"
		}							
		"OverallRecord4Value"
		{
			"ControlName"		"Label"
			"fieldName"		"OverallRecord4Value"
			"labelText"		"%classrecord4value%"
			"xpos"			"c+210"
			"ypos"			"244"
			"zpos"			"5"
			"wide"			"200"
			"tall"			"20"
			//		"0"
		}							
		"OverallRecord5Label"
		{
			"ControlName"		"Label"
			"fieldName"		"OverallRecord5Label"
			"labelText"		"%classrecord5label%"
			"xpos"			"c+128"
			"ypos"			"254"
			"zpos"			"5"
			"wide"			"200"
			"tall"			"20"
			//		"0"
		}							
		"OverallRecord5Value"
		{
			"ControlName"		"Label"
			"fieldName"		"OverallRecord5Value"
			"labelText"		"%classrecord5value%"
			"xpos"			"c+210"
			"ypos"			"254"
			"zpos"			"5"
			"wide"			"200"
			"tall"			"20"
			//		"0"
		}							
		"OverallRecord6Label"
		{
			"ControlName"		"Label"
			"fieldName"		"OverallRecord6Label"
			"labelText"		"%classrecord6label%"
			"xpos"			"c+128"
			"ypos"			"264"
			"zpos"			"5"
			"wide"			"200"
			"tall"			"20"
			//		"0"
		}							
		"OverallRecord6Value"
		{
			"ControlName"		"Label"
			"fieldName"		"OverallRecord6Value"
			"labelText"		"%classrecord6value%"
			"xpos"			"c+210"
			"ypos"			"264"
			"zpos"			"5"
			"wide"			"200"
			"tall"			"20"
			//		"0"
		}							
		"OverallRecord7Label"
		{
			"ControlName"		"Label"
			"fieldName"		"OverallRecord7Label"
			"labelText"		"%classrecord7label%"
			"xpos"			"c+128"
			"ypos"			"274"
			"zpos"			"5"
			"wide"			"200"
			"tall"			"20"
			//		"0"
		}							
		"OverallRecord7Value"
		{
			"ControlName"		"Label"
			"fieldName"		"OverallRecord7Value"
			"labelText"		"%classrecord7value%"
			"xpos"			"c+210"
			"ypos"			"274"
			"zpos"			"5"
			"wide"			"200"
			"tall"			"20"
			//		"0"
		}							
		"OverallRecord8Label"
		{
			"ControlName"		"Label"
			"fieldName"		"OverallRecord8Label"
			"labelText"		"%classrecord8label%"
			"xpos"			"c+128"
			"ypos"			"284"
			"zpos"			"5"
			"wide"			"200"
			"tall"			"20"
			//		"0"
		}							
		"OverallRecord8Value"
		{
			"ControlName"		"Label"
			"fieldName"		"OverallRecord8Value"
			"labelText"		"%classrecord8value%"
			"xpos"			"c+210"
			"ypos"			"284"
			"zpos"			"5"
			"wide"			"200"
			"tall"			"20"
			//		"0"
		}
		"OverallRecord9Label"
		{
			"ControlName"		"Label"
			"fieldName"		"OverallRecord9Label"
			"labelText"		"%classrecord9label%"
			"xpos"			"c+128"
			"ypos"			"294"
			"zpos"			"5"
			"wide"			"200"
			"tall"			"20"
			//		"0"
		}							
		"OverallRecord9Value"
		{
			"ControlName"		"Label"
			"fieldName"		"OverallRecord9Value"
			"labelText"		"%classrecord9value%"
			"xpos"			"c+210"
			"ypos"			"294"
			"zpos"			"5"
			"wide"			"200"
			"tall"			"20"
			//		"0"
		}
		"OverallRecord10Label"
		{
			"ControlName"		"Label"
			"fieldName"		"OverallRecord10Label"
			"labelText"		"%classrecord10label%"
			"xpos"			"c+128"
			"ypos"			"304"
			"zpos"			"5"
			"wide"			"200"
			"tall"			"20"
			//		"0"
		}							
		"OverallRecord10Value"
		{
			"ControlName"		"Label"
			"fieldName"		"OverallRecord10Value"
			"labelText"		"%classrecord10value%"
			"xpos"			"c+210"
			"ypos"			"304"
			"zpos"			"5"
			"wide"			"200"
			"tall"			"20"
			//		"0"
		}
		"OverallRecord11Label"
		{
			"ControlName"		"Label"
			"fieldName"		"OverallRecord11Label"
			"labelText"		"%classrecord11label%"
			"xpos"			"c+128"
			"ypos"			"314"
			"zpos"			"5"
			"wide"			"200"
			"tall"			"20"
			//		"0"
		}							
		"OverallRecord11Value"
		{
			"ControlName"		"Label"
			"fieldName"		"OverallRecord11Value"
			"labelText"		"%classrecord11value%"
			"xpos"			"c+210"
			"ypos"			"314"
			"zpos"			"5"
			"wide"			"200"
			"tall"			"20"
			//		"0"
		}
		"OverallRecord12Label"
		{
			"ControlName"		"Label"
			"fieldName"		"OverallRecord12Label"
			"labelText"		"%classrecord12label%"
			"xpos"			"c+128"
			"ypos"			"324"
			"zpos"			"5"
			"wide"			"200"
			"tall"			"20"
			//		"0"
		}							
		"OverallRecord12Value"
		{
			"ControlName"		"Label"
			"fieldName"		"OverallRecord12Value"
			"labelText"		"%classrecord12value%"
			"xpos"			"c+210"
			"ypos"			"324"
			"zpos"			"5"
			"wide"			"200"
			"tall"			"20"
			//		"0"
		}
		"OverallRecord13Label"
		{
			"ControlName"		"Label"
			"fieldName"		"OverallRecord13Label"
			"labelText"		"%classrecord13label%"
			"xpos"			"c+128"
			"ypos"			"334"
			"zpos"			"5"
			"wide"			"200"
			"tall"			"20"
			//		"0"
		}							
		"OverallRecord13Value"
		{
			"ControlName"		"Label"
			"fieldName"		"OverallRecord13Value"
			"labelText"		"%classrecord13value%"
			"xpos"			"c+210"
			"ypos"			"334"
			"zpos"			"5"
			"wide"			"200"
			"tall"			"20"
			//		"0"
		}
		"OverallRecord14Label"
		{
			"ControlName"		"Label"
			"fieldName"		"OverallRecord14Label"
			"labelText"		"%classrecord14label%"
			"xpos"			"c+128"
			"ypos"			"344"
			"zpos"			"5"
			"wide"			"200"
			"tall"			"20"
			//		"0"
		}							
		"OverallRecord14Value"
		{
			"ControlName"		"Label"
			"fieldName"		"OverallRecord14Value"
			"labelText"		"%classrecord14value%"
			"xpos"			"c+210"
			"ypos"			"344"
			"zpos"			"5"
			"wide"			"200"
			"tall"			"20"
			//		"0"
		}
		"OverallRecord15Label"
		{
			"ControlName"		"Label"
			"fieldName"		"OverallRecord15Label"
			"labelText"		"%classrecord15label%"
			"xpos"			"c+128"
			"ypos"			"354"
			"zpos"			"5"
			"wide"			"200"
			"tall"			"20"
			//		"0"
		}							
		"OverallRecord15Value"
		{
			"ControlName"		"Label"
			"fieldName"		"OverallRecord15Value"
			"labelText"		"%classrecord15value%"
			"xpos"			"c+210"
			"ypos"			"354"
			"zpos"			"5"
			"wide"			"200"
			"tall"			"20"
			//		"0"
		}
	}
	"TipImage"
	{
		"ControlName"	"CTFImagePanel"
		"fieldName"		"TipImage"
		"xpos"			"c-285"
		"ypos"			"412"
		"zpos"			"12"
		"wide"			"35"
		"tall"			"35"
		"visible"		"0"
		"image"			""	
		"scaleImage"	"1"	
	}
	"TipText"
	{
		"ControlName"		"Label"
		"fieldName"		"TipText"
		"labelText"		"%tiptext%"
		"xpos"			"c-245"
		"ypos"			"405"
		"zpos"			"12"
		"wide"			"350"
		"tall"			"48"
		//		"0"
		"wrap"			"1"
	}
	"NextTipButton" [$WIN32]
	{
		"ControlName"		"Button"
		"fieldName"		"NextTipButton"
		"xpos"			"c-248"
		"ypos"			"310"
		"zpos"			"6"
		"wide"			"90"
		"tall"			"15"
		//		"0"
		//	"0"
		"labelText"		"#TF_NextTip"
		"textAlignment"	"center"
		"Command"		"nexttip"
	}
	"ResetStatsButton" [$WIN32]
	{
		"ControlName"		"Button"
		"fieldName"		"ResetStatsButton"
		"xpos"			"c130"
		"ypos"			"270"
		"zpos"			"6"
		"wide"			"150"
		"tall"			"30"
		//		"0"
		//	"0"
		"labelText"		"#TF_ResetStats"
		"textAlignment"	"center"
		"Command"		"resetstatsbutton"
	}
	"CloseButton" [$WIN32]
	{
		"ControlName"		"Button"
		"fieldName"		"CloseButton"
		"xpos"			"r190"
		"ypos"			"r50"
		"zpos"			"6"
		"wide"			"150"
		"tall"			"30"
		//		"2"
		"visible"		"0"
		//	"0"
		"labelText"		"#TF_Close"
		"textAlignment"	"center"
		"Command"		"vguicancel"
	}
}
