#base "../base/build-more/mainbg/main.res"
#base "../base/build-more/mainbg/position/wide450.res"
#base "../base/build-more/mainbg/position/xpos0.res"
#base "../base/build-more/mainbg/position/tall170.res"
#base "../base/build-more/mainbg/ctrl_other.res"
#base "../base/build-more/mainbg/image/scale.res"
#base "../base/build-more/mainbg/image/color1.res"
#base "../base/build-more/mainbg/image/hud_menu_bg.res"

#base "../base/build-more/buildicon/main.res"
#base "../base/build-more/buildiconshadow/main.res"

#base "../base/build-more/titlelabel/main.res"
#base "../base/build-more/titlelabel/font/giant.res"
#base "../base/build-more/titlelabel/content1.res"
#base "../base/build-more/titlelabel/position/tall38.res"
#base "../base/build-more/titlelabel/text/left.res"

#base "../base/build-more/titlelabelshadow/main.res"
#base "../base/build-more/titlelabelshadow/font/giant.res"
#base "../base/build-more/titlelabelshadow/position/content1.res"
#base "../base/build-more/titlelabelshadow/position/tall38.res"
#base "../base/build-more/titlelabelshadow/text/left.res"

#base "../base/build-more/available_target/1/new/ctrl_edit.res"
#base "../base/build-more/available_target/1/new/vis1.res"
#base "../base/build-more/available_target/1/new/main.res"
#base "../base/build-more/available_target/1/new/ypos47.res"

#base "../base/build-more/unavailable_target/1/new/ctrl_edit.res"
#base "../base/build-more/unavailable_target/1/vis1.res"
#base "../base/build-more/unavailable_target/1/new/main.res"
#base "../base/build-more/unavailable_target/1/new/ypos47.res"