"AddOns/Chess/DialogChessPawnPromote.res"
{
	"DialogChessPawnPromote"
	{
		"ControlName"		"CDialogChessPawnPromote"
		"fieldName"		"DialogChessPawnPromote"
		"xpos"		"519"
		"ypos"		"306"
		"wide"		"250"
		"tall"		"230"
		//		"0"
		//		"0"
		"visible"		"1"
		"enabled"		"1"
		//		"0"
	}
	"TextLabel"
	{
		"ControlName"		"Label"
		"fieldName"		"TextLabel"
		"xpos"		"15"
		"ypos"		"35"
		"wide"		"225"
		"tall"		"40"
		//		"0"
		//		"0"
		"visible"		"1"
		"enabled"		"1"
		//		"0"
		"labelText"		"#Chess_PawnPromotion_Text"
		"textAlignment"		"west"
		////		"0"
		////		"0"
	}
	"QueenBtn"
	{
		"ControlName"		"Button"
		"fieldName"		"QueenBtn"
		"xpos"		"55"
		"ypos"		"84"
		"wide"		"128"
		"tall"		"24"
		//		"0"
		//		"0"
		"visible"		"1"
		"enabled"		"1"
		//		"0"
		"labelText"		"#Chess_PromoteQueen"
		"textAlignment"		"west"
		////		"0"
		////		"0"
		"Default"		"0"
	}
	"RookBtn"
	{
		"ControlName"		"Button"
		"fieldName"		"RookBtn"
		"xpos"		"55"
		"ypos"		"115"
		"wide"		"128"
		"tall"		"24"
		//		"0"
		//		"0"
		"visible"		"1"
		"enabled"		"1"
		//		"0"
		"labelText"		"#Chess_PromoteRook"
		"textAlignment"		"west"
		////		"0"
		////		"0"
		"Default"		"0"
	}
	"BishopBtn"
	{
		"ControlName"		"Button"
		"fieldName"		"BishopBtn"
		"xpos"		"55"
		"ypos"		"145"
		"wide"		"128"
		"tall"		"24"
		//		"0"
		//		"0"
		"visible"		"1"
		"enabled"		"1"
		//		"0"
		"labelText"		"#Chess_PromoteBishop"
		"textAlignment"		"west"
		////		"0"
		////		"0"
		"Default"		"0"
	}
	"KnightBtn"
	{
		"ControlName"		"Button"
		"fieldName"		"KnightBtn"
		"xpos"		"55"
		"ypos"		"176"
		"wide"		"128"
		"tall"		"24"
		//		"0"
		//		"0"
		"visible"		"1"
		"enabled"		"1"
		//		"0"
		"labelText"		"#Chess_PromoteKnight"
		"textAlignment"		"west"
		////		"0"
		////		"0"
		"Default"		"1"
	}
}
