#base "../../../#uni_base/filesv1/maplabel/main.res"
#base "../../../#uni_base/filesv1/maplabel/controlname/cex.res"
#base "hudinspectpanel.res"
#base "spec/new/classorteamlabel.res"
#base "spec/new/switchcammodekeylabel.res"
#base "spec/new/cycletargetfwdkeylabel.res"
#base "spec/new/cycletargetfwdlabel.res"
#base "spec/new/cycletargetrevkeylabel.res"
#base "spec/new/cycletargetrevlabel.res"

#base "spec/new/switchcammodekeylabel.res"
#base "spec/new/tiplabel.res"
#base "spec/new/switchcammodelabel.res"

#base "spec/spec_extra.res"
//#base "spec/buybacklabel.res"
#base "spec/reinforcementslabel.res"