"friends/AddFriendResultSubPanel.res"
{
"AcceptButton"
{
//"sound_depressed""UI/buttonclick.wav"
//"sound_released""UI/buttonclickrelease.wav"
}
"DeclineButton"
{
//"sound_depressed""UI/buttonclick.wav"
//"sound_released""UI/buttonclickrelease.wav"
}}
