"Resource/baseaction_sys.res"
{
"ItemEffectMeterBG"
{
"image""../hud/misc_ammo_area_horiz2_blue"
"teambg_2""../hud/misc_ammo_area_horiz2_red"
//"teambg_2_lodef""../hud/misc_ammo_area_red_lodef"
"teambg_3""../hud/misc_ammo_area_horiz2_blue"
//"teambg_3_lodef""../hud/misc_ammo_area_blue_lodef"
}
}
