#base "../../../base/filesv1/notifipresentpanel/main.res"
#base "../../../base/filesv1/notifipresentpanel/content1.res"
#base "../../../base/filesv1/armory_panel/main.res"
#base "../../../base/filesv2/footerline/main.res"
#base "../../../base/filesv2/footerline/xpos0.res"
#base "../../../base/filesv2/footerline/ypos420.res"
#base "../../../base/filesv2/footerline/zpos2.res"

#base "../../../../../#uni_base/filesv1/closebutton/main.res"
#base "../../../../../#uni_base/filesv1/closebutton/vis1.res"
#base "../../../../../#uni_base/filesv1/closebutton/position/tall25.res"
#base "../../../../../#uni_base/filesv1/closebutton/label/gameui_close.res"
#base "../../../../../#uni_base/filesv1/closebutton/text/center.res"
#base "../../../../../#uni_base/filesv1/closebutton/enabled.res"
#base "../../../../../#uni_base/filesv1/closebutton/ctrl/cex.res"
#base "../../../../../#uni_base/filesv1/closebutton/def1.res"
#base "../../../../../#uni_base/filesv1/closebutton/tab.res"
#base "../../../../../#uni_base/filesv1/closebutton/dull0.res"
#base "../../../../../#uni_base/filesv1/closebutton/bright0.res"
#base "../../../../../#uni_base/filesv1/closebutton/sound.res"

#base "../../../../../#uni_base/filesv1/closebutton/font/hudfontsmallbold.res"
#base "../../../../../#uni_base/filesv1/closebutton/auto.res"
#base "../../../../../#uni_base/filesv1/closebutton/pin3.res"
#base "../../../../../#uni_base/filesv1/closebutton/cmd/close.res"