"j"
{
	"CustomizationMenu"
	{
		"MainPanel"
		{
			"MenuContainer"
			{
				
				"BGButtons"
				{
	
					"choosedef"
					{
						"ControlName"			"CExButton"
						"fieldName"				"choosedef"
						"xpos"					"0"
						"zpos"					"0"
						"wide"					"470"
						"tall"					"40"
						"proportionaltoparent"	"1"
						"labeltext"				"Keep Gray solid color one! (Removes bg)"
						"font"					"Noto20"
						"textalignment"			"center"
"command" "engine sixense_clear_bindings; sixense_write_bindings _jp_stat_bg.txt"
						"actionsignallevel"		"5" 
						"actionsignallevel"		"5" 
						"paintbackground"		"1"
							"defaultBgColor_override" 	"NotoBlack"
		"armedBgColor_override"		"Notowhite"
		"depressedBgColor_override" "0 0 0 0"
		"selectedBgColor_override" 	"NotoBlueSolid"
		
		"defaultFgColor_override" 	"NotoWhite"
		"armedFgColor_override"		"NotoBlack"
		"depressedFgColor_override" "NotoWhite"
		"selectedFgColor_override" 	"NotoBlack"			
						"border_default"		"FLAT_Black_4"
						"border_armed"			"FLAT_Black_2"
						"sound_depressed"		"UI/buttonclick.wav"
						"sound_released"		"UI/buttonclickrelease.wav"

					}	
					"choosecustom1"
					{
						"ControlName"			"CExButton"
						"fieldName"				"choosecustom1"
						"xpos"					"0"
						"ypos"					"40" 
						"wide"					"470"
						"tall"					"180"
						"textinsety"			"10"
						"labeltext"				"InsomniaHUD BG"
						"font"					"Regular12"
						"textalignment"			"north"
"command" "engine sixense_clear_bindings; sixense_write_bindings _jp_stat_bg.txt;con_logfile cfg/_jp_stat_bg.txt; echo #base ../custom/jofrehud-main/_jofrenew/new/ui_overrides/background/lead.res; con_logfile ."
						"actionsignallevel"		"5" 
						"paintbackground"		"0"
						"border_default"		"FLAT_Black_4"
						"border_armed"			"FLAT_Black_2"
						"sound_depressed"		"UI/buttonclick.wav"
						"sound_released"		"UI/buttonclickrelease.wav"

					}	
		"custombgshowcase"
		{
			"ControlName"							"ImagePanel"
			"fieldName"								"custombgshowcase"
			"xpos"									"80"
			"ypos"									"60"
			"wide"									"300"
			"tall"									"o0.5"
			"proportionaltoparent"					"1"
			"scaleImage"							"1"
			"mouseinputenabled"		"0"
			"drawcolor"	"Primary"
			"image"									replay/thumbnails/ui_effects/menu_glow
		}								
					"choosecustom2"
					{
						"textinsety"			"10"
						"ControlName"			"CExButton"
						"fieldName"				"choosecustom2"
						"xpos"					"0"
						"ypos"					"220"
						"wide"					"470"
						"tall"					"180"
						"proportionaltoparent"	"1"
						"labeltext"				"Gruvbox"
						"font"					"Regular12"
						"textalignment"			"north"
"command" "engine sixense_clear_bindings; sixense_write_bindings _jp_stat_bg.txt;con_logfile cfg/_jp_stat_bg.txt; echo #base ../custom/jofrehud-main/_jofrenew/new/ui_overrides/background/gruvbox1.res; con_logfile ."
						"actionsignallevel"		"5" 
						"actionsignallevel"		"5" 
						"paintbackground"		"0"
						"border_default"		"FLAT_Black_4"
						"border_armed"			"FLAT_Black_2"
						"sound_depressed"		"UI/buttonclick.wav"
						"sound_released"		"UI/buttonclickrelease.wav"

					}		
		"custombgshowcase2"
		{
			"ControlName"							"ImagePanel"
			"fieldName"								"custombgshowcase2"
			"xpos"									"80"
			"ypos"									"220+20"
			"wide"									"300"
			"tall"									"o0.5"
			"proportionaltoparent"					"1"
			"scaleImage"							"1"
			"mouseinputenabled"		"0"
			"image"									"replay/thumbnails/gruvbox"
		}	
							"choosecustom3"
					{
						"ControlName"			"CExButton"
						"fieldName"				"choosecustom3"
						"xpos"					"0"
						"ypos"					"400" 
						"wide"					"470"
						"tall"					"180"
						"textinsety"			"10"
						"labeltext"				"Danganronpa"
						"font"					"Regular12"
						"textalignment"			"north"
"command" "engine sixense_clear_bindings; sixense_write_bindings _jp_stat_bg.txt;con_logfile cfg/_jp_stat_bg.txt; echo #base ../custom/jofrehud-main/_jofrenew/new/ui_overrides/background/danganronpa.res; con_logfile ."
						"actionsignallevel"		"5" 
						"paintbackground"		"0"
						"border_default"		"FLAT_Black_4"
						"border_armed"			"FLAT_Black_2"
						"sound_depressed"		"UI/buttonclick.wav"
						"sound_released"		"UI/buttonclickrelease.wav"

					}	
		"custombgshowcase3"
		{
			"ControlName"							"ImagePanel"
			"fieldName"								"custombgshowcase3"
			"xpos"									"80"
			"ypos"									"400+20"
			"wide"									"300"
			"tall"									"o0.5"
			"proportionaltoparent"					"1"
			"scaleImage"							"1"
			"mouseinputenabled"		"0"
			"image"									"replay/thumbnails/danganronpa"
		}	
							"choosecustom4"
					{
						"ControlName"			"CExButton"
						"fieldName"				"choosecustom4"
						"xpos"					"0"
						"ypos"					"400+180" 
						"wide"					"470"
						"tall"					"180"
						"textinsety"			"10"
						"labeltext"				"Abstract"
						"font"					"Regular12"
						"textalignment"			"north"
"command" "engine sixense_clear_bindings; sixense_write_bindings _jp_stat_bg.txt;con_logfile cfg/_jp_stat_bg.txt; echo #base ../custom/jofrehud-main/_jofrenew/new/ui_overrides/background/abstract.res; con_logfile ."
						"actionsignallevel"		"5" 
						"paintbackground"		"0"
						"border_default"		"FLAT_Black_4"
						"border_armed"			"FLAT_Black_2"
						"sound_depressed"		"UI/buttonclick.wav"
						"sound_released"		"UI/buttonclickrelease.wav"

					}	
		"custombgshowcase4"
		{
			"ControlName"							"ImagePanel"
			"fieldName"								"custombgshowcase4"
			"xpos"									"80"
			"ypos"									"400+180+20"
			"wide"									"300"
			"tall"									"o0.5"
			"proportionaltoparent"					"1"
			"scaleImage"							"1"
			"mouseinputenabled"		"0"
			"image"									"replay/thumbnails/abstract"
		}			

							"choosecustom5"
					{
						"ControlName"			"CExButton"
						"fieldName"				"choosecustom5"
						"xpos"					"0"
						"ypos"					"400+180+180" 
						"wide"					"470"
						"tall"					"180"
						"textinsety"			"10"
						"labeltext"				"Beach"
						"font"					"Regular12"
						"textalignment"			"north"
"command" "engine sixense_clear_bindings; sixense_write_bindings _jp_stat_bg.txt;con_logfile cfg/_jp_stat_bg.txt; echo #base ../custom/jofrehud-main/_jofrenew/new/ui_overrides/background/beach.res; con_logfile ."
						"actionsignallevel"		"5" 
						"paintbackground"		"0"
						"border_default"		"FLAT_Black_4"
						"border_armed"			"FLAT_Black_2"
						"sound_depressed"		"UI/buttonclick.wav"
						"sound_released"		"UI/buttonclickrelease.wav"

					}	
		"custombgshowcase5"
		{
			"ControlName"							"ImagePanel"
			"fieldName"								"custombgshowcase5"
			"xpos"									"80"
			"ypos"									"400+180+180+20"
			"wide"									"300"
			"tall"									"o0.5"
			"proportionaltoparent"					"1"
			"scaleImage"							"1"
			"mouseinputenabled"		"0"
			"image"									"replay/thumbnails/beach"
		}			
		"choosecustom6"
{
	"ControlName"			"CExButton"
	"fieldName"				"choosecustom6"
	"xpos"					"0"
	"ypos"					"400+180+180+180" 
	"wide"					"470"
	"tall"					"180"
	"textinsety"			"10"
	"labeltext"				"Old1"
	"font"					"Regular12"
	"textalignment"			"north"
"command" "engine sixense_clear_bindings; sixense_write_bindings _jp_stat_bg.txt;con_logfile cfg/_jp_stat_bg.txt; echo #base ../custom/jofrehud-main/_jofrenew/new/ui_overrides/background/old1.res; con_logfile ."
	"actionsignallevel"		"5" 
	"paintbackground"		"0"
	"border_default"		"FLAT_Black_4"
	"border_armed"			"FLAT_Black_2"
	"sound_depressed"		"UI/buttonclick.wav"
	"sound_released"		"UI/buttonclickrelease.wav"

}	
"custombgshowcase6"
{
"ControlName"							"ImagePanel"
"fieldName"								"custombgshowcase6"
"xpos"									"80"
"ypos"									"400+180+180+20+180"
"wide"									"300"
"tall"									"o0.5"
"proportionaltoparent"					"1"
"scaleImage"							"1"
"mouseinputenabled"		"0"
"image"									"replay/thumbnails/old1"
}		
"choosecustom7"
{
	"ControlName"			"CExButton"
	"fieldName"				"choosecustom7"
	"xpos"					"0"
	"ypos"					"400+180+180+180+180" 
	"wide"					"470"
	"tall"					"180"
	"textinsety"			"10"
	"labeltext"				"Old2"
	"font"					"Regular12"
	"textalignment"			"north"
"command" "engine sixense_clear_bindings; sixense_write_bindings _jp_stat_bg.txt;con_logfile cfg/_jp_stat_bg.txt; echo #base ../custom/jofrehud-main/_jofrenew/new/ui_overrides/background/old2.res; con_logfile ."
	"actionsignallevel"		"5" 
	"paintbackground"		"0"
	"border_default"		"FLAT_Black_4"
	"border_armed"			"FLAT_Black_2"
	"sound_depressed"		"UI/buttonclick.wav"
	"sound_released"		"UI/buttonclickrelease.wav"

}	
"custombgshowcase7"
{
"ControlName"							"ImagePanel"
"fieldName"								"custombgshowcase7"
"xpos"									"80"
"ypos"									"400+180+180+20+180+180"
"wide"									"300"
"tall"									"o0.5"
"proportionaltoparent"					"1"
"scaleImage"							"1"
"mouseinputenabled"		"0"
"image"									"replay/thumbnails/old2"
}	
"choosecustom8"
{
	"ControlName"			"CExButton"
	"fieldName"				"choosecustom8"
	"xpos"					"0"
	"ypos"					"400+180+180+180+180+180" 
	"wide"					"470"
	"tall"					"180"
	"textinsety"			"10"
	"labeltext"				"No Man Sky"
	"font"					"Regular12"
	"textalignment"			"north"
"command" "engine sixense_clear_bindings; sixense_write_bindings _jp_stat_bg.txt;con_logfile cfg/_jp_stat_bg.txt; echo #base ../custom/jofrehud-main/_jofrenew/new/ui_overrides/background/nomansky.res; con_logfile ."
	"actionsignallevel"		"5" 
	"paintbackground"		"0"
	"border_default"		"FLAT_Black_4"
	"border_armed"			"FLAT_Black_2"
	"sound_depressed"		"UI/buttonclick.wav"
	"sound_released"		"UI/buttonclickrelease.wav"

}	
"custombgshowcase8"
{
"ControlName"							"ImagePanel"
"fieldName"								"custombgshowcase8"
"xpos"									"80"
"ypos"									"400+180+180+20+180+180+180"
"wide"									"300"
"tall"									"o0.5"
"proportionaltoparent"					"1"
"scaleImage"							"1"
"mouseinputenabled"		"0"
"image"									"replay/thumbnails/nomansky"
}	

"choosecustom9"
{
	"ControlName"			"CExButton"
	"fieldName"				"choosecustom9"
	"xpos"					"0"
	"ypos"					"400+180+180+180+180+180+180" 
	"wide"					"470"
	"tall"					"180"
	"textinsety"			"10"
	"labeltext"				"Pink"
	"font"					"Regular12"
	"textalignment"			"north"
"command" "engine sixense_clear_bindings; sixense_write_bindings _jp_stat_bg.txt;con_logfile cfg/_jp_stat_bg.txt; echo #base ../custom/jofrehud-main/_jofrenew/new/ui_overrides/background/pink.res; con_logfile ."
	"actionsignallevel"		"5" 
	"paintbackground"		"0"
	"border_default"		"FLAT_Black_4"
	"border_armed"			"FLAT_Black_2"
	"sound_depressed"		"UI/buttonclick.wav"
	"sound_released"		"UI/buttonclickrelease.wav"

}	
"custombgshowcase9"
{
"ControlName"							"ImagePanel"
"fieldName"								"custombgshowcase9"
"xpos"									"80"
"ypos"									"400+180+180+20+180+180+180+180"
"wide"									"300"
"tall"									"o0.5"
"proportionaltoparent"					"1"
"scaleImage"							"1"
"mouseinputenabled"		"0"
"image"									"replay/thumbnails/pink"
}
"choosecustom10"
{
	"ControlName"			"CExButton"
	"fieldName"				"choosecustom10"
	"xpos"					"0"
	"ypos"					"400+180+180+180+180+180+180+180" 
	"wide"					"470"
	"tall"					"180"
	"textinsety"			"10"
	"labeltext"				"-"
	"font"					"Regular12"
	"textalignment"			"north"
"command" "engine sixense_clear_bindings; sixense_write_bindings _jp_stat_bg.txt;con_logfile cfg/_jp_stat_bg.txt; echo #base ../custom/jofrehud-main/_jofrenew/new/ui_overrides/background/nsfw1.res; con_logfile ."
	"actionsignallevel"		"5" 
	"paintbackground"		"0"
	"border_default"		"FLAT_Black_4"
	"border_armed"			"FLAT_Black_2"
	"sound_depressed"		"UI/buttonclick.wav"
	"sound_released"		"UI/buttonclickrelease.wav"

}	
"custombgshowcase10"
{
"ControlName"							"ImagePanel"
"fieldName"								"custombgshowcase10"
"xpos"									"80"
"ypos"									"400+180+180+20+180+180+180+180+180"
"wide"									"300"
"tall"									"o0.5"
"proportionaltoparent"					"1"
"scaleImage"							"1"
"mouseinputenabled"		"0"
"image"									"replay/thumbnails/nsfw1"
}
"choosecustom11"
{
	"ControlName"			"CExButton"
	"fieldName"				"choosecustom11"
	"xpos"					"0"
	"ypos"					"400+180+180+180+180+180+180+180+180" 
	"wide"					"470"
	"tall"					"180"
	"textinsety"			"10"
	"labeltext"				"-"
	"font"					"Regular12"
	"textalignment"			"north"
"command" "engine sixense_clear_bindings; sixense_write_bindings _jp_stat_bg.txt;con_logfile cfg/_jp_stat_bg.txt; echo #base ../custom/jofrehud-main/_jofrenew/new/ui_overrides/background/nsfw2.res; con_logfile ."
	"actionsignallevel"		"5" 
	"paintbackground"		"0"
	"border_default"		"FLAT_Black_4"
	"border_armed"			"FLAT_Black_2"
	"sound_depressed"		"UI/buttonclick.wav"
	"sound_released"		"UI/buttonclickrelease.wav"

}	
"custombgshowcase11"
{
"ControlName"							"ImagePanel"
"fieldName"								"custombgshowcase11"
"xpos"									"80"
"ypos"									"400+180+180+20+180+180+180+180+180+180"
"wide"									"300"
"tall"									"o0.5"
"proportionaltoparent"					"1"
"scaleImage"							"1"
"mouseinputenabled"		"0"
"image"									"replay/thumbnails/nsfw2"
}
"choosecustom12"
{
	"ControlName"			"CExButton"
	"fieldName"				"choosecustom12"
	"xpos"					"0"
	"ypos"					"400+180+180+180+180+180+180+180+180+180" 
	"wide"					"470"
	"tall"					"180"
	"textinsety"			"10"
	"labeltext"				"-"
	"font"					"Regular12"
	"textalignment"			"north"
"command" "engine sixense_clear_bindings; sixense_write_bindings _jp_stat_bg.txt;con_logfile cfg/_jp_stat_bg.txt; echo #base ../custom/jofrehud-main/_jofrenew/new/ui_overrides/background/miku1.res; con_logfile ."
	"actionsignallevel"		"5" 
	"paintbackground"		"0"
	"border_default"		"FLAT_Black_4"
	"border_armed"			"FLAT_Black_2"
	"sound_depressed"		"UI/buttonclick.wav"
	"sound_released"		"UI/buttonclickrelease.wav"

}	
"custombgshowcase12"
{
"ControlName"							"ImagePanel"
"fieldName"								"custombgshowcase12"
"xpos"									"80"
"ypos"									"400+180+180+20+180+180+180+180+180+180+180"
"wide"									"300"
"tall"									"o0.5"
"proportionaltoparent"					"1"
"scaleImage"							"1"
"mouseinputenabled"		"0"
"image"									"replay/thumbnails/miku1"
}
"choosecustom13"
{
	"ControlName"			"CExButton"
	"fieldName"				"choosecustom13"
	"xpos"					"0"
	"ypos"					"400+180+180+180+180+180+180+180+180+180+180" 
	"wide"					"470"
	"tall"					"180"
	"textinsety"			"10"
	"labeltext"				"-"
	"font"					"Regular12"
	"textalignment"			"north"
"command" "engine sixense_clear_bindings; sixense_write_bindings _jp_stat_bg.txt;con_logfile cfg/_jp_stat_bg.txt; echo #base ../custom/jofrehud-main/_jofrenew/new/ui_overrides/background/whaven.res; con_logfile ."
	"actionsignallevel"		"5" 
	"paintbackground"		"0"
	"border_default"		"FLAT_Black_4"
	"border_armed"			"FLAT_Black_2"
	"sound_depressed"		"UI/buttonclick.wav"
	"sound_released"		"UI/buttonclickrelease.wav"

}	
"custombgshowcase13"
{
"ControlName"							"ImagePanel"
"fieldName"								"custombgshowcase13"
"xpos"									"80"
"ypos"									"400+180+180+20+180+180+180+180+180+180+180+180"
"wide"									"300"
"tall"									"o0.5"
"proportionaltoparent"					"1"
"scaleImage"							"1"
"mouseinputenabled"		"0"
"image"									"replay/thumbnails/whaven"
}
"choosecustom14"
{
	"ControlName"			"CExButton"
	"fieldName"				"choosecustom14"
	"xpos"					"0"
	"ypos"					"400+180+180+180+180+180+180+180+180+180+180+180" 
	"wide"					"470"
	"tall"					"180"
	"textinsety"			"10"
	"labeltext"				"-"
	"font"					"Regular12"
	"textalignment"			"north"
"command" "engine sixense_clear_bindings; sixense_write_bindings _jp_stat_bg.txt;con_logfile cfg/_jp_stat_bg.txt; echo #base ../custom/jofrehud-main/_jofrenew/new/ui_overrides/background/whaven2.res; con_logfile ."
	"actionsignallevel"		"5" 
	"paintbackground"		"0"
	"border_default"		"FLAT_Black_4"
	"border_armed"			"FLAT_Black_2"
	"sound_depressed"		"UI/buttonclick.wav"
	"sound_released"		"UI/buttonclickrelease.wav"

}	
"custombgshowcase14"
{
"ControlName"							"ImagePanel"
"fieldName"								"custombgshowcase14"
"xpos"									"80"
"ypos"									"400+180+180+20+180+180+180+180+180+180+180+180+180"
"wide"									"300"
"tall"									"o0.5"
"proportionaltoparent"					"1"
"scaleImage"							"1"
"mouseinputenabled"		"0"
"image"									"replay/thumbnails/whaven2"
}
"choosecustom15"
{
	"ControlName"			"CExButton"
	"fieldName"				"choosecustom15"
	"xpos"					"0"
	"ypos"					"400+180+180+180+180+180+180+180+180+180+180+180+180" 
	"wide"					"470"
	"tall"					"180"
	"textinsety"			"10"
	"labeltext"				"-"
	"font"					"Regular12"
	"textalignment"			"north"
"command" "engine sixense_clear_bindings; sixense_write_bindings _jp_stat_bg.txt;con_logfile cfg/_jp_stat_bg.txt; echo #base ../custom/jofrehud-main/_jofrenew/new/ui_overrides/background/whaven3.res; con_logfile ."
	"actionsignallevel"		"5" 
	"paintbackground"		"0"
	"border_default"		"FLAT_Black_4"
	"border_armed"			"FLAT_Black_2"
	"sound_depressed"		"UI/buttonclick.wav"
	"sound_released"		"UI/buttonclickrelease.wav"

}	
"custombgshowcase15"
{
"ControlName"							"ImagePanel"
"fieldName"								"custombgshowcase15"
"xpos"									"80"
"ypos"									"400+180+180+20+180+180+180+180+180+180+180+180+180+180"
"wide"									"300"
"tall"									"o0.5"
"proportionaltoparent"					"1"
"scaleImage"							"1"
"mouseinputenabled"		"0"
"image"									"replay/thumbnails/whaven3"
}
"choosecustom16"
{
	"ControlName"			"CExButton"
	"fieldName"				"choosecustom16"
	"xpos"					"0"
	"ypos"					"400+180+180+180+180+180+180+180+180+180+180+180+180+180" 
	"wide"					"470"
	"tall"					"180"
	"textinsety"			"10"
	"labeltext"				"noaimbot"
	"font"					"Regular12"
	"textalignment"			"north"
"command" "engine sixense_clear_bindings; sixense_write_bindings _jp_stat_bg.txt;con_logfile cfg/_jp_stat_bg.txt; echo #base ../custom/jofrehud-main/_jofrenew/new/ui_overrides/background/noaimbot.res; con_logfile ."
	"actionsignallevel"		"5" 
	"paintbackground"		"0"
	"border_default"		"FLAT_Black_4"
	"border_armed"			"FLAT_Black_2"
	"sound_depressed"		"UI/buttonclick.wav"
	"sound_released"		"UI/buttonclickrelease.wav"

}	
"custombgshowcase16"
{
"ControlName"							"ImagePanel"
"fieldName"								"custombgshowcase16"
"xpos"									"80"
"ypos"									"400+180+180+20+180+180+180+180+180+180+180+180+180+180+180"
"wide"									"300"
"tall"									"o0.5"
"proportionaltoparent"					"1"
"scaleImage"							"1"
"mouseinputenabled"		"0"
"image"									"replay/thumbnails/l4d2/noskill_tank_2"
}
"end"
{
	"ControlName"			"CExButton"
	"fieldName"				"end"
	"xpos"					"0"
	"ypos"					"5000" 
	"wide"					"470"
	"tall"					"1"
	"textinsety"			"10"
	"labeltext"				"Pink"
	"font"					"Regular12"
	"textalignment"			"north"
"command" "engine echo"
	"actionsignallevel"		"5" 
	"paintbackground"		"0"
	"border_default"		"FLAT_Black_4"
	"border_armed"			"FLAT_Black_2"
	"sound_depressed"		"UI/buttonclick.wav"
	"sound_released"		"UI/buttonclickrelease.wav"

}	
				}
			}
		}
	}
}