"j"
{
	"CustomizationMenu"
	{
		"MainPanel"
		{
			"MenuContainer"
			{
				"Buttons"
				{
					"CircularLabel"
					{
						"ControlName"				"CExLabel"
						"fieldName"					"CircularLabel"
						"xpos"						"0"
						"ypos"						"0"
						"zpos"						"53"
						"wide"					"p1"
						"tall"						"20"
						"proportionaltoparent"		"1"
						"font"						"regular12"
						"labelText"					"Circular Uber? Activates the other circular stuff too."
						"textAlignment"				"center"
						"border" "FLAT_Black_2"
					}					
					"ProgressBarYes"
					{
						"ControlName"			"CExButton"
						"fieldName"				"ProgressBarYes"
						"xpos"					"0"
						"ypos"					"20"
						"wide"					"p0.5"
						"tall"					"25"
						"proportionaltoparent"	"1"
						"labeltext"				"Yes"
						"font"					"Size 14"
						"textalignment"			"center"
						"command"				"engine sixense_clear_bindings; sixense_write_bindings jp_ui_circular.txt;  con_logfile cfg/jp_ui_circular.txt; echo #base ../custom/jofrehud-main/new/ui_overrides/circulo/file2.res; con_logfile ."
						"actionsignallevel"		"5"
						"paintbackground"		"0"
						"border_default"		"FLAT_Black_4"
						"border_armed"			"FLAT_Black_2"
						"sound_depressed"		"UI/buttonclick.wav"
						"sound_released"		"UI/buttonclickrelease.wav"
					}
					"ProgressBarNo"
					{
						"ControlName"			"CExButton"
						"fieldName"				"ProgressBarNo"
						"xpos"					"0+p0.5"
						"ypos"					"20"
						"wide"					"p0.5"
						"tall"					"25"
						"proportionaltoparent"	"1"
						"labeltext"				"No"
						"font"					"Size 14"
						"textalignment"			"center"
						"command"				"engine sixense_clear_bindings; sixense_write_bindings jp_ui_circular.txt"
						"actionsignallevel"		"5"
						"paintbackground"		"0"
						"border_default"		"FLAT_Black_4"
						"border_armed"			"FLAT_Black_2"
						"sound_depressed"		"UI/buttonclick.wav"
						"sound_released"		"UI/buttonclickrelease.wav"
					}	
					"ColorLabel"
					{
						"ControlName"				"CExLabel"
						"fieldName"					"ColorLabel"
						"xpos"						"0"
						"ypos"						"45"
						"zpos"						"53"
						"wide"					"p1"
						"tall"						"25"
						"proportionaltoparent"		"1"
						"font"						"regular12"
						"labelText"					"Choose BG Color"
						"textAlignment"				"center"
						"border" "FLAT_Black_2"
					}
					"TeamBased"
					{
						"ControlName"			"CExButton"
						"fieldName"				"TeamBased"
						"xpos"					"0"
						"ypos"					"70"
						"wide"					"p1"
						"tall"					"30"
						"proportionaltoparent"	"1"
						"labeltext"				"Team Based: Red & Blue"
						"font"					"Size 14"
						"textalignment"			"center"
						"command"				"engine sixense_clear_bindings; sixense_write_bindings jp_ui_ammobg.txt"
						"actionsignallevel"		"5"
						"paintbackground"		"0"
						"border_default"		"FLAT_Black_4"
						"border_armed"			"FLAT_Black_2"
						"sound_depressed"		"UI/buttonclick.wav"
						"sound_released"		"UI/buttonclickrelease.wav"
					}		
					"TeamBasedWhite"
					{
						"ControlName"			"CExButton"
						"fieldName"				"TeamBasedWhite"
						"xpos"					"0"
						"ypos"					"100"
						"wide"					"p1"
						"tall"					"30"
						"proportionaltoparent"	"1"
						"labeltext"				"White"
						"font"					"Size 14"
						"textalignment"			"center"
						"command"				"engine sixense_clear_bindings; sixense_write_bindings jp_ui_ammobg.txt;  con_logfile; cfg/jp_ui_ammobg.txt; echo #base ../custom/jofrehud-main/new/ui_overrides/teamfondo/ammo_white.res; con_logfile ."
						"actionsignallevel"		"5"
						"paintbackground"		"0"
						"border_default"		"FLAT_Black_4"
						"border_armed"			"FLAT_Black_2"
						"sound_depressed"		"UI/buttonclick.wav"
						"sound_released"		"UI/buttonclickrelease.wav"
					}			
					"Red"
					{
						"ControlName"			"CExButton"
						"fieldName"				"Red"
						"xpos"					"0"
						"ypos"					"130"
						"wide"					"p1"
						"tall"					"30"
						"proportionaltoparent"	"1"
						"labeltext"				"Always Red"
						"font"					"Size 14"
						"textalignment"			"center"
						"command"				"engine sixense_clear_bindings; sixense_write_bindings jp_ui_ammobg.txt;  con_logfile; cfg/jp_ui_ammobg.txt; echo #base ../custom/jofrehud-main/new/ui_overrides/teamfondo/ammo_red.res; con_logfile ."
						"actionsignallevel"		"5"
						"paintbackground"		"0"
						"border_default"		"FLAT_Black_4"
						"border_armed"			"FLAT_Black_2"
						"sound_depressed"		"UI/buttonclick.wav"
						"sound_released"		"UI/buttonclickrelease.wav"
					}		
					"Blu"
					{
						"ControlName"			"CExButton"
						"fieldName"				"Blu"
						"xpos"					"0"
						"ypos"					"160"
						"wide"					"p1"
						"tall"					"30"
						"proportionaltoparent"	"1"
						"labeltext"				"Always Blue"
						"font"					"Size 14"
						"textalignment"			"center"
						"command"				"engine sixense_clear_bindings; sixense_write_bindings jp_ui_ammobg.txt;  con_logfile; cfg/jp_ui_ammobg.txt; echo #base ../custom/jofrehud-main/new/ui_overrides/teamfondo/ammo_blu.res; con_logfile ."
						"actionsignallevel"		"5"
						"paintbackground"		"0"
						"border_default"		"FLAT_Black_4"
						"border_armed"			"FLAT_Black_2"
						"sound_depressed"		"UI/buttonclick.wav"
						"sound_released"		"UI/buttonclickrelease.wav"
					}																														
				}
							
				}
			}
		}
}