"Resource/UI/ItemRenameConfirmationDialog.res"
{
"LearnMoreButton"
{
"fieldName""LearnMoreButton"
"tall""25"
////"autoResize""0"
//"visible""1"
////"enabled""1"
//"tabposition""0"
"font""HudFontSmall"
"textAlignment""center"
//"dulltext""0"
"brighttext""0"

//"sound_depressed""UI/buttonclick.wav"
//"sound_released""UI/buttonclickrelease.wav"
}
}
