"Resource/baseaction_sys.res"
{
"HudTrainingMsgBG"
{
"ControlName""CTFImagePanel"
"fieldName""HudTrainingMsgBG"
////"autoResize""0"
//"pinCorner""0"
//"visible""1"
////"enabled""1"
"image""../hud/death_panel_blue_bg"
"scaleImage""1"
"teambg_2""../hud/death_panel_red_bg"
"teambg_3""../hud/death_panel_blue_bg"
}
}
