"Resource/UI/HudArenaPlayerCount.res"
{	
			"tank_gif"
			{
			"ControlName""ImagePanel"
			"fieldName""tank_gif"
			"wide""20"
			"tall""o1"
			"scaleImage""1"
			"image""replay/thumbnails/l4d2/gif_noskill"
			"fgcolor""TanDark"
			}	
}
