#base "base/label1_main.res"
#base "base/label1_autoresize.res"
#base "base/label1_north.res"
#base "base/label1_paintb.res"
#base "base/label1_wrap0.res"
#base "base/button1.res"
#base "../#uni_base/filesv1/imagepanel1/main.res"