"Resource/UI/CharInfoPanel.res"
{
"ShowExplanationsButton"
{
"ControlName""CExButton"
"fieldName""ShowExplanationsButton"
////"autoResize""0"
//"pinCorner""0"
//"visible""1"
////"enabled""1"
//"tabposition""0"
"labelText""?"
"textAlignment""center"
//"dulltext""0"
"brighttext""0"
"Command""show_explanations"
//"sound_depressed""UI/buttonclick.wav"
//"sound_released""UI/buttonclickrelease.wav"
}
}