#base "vis1.res"
#base "auto1.res"
#base "pin0.res"
#base "is-cex.res"
"Resource/baseaction_sys.res"
{
"WarningLabel"
{
//"ControlName""CExLabel"
//"fieldName""WarningLabel"
"font""HudFontSmall"
"textAlignment""center"
//"xpos""0"
"ypos""170"
//"zpos""0"
"wide""400"
"tall""20"
//"autoResize""1"
////"pinCorner""0"
////"visible""1"
////"enabled""1"
"fgcolor_override" "LightRed"
}}
