"j"
{
	"CustomizationMenu"
	{
		"MainPanel"
		{
			"MenuContainer"
			{
				"DamageIndicatorButtons"
				{

					"xhair"
					{
						"ControlName"			"CExButton"
						"fieldName"				"xhair"
						"xpos"					"0"
						"ypos"					"0"
						"wide"					"p1"
						"tall"					"180"
						"proportionaltoparent"	"1"
						"labeltext"				"XHair"
						"textinsety"			"10"
						"font"					"Regular12"
						"textalignment"			"north"
						"command"				"engine jp_damage_indicator_clear; con_logfile cfg/jp_damage_indicator.txt; echo #base ../custom/jofrehud-main/new/ui_overrides/damage_indicator/xhair.res; con_logfile ."
						"actionsignallevel"		"5" 
						"tooltiptext"	"This option forces a gigantic circle crosshair, and whenever you get hit, it will show around the crosshair the red indicator damage."
						"paintbackground"		"0"
						"border_default"		"FLAT_Black_4"
						"border_armed"			"FLAT_Black_2"
						"sound_depressed"		"UI/buttonclick.wav"
						"sound_released"		"UI/buttonclickrelease.wav"
					}	
		"xhairimage"
		{
			"ControlName"							"ImagePanel"
			"fieldName"								"xhairimage"
			"xpos"									"70"
			"ypos"									"20"
			"wide"									"300"
			"tall"									"o0.5"
			"proportionaltoparent"					"1"
			"scaleImage"							"1"
			"mouseinputenabled"		"0"
			"border"		"cs1"
			"image"									"replay/thumbnails/custom/xhairshowcase"
		}					
					"critheals"
					{
						"ControlName"			"CExButton"
						"fieldName"				"critheals"
						"xpos"					"0"
						"ypos"					"180"
						"wide"					"p1"
						"tall"					"180"
						"proportionaltoparent"	"1"
						"textinsety"			"10"
						"labeltext"				"Crit Heals"
						"font"					"Regular12"
						"textalignment"			"north"
						"command"				"engine jp_damage_indicator_clear; con_logfile cfg/jp_damage_indicator.txt; echo #base ../custom/jofrehud-main/new/ui_overrides/damage_indicator/critheals.res; con_logfile ."
						"actionsignallevel"		"5" 
						"paintbackground"		"0"
						"border_default"		"FLAT_Black_4"
						"border_armed"			"FLAT_Black_2"
						"sound_depressed"		"UI/buttonclick.wav"
						"sound_released"		"UI/buttonclickrelease.wav"
					}		
					"crosshairdot"
					{
						"ControlName"			"CExButton"
						"fieldName"				"crosshairdot"
						"xpos"					"0"
						"ypos"					"180+180"
						"wide"					"p1"
						"tall"					"180"
						"proportionaltoparent"	"1"
						"textinsety"			"10"
						"labeltext"				"Crosshair Dot"
						"font"					"Regular12"
						"textalignment"			"north"
						"command"				"engine jp_damage_indicator_clear; con_logfile cfg/jp_damage_indicator.txt; echo #base ../custom/jofrehud-main/new/ui_overrides/damage_indicator/crosshairdot.res; con_logfile ."
						"actionsignallevel"		"5" 
						"paintbackground"		"0"
						"border_default"		"FLAT_Black_4"
						"border_armed"			"FLAT_Black_2"
						"sound_depressed"		"UI/buttonclick.wav"
						"sound_released"		"UI/buttonclickrelease.wav"
					}		
					"l4d2mod"
					{
						"ControlName"			"CExButton"
						"fieldName"				"l4d2mod"
						"xpos"					"0"
						"ypos"					"180+180+180"
						"wide"					"p1"
						"tall"					"180"
						"proportionaltoparent"	"1"
						"textinsety"			"10"
						"labeltext"				"L4D2 Style Mod"
						"font"					"Regular12"
						"textalignment"			"north"
						"command"				"engine jp_damage_indicator_clear; con_logfile cfg/jp_damage_indicator.txt; echo #base ../custom/jofrehud-main/new/ui_overrides/damage_indicator/l4d2mod.res; con_logfile ."
						"actionsignallevel"		"5" 
						"paintbackground"		"0"
						"border_default"		"FLAT_Black_4"
						"border_armed"			"FLAT_Black_2"
						"sound_depressed"		"UI/buttonclick.wav"
						"sound_released"		"UI/buttonclickrelease.wav"
					}							
					"off"
					{
						"ControlName"			"CExButton"
						"fieldName"				"off"
						"xpos"					"0"
						"ypos"					"180+180+180+180"
						"wide"					"p1"
						"tall"					"40"
						"proportionaltoparent"	"1"
						"labeltext"				"DAMAGE INDICATOR OFF"
						"font"					"Regular12"
						"textalignment"			"center"
						"command"				"engine jp_damage_indicator_clear"
						"actionsignallevel"		"5" 
						"paintbackground"		"1"
						"defaultbgcolor_override"	"Red"
						"border_default"		"FLAT_Black_4"
						"border_armed"			"FLAT_Black_2"
						"sound_depressed"		"UI/buttonclick.wav"
						"sound_released"		"UI/buttonclickrelease.wav"
					}	
					"def"
					{
						"ControlName"			"CExButton"
						"fieldName"				"off"
						"xpos"					"0"
						"ypos"					"180+180+180+180+40"
						"wide"					"p1"
						"tall"					"40"
						"proportionaltoparent"	"1"
						"labeltext"				"DAMAGE INDICATOR DEFAULT"
						"font"					"Regular12"
						"textalignment"			"center"
						"command"				"engine jp_damage_indicator_clear; con_logfile cfg/jp_damage_indicator.txt; echo #base ../custom/jofrehud-main/new/ui_overrides/damage_indicator/def.res; con_logfile ."
		
						"actionsignallevel"		"5" 
						"paintbackground"		"1"
						"defaultbgcolor_override"	"White"
						"defaultfgcolor_override"	"Black"
						"border_default"		"FLAT_Black_4"
						"border_armed"			"FLAT_Black_2"
						"sound_depressed"		"UI/buttonclick.wav"
						"sound_released"		"UI/buttonclickrelease.wav"
					}																					
				}
			}
		}
	}
}