"Resource/UI/ChatFilters.res"
{
	"HudChatFilterPanel"
	{
		"ControlName"		"EditablePanel"
		"fieldName"		"HudChatFilterPanel"
		"xpos"			"335"
		"ypos"			"275"
		"zpos"			"0"
		"wide"			"130"
		"tall"			"70"
		"visible"		"0"
		"enabled"		"1"
	}

	"joinleave_button"
	{
		"ControlName"		"CheckButton"
		"fieldName"		"joinleave_button"
		"xpos"			"10"
		"ypos"			"5"
		"wide"			"150"
		"tall"			"10"
		//		"1"
		//		"0"
		"visible"		"1"
		"enabled"		"1"
		//		"0"
		"labelText"		"#filter_joinleave"
	}
	"namechange_button"
	{
		"ControlName"		"CheckButton"
		"fieldName"		"namechange_button"
		"xpos"			"10"
		"ypos"			"15"
		"wide"			"150"
		"tall"			"10"
		//		"1"
		//		"0"
		"visible"		"1"
		"enabled"		"1"
		//		"0"
		"labelText"		"#filter_namechange"
	}
	"publicchat_button"
	{
		"ControlName"		"CheckButton"
		"fieldName"		"publicchat_button"
		"xpos"			"10"
		"ypos"			"25"
		"wide"			"150"
		"tall"			"10"
		//		"1"
		//		"0"
		"visible"		"1"
		"enabled"		"1"
		//		"0"
		"labelText"		"#filter_publicchat"
	}
	"servermsg_button"
	{
		"ControlName"		"CheckButton"
		"fieldName"		"servermsg_button"
		"xpos"			"10"
		"ypos"			"35"
		"wide"			"150"
		"tall"			"10"
		//		"1"
		//		"0"
		"visible"		"1"
		"enabled"		"1"
		//		"0"
		"labelText"		"#filter_servermsg"
	}
	"teamchange_button"
	{
		"ControlName"		"CheckButton"
		"fieldName"		"teamchange_button"
		"xpos"			"10"
		"ypos"			"45"
		"wide"			"150"
		"tall"			"10"
		//		"1"
		//		"0"
		"visible"		"1"
		"enabled"		"1"
		//		"0"
		"labelText"		"#filter_teamchange"
	}
	
	"achivement_button"
	{
		"ControlName"		"CheckButton"
		"fieldName"		"achivement_button"
		"xpos"			"10"
		"ypos"			"55"
		"wide"			"150"
		"tall"			"10"
		//		"1"
		//		"0"
		"visible"		"1"
		"enabled"		"1"
		//		"0"
		"labelText"		"#filter_achievement"
	}
}
