"Resource/UI/MOTD.res"
{
	"ClientMOTD"
	{
		"ControlName"		"Frame"
		"fieldName"		"ClientMOTD"
		"xpos"		"50"
		"ypos"		"10"
		"wide"		"552"
		"tall"		"448"
		//		"0"
		//		"0"
		"visible"		"1"
		"enabled"		"1"
		//		"0"
	}
	"SysMenu"
	{
		"ControlName"		"Menu"
		"fieldName"		"SysMenu"
		"xpos"		"0"
		"ypos"		"0"
		"wide"		"64"
		"tall"		"24"
		//		"0"
		//		"0"
		"visible"		"0"
		"enabled"		"1"
		//		"0"
	}
	"Message"
	{
		"ControlName"		"TextEntry"
		"fieldName"		"Message"
		"xpos"		"11"
		"ypos"		"34"
		"wide"		"532"
		"tall"		"365"
		//		"3"
		//		"0"
		"visible"		"1"
		"enabled"		"1"
		//		"0"
		"maxchars"		"-1"
	}
	"ok"
	{
		"ControlName"		"Button"
		"fieldName"		"ok"
		"xpos"		"12"
		"ypos"		"408"
		"wide"		"70"
		"tall"		"30"
		//		"0"
		//		"2"
		"visible"		"1"
		"enabled"		"1"
		//		"0"
		"labelText"		"#PropertyDialog_OK"
		"textAlignment"		"center"
		"command"		"okay"
		"Default"		"1"
	}
}
