#base "base/namelabel_main.res"
#base "base/namelabel_tall24.res"
#base "base/namelabel_autoresize1.res"
#base "base/namelabel_pincorner.res"
#base "base/namelabel_paintb.res"
#base "base/namelabel_wrap.res"
#base "base/status_label.res"