#base "base/namelabel_main.res"
#base "base/infotext_main.res"
#base "base/infotext_enabled.res"
#base "base/infotext_west.res"

#base "../#uni_base/filesv1/cancelbutton/ctrl/btn.res"
#base "../#uni_base/filesv1/cancelbutton/main.res"
#base "../#uni_base/filesv1/cancelbutton/vis1.res"
#base "../#uni_base/filesv1/cancelbutton/enabled.res"
#base "../#uni_base/filesv1/cancelbutton/text/center.res"
#base "../#uni_base/filesv1/cancelbutton/tab3.res"
#base "../#uni_base/filesv1/cancelbutton/cmd/cancel.res"
#base "../#uni_base/filesv1/cancelbutton/position/x0.res"
#base "../#uni_base/filesv1/cancelbutton/position/y192.res"
#base "../#uni_base/filesv1/cancelbutton/position/w104.res"
#base "../#uni_base/filesv1/cancelbutton/position/t24.res"