	#base "customgamespage.res"
"servers/CustomGamesPage_Filters_Custom.res"
{
       "GameFilterLabel"
        {
                "ControlName"                "Label"
                "fieldName"                "GameFilterLabel"
                "xpos"                "12"
                "ypos"                "150"
                "wide"                "44"
                "tall"                "24"
                "AutoResize"                "0"
                "PinCorner"                "2"
                "visible"                "1"
                "enabled"                "1"
                "tabPosition"                "0"
                "paintbackground"                "1"
		"labelText"		"¦ Game"
		"font"	"Productv2_16"
		"textAlignment"		"east"
                "wrap"                "0"
        }
        "LocationFilterLabel"
        {
                "ControlName"                "Label"
                "fieldName"                "LocationFilterLabel"
                "xpos"                "234"
                "ypos"                "180"
                "wide"                "72"
                "tall"                "24"
                "AutoResize"                "0"
                "PinCorner"                "2"
                "visible"                "1"
                "enabled"                "1"
                "tabPosition"                "0"
                "paintbackground"                "1"
 		"labelText"		"£ Location"
		"textAlignment"		"east"
		"font"	"Productv2_16"
                "wrap"                "0"
        }
        "MapFilterLabel"
        {
                "ControlName"                "Label"
                "fieldName"                "MapFilterLabel"
                "xpos"                "12"
                "ypos"                "180"
                "wide"                "44"
                "tall"                "24"
                "AutoResize"                "0"
                "PinCorner"                "2"
                "visible"                "1"
                "enabled"                "1"
                "tabPosition"                "0"
                "paintbackground"                "1"
		"labelText"		"¢ Map"
		"textAlignment"		"east"
		"font"	"Productv2_16"
                "wrap"                "0"
        }
        "MaxPlayerFilterLabel"
        {
                "ControlName"                "Label"
                "fieldName"                "MaxPlayerFilterLabel"
                "xpos"                "12"
                "ypos"                "210"
                "wide"                "144"
                "tall"                "24"
                "AutoResize"                "0"
                "PinCorner"                "2"
                "visible"                "1"
                "enabled"                "1"
                "tabPosition"                "0"
                "paintbackground"                "1"
		"labelText"		"¡ Max Players"
		"textAlignment"		"east"
		"font"	"Productv2_16"
                "wrap"                "0"
        }
        "PingFilterLabel"
        {
                "ControlName"                "Label"
                "fieldName"                "PingFilterLabel"
                "xpos"                "234"
                "ypos"                "150"
                "wide"                "72"
                "tall"                "24"
                "AutoResize"                "0"
                "PinCorner"                "2"
                "visible"                "1"
                "enabled"                "1"
                "tabPosition"                "0"
                "paintbackground"                "1"
 				"labelText"		"¤ Latency"
		"textAlignment"		"east"
		"font"	"Productv2_16"
                "wrap"                "0"
        }
        "SecureFilterLabel"
        {
                "ControlName"                "Label"
                "fieldName"                "SecureFilterLabel"
                "xpos"                "236"
                "ypos"                "210"
                "wide"                "72"
                "tall"                "24"
                "AutoResize"                "0"
                "PinCorner"                "2"
                "visible"                "1"
                "enabled"                "1"
                "tabPosition"                "0"
                "paintbackground"                "1"
 		"font" "Productv2_16"
		"labelText"		"§ VAC"
		"textAlignment"		"east"
                "wrap"                "0"
        }
}
