"Resource/UI/CharInfoPanel.res"
{
"ChargeMeter"
{
"ControlName""ContinuousProgressBar"
"fieldName""ChargeMeter"
//"font""Default"
"zpos""2"
////"autoResize""0"
//"pinCorner""0"
//"visible""1"
////"enabled""1"
"textAlignment""Left"
//"dulltext""0"
"brighttext""0"
}
}