"Resource/EngineVGuiLayout.res"
{
"keybindings"
{
"ControlName""VControlsListPanel"
"fieldName""KeyBindings"
"xpos""0"
"ypos""0"
"tall""300"
"autoResize""3"
//"pinCorner""0"
"visible""1"
////"enabled""1"
"tabPosition""0"
}
}