"resource/BaseActionCDTrackStartDialog.res"
{
"LeftSideBG"
{
"ControlName""ImagePanel"
"fieldName""LeftSideBG"
"zpos""1"
"wide""280"
"tall""80"
"visible""1"
////"enabled""1"
"image""../hud/objectives_flagpanel_bg_left"
"scaleImage""1"
}}
