#base "../../../../../cfg/_jp_color_primary.txt"
#base "../../../../../cfg/_jp_color_neutral.txt"
#base "../../../../../cfg/_jp_color_positive.txt"
#base "../../../../../cfg/_jp_color_warning.txt"
#base "../../../../../cfg/_jp_color_negative.txt"
#base "../../../../../cfg/_jp_color_crosshair.txt"