"Resource/EngineVGuiLayout.res"
{
"DiscardButton"
{
"fieldName""DiscardButton"
"font""HudFontSmall"
"textAlignment""center"
//"sound_depressed""UI/buttonclick.wav"
//"sound_released""UI/buttonclickrelease.wav"
}
}