"friends/AddFriendResultSubPanel.res"
{
"AcceptButton"
{
"fieldName""AcceptButton"
////"enabled""1"
//"tabposition""0"
//"dulltext""0"
"brighttext""0"
"Command""accept"
}
"DeclineButton"
{
"fieldName""DeclineButton"
////"enabled""1"
//"tabposition""0"
//"dulltext""0"
"brighttext""0"
"Command""decline"
}}
