"Resource/EngineVGuiLayout.res"
{
"HorizontalLine"
{
"ControlName""ImagePanel"
"fieldName""HorizontalLine"
"zpos""3"
"tall""1"
////"autoResize""0"
//"pinCorner""0"
////"enabled""1"
//"tabposition""0"
"PaintBackgroundType""0"
}
}