#base "../base/build-more/mainbg/main.res"
#base "../base/build-more/mainbg/position/wide250.res"
#base "../base/build-more/mainbg/position/xpos0.res"
#base "../base/build-more/mainbg/position/tall170.res"
#base "../base/build-more/mainbg/ctrl_other.res"
#base "../base/build-more/mainbg/image/scale.res"
#base "../base/build-more/mainbg/image/color1.res"
#base "../base/build-more/mainbg/image/hud_menu_bg.res"
// hud_menu_item_bg
// hud_menu_item_bg
// 4 14 0 98 105
//#base "../base/build-more/bgengineer/main.res"
//#base "../base/build-more/bgengineer/xpos405.res"

#base "../base/build-more/buildicon/main.res"
#base "../base/build-more/buildiconshadow/main.res"

#base "../base/build-more/titlelabel/main.res"
#base "../base/build-more/titlelabel/font/chalk.res"
#base "../base/build-more/titlelabel/content1.res"
#base "../base/build-more/titlelabel/position/tall38.res"
#base "../base/build-more/titlelabel/text/left.res"

#base "../base/build-more/cancellabel/main.res"
#base "../base/build-more/cancellabel/ctrl/cex.res"
#base "../base/build-more/cancellabel/autopin0.res"
#base "../base/build-more/cancellabel/dullbright.res"
#base "../base/build-more/cancellabel/visenabled1.res"
#base "../base/build-more/cancellabel/position/zpos1.res"
#base "../base/build-more/cancellabel/position/wide200.res"
#base "../base/build-more/cancellabel/position/tall13.res"
#base "../base/build-more/cancellabel/position/ypos35.res"
#base "../base/build-more/cancellabel/position/xpos35.res"
#base "../base/build-more/cancellabel/font/spec.res"
#base "../base/build-more/cancellabel/text/east.res"

#base "../base/build-more/available_target/1/new/ctrl_edit.res"
#base "../base/build-more/available_target/1/new/vis1.res"
#base "../base/build-more/available_target/1/new/main.res"
#base "../base/build-more/available_target/1/new/ypos47.res"

#base "../base/build-more/unavailable_target/1/new/ctrl_edit.res"
#base "../base/build-more/unavailable_target/1/vis1.res"
#base "../base/build-more/unavailable_target/1/new/main.res"
#base "../base/build-more/unavailable_target/1/new/ypos47.res"