"Resource/LoadingDialog.res"
{
	"LoadingDialog"
	{
		"ControlName"		"Frame"
		"fieldName"		"LoadingDialog"
		"xpos"		"322"
		"ypos"		"249"
		"wide"		"380"
		"tall"		"220"
		//		"0"
		//		"0"
		"enabled"		"1"
		//		"0"
	}
	"SysMenu"
	{
		"ControlName"		"Menu"
		"fieldName"		"SysMenu"
		"xpos"		"0"
		"ypos"		"0"
		"wide"		"64"
		"tall"		"24"
		//		"0"
		//		"0"
		"visible"		"0"
		"enabled"		"1"
		//		"0"
	}
	"InfoLabel"
	{
		"ControlName"		"Label"
		"fieldName"		"InfoLabel"
		"xpos"		"20"
		"ypos"		"34"
		"wide"		"340"
		"tall"		"24"
		//		"0"
		//		"0"
		"enabled"		"1"
		//		"0"
		"labelText"		"#GameUI_ParseBaseline"
		"textAlignment"		"west"
		"dulltext"		"1"
	}
	"progress"
	{
		"ControlName"		"ProgressBar"
		"fieldName"		"Progress"
		"xpos"		"20"
		"ypos"		"64"
		"wide"		"260"
		"tall"		"24"
		//		"0"
		//		"0"
		"enabled"		"1"
		//		"0"
	}
	"CancelButton"
	{
		"ControlName"		"Button"
		"fieldName"		"CancelButton"
		"xpos"		"288"
		"ypos"		"64"
		"wide"		"72"
		"tall"		"24"
		//		"0"
		//		"0"
		"enabled"		"1"
		//		"0"
		"labelText"		"#GameUI_Cancel"
		"textAlignment"		"west"
		"command"		"Cancel"
	}
	"Divider1"
	{
		"ControlName"		"Divider"
		"fieldName"		"Divider1"
		"xpos"		"20"
		"ypos"		"104"
		"wide"		"340"
		"tall"		"2"
		//		"0"
		//		"0"
		"enabled"		"1"
		//		"0"
	}
	"Label1"
	{
		"ControlName"		"Label"
		"fieldName"		"Label1"
		"xpos"		"20"
		"ypos"		"116"
		"wide"		"340"
		"tall"		"24"
		//		"0"
		//		"0"
		"enabled"		"1"
		//		"0"
		"labelText"		"#GameUI_LoadingDialog_ContentHosting"
		"textAlignment"		"west"
		"dulltext"		"1"
	}
	"BannerAd"
	{
		"ControlName"		"HTML"
		"fieldName"		"BannerAd"
		"xpos"		"20"
		"ypos"		"144"
		"wide"		"340"
		"tall"		"56"
		//		"0"
		//		"0"
		"enabled"		"1"
		//		"0"
	}
}
