"Resource/UI/Customizations/#Customization_Menu/HUD_Customization_Fonts.res"
{
	"SafeMode"
	{
		"Customizations_Panel"
		{
			"HUD_Font_Selection" // dedicated to maxihud original customization
			{
				"ControlName"							"CScrollableList"
				"FieldName"								"HUD_Font_Selection"
				"XPos"									"cs-0.5"
				"YPos"									"cs-0.5"
				"ZPos"									"0"
				"Wide"									"f0"
				"Tall"									"f0"
				"Visible"								"0"
				"Enabled"								"1"
				"ProportionalToParent"					"1"
				"PaintBackground"						"0"
				"paintBackgroundType"					"0"
				"BGColor_Override"						"Black"

				"Scrollbar"
				{
					"XPos"								"rs1+1"
					"YPos"								"0"
					"Wide"								"6"
					"Tall"								"f0"
					"ZPos"								"1000"
					"ProportionalToParent"				"1"

					"Slider"
					{
						"PaintBackgroundType"			"0"
						"FGColor_Override"				"Gray"
					}

					"nobuttons"							"1"
				}
				"Title_Icon"
				{
					"ControlName"						"imagepanel"//"CExLabel"
					"FieldName"							"Title_Icon"
					"XPos"								"2"
					"YPos"								"0"
					"ZPos"								"0"
					"Wide"								"25"
					"Tall"								"25"
					"Visible"							"1"
					"Enabled"							"1"
					"ProportionalToParent"				"1"
					"LabelText"							"6"
					"Font"								"Symbols20"
					"TextAlignment"						"center"
					"FGColor"							"Gray"
					scaleimage 1
					drawcolor gray
					image "replay/thumbnails/glyph_hardhat"
				}
				"Title"
				{
					"ControlName"						"CExLabel"
					"FieldName"							"Title"
					"XPos"								"30"
					"YPos"								"0"
					"ZPos"								"0"
					"Wide"								"f35"
					"Tall"								"25"
					"Visible"							"1"
					"Enabled"							"1"
					"ProportionalToParent"				"1"
					"LabelText"							"#HudCustomization_MaxiHud"
					"Font"								"itemfontnamesmall"
					"TextAlignment"						"west"
					"FGColor"							"Gray"
				}
				"Separator_1"
				{
					"ControlName"						"EditablePanel"
					"FieldName"							"Separator_1"
					"XPos"								"3"
					"YPos"								"25"
					"ZPos"								"0"
					"Wide"								"f40"
					"Tall"								"2"
					"Visible"							"1"
					"Enabled"							"1"
					"ProportionalToParent"				"1"
					"paintBackground"					"1"
					"paintBackgroundtype"				"3"
					"BGcolor_Override"					"Background_Bright"
				}
				"DeathNoticeStuff"
				{
					"ControlName"						"EditablePanel"
					"FieldName"							"DeathNoticeStuff"
					"XPos"								"0"
					"YPos"								"36"
					"ZPos"								"20"
					"Wide"								"f7"
					"Tall"								"100"
					"Visible"							"1"
					"Enabled"							"1"
					"ProportionalToParent"				"1"

					"Damage_Title"
					{
						"ControlName"					"CExLabel"
						"FieldName"						"Damage_Title"
						"XPos"							"4"
						"YPos"							"0"
						"ZPos"							"0"
						"Wide"							"f35"
						"Tall"							"15"
						"Visible"						"1"
						"Enabled"						"1"
						"ProportionalToParent"			"1"
						"AllCaps"						"1"
						"LabelText"						"#HudCustomization_MaxiHud_DeathNotice"
						"Font"							"HudFontSmallBold"
						"TextAlignment"					"west"
						"FGColor"						"Gray"
					}
					"Separator"
					{
						"ControlName"					"EditablePanel"
						"FieldName"						"Separator"
						"XPos"							"2"
						"YPos"							"15"
						"ZPos"							"0"
						"Wide"							"f40"
						"Tall"							"1"
						"Visible"						"1"
						"Enabled"						"1"
						"ProportionalToParent"			"1"
						"paintBackground"				"1"
						"paintBackgroundtype"			"3"
						"BGcolor_Override"				"Background_Bright"
					}
					"8rows"
					{
						"ControlName"					"EditablePanel"
						"FieldName"						"8rows"
						"XPos"							"-2"
						"YPos"							"5"
						"ZPos"							"1"
						"Wide"							"68"
						"Tall"							"68"
						"Visible"						"1"
						"Enabled"						"1"
						"ProportionalToParent"			"1"
						"PaintBackground"				"1"
						"BGcolor_Override"				"104 101 100 255"

						"Pin_To_Sibling"				"Separator"
						"Pin_Corner_To_Sibling"			"PIN_TOPLEFT"
						"Pin_To_Sibling_Corner"			"PIN_BOTTOMLEFT"

						"Style_Image"
						{
							"ControlName"				"ImagePanel"
							"FieldName"					"Style_Image"
							"XPos"						"cs-0.5"
							"YPos"						"cs-0.5-7"
							"ZPos"						"0"
							"Wide"						"70"
							"Tall"						"70"
							"Visible"					"1"
							"Enabled"					"1"
							"MouseInputEnabled"			"0"
							"ScaleImage"				"1"
							"ProportionalToParent"		"1"
							"Image"						"replay/thumbnails/customizations/maxi/8rows"
						}
						"Style_Label"
						{
							"ControlName"				"CExLabel"
							"FieldName"					"Style_Label"
							"XPos"						"0"
							"YPos"						"rs1"
							"ZPos"						"1"
							"Wide"						"f0"
							"Tall"						"12"
							"Visible"					"1"
							"Enabled"					"1"
							"MouseInputEnabled"			"0"
							"ProportionalToParent"		"1"
							"AllCaps"					"1"
							"Font"						"FontStorePrice"
							"LabelText"					"#HudCustomization_MaxiHud_Death_Style1"
							"TextAlignment"				"center"
							"FGColor"					"Gray"
							"PaintBackground"			"1"
							"PaintBackgroundType"		"0"
							"BGColor_Override"			"Background_Darkest"
						}
						"Style_Button"
						{
							"ControlName"				"CExButton"
							"FieldName"					"Style_Button"
							"XPos"						"0"
							"YPos"						"0"
							"ZPos"						"5"
							"Wide"						"f0"
							"Tall"						"f0"
							"Visible"					"1"
							"Enabled"					"1"
							"Font"						""
							"Command"					"engine maxi_standard"
							"LabelText"					""
							"Sound_Depressed"			"UI/buttonclick.wav"
							"ProportionalToParent"		"1"
							"ActionSignalLevel"			"6"

							"PaintBackground"			"0"
							"PaintBorder"				"1"

							"border_default"			"NoBorder"
							"border_armed"				"BorderSelectionGray"
						}
					}
// DAMAGE SMALL MINUSLESS -------------------------------------------------------------------------------------------
					"12rowsextended"
					{
						"ControlName"					"EditablePanel"
						"FieldName"						"12rowsextended"
						"XPos"							"5"
						"YPos"							"0"
						"ZPos"							"1"
						"Wide"							"68"
						"Tall"							"68"
						"Visible"						"1"
						"Enabled"						"1"
						"ProportionalToParent"			"1"
						"PaintBackground"				"1"
						"BGcolor_Override"				"104 101 100 255"

						"Pin_To_Sibling"				"8rows"
						"Pin_Corner_To_Sibling"			"PIN_TOPLEFT"
						"Pin_To_Sibling_Corner"			"PIN_TOPRIGHT"

						"Style_Image"
						{
							"ControlName"				"ImagePanel"
							"FieldName"					"Style_Image"
							"XPos"						"cs-0.5"
							"YPos"						"cs-0.5-7"
							"ZPos"						"0"
							"Wide"						"70"
							"Tall"						"70"
							"Visible"					"1"
							"Enabled"					"1"
							"MouseInputEnabled"			"0"
							"ScaleImage"				"1"
							"ProportionalToParent"		"1"
							"Image"						"replay/thumbnails/customizations/maxi/12rows"
						}
						"Style_Label"
						{
							"ControlName"				"CExLabel"
							"FieldName"					"Style_Label"
							"XPos"						"0"
							"YPos"						"rs1"
							"ZPos"						"1"
							"Wide"						"f0"
							"Tall"						"12"
							"Visible"					"1"
							"Enabled"					"1"
							"MouseInputEnabled"			"0"
							"ProportionalToParent"		"1"
							"AllCaps"					"1"
							"Font"						"FontStorePriceSmall"
							"LabelText"					"#HudCustomization_MaxiHud_Death_Style2"
							"TextAlignment"				"center"
							"FGColor"					"Gray"
							"PaintBackground"			"1"
							"PaintBackgroundType"		"0"
							"BGColor_Override"			"Background_Darkest"
						}
						"Style_Button"
						{
							"ControlName"				"CExButton"
							"FieldName"					"Style_Button"
							"XPos"						"0"
							"YPos"						"0"
							"ZPos"						"5"
							"Wide"						"f0"
							"Tall"						"f0"
							"Visible"					"1"
							"Enabled"					"1"
							"Font"						""
							"Command"					"engine maxi_ext"
							"LabelText"					""
							"Sound_Depressed"			"UI/buttonclick.wav"
							"ProportionalToParent"		"1"
							"ActionSignalLevel"			"6"

							"PaintBackground"			"0"
							"PaintBorder"				"1"

							"border_default"			"NoBorder"
							"border_armed"				"BorderSelectionGray"
						}
					}		
					"12rowssmall"
					{
						"ControlName"					"EditablePanel"
						"FieldName"						"12rowssmall"
						"XPos"							"5"
						"YPos"							"0"
						"ZPos"							"1"
						"Wide"							"68"
						"Tall"							"68"
						"Visible"						"1"
						"Enabled"						"1"
						"ProportionalToParent"			"1"
						"PaintBackground"				"1"
						"BGcolor_Override"				"104 101 100 255"

						"Pin_To_Sibling"				"12rowsextended"
						"Pin_Corner_To_Sibling"			"PIN_TOPLEFT"
						"Pin_To_Sibling_Corner"			"PIN_TOPRIGHT"

						"Style_Image"
						{
							"ControlName"				"ImagePanel"
							"FieldName"					"Style_Image"
							"XPos"						"cs-0.5"
							"YPos"						"cs-0.5-7"
							"ZPos"						"0"
							"Wide"						"70"
							"Tall"						"70"
							"Visible"					"1"
							"Enabled"					"1"
							"MouseInputEnabled"			"0"
							"ScaleImage"				"1"
							"ProportionalToParent"		"1"
							"Image"						"replay/thumbnails/customizations/maxi/12rows2"
						}
						"Style_Label"
						{
							"ControlName"				"CExLabel"
							"FieldName"					"Style_Label"
							"XPos"						"0"
							"YPos"						"rs1"
							"ZPos"						"1"
							"Wide"						"f0"
							"Tall"						"12"
							"Visible"					"1"
							"Enabled"					"1"
							"MouseInputEnabled"			"0"
							"ProportionalToParent"		"1"
							"AllCaps"					"1"
							"Font"						"FontStorePriceSmall"
							"LabelText"					"#HudCustomization_MaxiHud_Death_Style3"
							"TextAlignment"				"center"
							"FGColor"					"Gray"
							"PaintBackground"			"1"
							"PaintBackgroundType"		"0"
							"BGColor_Override"			"Background_Darkest"
						}
						"Style_Button"
						{
							"ControlName"				"CExButton"
							"FieldName"					"Style_Button"
							"XPos"						"0"
							"YPos"						"0"
							"ZPos"						"5"
							"Wide"						"f0"
							"Tall"						"f0"
							"Visible"					"1"
							"Enabled"					"1"
							"Font"						""
							"Command"					"engine maxi_mini_12"
							"LabelText"					""
							"Sound_Depressed"			"UI/buttonclick.wav"
							"ProportionalToParent"		"1"
							"ActionSignalLevel"			"6"

							"PaintBackground"			"0"
							"PaintBorder"				"1"

							"border_default"			"NoBorder"
							"border_armed"				"BorderSelectionGray"
						}
					}	
					"24r"
					{
						"ControlName"					"EditablePanel"
						"FieldName"						"24r"
						"XPos"							"5"
						"YPos"							"0"
						"ZPos"							"1"
						"Wide"							"68"
						"Tall"							"68"
						"Visible"						"1"
						"Enabled"						"1"
						"ProportionalToParent"			"1"
						"PaintBackground"				"1"
						"BGcolor_Override"				"104 101 100 255"

						"Pin_To_Sibling"				"12rowssmall"
						"Pin_Corner_To_Sibling"			"PIN_TOPLEFT"
						"Pin_To_Sibling_Corner"			"PIN_TOPRIGHT"

						"Style_Image"
						{
							"ControlName"				"ImagePanel"
							"FieldName"					"Style_Image"
							"XPos"						"cs-0.5"
							"YPos"						"cs-0.5-7"
							"ZPos"						"0"
							"Wide"						"70"
							"Tall"						"70"
							"Visible"					"1"
							"Enabled"					"1"
							"MouseInputEnabled"			"0"
							"ScaleImage"				"1"
							"ProportionalToParent"		"1"
							"Image"						"replay/thumbnails/customizations/maxi/24rows"
						}
						"Style_Label"
						{
							"ControlName"				"CExLabel"
							"FieldName"					"Style_Label"
							"XPos"						"0"
							"YPos"						"rs1"
							"ZPos"						"1"
							"Wide"						"f0"
							"Tall"						"12"
							"Visible"					"1"
							"Enabled"					"1"
							"MouseInputEnabled"			"0"
							"ProportionalToParent"		"1"
							"AllCaps"					"1"
							"Font"						"FontStorePriceSmall"
							"LabelText"					"#HudCustomization_MaxiHud_Death_Style4"
							"TextAlignment"				"center"
							"FGColor"					"Gray"
							"PaintBackground"			"1"
							"PaintBackgroundType"		"0"
							"BGColor_Override"			"Background_Darkest"
						}
						"Style_Button"
						{
							"ControlName"				"CExButton"
							"FieldName"					"Style_Button"
							"XPos"						"0"
							"YPos"						"0"
							"ZPos"						"5"
							"Wide"						"f0"
							"Tall"						"f0"
							"Visible"					"1"
							"Enabled"					"1"
							"Font"						""
							"Command"					"engine maxi_mini_24"
							"LabelText"					""
							"Sound_Depressed"			"UI/buttonclick.wav"
							"ProportionalToParent"		"1"
							"ActionSignalLevel"			"6"

							"PaintBackground"			"0"
							"PaintBorder"				"1"

							"border_default"			"NoBorder"
							"border_armed"				"BorderSelectionGray"
						}
					}
					
																	
				}		
				"lastdmg"
				{
					"ControlName"						"EditablePanel"
					"FieldName"							"lastdmg"
					"XPos"								"0"
					"YPos"								"140"
					"ZPos"								"20"
					"Wide"								"f7"
					"Tall"								"100"
					"Visible"							"1"
					"Enabled"							"1"
					"ProportionalToParent"				"1"

					"Damage_Title"
					{
						"ControlName"					"CExLabel"
						"FieldName"						"Damage_Title"
						"XPos"							"4"
						"YPos"							"0"
						"ZPos"							"0"
						"Wide"							"f35"
						"Tall"							"15"
						"Visible"						"1"
						"Enabled"						"1"
						"ProportionalToParent"			"1"
						"AllCaps"						"1"
						"LabelText"						"#HudCustomization_MaxiHud_Damage"
						"Font"							"HudFontSmallBold"
						"TextAlignment"					"west"
						"FGColor"						"Gray"
					}
					"Separator"
					{
						"ControlName"					"EditablePanel"
						"FieldName"						"Separator"
						"XPos"							"2"
						"YPos"							"15"
						"ZPos"							"0"
						"Wide"							"f40"
						"Tall"							"1"
						"Visible"						"1"
						"Enabled"						"1"
						"ProportionalToParent"			"1"
						"paintBackground"				"1"
						"paintBackgroundtype"			"3"
						"BGcolor_Override"				"Background_Bright"
					}
					"8rows"
					{
						"ControlName"					"EditablePanel"
						"FieldName"						"8rows"
						"XPos"							"-2"
						"YPos"							"5"
						"ZPos"							"1"
						"Wide"							"68"
						"Tall"							"68"
						"Visible"						"1"
						"Enabled"						"1"
						"ProportionalToParent"			"1"
						"PaintBackground"				"1"
						"BGcolor_Override"				"104 101 100 255"

						"Pin_To_Sibling"				"Separator"
						"Pin_Corner_To_Sibling"			"PIN_TOPLEFT"
						"Pin_To_Sibling_Corner"			"PIN_BOTTOMLEFT"

						"Style_Image"
						{
							"ControlName"				"ImagePanel"
							"FieldName"					"Style_Image"
							"XPos"						"cs-0.5"
							"YPos"						"cs-0.5-7"
							"ZPos"						"0"
							"Wide"						"70"
							"Tall"						"70"
							"Visible"					"1"
							"Enabled"					"1"
							"MouseInputEnabled"			"0"
							"ScaleImage"				"1"
							"ProportionalToParent"		"1"
							"Image"						"replay/thumbnails/customizations/maxi/dmg"
						}
						"Style_Disabled"
						{
							"ControlName"				"ImagePanel"
							"FieldName"					"Style_Disabled"
							"XPos"						"cs-0.5"
							"YPos"						"cs-0.5-6"
							"ZPos"						"3"
							"Wide"						"68"
							"Tall"						"42"
							"Visible"					"1"
							"Enabled"					"1"
							"MouseInputEnabled"			"0"
							"ProportionalToParent"		"1"
							"Image"						"replay/thumbnails/customizations/general/disabled_cross"
							"ScaleImage"				"1"
							"Drawcolor"					"Red"
							"Alpha"						"200"
						}						
						"Style_Label"
						{
							"ControlName"				"CExLabel"
							"FieldName"					"Style_Label"
							"XPos"						"0"
							"YPos"						"rs1"
							"ZPos"						"1"
							"Wide"						"f0"
							"Tall"						"12"
							"Visible"					"1"
							"Enabled"					"1"
							"MouseInputEnabled"			"0"
							"ProportionalToParent"		"1"
							"AllCaps"					"1"
							"Font"						"FontStorePrice"
							"LabelText"					"#HudCustomization_Off"
							"TextAlignment"				"center"
							"FGColor"					"Gray"
							"PaintBackground"			"1"
							"PaintBackgroundType"		"0"
							"BGColor_Override"			"Background_Darkest"
						}
						"Style_Button"
						{
							"ControlName"				"CExButton"
							"FieldName"					"Style_Button"
							"XPos"						"0"
							"YPos"						"0"
							"ZPos"						"5"
							"Wide"						"f0"
							"Tall"						"f0"
							"Visible"					"1"
							"Enabled"					"1"
							"Font"						""
							"Command"					"engine maxi_dmg_off"
							"LabelText"					""
							"Sound_Depressed"			"UI/buttonclick.wav"
							"ProportionalToParent"		"1"
							"ActionSignalLevel"			"6"

							"PaintBackground"			"0"
							"PaintBorder"				"1"

							"border_default"			"NoBorder"
							"border_armed"				"BorderSelectionGray"
						}
					}
// DAMAGE SMALL MINUSLESS -------------------------------------------------------------------------------------------
					"12rowsextended"
					{
						"ControlName"					"EditablePanel"
						"FieldName"						"12rowsextended"
						"XPos"							"5"
						"YPos"							"0"
						"ZPos"							"1"
						"Wide"							"68"
						"Tall"							"68"
						"Visible"						"1"
						"Enabled"						"1"
						"ProportionalToParent"			"1"
						"PaintBackground"				"1"
						"BGcolor_Override"				"104 101 100 255"

						"Pin_To_Sibling"				"8rows"
						"Pin_Corner_To_Sibling"			"PIN_TOPLEFT"
						"Pin_To_Sibling_Corner"			"PIN_TOPRIGHT"

						"Style_Image"
						{
							"ControlName"				"ImagePanel"
							"FieldName"					"Style_Image"
							"XPos"						"cs-0.5"
							"YPos"						"cs-0.5-7"
							"ZPos"						"0"
							"Wide"						"70"
							"Tall"						"70"
							"Visible"					"1"
							"Enabled"					"1"
							"MouseInputEnabled"			"0"
							"ScaleImage"				"1"
							"ProportionalToParent"		"1"
							"Image"						"replay/thumbnails/customizations/maxi/dmg"
						}
						"Style_Label"
						{
							"ControlName"				"CExLabel"
							"FieldName"					"Style_Label"
							"XPos"						"0"
							"YPos"						"rs1"
							"ZPos"						"1"
							"Wide"						"f0"
							"Tall"						"12"
							"Visible"					"1"
							"Enabled"					"1"
							"MouseInputEnabled"			"0"
							"ProportionalToParent"		"1"
							"AllCaps"					"1"
							"Font"						"FontStorePrice"
							"LabelText"					"#HudCustomization_On"
							"TextAlignment"				"center"
							"FGColor"					"Gray"
							"PaintBackground"			"1"
							"PaintBackgroundType"		"0"
							"BGColor_Override"			"Background_Darkest"
						}
						"Style_Button"
						{
							"ControlName"				"CExButton"
							"FieldName"					"Style_Button"
							"XPos"						"0"
							"YPos"						"0"
							"ZPos"						"5"
							"Wide"						"f0"
							"Tall"						"f0"
							"Visible"					"1"
							"Enabled"					"1"
							"Font"						""
							"Command"					"engine maxi_dmg_on"
							"LabelText"					""
							"Sound_Depressed"			"UI/buttonclick.wav"
							"ProportionalToParent"		"1"
							"ActionSignalLevel"			"6"

							"PaintBackground"			"0"
							"PaintBorder"				"1"

							"border_default"			"NoBorder"
							"border_armed"				"BorderSelectionGray"
						}
					}		
						
				}	
				"teamstatusbar"
				{
					"ControlName"						"EditablePanel"
					"FieldName"							"teamstatusbar"
					"XPos"								"0"
					"YPos"								"250"
					"ZPos"								"20"
					"Wide"								"f7"
					"Tall"								"200"
					"Visible"							"0"
					"Enabled"							"1"
					"ProportionalToParent"				"1"

					"Title"
					{
						"ControlName"					"CExLabel"
						"FieldName"						"Title"
						"XPos"							"4"
						"YPos"							"0"
						"ZPos"							"0"
						"Wide"							"f35"
						"Tall"							"15"
						"Visible"						"1"
						"Enabled"						"1"
						"ProportionalToParent"			"1"
						"AllCaps"						"1"
						"LabelText"						"#HudCustomization_MatchStatus_Style"
						"Font"							"HudFontSmallBold"
						"TextAlignment"					"west"
						"FGColor"						"Gray"
					}
					"Separator"
					{
						"ControlName"					"EditablePanel"
						"FieldName"						"Separator"
						"XPos"							"2"
						"YPos"							"15"
						"ZPos"							"0"
						"Wide"							"f40"
						"Tall"							"1"
						"Visible"						"1"
						"Enabled"						"1"
						"ProportionalToParent"			"1"
						"paintBackground"				"1"
						"paintBackgroundtype"			"3"
						"BGcolor_Override"				"Background_Bright"
					}
					"Full"
					{
						"ControlName"					"EditablePanel"
						"FieldName"						"Full"
						"XPos"							"-2"
						"YPos"							"5"
						"ZPos"							"1"
						"Wide"							"140"
						"Tall"							"68"
						"Visible"						"1"
						"Enabled"						"1"
						"ProportionalToParent"			"1"
						"PaintBackground"				"1"
						"BGcolor_Override"				"104 101 100 255"

						"Pin_To_Sibling"				"Separator"
						"Pin_Corner_To_Sibling"			"PIN_TOPLEFT"
						"Pin_To_Sibling_Corner"			"PIN_BOTTOMLEFT"

						"Style_Image"
						{
							"ControlName"				"ImagePanel"
							"FieldName"					"Style_Image"
							"XPos"						"cs-0.5"
							"YPos"						"cs-0.5-1"
							"ZPos"						"0"
							"Wide"						"138"
							"Tall"						"65"
							"Visible"					"1"
							"Enabled"					"1"
							"MouseInputEnabled"			"0"
							"ScaleImage"				"1"
							"ProportionalToParent"		"1"
							"Image"						"replay/thumbnails/customizations/maxi/tm_full"
						}
						"Style_Label"
						{
							"ControlName"				"CExLabel"
							"FieldName"					"Style_Label"
							"XPos"						"0"
							"YPos"						"rs1"
							"ZPos"						"1"
							"Wide"						"f0"
							"Tall"						"12"
							"Visible"					"1"
							"Enabled"					"1"
							"MouseInputEnabled"			"0"
							"ProportionalToParent"		"1"
							"AllCaps"					"1"
							"Font"						"FontStorePrice"
							"LabelText"					"#HudCustomization_MatchStatus_Style1"
							"TextAlignment"				"center"
							"FGColor"					"Gray"
							"PaintBackground"			"1"
							"PaintBackgroundType"		"0"
							"BGColor_Override"			"Background_Darkest"
						}
						"Style_Button"
						{
							"ControlName"				"CExButton"
							"FieldName"					"Style_Button"
							"XPos"						"0"
							"YPos"						"0"
							"ZPos"						"5"
							"Wide"						"f0"
							"Tall"						"f0"
							"Visible"					"1"
							"Enabled"					"1"
							"Font"						""
							"Command"					"engine maxi_tm_1; maxi_tm2_1"
							"LabelText"					""
							"Sound_Depressed"			"UI/buttonclick.wav"
							"ProportionalToParent"		"1"
							"ActionSignalLevel"			"6"

							"PaintBackground"			"0"
							"PaintBorder"				"1"

							"border_default"			"NoBorder"
							"border_armed"				"BorderSelectionGray"
						}
					}

					"fullnf"
					{
						"ControlName"					"EditablePanel"
						"FieldName"						"fullnf"
						"XPos"							"5"
						"YPos"							"0"
						"ZPos"							"1"
						"Wide"							"140"
						"Tall"							"68"
						"Visible"						"1"
						"Enabled"						"1"
						"ProportionalToParent"			"1"
						"PaintBackground"				"1"
						"BGcolor_Override"				"104 101 100 255"

						"Pin_To_Sibling"				"full"
						"Pin_Corner_To_Sibling"			"PIN_TOPLEFT"
						"Pin_To_Sibling_Corner"			"PIN_TOPRIGHT"

						"Style_Image"
						{
							"ControlName"				"ImagePanel"
							"FieldName"					"Style_Image"
							"XPos"						"cs-0.5"
							"YPos"						"cs-0.5-1"
							"ZPos"						"0"
							"Wide"						"138"
							"Tall"						"65"
							"Visible"					"1"
							"Enabled"					"1"
							"MouseInputEnabled"			"0"
							"ScaleImage"				"1"
							"ProportionalToParent"		"1"
							"Image"						"replay/thumbnails/customizations/maxi/tm_full_nf"
						}
						"Style_Label"
						{
							"ControlName"				"CExLabel"
							"FieldName"					"Style_Label"
							"XPos"						"0"
							"YPos"						"rs1"
							"ZPos"						"1"
							"Wide"						"f0"
							"Tall"						"12"
							"Visible"					"1"
							"Enabled"					"1"
							"MouseInputEnabled"			"0"
							"ProportionalToParent"		"1"
							"AllCaps"					"1"
							"Font"						"FontStorePrice"
							"LabelText"					"#HudCustomization_MatchStatus_Style2"
							"TextAlignment"				"center"
							"FGColor"					"Gray"
							"PaintBackground"			"1"
							"PaintBackgroundType"		"0"
							"BGColor_Override"			"Background_Darkest"
						}
						"Style_Button"
						{
							"ControlName"				"CExButton"
							"FieldName"					"Style_Button"
							"XPos"						"0"
							"YPos"						"0"
							"ZPos"						"5"
							"Wide"						"f0"
							"Tall"						"f0"
							"Visible"					"1"
							"Enabled"					"1"
							"Font"						""
							"Command"					"engine maxi_tm_2; maxi_tm2_2"
							"LabelText"					""
							"Sound_Depressed"			"UI/buttonclick.wav"
							"ProportionalToParent"		"1"
							"ActionSignalLevel"			"6"

							"PaintBackground"			"0"
							"PaintBorder"				"1"

							"border_default"			"NoBorder"
							"border_armed"				"BorderSelectionGray"
						}
					}		

					"extendef"
					{
						"ControlName"					"EditablePanel"
						"FieldName"						"extendef"
						"XPos"							"4"
						"YPos"							"100"
						"ZPos"							"1"
						"Wide"							"140"
						"Tall"							"68"
						"Visible"						"1"
						"Enabled"						"1"
						"ProportionalToParent"			"1"
						"PaintBackground"				"1"
						"BGcolor_Override"				"104 101 100 255"

						"Style_Image"
						{
							"ControlName"				"ImagePanel"
							"FieldName"					"Style_Image"
							"XPos"						"cs-0.5"
							"YPos"						"cs-0.5-1"
							"ZPos"						"0"
							"Wide"						"138"
							"Tall"						"65"
							"Visible"					"1"
							"Enabled"					"1"
							"MouseInputEnabled"			"0"
							"ScaleImage"				"1"
							"ProportionalToParent"		"1"
							"Image"						"replay/thumbnails/customizations/maxi/tm_full"
						}
						"Style_Label"
						{
							"ControlName"				"CExLabel"
							"FieldName"					"Style_Label"
							"XPos"						"0"
							"YPos"						"rs1"
							"ZPos"						"1"
							"Wide"						"f0"
							"Tall"						"12"
							"Visible"					"1"
							"Enabled"					"1"
							"MouseInputEnabled"			"0"
							"ProportionalToParent"		"1"
							"AllCaps"					"1"
							"Font"						"FontStorePrice"
							"LabelText"					"#HudCustomization_MatchStatus_Style3"
							"TextAlignment"				"center"
							"FGColor"					"Gray"
							"PaintBackground"			"1"
							"PaintBackgroundType"		"0"
							"BGColor_Override"			"Background_Darkest"
						}
						"Style_Button"
						{
							"ControlName"				"CExButton"
							"FieldName"					"Style_Button"
							"XPos"						"0"
							"YPos"						"0"
							"ZPos"						"5"
							"Wide"						"f0"
							"Tall"						"f0"
							"Visible"					"1"
							"Enabled"					"1"
							"Font"						""
							"Command"					"engine maxi_tm_4; maxi_tm2_4"
							"LabelText"					""
							"Sound_Depressed"			"UI/buttonclick.wav"
							"ProportionalToParent"		"1"
							"ActionSignalLevel"			"6"

							"PaintBackground"			"0"
							"PaintBorder"				"1"

							"border_default"			"NoBorder"
							"border_armed"				"BorderSelectionGray"
						}
					}
					"extendenoframe"
					{
						"ControlName"					"EditablePanel"
						"FieldName"						"extendenoframe"
						"XPos"							"5"
						"YPos"							"0"
						"ZPos"							"1"
						"Wide"							"140"
						"Tall"							"68"
						"Visible"						"1"
						"Enabled"						"1"
						"ProportionalToParent"			"1"
						"PaintBackground"				"1"
						"BGcolor_Override"				"104 101 100 255"

						"Pin_To_Sibling"				"compact2"
						"Pin_Corner_To_Sibling"			"PIN_TOPLEFT"
						"Pin_To_Sibling_Corner"			"PIN_TOPRIGHT"

						"Style_Image"
						{
							"ControlName"				"ImagePanel"
							"FieldName"					"Style_Image"
							"XPos"						"cs-0.5"
							"YPos"						"cs-0.5-1"
							"ZPos"						"0"
							"Wide"						"138"
							"Tall"						"65"
							"Visible"					"1"
							"Enabled"					"1"
							"MouseInputEnabled"			"0"
							"ScaleImage"				"1"
							"ProportionalToParent"		"1"
							"Image"						"replay/thumbnails/customizations/maxi/tm_full_nf"
						}
						"Style_Label"
						{
							"ControlName"				"CExLabel"
							"FieldName"					"Style_Label"
							"XPos"						"0"
							"YPos"						"rs1"
							"ZPos"						"1"
							"Wide"						"f0"
							"Tall"						"12"
							"Visible"					"1"
							"Enabled"					"1"
							"MouseInputEnabled"			"0"
							"ProportionalToParent"		"1"
							"AllCaps"					"1"
							"Font"						"FontStorePrice"
							"LabelText"					"#HudCustomization_MatchStatus_Style4"
							"TextAlignment"				"center"
							"FGColor"					"Gray"
							"PaintBackground"			"1"
							"PaintBackgroundType"		"0"
							"BGColor_Override"			"Background_Darkest"
						}
						"Style_Button"
						{
							"ControlName"				"CExButton"
							"FieldName"					"Style_Button"
							"XPos"						"0"
							"YPos"						"0"
							"ZPos"						"5"
							"Wide"						"f0"
							"Tall"						"f0"
							"Visible"					"1"
							"Enabled"					"1"
							"Font"						""
							"Command"					"engine maxi_tm_3; maxi_tm2_3"
							"LabelText"					""
							"Sound_Depressed"			"UI/buttonclick.wav"
							"ProportionalToParent"		"1"
							"ActionSignalLevel"			"6"

							"PaintBackground"			"0"
							"PaintBorder"				"1"

							"border_default"			"NoBorder"
							"border_armed"				"BorderSelectionGray"
						}
					}
					"compact"
					{
						"ControlName"					"EditablePanel"
						"FieldName"						"compact"
						"XPos"							"5"
						"YPos"							"0"
						"ZPos"							"1"
						"Wide"							"140"
						"Tall"							"68"
						"Visible"						"1"
						"Enabled"						"1"
						"ProportionalToParent"			"1"
						"PaintBackground"				"1"
						"BGcolor_Override"				"104 101 100 255"

						"Pin_To_Sibling"				"fullnf"
						"Pin_Corner_To_Sibling"			"PIN_TOPLEFT"
						"Pin_To_Sibling_Corner"			"PIN_TOPRIGHT"

						"Style_Image"
						{
							"ControlName"				"Panel"
							"FieldName"					"Style_Image"
							"XPos"						"cs-0.5"
							"YPos"						"cs-0.5-1"
							"ZPos"						"0"
							"Wide"						"138"
							"Tall"						"65"
							"Visible"					"0"
							"Enabled"					"1"
							"MouseInputEnabled"			"0"
							"ScaleImage"				"1"
							"ProportionalToParent"		"1"
						}
						"Style_Label"
						{
							"ControlName"				"CExLabel"
							"FieldName"					"Style_Label"
							"XPos"						"0"
							"YPos"						"rs1"
							"ZPos"						"1"
							"Wide"						"f0"
							"Tall"						"12"
							"Visible"					"1"
							"Enabled"					"1"
							"MouseInputEnabled"			"0"
							"ProportionalToParent"		"1"
							"AllCaps"					"1"
							"Font"						"FontStorePrice"
							"LabelText"					"#HudCustomization_MatchStatus_Style5"
							"TextAlignment"				"center"
							"FGColor"					"Gray"
							"PaintBackground"			"1"
							"PaintBackgroundType"		"0"
							"BGColor_Override"			"Background_Darkest"
						}
						"Style_Button"
						{
							"ControlName"				"CExButton"
							"FieldName"					"Style_Button"
							"XPos"						"0"
							"YPos"						"0"
							"ZPos"						"5"
							"Wide"						"f0"
							"Tall"						"f0"
							"Visible"					"1"
							"Enabled"					"1"
							"Font"						""
							"Command"					"engine maxi_tm_5; maxi_tm2_5"
							"LabelText"					""
							"Sound_Depressed"			"UI/buttonclick.wav"
							"ProportionalToParent"		"1"
							"ActionSignalLevel"			"6"

							"PaintBackground"			"0"
							"PaintBorder"				"1"

							"border_default"			"NoBorder"
							"border_armed"				"BorderSelectionGray"
						}
					}	
					"compact2"
					{
						"ControlName"					"EditablePanel"
						"FieldName"						"compact2"
						"XPos"							"150"
						"YPos"							"100"
						"ZPos"							"1"
						"Wide"							"140"
						"Tall"							"68"
						"Visible"						"1"
						"Enabled"						"1"
						"ProportionalToParent"			"1"
						"PaintBackground"				"1"
						"BGcolor_Override"				"104 101 100 255"

						"Style_Image"
						{
							"ControlName"				"Panel"
							"FieldName"					"Style_Image"
							"XPos"						"cs-0.5"
							"YPos"						"cs-0.5-1"
							"ZPos"						"0"
							"Wide"						"138"
							"Tall"						"65"
							"Visible"					"0"
							"Enabled"					"1"
							"MouseInputEnabled"			"0"
							"ScaleImage"				"1"
							"ProportionalToParent"		"1"
						}
						"Style_Label"
						{
							"ControlName"				"CExLabel"
							"FieldName"					"Style_Label"
							"XPos"						"0"
							"YPos"						"rs1"
							"ZPos"						"1"
							"Wide"						"f0"
							"Tall"						"12"
							"Visible"					"1"
							"Enabled"					"1"
							"MouseInputEnabled"			"0"
							"ProportionalToParent"		"1"
							"AllCaps"					"1"
							"Font"						"FontStorePrice"
							"LabelText"					"#HudCustomization_MatchStatus_Style6"
							"TextAlignment"				"center"
							"FGColor"					"Gray"
							"PaintBackground"			"1"
							"PaintBackgroundType"		"0"
							"BGColor_Override"			"Background_Darkest"
						}
						"Style_Button"
						{
							"ControlName"				"CExButton"
							"FieldName"					"Style_Button"
							"XPos"						"0"
							"YPos"						"0"
							"ZPos"						"5"
							"Wide"						"f0"
							"Tall"						"f0"
							"Visible"					"1"
							"Enabled"					"1"
							"Font"						""
							"Command"					"engine maxi_tm_6; maxi_tm2_6"
							"LabelText"					""
							"Sound_Depressed"			"UI/buttonclick.wav"
							"ProportionalToParent"		"1"
							"ActionSignalLevel"			"6"

							"PaintBackground"			"0"
							"PaintBorder"				"1"

							"border_default"			"NoBorder"
							"border_armed"				"BorderSelectionGray"
						}
					}																							
				}	
				"payloadicon"
				{
					"ControlName"						"EditablePanel"
					"FieldName"							"payloadicon"
					"XPos"								"0"
					"YPos"								"250"
					"ZPos"								"20"
					"Wide"								"f7"
					"Tall"								"100"
					"Visible"							"1"
					"Enabled"							"1"
					"ProportionalToParent"				"1"

					"Damage_Title"
					{
						"ControlName"					"CExLabel"
						"FieldName"						"Damage_Title"
						"XPos"							"4"
						"YPos"							"0"
						"ZPos"							"0"
						"Wide"							"f35"
						"Tall"							"15"
						"Visible"						"1"
						"Enabled"						"1"
						"ProportionalToParent"			"1"
						"AllCaps"						"1"
						"LabelText"						"#HudCustomization_MaxiHud_PayloadIcon"
						"Font"							"HudFontSmallBold"
						"TextAlignment"					"west"
						"FGColor"						"Gray"
					}
					"Separator"
					{
						"ControlName"					"EditablePanel"
						"FieldName"						"Separator"
						"XPos"							"2"
						"YPos"							"15"
						"ZPos"							"0"
						"Wide"							"f40"
						"Tall"							"1"
						"Visible"						"1"
						"Enabled"						"1"
						"ProportionalToParent"			"1"
						"paintBackground"				"1"
						"paintBackgroundtype"			"3"
						"BGcolor_Override"				"Background_Bright"
					}
					"8rows"
					{
						"ControlName"					"EditablePanel"
						"FieldName"						"8rows"
						"XPos"							"-2"
						"YPos"							"5"
						"ZPos"							"1"
						"Wide"							"68"
						"Tall"							"68"
						"Visible"						"1"
						"Enabled"						"1"
						"ProportionalToParent"			"1"
						"PaintBackground"				"1"
						"BGcolor_Override"				"104 101 100 255"

						"Pin_To_Sibling"				"Separator"
						"Pin_Corner_To_Sibling"			"PIN_TOPLEFT"
						"Pin_To_Sibling_Corner"			"PIN_BOTTOMLEFT"

						"Style_Image"
						{
							"ControlName"				"ImagePanel"
							"FieldName"					"Style_Image"
							"XPos"						"cs-0.5"
							"YPos"						"cs-0.5-13"
							"ZPos"						"0"
							"Wide"						"70"
							"Tall"						"70"
							"Visible"					"1"
							"Enabled"					"1"
							"MouseInputEnabled"			"0"
							"ScaleImage"				"1"
							"ProportionalToParent"		"1"
							"Image"						"replay/thumbnails/customizations/maxi/payload_vex"
						}
						"Style_Label"
						{
							"ControlName"				"CExLabel"
							"FieldName"					"Style_Label"
							"XPos"						"0"
							"YPos"						"rs1"
							"ZPos"						"1"
							"Wide"						"f0"
							"Tall"						"12"
							"Visible"					"1"
							"Enabled"					"1"
							"MouseInputEnabled"			"0"
							"ProportionalToParent"		"1"
							"AllCaps"					"1"
							"Font"						"fontstoreprice"
							"LabelText"					"Vexcenot"
							"TextAlignment"				"center"
							"FGColor"					"Gray"
							"PaintBackground"			"1"
							"PaintBackgroundType"		"0"
							"BGColor_Override"			"Background_Darkest"
						}
						"Style_Button"
						{
							"ControlName"				"CExButton"
							"FieldName"					"Style_Button"
							"XPos"						"0"
							"YPos"						"0"
							"ZPos"						"5"
							"Wide"						"f0"
							"Tall"						"f0"
							"Visible"					"1"
							"Enabled"					"1"
							"Font"						""
							"Command"					"engine maxi_payload_vex"
							"LabelText"					""
							"Sound_Depressed"			"UI/buttonclick.wav"
							"ProportionalToParent"		"1"
							"ActionSignalLevel"			"6"

							"PaintBackground"			"0"
							"PaintBorder"				"1"

							"border_default"			"NoBorder"
							"border_armed"				"BorderSelectionGray"
						}
					}
//
					"12rowsextended"
					{
						"ControlName"					"EditablePanel"
						"FieldName"						"12rowsextended"
						"XPos"							"5"
						"YPos"							"0"
						"ZPos"							"1"
						"Wide"							"68"
						"Tall"							"68"
						"Visible"						"1"
						"Enabled"						"1"
						"ProportionalToParent"			"1"
						"PaintBackground"				"1"
						"BGcolor_Override"				"104 101 100 255"

						"Pin_To_Sibling"				"8rows"
						"Pin_Corner_To_Sibling"			"PIN_TOPLEFT"
						"Pin_To_Sibling_Corner"			"PIN_TOPRIGHT"

						"Style_Image"
						{
							"ControlName"				"ImagePanel"
							"FieldName"					"Style_Image"
							"XPos"						"cs-0.5"
							"YPos"						"cs-0.5-13"
							"ZPos"						"0"
							"Wide"						"70"
							"Tall"						"70"
							"Visible"					"1"
							"Enabled"					"1"
							"MouseInputEnabled"			"0"
							"ScaleImage"				"1"
							"ProportionalToParent"		"1"
							"Image"						"replay/thumbnails/customizations/maxi/payload_stock"
						}
						"Style_Label"
						{
							"ControlName"				"CExLabel"
							"FieldName"					"Style_Label"
							"XPos"						"0"
							"YPos"						"rs1"
							"ZPos"						"1"
							"Wide"						"f0"
							"Tall"						"12"
							"Visible"					"1"
							"Enabled"					"1"
							"MouseInputEnabled"			"0"
							"ProportionalToParent"		"1"
							"AllCaps"					"1"
							"Font"						"FontStorePrice"
							"LabelText"					"#HudCustomization_Vanilla"
							"TextAlignment"				"center"
							"FGColor"					"Gray"
							"PaintBackground"			"1"
							"PaintBackgroundType"		"0"
							"BGColor_Override"			"Background_Darkest"
						}
						"Style_Button"
						{
							"ControlName"				"CExButton"
							"FieldName"					"Style_Button"
							"XPos"						"0"
							"YPos"						"0"
							"ZPos"						"5"
							"Wide"						"f0"
							"Tall"						"f0"
							"Visible"					"1"
							"Enabled"					"1"
							"Font"						""
							"Command"					"engine maxi_payload_vanilla"
							"LabelText"					""
							"Sound_Depressed"			"UI/buttonclick.wav"
							"ProportionalToParent"		"1"
							"ActionSignalLevel"			"6"

							"PaintBackground"			"0"
							"PaintBorder"				"1"

							"border_default"			"NoBorder"
							"border_armed"				"BorderSelectionGray"
						}
					}
				}
// CHARGE METERS/STICKYBOMB COUNTER -------------------------------------------------------------------------------------------				
				"chargmeter"
				{
					"ControlName"						"EditablePanel"
					"FieldName"							"chargmeter"
					"XPos"								"0"
					"YPos"								"350"
					"ZPos"								"20"
					"Wide"								"f7"
					"Tall"								"100"
					"Visible"							"1"
					"Enabled"							"1"
					"ProportionalToParent"				"1"

					"Damage_Title"
					{
						"ControlName"					"CExLabel"
						"FieldName"						"Damage_Title"
						"XPos"							"4"
						"YPos"							"0"
						"ZPos"							"0"
						"Wide"							"f35"
						"Tall"							"15"
						"Visible"						"1"
						"Enabled"						"1"
						"ProportionalToParent"			"1"
						"AllCaps"						"1"
						"LabelText"						"#HudCustomization_MaxiHud_Meter"
						"Font"							"HudFontSmallBold"
						"TextAlignment"					"west"
						"FGColor"						"Gray"
					}
					"Separator"
					{
						"ControlName"					"EditablePanel"
						"FieldName"						"Separator"
						"XPos"							"2"
						"YPos"							"15"
						"ZPos"							"0"
						"Wide"							"f40"
						"Tall"							"1"
						"Visible"						"1"
						"Enabled"						"1"
						"ProportionalToParent"			"1"
						"paintBackground"				"1"
						"paintBackgroundtype"			"3"
						"BGcolor_Override"				"Background_Bright"
					}
// TYPE A -------------------------------------------------------------------------------------------					
					"8rows"
					{
						"ControlName"					"EditablePanel"
						"FieldName"						"8rows"
						"XPos"							"-2"
						"YPos"							"5"
						"ZPos"							"1"
						"Wide"							"136"
						"Tall"							"68"
						"Visible"						"1"
						"Enabled"						"1"
						"ProportionalToParent"			"1"
						"PaintBackground"				"1"
						"BGcolor_Override"				"104 101 100 255"

						"Pin_To_Sibling"				"Separator"
						"Pin_Corner_To_Sibling"			"PIN_TOPLEFT"
						"Pin_To_Sibling_Corner"			"PIN_BOTTOMLEFT"

						"Style_Image"
						{
							"ControlName"				"ImagePanel"
							"FieldName"					"Style_Image"
							"XPos"						"cs-0.5"
							"YPos"						"cs-0.5-7"
							"ZPos"						"0"
							"Wide"						"140"
							"Tall"						"70"
							"Visible"					"1"
							"Enabled"					"1"
							"MouseInputEnabled"			"0"
							"ScaleImage"				"1"
							"ProportionalToParent"		"1"
							"Image"						"replay/thumbnails/customizations/maxi/charge_og"
						}
						"Style_Label"
						{
							"ControlName"				"CExLabel"
							"FieldName"					"Style_Label"
							"XPos"						"0"
							"YPos"						"rs1"
							"ZPos"						"1"
							"Wide"						"f0"
							"Tall"						"12"
							"Visible"					"1"
							"Enabled"					"1"
							"MouseInputEnabled"			"0"
							"ProportionalToParent"		"1"
							"AllCaps"					"1"
							"Font"						"FontStorePrice"
							"LabelText"					"#HudCustomization_MaxiHud_Meter_Style1"
							"TextAlignment"				"center"
							"FGColor"					"Gray"
							"PaintBackground"			"1"
							"PaintBackgroundType"		"0"
							"BGColor_Override"			"Background_Darkest"
						}
						"Style_Button"
						{
							"ControlName"				"CExButton"
							"FieldName"					"Style_Button"
							"XPos"						"0"
							"YPos"						"0"
							"ZPos"						"5"
							"Wide"						"f0"
							"Tall"						"f0"
							"Visible"					"1"
							"Enabled"					"1"
							"Font"						""
							"Command"					"engine maxi_charge_og_lay; maxi_res_charge_clear_pipe"
							"LabelText"					""
							"Sound_Depressed"			"UI/buttonclick.wav"
							"ProportionalToParent"		"1"
							"ActionSignalLevel"			"6"

							"PaintBackground"			"0"
							"PaintBorder"				"1"

							"border_default"			"NoBorder"
							"border_armed"				"BorderSelectionGray"
						}
					}
// TYPE B -------------------------------------------------------------------------------------------
					"12rowsextended"
					{
						"ControlName"					"EditablePanel"
						"FieldName"						"12rowsextended"
						"XPos"							"5"
						"YPos"							"0"
						"ZPos"							"1"
						"Wide"							"136"
						"Tall"							"68"
						"Visible"						"1"
						"Enabled"						"1"
						"ProportionalToParent"			"1"
						"PaintBackground"				"1"
						"BGcolor_Override"				"104 101 100 255"

						"Pin_To_Sibling"				"8rows"
						"Pin_Corner_To_Sibling"			"PIN_TOPLEFT"
						"Pin_To_Sibling_Corner"			"PIN_TOPRIGHT"

						"Style_Image"
						{
							"ControlName"				"ImagePanel"
							"FieldName"					"Style_Image"
							"XPos"						"cs-0.5"
							"YPos"						"cs-0.5-7"
							"ZPos"						"0"
							"Wide"						"140"
							"Tall"						"70"
							"Visible"					"1"
							"Enabled"					"1"
							"MouseInputEnabled"			"0"
							"ScaleImage"				"1"
							"ProportionalToParent"		"1"
							"Image"						"replay/thumbnails/customizations/maxi/charge_def"
						}
						"Style_Label"
						{
							"ControlName"				"CExLabel"
							"FieldName"					"Style_Label"
							"XPos"						"0"
							"YPos"						"rs1"
							"ZPos"						"1"
							"Wide"						"f0"
							"Tall"						"12"
							"Visible"					"1"
							"Enabled"					"1"
							"MouseInputEnabled"			"0"
							"ProportionalToParent"		"1"
							"AllCaps"					"1"
							"Font"						"FontStorePrice"
							"LabelText"					"#HudCustomization_MaxiHud_Meter_Style2"
							"TextAlignment"				"center"
							"FGColor"					"Gray"
							"PaintBackground"			"1"
							"PaintBackgroundType"		"0"
							"BGColor_Override"			"Background_Darkest"
						}
						"Style_Button"
						{
							"ControlName"				"CExButton"
							"FieldName"					"Style_Button"
							"XPos"						"0"
							"YPos"						"0"
							"ZPos"						"5"
							"Wide"						"f0"
							"Tall"						"f0"
							"Visible"					"1"
							"Enabled"					"1"
							"Font"						""
							"Command"					"engine maxi_charge_def_lay; maxi_charge_def_pipe"
							"LabelText"					""
							"Sound_Depressed"			"UI/buttonclick.wav"
							"ProportionalToParent"		"1"
							"ActionSignalLevel"			"6"

							"PaintBackground"			"0"
							"PaintBorder"				"1"

							"border_default"			"NoBorder"
							"border_armed"				"BorderSelectionGray"
						}
					}		
				}
				"walk"
				{
					"ControlName"						"EditablePanel"
					"FieldName"							"walk"
					"XPos"								"0"
					"YPos"								"450"
					"ZPos"								"20"
					"Wide"								"f7"
					"Tall"								"140"
					"Visible"							"1"
					"Enabled"							"1"
					"ProportionalToParent"				"1"

					"Damage_Title"
					{
						"ControlName"					"CExLabel"
						"FieldName"						"Damage_Title"
						"XPos"							"4"
						"YPos"							"0"
						"ZPos"							"0"
						"Wide"							"f35"
						"Tall"							"15"
						"Visible"						"1"
						"Enabled"						"1"
						"ProportionalToParent"			"1"
						"AllCaps"						"1"
						"LabelText"						"#HudCustomization_MaxiHud_Walkway"
						"Font"							"HudFontSmallBold"
						"TextAlignment"					"west"
						"FGColor"						"Gray"
					}
					"Separator"
					{
						"ControlName"					"EditablePanel"
						"FieldName"						"Separator"
						"XPos"							"2"
						"YPos"							"15"
						"ZPos"							"0"
						"Wide"							"f40"
						"Tall"							"1"
						"Visible"						"1"
						"Enabled"						"1"
						"ProportionalToParent"			"1"
						"paintBackground"				"1"
						"paintBackgroundtype"			"3"
						"BGcolor_Override"				"Background_Bright"
					}
					"8rows"
					{
						"ControlName"					"EditablePanel"
						"FieldName"						"8rows"
						"XPos"							"-2"
						"YPos"							"5"
						"ZPos"							"1"
						"Wide"							"68"
						"Tall"							"68"
						"Visible"						"1"
						"Enabled"						"1"
						"ProportionalToParent"			"1"
						"PaintBackground"				"1"
						"BGcolor_Override"				"104 101 100 255"

						"Pin_To_Sibling"				"Separator"
						"Pin_Corner_To_Sibling"			"PIN_TOPLEFT"
						"Pin_To_Sibling_Corner"			"PIN_BOTTOMLEFT"

						"Style_Image"
						{
							"ControlName"				"ImagePanel"
							"FieldName"					"Style_Image"
							"XPos"						"cs-0.5"
							"YPos"						"cs-0.5-7"
							"ZPos"						"0"
							"Wide"						"70"
							"Tall"						"70"
							"Visible"					"1"
							"Enabled"					"1"
							"MouseInputEnabled"			"0"
							"ScaleImage"				"1"
							"ProportionalToParent"		"1"
							"Image"						"replay/thumbnails/customizations/maxi/rc2"
						}
						"Style_Label"
						{
							"ControlName"				"CExLabel"
							"FieldName"					"Style_Label"
							"XPos"						"0"
							"YPos"						"rs1"
							"ZPos"						"1"
							"Wide"						"f0"
							"Tall"						"12"
							"Visible"					"1"
							"Enabled"					"1"
							"MouseInputEnabled"			"0"
							"ProportionalToParent"		"1"
							"AllCaps"					"1"
							"Font"						"FontStorePriceSmall"
							"LabelText"					"tr_walkway_rc2"
							"TextAlignment"				"center"
							"FGColor"					"Gray"
							"PaintBackground"			"1"
							"PaintBackgroundType"		"0"
							"BGColor_Override"			"Background_Darkest"
						}
						"Style_Button"
						{
							"ControlName"				"CExButton"
							"FieldName"					"Style_Button"
							"XPos"						"0"
							"YPos"						"0"
							"ZPos"						"5"
							"Wide"						"f0"
							"Tall"						"f0"
							"Visible"					"1"
							"Enabled"					"1"
							"Font"						""
							"Command"					"engine maxi_walk_rc2"
							"LabelText"					""
							"Sound_Depressed"			"UI/buttonclick.wav"
							"ProportionalToParent"		"1"
							"ActionSignalLevel"			"6"

							"PaintBackground"			"0"
							"PaintBorder"				"1"

							"border_default"			"NoBorder"
							"border_armed"				"BorderSelectionGray"
						}
					}
					"Explanation_1"
					{
						"ControlName"					"CExLabel"
						"FieldName"						"Explanation_1"
						"XPos"							"6"
						"YPos"							"95"
						"ZPos"							"1"
						"Wide"							"f10"
						"Tall"							"15"
						"Visible"						"1"
						"Enabled"						"1"
						"mouseinputenabled"				"0"
						"ProportionalToParent"			"1"
						"Wrap"							"1"
						"CenterWrap"					"0"
						"Font"							"FontStoreOriginalPrice"
						"labeltext"						"#HudCustomization_MaxiHud_Walkway_Download"
						"TextAlignment"					"North-West"
						"FGColor"						"Gray"
					}
					"DownloadButton_1"
					{
						"ControlName"					"CExImageButton"
						"FieldName"						"DownloadButton_1"
						"XPos"							"4"
						"YPos"							"107"
						"ZPos"							"20"
						"Wide"							"160"
						"Tall"							"15"
						"Visible"						"1"
						"Enabled"						"1"
						"ActionSignalLevel"				"5"
						"ProportionalToParent"			"1"
						"AllCaps"						"1"
						"Font"							"HudFontSmallestBold"
						"LabelText"						"#HudCustomization_MaxiHud_WW_Download1"
						"TextAlignment"					"west"
						"textinsetx"					"35"
						"Command"						"url https://gamebanana.com/mods/74812"
						"Sound_Depressed"				"UI/buttonclick.wav"
						"PaintBackground"				"1"
						"image_drawcolor"				"235 226 202 255"
						
						"SubImage"
						{
							"ControlName"	"ImagePanel"
							"fieldName"		"SubImage"
							"xpos"			"3"
							"ypos"			"3"
							"zpos"			"1"
							"wide"			"10"
							"tall"			"10"
							"visible"		"1"
							"enabled"		"1"
							"image"			"../vgui/replay/thumbnails/glyph_link"
							"scaleImage"	"1"
						}
					}
					"DownloadButton_2"
					{
						"ControlName"					"CExImageButton"
						"FieldName"						"DownloadButton_2"
						"XPos"							"4+163"
						"YPos"							"107"
						"ZPos"							"20"
						"Wide"							"160"
						"Tall"							"15"
						"Visible"						"1"
						"Enabled"						"1"
						"ActionSignalLevel"				"5"
						"ProportionalToParent"			"1"
						"AllCaps"						"1"
						"Font"							"HudFontSmallestBold"
						"LabelText"						"#HudCustomization_MaxiHud_WW_Download2"
						"TextAlignment"					"west"
						"textinsetx"					"35"
						"Command"						"url https://gamebanana.com/mods/74813"
						"Sound_Depressed"				"UI/buttonclick.wav"
						"PaintBackground"				"1"
						"image_drawcolor"				"235 226 202 255"						
						
						"SubImage"
						{
							"ControlName"	"ImagePanel"
							"fieldName"		"SubImage"
							"xpos"			"3"
							"ypos"			"3"
							"zpos"			"1"
							"wide"			"10"
							"tall"			"10"
							"visible"		"1"
							"enabled"		"1"
							"image"			"../vgui/replay/thumbnails/glyph_link"					
							"scaleImage"	"1"
						}
					}
// DAMAGE SMALL MINUSLESS -------------------------------------------------------------------------------------------
					"12rowsextended"
					{
						"ControlName"					"EditablePanel"
						"FieldName"						"12rowsextended"
						"XPos"							"5"
						"YPos"							"0"
						"ZPos"							"1"
						"Wide"							"68"
						"Tall"							"68"
						"Visible"						"1"
						"Enabled"						"1"
						"ProportionalToParent"			"1"
						"PaintBackground"				"1"
						"BGcolor_Override"				"104 101 100 255"

						"Pin_To_Sibling"				"8rows"
						"Pin_Corner_To_Sibling"			"PIN_TOPLEFT"
						"Pin_To_Sibling_Corner"			"PIN_TOPRIGHT"

						"Style_Image"
						{
							"ControlName"				"ImagePanel"
							"FieldName"					"Style_Image"
							"XPos"						"cs-0.5"
							"YPos"						"cs-0.5-7"
							"ZPos"						"0"
							"Wide"						"70"
							"Tall"						"70"
							"Visible"					"1"
							"Enabled"					"1"
							"MouseInputEnabled"			"0"
							"ScaleImage"				"1"
							"ProportionalToParent"		"1"
							"Image"						"replay/thumbnails/customizations/maxi/h1"
						}
						"Style_Label"
						{
							"ControlName"				"CExLabel"
							"FieldName"					"Style_Label"
							"XPos"						"0"
							"YPos"						"rs1"
							"ZPos"						"1"
							"Wide"						"f0"
							"Tall"						"12"
							"Visible"					"1"
							"Enabled"					"1"
							"MouseInputEnabled"			"0"
							"ProportionalToParent"		"1"
							"AllCaps"					"1"
							"Font"						"FontStorePriceSmall"
							"LabelText"					"tr_walkway_h1"
							"TextAlignment"				"center"
							"FGColor"					"Gray"
							"PaintBackground"			"1"
							"PaintBackgroundType"		"0"
							"BGColor_Override"			"Background_Darkest"
						}
						"Style_Button"
						{
							"ControlName"				"CExButton"
							"FieldName"					"Style_Button"
							"XPos"						"0"
							"YPos"						"0"
							"ZPos"						"5"
							"Wide"						"f0"
							"Tall"						"f0"
							"Visible"					"1"
							"Enabled"					"1"
							"Font"						""
							"Command"					"engine maxi_walk_h1"
							"LabelText"					""
							"Sound_Depressed"			"UI/buttonclick.wav"
							"ProportionalToParent"		"1"
							"ActionSignalLevel"			"6"

							"PaintBackground"			"0"
							"PaintBorder"				"1"

							"border_default"			"NoBorder"
							"border_armed"				"BorderSelectionGray"
						}
					}
				}
				
				"buildstatus"
				{
					"ControlName"						"EditablePanel"
					"FieldName"							"buildstatus"
					"XPos"								"0"
					"YPos"								"550+30"
					"ZPos"								"20"
					"Wide"								"f7"
					"Tall"								"100"
					"Visible"							"1"
					"Enabled"							"1"
					"ProportionalToParent"				"1"

					"Damage_Title"
					{
						"ControlName"					"CExLabel"
						"FieldName"						"Damage_Title"
						"XPos"							"4"
						"YPos"							"0"
						"ZPos"							"0"
						"Wide"							"f35"
						"Tall"							"15"
						"Visible"						"1"
						"Enabled"						"1"
						"ProportionalToParent"			"1"
						"AllCaps"						"1"
						"LabelText"						"#HudCustomization_MaxiHud_Buildings"
						"Font"							"HudFontSmallBold"
						"TextAlignment"					"west"
						"FGColor"						"Gray"
					}
					"Separator"
					{
						"ControlName"					"EditablePanel"
						"FieldName"						"Separator"
						"XPos"							"2"
						"YPos"							"15"
						"ZPos"							"0"
						"Wide"							"f40"
						"Tall"							"1"
						"Visible"						"1"
						"Enabled"						"1"
						"ProportionalToParent"			"1"
						"paintBackground"				"1"
						"paintBackgroundtype"			"3"
						"BGcolor_Override"				"Background_Bright"
					}
					"8rows"
					{
						"ControlName"					"EditablePanel"
						"FieldName"						"8rows"
						"XPos"							"-2"
						"YPos"							"5"
						"ZPos"							"1"
						"Wide"							"68"
						"Tall"							"68"
						"Visible"						"1"
						"Enabled"						"1"
						"ProportionalToParent"			"1"
						"PaintBackground"				"1"
						"BGcolor_Override"				"104 101 100 255"

						"Pin_To_Sibling"				"Separator"
						"Pin_Corner_To_Sibling"			"PIN_TOPLEFT"
						"Pin_To_Sibling_Corner"			"PIN_BOTTOMLEFT"

						"Style_Image"
						{
							"ControlName"				"ImagePanel"
							"FieldName"					"Style_Image"
							"XPos"						"cs-0.5"
							"YPos"						"cs-0.5-7"
							"ZPos"						"0"
							"Wide"						"70"
							"Tall"						"70"
							"Visible"					"1"
							"Enabled"					"1"
							"MouseInputEnabled"			"0"
							"ScaleImage"				"1"
							"ProportionalToParent"		"1"
							"Image"						"replay/thumbnails/customizations/maxi/build_center"
						}
						"Style_Label"
						{
							"ControlName"				"CExLabel"
							"FieldName"					"Style_Label"
							"XPos"						"0"
							"YPos"						"rs1"
							"ZPos"						"1"
							"Wide"						"f0"
							"Tall"						"12"
							"Visible"					"1"
							"Enabled"					"1"
							"MouseInputEnabled"			"0"
							"ProportionalToParent"		"1"
							"AllCaps"					"1"
							"Font"						"fontstoreprice"
							"LabelText"					"#HudCustomization_Centered"
							"TextAlignment"				"center"
							"FGColor"					"Gray"
							"PaintBackground"			"1"
							"PaintBackgroundType"		"0"
							"BGColor_Override"			"Background_Darkest"
						}
						"Style_Button"
						{
							"ControlName"				"CExButton"
							"FieldName"					"Style_Button"
							"XPos"						"0"
							"YPos"						"0"
							"ZPos"						"5"
							"Wide"						"f0"
							"Tall"						"f0"
							"Visible"					"1"
							"Enabled"					"1"
							"Font"						""
							"Command"					"engine maxi_build_center"
							"LabelText"					""
							"Sound_Depressed"			"UI/buttonclick.wav"
							"ProportionalToParent"		"1"
							"ActionSignalLevel"			"6"

							"PaintBackground"			"0"
							"PaintBorder"				"1"

							"border_default"			"NoBorder"
							"border_armed"				"BorderSelectionGray"
						}
					}
// DAMAGE SMALL MINUSLESS -------------------------------------------------------------------------------------------
					"12rowsextended"
					{
						"ControlName"					"EditablePanel"
						"FieldName"						"12rowsextended"
						"XPos"							"5"
						"YPos"							"0"
						"ZPos"							"1"
						"Wide"							"68"
						"Tall"							"68"
						"Visible"						"1"
						"Enabled"						"1"
						"ProportionalToParent"			"1"
						"PaintBackground"				"1"
						"BGcolor_Override"				"104 101 100 255"

						"Pin_To_Sibling"				"8rows"
						"Pin_Corner_To_Sibling"			"PIN_TOPLEFT"
						"Pin_To_Sibling_Corner"			"PIN_TOPRIGHT"

						"Style_Image"
						{
							"ControlName"				"ImagePanel"
							"FieldName"					"Style_Image"
							"XPos"						"cs-0.5"
							"YPos"						"cs-0.5-2"
							"ZPos"						"0"
							"Wide"						"70"
							"Tall"						"70"
							"Visible"					"1"
							"Enabled"					"1"
							"MouseInputEnabled"			"0"
							"ScaleImage"				"1"
							"ProportionalToParent"		"1"
							"Image"						"replay/thumbnails/customizations/maxi/build_top"
						}
						"Style_Label"
						{
							"ControlName"				"CExLabel"
							"FieldName"					"Style_Label"
							"XPos"						"0"
							"YPos"						"rs1"
							"ZPos"						"1"
							"Wide"						"f0"
							"Tall"						"12"
							"Visible"					"1"
							"Enabled"					"1"
							"MouseInputEnabled"			"0"
							"ProportionalToParent"		"1"
							"AllCaps"					"1"
							"Font"						"FontStorePrice"
							"LabelText"					"#HudCustomization_MaxiHud_Buildings_TL"
							"TextAlignment"				"center"
							"FGColor"					"Gray"
							"PaintBackground"			"1"
							"PaintBackgroundType"		"0"
							"BGColor_Override"			"Background_Darkest"
						}
						"Style_Button"
						{
							"ControlName"				"CExButton"
							"FieldName"					"Style_Button"
							"XPos"						"0"
							"YPos"						"0"
							"ZPos"						"5"
							"Wide"						"f0"
							"Tall"						"f0"
							"Visible"					"1"
							"Enabled"					"1"
							"Font"						""
							"Command"					"engine maxi_build_top"
							"LabelText"					""
							"Sound_Depressed"			"UI/buttonclick.wav"
							"ProportionalToParent"		"1"
							"ActionSignalLevel"			"6"

							"PaintBackground"			"0"
							"PaintBorder"				"1"

							"border_default"			"NoBorder"
							"border_armed"				"BorderSelectionGray"
						}
					}		
						
				}		
				"vgui1"
				{
					"ControlName"						"EditablePanel"
					"FieldName"							"vgui1"
					"XPos"								"0"
					"YPos"								"650+30"
					"ZPos"								"20"
					"Wide"								"f7"
					"Tall"								"100"
					"Visible"							"1"
					"Enabled"							"1"
					"ProportionalToParent"				"1"

					"Damage_Title"
					{
						"ControlName"					"CExLabel"
						"FieldName"						"Damage_Title"
						"XPos"							"4"
						"YPos"							"0"
						"ZPos"							"0"
						"Wide"							"f35"
						"Tall"							"15"
						"Visible"						"1"
						"Enabled"						"1"
						"ProportionalToParent"			"1"
						"AllCaps"						"1"
						"LabelText"						"#HudCustomization_MaxiHud_VGUI"
						"Font"							"HudFontSmallBold"
						"TextAlignment"					"west"
						"FGColor"						"Gray"
					}
					"Restart_Warning"
					{
						"ControlName"					"CExLabel"
						"FieldName"						"Restart_Warning"
						"XPos"							"300"
						"YPos"							"-1"
						"ZPos"							"0"
						"Wide"							"20"
						"Tall"							"15"
						"Visible"						"1"
						"Enabled"						"1"
						"ProportionalToParent"			"1"
						"AllCaps"						"1"
						"LabelText"						"C"
						"Font"							"Symbols14"
						"TextAlignment"					"center"
						"FGColor"						"Red"
					}
					"Separator"
					{
						"ControlName"					"EditablePanel"
						"FieldName"						"Separator"
						"XPos"							"2"
						"YPos"							"15"
						"ZPos"							"0"
						"Wide"							"f40"
						"Tall"							"1"
						"Visible"						"1"
						"Enabled"						"1"
						"ProportionalToParent"			"1"
						"paintBackground"				"1"
						"paintBackgroundtype"			"3"
						"BGcolor_Override"				"Background_Bright"
					}
					"8rows"
					{
						"ControlName"					"EditablePanel"
						"FieldName"						"8rows"
						"XPos"							"-2"
						"YPos"							"5"
						"ZPos"							"1"
						"Wide"							"68"
						"Tall"							"68"
						"Visible"						"1"
						"Enabled"						"1"
						"ProportionalToParent"			"1"
						"PaintBackground"				"1"
						"BGcolor_Override"				"104 101 100 255"

						"Pin_To_Sibling"				"Separator"
						"Pin_Corner_To_Sibling"			"PIN_TOPLEFT"
						"Pin_To_Sibling_Corner"			"PIN_BOTTOMLEFT"

						"Style_Image"
						{
							"ControlName"				"ImagePanel"
							"FieldName"					"Style_Image"
							"XPos"						"cs-0.5"
							"YPos"						"cs-0.5-6"
							"ZPos"						"0"
							"Wide"						"70"
							"Tall"						"70"
							"Visible"					"1"
							"Enabled"					"1"
							"MouseInputEnabled"			"0"
							"ScaleImage"				"1"
							"ProportionalToParent"		"1"
							"Image"						"replay/thumbnails/customizations/maxi/ss_facelift"
						}
						"Style_Label"
						{
							"ControlName"				"CExLabel"
							"FieldName"					"Style_Label"
							"XPos"						"0"
							"YPos"						"rs1"
							"ZPos"						"1"
							"Wide"						"f0"
							"Tall"						"12"
							"Visible"					"1"
							"Enabled"					"1"
							"MouseInputEnabled"			"0"
							"ProportionalToParent"		"1"
							"AllCaps"					"1"
							"Font"						"fontstoreprice"
							"LabelText"					"#HudCustomization_MaxiHud_VGUI_Style1"
							"TextAlignment"				"center"
							"FGColor"					"Gray"
							"PaintBackground"			"1"
							"PaintBackgroundType"		"0"
							"BGColor_Override"			"Background_Darkest"
						}
						"Style_Button"
						{
							"ControlName"				"CExButton"
							"FieldName"					"Style_Button"
							"XPos"						"0"
							"YPos"						"0"
							"ZPos"						"5"
							"Wide"						"f0"
							"Tall"						"f0"
							"Visible"					"1"
							"Enabled"					"1"
							"Font"						""
							"Command"					"engine maxi_ss_vgui_face"
							"LabelText"					""
							"Sound_Depressed"			"UI/buttonclick.wav"
							"ProportionalToParent"		"1"
							"ActionSignalLevel"			"6"

							"PaintBackground"			"0"
							"PaintBorder"				"1"

							"border_default"			"NoBorder"
							"border_armed"				"BorderSelectionGray"
						}
					}
// DAMAGE SMALL MINUSLESS -------------------------------------------------------------------------------------------
					"12rowsextended"
					{
						"ControlName"					"EditablePanel"
						"FieldName"						"12rowsextended"
						"XPos"							"5"
						"YPos"							"0"
						"ZPos"							"1"
						"Wide"							"68"
						"Tall"							"68"
						"Visible"						"1"
						"Enabled"						"1"
						"ProportionalToParent"			"1"
						"PaintBackground"				"1"
						"BGcolor_Override"				"104 101 100 255"

						"Pin_To_Sibling"				"8rows"
						"Pin_Corner_To_Sibling"			"PIN_TOPLEFT"
						"Pin_To_Sibling_Corner"			"PIN_TOPRIGHT"

						"Style_Image"
						{
							"ControlName"				"ImagePanel"
							"FieldName"					"Style_Image"
							"XPos"						"cs-0.5"
							"YPos"						"cs-0.5-5"
							"ZPos"						"0"
							"Wide"						"67"
							"Tall"						"o1"
							"Visible"					"1"
							"Enabled"					"1"
							"MouseInputEnabled"			"0"
							"ScaleImage"				"1"
							"ProportionalToParent"		"1"
							"Image"						"replay/thumbnails/customizations/maxi/ss_def"
						}
						"Style_Label"
						{
							"ControlName"				"CExLabel"
							"FieldName"					"Style_Label"
							"XPos"						"0"
							"YPos"						"rs1"
							"ZPos"						"1"
							"Wide"						"f0"
							"Tall"						"12"
							"Visible"					"1"
							"Enabled"					"1"
							"MouseInputEnabled"			"0"
							"ProportionalToParent"		"1"
							"AllCaps"					"1"
							"Font"						"FontStorePrice"
							"LabelText"					"#HudCustomization_Vanilla"
							"TextAlignment"				"center"
							"FGColor"					"Gray"
							"PaintBackground"			"1"
							"PaintBackgroundType"		"0"
							"BGColor_Override"			"Background_Darkest"
						}
						"Style_Button"
						{
							"ControlName"				"CExButton"
							"FieldName"					"Style_Button"
							"XPos"						"0"
							"YPos"						"0"
							"ZPos"						"5"
							"Wide"						"f0"
							"Tall"						"f0"
							"Visible"					"1"
							"Enabled"					"1"
							"Font"						""
							"Command"					"engine maxi_ss_vgui_def"
							"LabelText"					""
							"Sound_Depressed"			"UI/buttonclick.wav"
							"ProportionalToParent"		"1"
							"ActionSignalLevel"			"6"

							"PaintBackground"			"0"
							"PaintBorder"				"1"

							"border_default"			"NoBorder"
							"border_armed"				"BorderSelectionGray"
						}
					}		
					"3thui"
					{
						"ControlName"					"EditablePanel"
						"FieldName"						"3thui"
						"XPos"							"5"
						"YPos"							"0"
						"ZPos"							"1"
						"Wide"							"68"
						"Tall"							"68"
						"Visible"						"1"
						"Enabled"						"1"
						"ProportionalToParent"			"1"
						"PaintBackground"				"1"
						"BGcolor_Override"				"104 101 100 255"

						"Pin_To_Sibling"				"12rowsextended"
						"Pin_Corner_To_Sibling"			"PIN_TOPLEFT"
						"Pin_To_Sibling_Corner"			"PIN_TOPRIGHT"

						"Style_Image"
						{
							"ControlName"				"ImagePanel"
							"FieldName"					"Style_Image"
							"XPos"						"cs-0.5"
							"YPos"						"cs-0.5-7"
							"ZPos"						"0"
							"Wide"						"70"
							"Tall"						"70"
							"Visible"					"1"
							"Enabled"					"1"
							"MouseInputEnabled"			"0"
							"ScaleImage"				"1"
							"ProportionalToParent"		"1"
							"Image"						"replay/thumbnails/customizations/maxi/ss_deftf2"
						}
						"Style_Label"
						{
							"ControlName"				"CExLabel"
							"FieldName"					"Style_Label"
							"XPos"						"0"
							"YPos"						"rs1"
							"ZPos"						"1"
							"Wide"						"f0"
							"Tall"						"12"
							"Visible"					"1"
							"Enabled"					"1"
							"MouseInputEnabled"			"0"
							"ProportionalToParent"		"1"
							"AllCaps"					"1"
							"Font"						"FontStorePriceSmall"
							"LabelText"					"#HudCustomization_MaxiHud_VGUI_Style2"
							"TextAlignment"				"center"
							"FGColor"					"Gray"
							"PaintBackground"			"1"
							"PaintBackgroundType"		"0"
							"BGColor_Override"			"Background_Darkest"
						}
						"Style_Button"
						{
							"ControlName"				"CExButton"
							"FieldName"					"Style_Button"
							"XPos"						"0"
							"YPos"						"0"
							"ZPos"						"5"
							"Wide"						"f0"
							"Tall"						"f0"
							"Visible"					"1"
							"Enabled"					"1"
							"Font"						""
							"Command"					"engine maxi_ss_vgui_deftf2"
							"LabelText"					""
							"Sound_Depressed"			"UI/buttonclick.wav"
							"ProportionalToParent"		"1"
							"ActionSignalLevel"			"6"

							"PaintBackground"			"0"
							"PaintBorder"				"1"

							"border_default"			"NoBorder"
							"border_armed"				"BorderSelectionGray"
						}
					}							
				}																										
			}
		}
	}
}