"Resource/UI/Customizations/#Customization_Menu/HUD_Customization_Health_Ammo_Uber.res"
{
	"SafeMode"
	{
		"Customizations_Panel"
		{
			"HUD_Health_Ammo_Uber_Selection"
			{
				"ControlName"							"CScrollableList"
				"FieldName"								"HUD_Health_Ammo_Uber_Selection"
				"XPos"									"cs-0.5"
				"YPos"									"cs-0.5"
				"ZPos"									"0"
				"Wide"									"f0"
				"Tall"									"f0"
				"Visible"								"0"
				"Enabled"								"1"
				"ProportionalToParent"					"1"
				"PaintBackground"						"0"
				"paintBackgroundType"					"0"
				"BGColor_Override"						"Black"

				"Scrollbar"
				{
					"XPos"								"rs1+1"
					"YPos"								"0"
					"Wide"								"6"
					"Tall"								"f0"
					"ZPos"								"1000"
					"ProportionalToParent"				"1"

					"Slider"
					{
						"PaintBackgroundType"			"0"
						"FGColor_Override"				"Gray"
					}

					"nobuttons"							"1"
				}
				"Title_Icon"
				{
					"ControlName"						"CExLabel"
					"FieldName"							"Title_Icon"
					"XPos"								"4"
					"YPos"								"1"
					"ZPos"								"0"
					"Wide"								"20"
					"Tall"								"25"
					"Visible"							"1"
					"Enabled"							"1"
					"ProportionalToParent"				"1"
					"LabelText"							"$"
					"Font"								"Symbols24"
					"TextAlignment"						"center"
					"FGColor"							"Gray"
				}
				"Title"
				{
					"ControlName"						"CExLabel"
					"FieldName"							"Title"
					"XPos"								"30"
					"YPos"								"2"
					"ZPos"								"0"
					"Wide"								"f25"
					"Tall"								"27"
					"Visible"							"1"
					"Enabled"							"1"
					"ProportionalToParent"				"1"
					"LabelText"							"#HudCustomization_jofrehud_HUDStyle"
					"Font"								"HudFontMediumbold"
					"TextAlignment"						"west"
					"FGColor"							"Gray"
				}
				"Separator_1"
				{
					"ControlName"						"EditablePanel"
					"FieldName"							"Separator_1"
					"XPos"								"3"
					"YPos"								"28"
					"ZPos"								"0"
					"Wide"								"f40"
					"Tall"								"2"
					"Visible"							"1"
					"Enabled"							"1"
					"ProportionalToParent"				"1"
					"paintBackground"					"1"
					"paintBackgroundtype"				"3"
					"BGcolor_Override"					"Background_Bright"
				}
				"General_Styles"
				{
					"ControlName"						"EditablePanel"
					"FieldName"							"General_Styles"
					"XPos"								"4"
					"YPos"								"36"
					"ZPos"								"20"
					"Wide"								"f0"
					"Tall"								"180"
					"Visible"							"1"
					"Enabled"							"1"
					"ProportionalToParent"				"1"
// NORMAL SIZE --------------------------------------------------------------------------------------
					"Style_Normal"
					{
						"ControlName"					"EditablePanel"
						"FieldName"						"Style_Normal"
						"XPos"							"0"
						"YPos"							"0"
						"ZPos"							"1"
						"Wide"							"120"
						"Tall"							"45"
						"Visible"						"1"
						"Enabled"						"1"
						"ProportionalToParent"			"1"
						"PaintBackground"				"0"

						"Style_Name"
						{
							"ControlName"				"CExLabel"
							"FieldName"					"Style_Name"
							"XPos"						"cs-0.5"
							"YPos"						"rs1"
							"ZPos"						"1"
							"Wide"						"f0"
							"Tall"						"12"
							"Visible"					"1"
							"Enabled"					"1"
							"AllCaps"					"1"
							"MouseInputEnabled"			"0"
							"ProportionalToParent"		"1"
							"Font"						"FontStoreOriginalPrice"
							"LabelText"					"Default"
							"TextAlignment"				"center"
							"FGColor"					"Gray"
							"PaintBackground"			"1"
							"PaintBackgroundType"		"0"
							"BGColor_Override"			"Background_Darkest"
						}
						"Size_Normal_Image"
						{
							"ControlName"				"ImagePanel"
							"FieldName"					"Size_Normal_Image"
							"XPos"						"cs-0.5"
							"YPos"						"-4"
							"ZPos"						"0"
							"Wide"						"88"
							"Tall"						"38"
							"Visible"					"1"
							"Enabled"					"1"
							"MouseInputEnabled"			"0"
							"ScaleImage"				"1"
							"ProportionalToParent"		"1"
							"Image"						"replay/thumbnails/hp/redteam2"
						}
						"PlayerStatusHealthValue"
						{
							"ControlName"	"Label"
							"fieldName"		"PlayerStatusHealthValue"
							"xpos"			"-15"
							"ypos"			"-5"
							"zpos"			"0"
							"wide"			"150"
							"tall"			"40"
							"visible"		"1"
							"enabled"		"1"
							"labelText"		"-125-"
							"textAlignment"	"center"	
							"font"			"HealthAndAmmo"
							"fgcolor_override"		"1 1 1 255"
						}								
						"Size_Button"
						{
							"ControlName"				"CExButton"
							"FieldName"					"Size_Button"
							"XPos"						"0"
							"YPos"						"0"
							"ZPos"						"5"
							"Wide"						"f0"
							"Tall"						"f0"
							"Visible"					"1"
							"Enabled"					"1"
							"Font"						""
							"Command"					"engine jp_hp_bg_style_clear"// jp_hp_bg_spectral
							"LabelText"					""
							"Sound_Depressed"			"UI/buttonclick.wav"
							"ProportionalToParent"		"1"
							"ActionSignalLevel"			"6"

							"PaintBackground"			"0"
							"PaintBorder"				"1"

							"border_default"			"NoBorder"
							"border_armed"				"BorderSelectionGray"
						}
					}
// SMALLER SIZE --------------------------------------------------------------------------------------
					"Style_Small"
					{
						"ControlName"					"EditablePanel"
						"FieldName"						"Style_Small"
						"XPos"							"5"
						"YPos"							"0"
						"ZPos"							"1"
						"Wide"							"120"
						"Tall"							"45"
						"Visible"						"1"
						"Enabled"						"1"
						"ProportionalToParent"			"1"
						"PaintBackground"				"0"

						"Pin_To_Sibling"				"Style_Normal"
						"Pin_Corner_To_Sibling"			"PIN_TOPLEFT"
						"Pin_To_Sibling_Corner"			"PIN_TOPRIGHT"

						"Style_Name"
						{
							"ControlName"				"CExLabel"
							"FieldName"					"Style_Name"
							"XPos"						"cs-0.5"
							"YPos"						"rs1"
							"ZPos"						"1"
							"Wide"						"f0"
							"Tall"						"12"
							"Visible"					"1"
							"Enabled"					"1"
							"AllCaps"					"1"
							"MouseInputEnabled"			"0"
							"ProportionalToParent"		"1"
							"Font"						"FontStoreOriginalPrice"
							"LabelText"					"Red Always"
							"TextAlignment"				"center"
							"FGColor"					"Gray"
							"PaintBackground"			"1"
							"PaintBackgroundType"		"0"
							"BGColor_Override"			"Background_Darkest"
						}
						"Size_Normal_Image"
						{
							"ControlName"				"ImagePanel"
							"FieldName"					"Size_Normal_Image"
							"XPos"						"cs-0.5"
							"YPos"						"-4"
							"ZPos"						"0"
							"Wide"						"88"
							"Tall"						"38"
							"Visible"					"1"
							"Enabled"					"1"
							"MouseInputEnabled"			"0"
							"ScaleImage"				"1"
							"ProportionalToParent"		"1"
							"Image"						"replay/thumbnails/hp/redteam2"
						}
						"PlayerStatusHealthValue"
						{
							"ControlName"	"Label"
							"fieldName"		"PlayerStatusHealthValue"
							"xpos"			"-15"
							"ypos"			"-5"
							"zpos"			"0"
							"wide"			"150"
							"tall"			"40"
							"visible"		"1"
							"enabled"		"1"
							"labelText"		"-125-"
							"textAlignment"	"center"	
							"font"			"HealthAndAmmo"
							"fgcolor_override"		"1 1 1 255"
						}								
						"Size_Button"
						{
							"ControlName"				"CExButton"
							"FieldName"					"Size_Button"
							"XPos"						"0"
							"YPos"						"0"
							"ZPos"						"5"
							"Wide"						"f0"
							"Tall"						"f0"
							"Visible"					"1"
							"Enabled"					"1"
							"Font"						""
							"Command"					"engine jp_hp_bg_red"
							"LabelText"					""
							"Sound_Depressed"			"UI/buttonclick.wav"
							"ProportionalToParent"		"1"
							"ActionSignalLevel"			"6"

							"PaintBackground"			"0"
							"PaintBorder"				"1"

							"border_default"			"NoBorder"
							"border_armed"				"BorderSelectionGray"
						}
					}
// MINMODE SIZE --------------------------------------------------------------------------------------
					"Style_Minmode"
					{
						"ControlName"					"EditablePanel"
						"FieldName"						"Style_Minmode"
						"XPos"							"5"
						"YPos"							"0"
						"ZPos"							"1"
						"Wide"							"120"
						"Tall"							"45"
						"Visible"						"1"
						"Enabled"						"1"
						"ProportionalToParent"			"1"
						"PaintBackground"				"0"

						"Pin_To_Sibling"				"Style_Small"
						"Pin_Corner_To_Sibling"			"PIN_TOPLEFT"
						"Pin_To_Sibling_Corner"			"PIN_TOPRIGHT"

						"Style_Name"
						{
							"ControlName"				"CExLabel"
							"FieldName"					"Style_Name"
							"XPos"						"cs-0.5"
							"YPos"						"rs1"
							"ZPos"						"1"
							"Wide"						"f0"
							"Tall"						"12"
							"Visible"					"1"
							"Enabled"					"1"
							"AllCaps"					"1"
							"MouseInputEnabled"			"0"
							"ProportionalToParent"		"1"
							"Font"						"FontStoreOriginalPrice"
							"LabelText"					"White"
							"TextAlignment"				"center"
							"FGColor"					"Gray"
							"PaintBackground"			"1"
							"PaintBackgroundType"		"0"
							"BGColor_Override"			"Background_Darkest"
						}
						"Size_Normal_Image"
						{
							"ControlName"				"ImagePanel"
							"FieldName"					"Size_Normal_Image"
							"XPos"						"cs-0.5"
							"YPos"						"-12"
							"ZPos"						"0"
							"Wide"						"88"
							"Tall"						"45"
							"Visible"					"1"
							"Enabled"					"1"
							"MouseInputEnabled"			"0"
							"ScaleImage"				"1"
							"ProportionalToParent"		"1"
							"Image"						"replay/thumbnails/hp/whiteam2"
						}
						"PlayerStatusHealthValue"
						{
							"ControlName"	"Label"
							"fieldName"		"PlayerStatusHealthValue"
							"xpos"			"-15"
							"ypos"			"-5"
							"zpos"			"0"
							"wide"			"150"
							"tall"			"40"
							"visible"		"1"
							"enabled"		"1"
							"labelText"		"-125-"
							"textAlignment"	"center"	
							"font"			"HealthAndAmmo"
							"fgcolor_override"		"1 1 1 255"
						}						
						"Size_Button"
						{
							"ControlName"				"CExButton"
							"FieldName"					"Size_Button"
							"XPos"						"0"
							"YPos"						"0"
							"ZPos"						"5"
							"Wide"						"f0"
							"Tall"						"f0"
							"Visible"					"1"
							"Enabled"					"1"
							"Font"						""
							"Command"					"engine jp_hp_bg_white"
							"LabelText"					""
							"Sound_Depressed"			"UI/buttonclick.wav"
							"ProportionalToParent"		"1"
							"ActionSignalLevel"			"6"

							"PaintBackground"			"0"
							"PaintBorder"				"1"

							"border_default"			"NoBorder"
							"border_armed"				"BorderSelectionGray"
						}
					}
// NORMAL SIZE --------------------------------------------------------------------------------------
					"Style_Normal2"
					{
						"ControlName"					"EditablePanel"
						"FieldName"						"Style_Normal2"
						"XPos"							"0"
						"YPos"							"60"
						"ZPos"							"1"
						"Wide"							"120"
						"Tall"							"45"
						"Visible"						"1"
						"Enabled"						"1"
						"ProportionalToParent"			"1"
						"PaintBackground"				"1"

						"Style_Name"
						{
							"ControlName"				"CExLabel"
							"FieldName"					"Style_Name"
							"XPos"						"cs-0.5"
							"YPos"						"rs1"
							"ZPos"						"1"
							"Wide"						"f0"
							"Tall"						"12"
							"Visible"					"1"
							"Enabled"					"1"
							"AllCaps"					"1"
							"MouseInputEnabled"			"0"
							"ProportionalToParent"		"1"
							"Font"						"FontStoreOriginalPrice"
							"LabelText"					"Ō Pigmentation"
							"TextAlignment"				"center"
							"FGColor"					"Gray"
							"PaintBackground"			"1"
							"PaintBackgroundType"		"0"
							"BGColor_Override"			"Background_Darkest"
						}
						"Size_Normal_Image"
						{
							"ControlName"				"ImagePanel"
							"FieldName"					"Size_Normal_Image"
							"XPos"						"cs-0.5"
							"YPos"						"-4"
							"ZPos"						"0"
							"Wide"						"88"
							"Tall"						"38"
							"Visible"					"1"
							"Enabled"					"1"
							"MouseInputEnabled"			"0"
							"ScaleImage"				"1"
							"ProportionalToParent"		"1"
							"Image"						"replay/thumbnails/backpacktf/pigmen_30"
						}
						"PlayerStatusHealthValue"
						{
							"ControlName"	"Label"
							"fieldName"		"PlayerStatusHealthValue"
							"xpos"			"-15"
							"ypos"			"-5"
							"zpos"			"0"
							"wide"			"150"
							"tall"			"40"
							"visible"		"1"
							"enabled"		"1"
							"labelText"		"-125-"
							"textAlignment"	"center"	
							"font"			"HealthAndAmmo"
							"fgcolor_override"		"1 1 1 255"
						}								
						"Size_Button"
						{
							"ControlName"				"CExButton"
							"FieldName"					"Size_Button"
							"XPos"						"0"
							"YPos"						"0"
							"ZPos"						"5"
							"Wide"						"f0"
							"Tall"						"f0"
							"Visible"					"1"
							"Enabled"					"1"
							"Font"						""
							"Command"					"engine jp_hp_spell_pigmen"
							"LabelText"					""
							"Sound_Depressed"			"UI/buttonclick.wav"
							"ProportionalToParent"		"1"
							"ActionSignalLevel"			"6"

							"PaintBackground"			"0"
							"PaintBorder"				"1"

							"border_default"			"NoBorder"
							"border_armed"				"BorderSelectionGray"
						}
					}
// SMALLER SIZE --------------------------------------------------------------------------------------
					"Style_Small2"
					{
						"ControlName"					"EditablePanel"
						"FieldName"						"Style_Small2"
						"XPos"							"5"
						"YPos"							"0"
						"ZPos"							"1"
						"Wide"							"120"
						"Tall"							"45"
						"Visible"						"1"
						"Enabled"						"1"
						"ProportionalToParent"			"1"
						"PaintBackground"				"0"

						"Pin_To_Sibling"				"Style_Normal2"
						"Pin_Corner_To_Sibling"			"PIN_TOPLEFT"
						"Pin_To_Sibling_Corner"			"PIN_TOPRIGHT"

						"Style_Name"
						{
							"ControlName"				"CExLabel"
							"FieldName"					"Style_Name"
							"XPos"						"cs-0.5"
							"YPos"						"rs1"
							"ZPos"						"1"
							"Wide"						"f0"
							"Tall"						"12"
							"Visible"					"1"
							"Enabled"					"1"
							"AllCaps"					"1"
							"MouseInputEnabled"			"0"
							"ProportionalToParent"		"1"
							"Font"						"FontStoreOriginalPrice"
							"LabelText"					"Ō Spectral BLU"
							"TextAlignment"				"center"
							"FGColor"					"Gray"
							"PaintBackground"			"1"
							"PaintBackgroundType"		"0"
							"BGColor_Override"			"Background_Darkest"
						}
						"Size_Normal_Image"
						{
							"ControlName"				"ImagePanel"
							"FieldName"					"Size_Normal_Image"
							"XPos"						"cs-0.5"
							"YPos"						"-4"
							"ZPos"						"0"
							"Wide"						"88"
							"Tall"						"38"
							"Visible"					"1"
							"Enabled"					"1"
							"MouseInputEnabled"			"0"
							"ScaleImage"				"1"
							"ProportionalToParent"		"1"
							"Image"						"replay/thumbnails/backpacktf/spectral_spectrum_blu_30"
						}
						"PlayerStatusHealthValue"
						{
							"ControlName"	"Label"
							"fieldName"		"PlayerStatusHealthValue"
							"xpos"			"-15"
							"ypos"			"-5"
							"zpos"			"0"
							"wide"			"150"
							"tall"			"40"
							"visible"		"1"
							"enabled"		"1"
							"labelText"		"-125-"
							"textAlignment"	"center"	
							"font"			"HealthAndAmmo"
							"fgcolor_override"		"1 1 1 255"
						}								
						"Size_Button"
						{
							"ControlName"				"CExButton"
							"FieldName"					"Size_Button"
							"XPos"						"0"
							"YPos"						"0"
							"ZPos"						"5"
							"Wide"						"f0"
							"Tall"						"f0"
							"Visible"					"1"
							"Enabled"					"1"
							"Font"						""
							"Command"					"engine jp_hp_bg_spectralblu"
							"LabelText"					""
							"Sound_Depressed"			"UI/buttonclick.wav"
							"ProportionalToParent"		"1"
							"ActionSignalLevel"			"6"

							"PaintBackground"			"0"
							"PaintBorder"				"1"

							"border_default"			"NoBorder"
							"border_armed"				"BorderSelectionGray"
						}
					}
// MINMODE SIZE --------------------------------------------------------------------------------------
					"Style_Minmode2"
					{
						"ControlName"					"EditablePanel"
						"FieldName"						"Style_Minmode2"
						"XPos"							"5"
						"YPos"							"0"
						"ZPos"							"1"
						"Wide"							"120"
						"Tall"							"45"
						"Visible"						"1"
						"Enabled"						"1"
						"ProportionalToParent"			"1"
						"PaintBackground"				"0"

						"Pin_To_Sibling"				"Style_Small2"
						"Pin_Corner_To_Sibling"			"PIN_TOPLEFT"
						"Pin_To_Sibling_Corner"			"PIN_TOPRIGHT"

						"Style_Name"
						{
							"ControlName"				"CExLabel"
							"FieldName"					"Style_Name"
							"XPos"						"cs-0.5"
							"YPos"						"rs1"
							"ZPos"						"1"
							"Wide"						"f0"
							"Tall"						"12"
							"Visible"					"1"
							"Enabled"					"1"
							"AllCaps"					"1"
							"MouseInputEnabled"			"0"
							"ProportionalToParent"		"1"
							"Font"						"FontStoreOriginalPrice"
							"LabelText"					"Ō Spectral Spectrum"
							"TextAlignment"				"center"
							"FGColor"					"Gray"
							"PaintBackground"			"1"
							"PaintBackgroundType"		"0"
							"BGColor_Override"			"Background_Darkest"
						}
						"Size_Normal_Image"
						{
							"ControlName"				"ImagePanel"
							"FieldName"					"Size_Normal_Image"
							"XPos"						"cs-0.5"
							"YPos"						"-12"
							"ZPos"						"0"
							"Wide"						"88"
							"Tall"						"45"
							"Visible"					"1"
							"Enabled"					"1"
							"MouseInputEnabled"			"0"
							"ScaleImage"				"1"
							"ProportionalToParent"		"1"
							"Image"						"replay/thumbnails/backpacktf/spectral_spectrum_30"
						}
						"PlayerStatusHealthValue"
						{
							"ControlName"	"Label"
							"fieldName"		"PlayerStatusHealthValue"
							"xpos"			"-15"
							"ypos"			"-5"
							"zpos"			"0"
							"wide"			"150"
							"tall"			"40"
							"visible"		"1"
							"enabled"		"1"
							"labelText"		"-125-"
							"textAlignment"	"center"	
							"font"			"HealthAndAmmo"
							"fgcolor_override"		"1 1 1 255"
						}						
						"Size_Button"
						{
							"ControlName"				"CExButton"
							"FieldName"					"Size_Button"
							"XPos"						"0"
							"YPos"						"0"
							"ZPos"						"5"
							"Wide"						"f0"
							"Tall"						"f0"
							"Visible"					"1"
							"Enabled"					"1"
							"Font"						""
							"Command"					"engine jp_hp_bg_spectral"
							"LabelText"					""
							"Sound_Depressed"			"UI/buttonclick.wav"
							"ProportionalToParent"		"1"
							"ActionSignalLevel"			"6"

							"PaintBackground"			"0"
							"PaintBorder"				"1"

							"border_default"			"NoBorder"
							"border_armed"				"BorderSelectionGray"
						}
					}				
					"Style_Normal3"
					{
						"ControlName"					"EditablePanel"
						"FieldName"						"Style_Normal3"
						"XPos"							"0"
						"YPos"							"120"
						"ZPos"							"1"
						"Wide"							"120"
						"Tall"							"45"
						"Visible"						"1"
						"Enabled"						"1"
						"ProportionalToParent"			"1"
						"PaintBackground"				"1"

						"Style_Name"
						{
							"ControlName"				"CExLabel"
							"FieldName"					"Style_Name"
							"XPos"						"cs-0.5"
							"YPos"						"rs1"
							"ZPos"						"1"
							"Wide"						"f0"
							"Tall"						"12"
							"Visible"					"1"
							"Enabled"					"1"
							"AllCaps"					"1"
							"MouseInputEnabled"			"0"
							"ProportionalToParent"		"1"
							"Font"						"FontStoreOriginalPrice"
							"LabelText"					"Ō Chromatic Corruption"
							"TextAlignment"				"center"
							"FGColor"					"Gray"
							"PaintBackground"			"1"
							"PaintBackgroundType"		"0"
							"BGColor_Override"			"Background_Darkest"
						}
						"Size_Normal_Image"
						{
							"ControlName"				"ImagePanel"
							"FieldName"					"Size_Normal_Image"
							"XPos"						"cs-0.5"
							"YPos"						"-4"
							"ZPos"						"0"
							"Wide"						"88"
							"Tall"						"38"
							"Visible"					"1"
							"Enabled"					"1"
							"MouseInputEnabled"			"0"
							"ScaleImage"				"1"
							"ProportionalToParent"		"1"
							"Image"						"replay/thumbnails/backpacktf/chromatic_30"
						}
						"PlayerStatusHealthValue"
						{
							"ControlName"	"Label"
							"fieldName"		"PlayerStatusHealthValue"
							"xpos"			"-15"
							"ypos"			"-5"
							"zpos"			"0"
							"wide"			"150"
							"tall"			"40"
							"visible"		"1"
							"enabled"		"1"
							"labelText"		"-125-"
							"textAlignment"	"center"	
							"font"			"HealthAndAmmo"
							"fgcolor_override"		"1 1 1 255"
						}								
						"Size_Button"
						{
							"ControlName"				"CExButton"
							"FieldName"					"Size_Button"
							"XPos"						"0"
							"YPos"						"0"
							"ZPos"						"5"
							"Wide"						"f0"
							"Tall"						"f0"
							"Visible"					"1"
							"Enabled"					"1"
							"Font"						""
							"Command"					"engine jp_hp_bg_purple"
							"LabelText"					""
							"Sound_Depressed"			"UI/buttonclick.wav"
							"ProportionalToParent"		"1"
							"ActionSignalLevel"			"6"

							"PaintBackground"			"0"
							"PaintBorder"				"1"

							"border_default"			"NoBorder"
							"border_armed"				"BorderSelectionGray"
						}
					}
// SMALLER SIZE --------------------------------------------------------------------------------------
					"Style_Small3"
					{
						"ControlName"					"EditablePanel"
						"FieldName"						"Style_Small3"
						"XPos"							"5"
						"YPos"							"0"
						"ZPos"							"1"
						"Wide"							"120"
						"Tall"							"45"
						"Visible"						"1"
						"Enabled"						"1"
						"ProportionalToParent"			"1"
						"PaintBackground"				"0"

						"Pin_To_Sibling"				"Style_Normal3"
						"Pin_Corner_To_Sibling"			"PIN_TOPLEFT"
						"Pin_To_Sibling_Corner"			"PIN_TOPRIGHT"

						"Style_Name"
						{
							"ControlName"				"CExLabel"
							"FieldName"					"Style_Name"
							"XPos"						"cs-0.5"
							"YPos"						"rs1"
							"ZPos"						"1"
							"Wide"						"f0"
							"Tall"						"12"
							"Visible"					"1"
							"Enabled"					"1"
							"AllCaps"					"1"
							"MouseInputEnabled"			"0"
							"ProportionalToParent"		"1"
							"Font"						"FontStoreOriginalPrice"
							"LabelText"					"Ō Sinister Staining"
							"TextAlignment"				"center"
							"FGColor"					"Gray"
							"PaintBackground"			"1"
							"PaintBackgroundType"		"0"
							"BGColor_Override"			"Background_Darkest"
						}
						"Size_Normal_Image"
						{
							"ControlName"				"ImagePanel"
							"FieldName"					"Size_Normal_Image"
							"XPos"						"cs-0.5"
							"YPos"						"-4"
							"ZPos"						"0"
							"Wide"						"88"
							"Tall"						"38"
							"Visible"					"1"
							"Enabled"					"1"
							"MouseInputEnabled"			"0"
							"ScaleImage"				"1"
							"ProportionalToParent"		"1"
							"Image"						"replay/thumbnails/backpacktf/sinister_30"
						}
						"PlayerStatusHealthValue"
						{
							"ControlName"	"Label"
							"fieldName"		"PlayerStatusHealthValue"
							"xpos"			"-15"
							"ypos"			"-5"
							"zpos"			"0"
							"wide"			"150"
							"tall"			"40"
							"visible"		"1"
							"enabled"		"1"
							"labelText"		"-125-"
							"textAlignment"	"center"	
							"font"			"HealthAndAmmo"
							"fgcolor_override"		"1 1 1 255"
						}								
						"Size_Button"
						{
							"ControlName"				"CExButton"
							"FieldName"					"Size_Button"
							"XPos"						"0"
							"YPos"						"0"
							"ZPos"						"5"
							"Wide"						"f0"
							"Tall"						"f0"
							"Visible"					"1"
							"Enabled"					"1"
							"Font"						""
							"Command"					"engine jp_hp_spell_sinister"
							"LabelText"					""
							"Sound_Depressed"			"UI/buttonclick.wav"
							"ProportionalToParent"		"1"
							"ActionSignalLevel"			"6"

							"PaintBackground"			"0"
							"PaintBorder"				"1"

							"border_default"			"NoBorder"
							"border_armed"				"BorderSelectionGray"
						}
					}
// MINMODE SIZE --------------------------------------------------------------------------------------
					"Style_Minmode3"
					{
						"ControlName"					"EditablePanel"
						"FieldName"						"Style_Minmode3"
						"XPos"							"5"
						"YPos"							"0"
						"ZPos"							"1"
						"Wide"							"120"
						"Tall"							"45"
						"Visible"						"1"
						"Enabled"						"1"
						"ProportionalToParent"			"1"
						"PaintBackground"				"0"

						"Pin_To_Sibling"				"Style_Small3"
						"Pin_Corner_To_Sibling"			"PIN_TOPLEFT"
						"Pin_To_Sibling_Corner"			"PIN_TOPRIGHT"

						"Style_Name"
						{
							"ControlName"				"CExLabel"
							"FieldName"					"Style_Name"
							"XPos"						"cs-0.5"
							"YPos"						"rs1"
							"ZPos"						"1"
							"Wide"						"f0"
							"Tall"						"12"
							"Visible"					"1"
							"Enabled"					"1"
							"AllCaps"					"1"
							"MouseInputEnabled"			"0"
							"ProportionalToParent"		"1"
							"Font"						"FontStoreOriginalPrice"
							"LabelText"					"Ō Die Job"
							"TextAlignment"				"center"
							"FGColor"					"Gray"
							"PaintBackground"			"1"
							"PaintBackgroundType"		"0"
							"BGColor_Override"			"Background_Darkest"
						}
						"Size_Normal_Image"
						{
							"ControlName"				"ImagePanel"
							"FieldName"					"Size_Normal_Image"
							"XPos"						"cs-0.5"
							"YPos"						"-12"
							"ZPos"						"0"
							"Wide"						"88"
							"Tall"						"45"
							"Visible"					"1"
							"Enabled"					"1"
							"MouseInputEnabled"			"0"
							"ScaleImage"				"1"
							"ProportionalToParent"		"1"
							"Image"						"replay/thumbnails/backpacktf/diejob_30"
						}
						"PlayerStatusHealthValue"
						{
							"ControlName"	"Label"
							"fieldName"		"PlayerStatusHealthValue"
							"xpos"			"-15"
							"ypos"			"-5"
							"zpos"			"0"
							"wide"			"150"
							"tall"			"40"
							"visible"		"1"
							"enabled"		"1"
							"labelText"		"-125-"
							"textAlignment"	"center"	
							"font"			"HealthAndAmmo"
							"fgcolor_override"		"1 1 1 255"
						}						
						"Size_Button"
						{
							"ControlName"				"CExButton"
							"FieldName"					"Size_Button"
							"XPos"						"0"
							"YPos"						"0"
							"ZPos"						"5"
							"Wide"						"f0"
							"Tall"						"f0"
							"Visible"					"1"
							"Enabled"					"1"
							"Font"						""
							"Command"					"engine jp_hp_spell_diejob"
							"LabelText"					""
							"Sound_Depressed"			"UI/buttonclick.wav"
							"ProportionalToParent"		"1"
							"ActionSignalLevel"			"6"

							"PaintBackground"			"0"
							"PaintBorder"				"1"

							"border_default"			"NoBorder"
							"border_armed"				"BorderSelectionGray"
						}
					}								
				}
//================================================================================================
// HEALTH
//================================================================================================
				"Health_Icon"
				{
					"ControlName"						"CExLabel"
					"FieldName"							"Health_Icon"
					"XPos"								"4"
					"YPos"								"82+120"
					"ZPos"								"0"
					"Wide"								"20"
					"Tall"								"25"
					"Visible"							"1"
					"Enabled"							"1"
					"ProportionalToParent"				"1"
					"LabelText"							"g"
					"Font"								"Symbols24"
					"TextAlignment"						"center"
					"FGColor"							"Gray"
				}
				"Health"
				{
					"ControlName"						"CExLabel"
					"FieldName"							"Health"
					"XPos"								"30"
					"YPos"								"82+120"
					"ZPos"								"0"
					"Wide"								"f25"
					"Tall"								"27"
					"Visible"							"1"
					"Enabled"							"1"
					"ProportionalToParent"				"1"
					"LabelText"							"#HudCustomization_Health"
					"Font"								"HudFontMediumbold"
					"TextAlignment"						"west"
					"FGColor"							"Gray"
				}
				"Separator_2"
				{
					"ControlName"						"EditablePanel"
					"FieldName"							"Separator_2"
					"XPos"								"3"
					"YPos"								"109+120"
					"ZPos"								"0"
					"Wide"								"f40"
					"Tall"								"2"
					"Visible"							"1"
					"Enabled"							"1"
					"ProportionalToParent"				"1"
					"paintBackground"					"1"
					"paintBackgroundtype"				"3"
					"BGcolor_Override"					"Background_Bright"
				}
				"Health_Options"
				{
					"ControlName"						"EditablePanel"
					"FieldName"							"Health_Options"
					"XPos"								"3"
					"YPos"								"117+120"
					"ZPos"								"20"
					"Wide"								"f0"
					"Tall"								"300"
					"Visible"							"1"
					"Enabled"							"1"
					"ProportionalToParent"				"1"

//=================================================================================
// HEALTH WARNING LEVEL
//=================================================================================
					"Health_Warning"
					{
						"ControlName"					"CExLabel"
						"FieldName"						"Health_Warning"
						"XPos"							"0"
						"YPos"							"2"
						"ZPos"							"0"
						"Wide"							"160"
						"Tall"							"15"
						"Visible"						"1"
						"Enabled"						"1"
						"ProportionalToParent"			"1"
						"AllCaps"						"1"
						"LabelText"						"Health Font"
						"Font"							"HudFontSmallBold"
						"TextAlignment"					"west"
						"FGColor"						"Gray"
					}
					"Separator_2"
					{
						"ControlName"					"EditablePanel"
						"FieldName"						"Separator_2"
						"XPos"							"2"
						"YPos"							"1"
						"ZPos"							"0"
						"Wide"							"160"
						"Tall"							"1"
						"Visible"						"1"
						"Enabled"						"1"
						"ProportionalToParent"			"1"
						"paintBackground"				"1"
						"paintBackgroundtype"			"3"
						"BGcolor_Override"				"Background_Bright"

						"Pin_To_Sibling"				"Health_Warning"
						"Pin_Corner_To_Sibling"			"PIN_TOPLEFT"
						"Pin_To_Sibling_Corner"			"PIN_BOTTOMLEFT"
					}
// WARNING 50% ---------------------------------------------------------------------------------
					"Warning_50"
					{
						"ControlName"					"EditablePanel"
						"FieldName"						"Warning_50"
						"XPos"							"-2"
						"YPos"							"5"
						"ZPos"							"1"
						"Wide"							"90"
						"Tall"							"44"
						"Visible"						"1"
						"Enabled"						"1"
						"ProportionalToParent"			"1"
						"PaintBackground"				"1"
						"BGcolor_Override"				"104 101 100 255"

						"Pin_To_Sibling"				"Separator_2"
						"Pin_Corner_To_Sibling"			"PIN_TOPLEFT"
						"Pin_To_Sibling_Corner"			"PIN_BOTTOMLEFT"

						"Style_Image"
						{
							"ControlName"				"ImagePanel"
							"FieldName"					"Style_Image"
							"XPos"						"cs-0.5-5"
							"YPos"						"cs-0.5-7"
							"ZPos"						"0"
							"Wide"						"54"
							"Tall"						"44"
							"Visible"					"1"
							"Enabled"					"1"
							"MouseInputEnabled"			"0"
							"ScaleImage"				"1"
							"ProportionalToParent"		"1"
							"Image"						"replay/thumbnails/hp/whiteam2"
						}
						"Health_Warning_Label2"
						{
							"ControlName"	"Label"
							"fieldName"		"Health_Warning_Label2"
							"xpos"			"-29"
							"ypos"			"-5"
							"zpos"			"0"
							"wide"			"150"
							"tall"			"40"
							"visible"		"1"
							"enabled"		"1"
							"labelText"		"-125-"
							"textAlignment"	"center"	
							"font"			"HealthAndAmmo"
							"fgcolor_override"		"1 1 1 255"
						}						
						"Health_Warning_Label"
						{
							"ControlName"				"CExLabel"
							"FieldName"					"Health_Warning_Label"
							"XPos"						"0"
							"YPos"						"rs1"
							"ZPos"						"1"
							"Wide"						"f0"
							"Tall"						"12"
							"Visible"					"1"
							"Enabled"					"1"
							"MouseInputEnabled"			"0"
							"ProportionalToParent"		"1"
							"AllCaps"					"1"
							"Font"						"FontStoreOriginalPrice"
							"LabelText"					"Bold"
							"TextAlignment"				"center"
							"FGColor"					"Gray"
							"PaintBackground"			"1"
							"PaintBackgroundType"		"0"
							"BGColor_Override"			"Background_Darkest"
						}
						"Health_Warning_Button"
						{
							"ControlName"				"CExButton"
							"FieldName"					"Health_Warning_Button"
							"XPos"						"0"
							"YPos"						"0"
							"ZPos"						"5"
							"Wide"						"f0"
							"Tall"						"f0"
							"Visible"					"1"
							"Enabled"					"1"
							"Font"						""
							"Command"					"engine m0_health_warning_clear"
							"LabelText"					""
							"Sound_Depressed"			"UI/buttonclick.wav"
							"ProportionalToParent"		"1"
							"ActionSignalLevel"			"6"

							"PaintBackground"			"0"
							"PaintBorder"				"1"

							"border_default"			"NoBorder"
							"border_armed"				"BorderSelectionGray"
						}
					}
// WARNING 75% ---------------------------------------------------------------------------------
					"Warning_75"
					{
						"ControlName"					"EditablePanel"
						"FieldName"						"Warning_75"
						"XPos"							"5"
						"YPos"							"0"
						"ZPos"							"1"
						"Wide"							"90"
						"Tall"							"44"
						"Visible"						"1"
						"Enabled"						"1"
						"ProportionalToParent"			"1"
						"PaintBackground"				"1"
						"BGcolor_Override"				"104 101 100 255"

						"Pin_To_Sibling"				"Warning_50"
						"Pin_Corner_To_Sibling"			"PIN_TOPLEFT"
						"Pin_To_Sibling_Corner"			"PIN_TOPRIGHT"

						"Style_Image"
						{
							"ControlName"				"ImagePanel"
							"FieldName"					"Style_Image"
							"XPos"						"cs-0.5-5"
							"YPos"						"cs-0.5-7"
							"ZPos"						"0"
							"Wide"						"54"
							"Tall"						"54"
							"Visible"					"1"
							"Enabled"					"1"
							"MouseInputEnabled"			"0"
							"ScaleImage"				"1"
							"ProportionalToParent"		"1"
							"Image"						"replay/thumbnails/hp/whiteam"
						}
						"Health_Warning_Label"
						{
							"ControlName"				"CExLabel"
							"FieldName"					"Health_Warning_Label"
							"XPos"						"0"
							"YPos"						"rs1"
							"ZPos"						"1"
							"Wide"						"f0"
							"Tall"						"12"
							"Visible"					"1"
							"Enabled"					"1"
							"MouseInputEnabled"			"0"
							"ProportionalToParent"		"1"
							"AllCaps"					"1"
							"Font"						"FontStoreOriginalPrice"
							"LabelText"					"Thin"
							"TextAlignment"				"center"
							"FGColor"					"Gray"
							"PaintBackground"			"1"
							"PaintBackgroundType"		"0"
							"BGColor_Override"			"Background_Darkest"
						}
						"Health_Warning_Label2"
						{
							"ControlName"	"Label"
							"fieldName"		"Health_Warning_Label2"
							"xpos"			"-30"
							"ypos"			"-5"
							"zpos"			"0"
							"wide"			"150"
							"tall"			"40"
							"visible"		"1"
							"enabled"		"1"
							"labelText"		"-125-"
							"textAlignment"	"center"	
							"font"			"HealthAndAmmoThin"
							"fgcolor_override"		"1 1 1 255"
						}													
						"Health_Warning_Button"
						{
							"ControlName"				"CExButton"
							"FieldName"					"Health_Warning_Button"
							"XPos"						"0"
							"YPos"						"0"
							"ZPos"						"5"
							"Wide"						"f0"
							"Tall"						"f0"
							"Visible"					"1"
							"Enabled"					"1"
							"Font"						""
							"Command"					"engine jp_hp_font_thin"
							"LabelText"					""
							"Sound_Depressed"			"UI/buttonclick.wav" 
							"ProportionalToParent"		"1"
							"ActionSignalLevel"			"6"

							"PaintBackground"			"0"
							"PaintBorder"				"1"

							"border_default"			"NoBorder"
							"border_armed"				"BorderSelectionGray"
						}
					}		
					"Warning_3"
					{
						"ControlName"					"EditablePanel"
						"FieldName"						"Warning_3"
						"XPos"							"5"
						"YPos"							"0"
						"ZPos"							"1"
						"Wide"							"90"
						"Tall"							"44"
						"Visible"						"1"
						"Enabled"						"1"
						"ProportionalToParent"			"1"
						"PaintBackground"				"1"
						"BGcolor_Override"				"104 101 100 255"

						"Pin_To_Sibling"				"Warning_75"
						"Pin_Corner_To_Sibling"			"PIN_TOPLEFT"
						"Pin_To_Sibling_Corner"			"PIN_TOPRIGHT"

						"Style_Image"
						{
							"ControlName"				"ImagePanel"
							"FieldName"					"Style_Image"
							"XPos"						"cs-0.5-5"
							"YPos"						"cs-0.5-7"
							"ZPos"						"0"
							"Wide"						"54"
							"Tall"						"54"
							"Visible"					"1"
							"Enabled"					"1"
							"MouseInputEnabled"			"0"
							"ScaleImage"				"1"
							"ProportionalToParent"		"1"
							"Image"						"replay/thumbnails/hp/whiteam"
						}
						"Health_Warning_Label"
						{
							"ControlName"				"CExLabel"
							"FieldName"					"Health_Warning_Label"
							"XPos"						"0"
							"YPos"						"rs1"
							"ZPos"						"1"
							"Wide"						"f0"
							"Tall"						"12"
							"Visible"					"1"
							"Enabled"					"1"
							"MouseInputEnabled"			"0"
							"ProportionalToParent"		"1"
							"AllCaps"					"1"
							"Font"						"FontStoreOriginalPrice"
							"LabelText"					"Outline"
							"TextAlignment"				"center"
							"FGColor"					"Gray"
							"PaintBackground"			"1"
							"PaintBackgroundType"		"0"
							"BGColor_Override"			"Background_Darkest"
						}
						"Health_Warning_Label2"
						{
							"ControlName"	"Label"
							"fieldName"		"Health_Warning_Label2"
							"xpos"			"-32"
							"ypos"			"-5"
							"zpos"			"0"
							"wide"			"150"
							"tall"			"40"
							"visible"		"1"
							"enabled"		"1"
							"labelText"		"-125-"
							"textAlignment"	"center"	
							"font"			"HealthAndAmmoOutline"
							"fgcolor_override"		"1 1 1 255"
						}													
						"Health_Warning_Button"
						{
							"ControlName"				"CExButton"
							"FieldName"					"Health_Warning_Button"
							"XPos"						"0"
							"YPos"						"0"
							"ZPos"						"5"
							"Wide"						"f0"
							"Tall"						"f0"
							"Visible"					"1"
							"Enabled"					"1"
							"Font"						""
							"Command"					"engine jp_hp_font_outline"
							"LabelText"					""
							"Sound_Depressed"			"UI/buttonclick.wav"
							"ProportionalToParent"		"1"
							"ActionSignalLevel"			"6"

							"PaintBackground"			"0"
							"PaintBorder"				"1"

							"border_default"			"NoBorder"
							"border_armed"				"BorderSelectionGray"
						}
					}								
				}

//================================================================================================
// TARGETIDS
//================================================================================================
				"Target_Icon"
				{
					"ControlName"						"CExLabel"
					"FieldName"							"Target_Icon"
					"XPos"								"4"
					"YPos"								"295+20"
					"ZPos"								"0"
					"Wide"								"20"
					"Tall"								"25"
					"Visible"							"1"
					"Enabled"							"1"
					"ProportionalToParent"				"1"
					"LabelText"							"."
					"Font"								"Symbols24"
					"TextAlignment"						"center"
					"FGColor"							"Gray"
				}
				"Target"
				{
					"ControlName"						"CExLabel"
					"FieldName"							"Target"
					"XPos"								"30"
					"YPos"								"295+20"
					"ZPos"								"0"
					"Wide"								"f25"
					"Tall"								"27"
					"Visible"							"1"
					"Enabled"							"1"
					"ProportionalToParent"				"1"
					"LabelText"							"#HudCustomization_Health_TargetID"
					"Font"								"HudFontMediumbold"
					"TextAlignment"						"west"
					"FGColor"							"Gray"
				}
				"Separator_5"
				{
					"ControlName"						"EditablePanel"
					"FieldName"							"Separator_5"
					"XPos"								"3"
					"YPos"								"320+20"
					"ZPos"								"0"
					"Wide"								"f40"
					"Tall"								"2"
					"Visible"							"1"
					"Enabled"							"1"
					"ProportionalToParent"				"1"
					"paintBackground"					"1"
					"paintBackgroundtype"				"3"
					"BGcolor_Override"					"Background_Bright"
				}
				"Target_Options"
				{
					"ControlName"						"EditablePanel"
					"FieldName"							"Target_Options"
					"XPos"								"3"
					"YPos"								"330+20"
					"ZPos"								"4000"
					"Wide"								"f0"
					"Tall"								"210"
					"Visible"							"1"
					"Enabled"							"1"
					"ProportionalToParent"				"1"
// TARGET CVARS ------------------------------------------------------------------------------------------------------------
					"Target_CVARS"
					{
						"ControlName"					"CExLabel"
						"FieldName"						"Target_CVARS"
						"XPos"							"5"
						"YPos"							"0"
						"ZPos"							"0"
						"Wide"							"360"
						"Tall"							"15"
						"Visible"						"1"
						"Enabled"						"1"
						"ProportionalToParent"			"1"
						"AllCaps"						"1"
						"LabelText"						"#HudCustomization_Health_TargetID_Settings"
						"Font"							"HudFontSmallBold"
						"TextAlignment"					"west"
						"FGColor"						"Gray"

						"Pin_To_Sibling"				"Target_Health_Style"
						"Pin_Corner_To_Sibling"			"PIN_TOPLEFT"
						"Pin_To_Sibling_Corner"			"PIN_TOPRIGHT"
					}
					"Separator_5"
					{
						"ControlName"					"EditablePanel"
						"FieldName"						"Separator_5"
						"XPos"							"2"
						"YPos"							"1"
						"ZPos"							"0"
						"Wide"							"260"
						"Tall"							"1"
						"Visible"						"1"
						"Enabled"						"1"
						"ProportionalToParent"			"1"
						"paintBackground"				"1"
						"paintBackgroundtype"			"3"
						"BGcolor_Override"				"Background_Bright"

						"Pin_To_Sibling"				"Target_CVARS"
						"Pin_Corner_To_Sibling"			"PIN_TOPLEFT"
						"Pin_To_Sibling_Corner"			"PIN_BOTTOMLEFT"
					}
					"Floating_Toggle_Button"
					{
						"ControlName"					"CExButton"
						"FieldName"						"Floating_Toggle_Button"
						"XPos"							"-2"
						"YPos"							"5"
						"ZPos"							"20"
						"Wide"							"160"
						"Tall"							"22"
						"Visible"						"1"
						"Enabled"						"1"
						"ActionSignalLevel"				"5"
						"ProportionalToParent"			"1"
						"LabelText"						""
						"TextAlignment"					"west"
						"Command"						"engine toggle tf_hud_target_id_disable_floating_health"
						"Sound_Depressed"				"UI/buttonclick.wav"
						"PaintBackground"				"1"
						"PaintBorder"					"0"

						"border_default"				"NoBorder"
						"border_armed"					"BorderSelectionWhite"

						"DefaultBGColor_Override"		"Blank"
						"ArmedBGColor_Override"			"Button_Hover"
						"DepressedBGColor_Override"		"Button_Hover"

						"Pin_To_Sibling"				"Separator_5"
						"Pin_Corner_To_Sibling"			"PIN_TOPLEFT"
						"Pin_To_Sibling_Corner"			"PIN_BOTTOMLEFT"
					}
					"Floating_Checkbox"
					{
						"ControlName"					"CvarToggleCheckButton"
						"FieldName"						"Floating_Checkbox"
						"XPos"							"2"
						"YPos"							"0"
						"ZPos"							"21"
						"Wide"							"22"
						"Tall"							"22"
						"Visible"						"1"
						"Enabled"						"1"
						"ProportionalToParent"			"1"
						"LabelText"						""
						"SmallCheckImage"				"0"
						"button_activation_type"		"1"
						"cvar_name"						"tf_hud_target_id_disable_floating_health"
						"MouseInputEnabled"				"0"

						"Pin_To_Sibling"				"Floating_Toggle_Button"
						"Pin_Corner_To_Sibling"			"PIN_CENTER_LEFT"
						"Pin_To_Sibling_Corner"			"PIN_CENTER_LEFT"
					}
					"Floating_Label"
					{
						"ControlName"					"CExLabel"
						"FieldName"						"Floating_Label"
						"XPos"							"-25"
						"YPos"							"0"
						"ZPos"							"21"
						"Wide"							"260"
						"Tall"							"12"
						"Visible"						"1"
						"Enabled"						"1"
						"MouseInputEnabled"				"0"
						"ProportionalToParent"			"1"
						"AllCaps"						"1"
						"Font"							"FontStoreOriginalPrice"
						"LabelText"						"#HudCustomization_Health_Numbers"
						"TextAlignment"					"west"
						"FGColor"						"White"

						"Pin_To_Sibling"				"Floating_Toggle_Button"
						"Pin_Corner_To_Sibling"			"PIN_CENTER_LEFT"
						"Pin_To_Sibling_Corner"			"PIN_CENTER_LEFT"
					}
					"Separator_6"
					{
						"ControlName"					"EditablePanel"
						"FieldName"						"Separator_6"
						"XPos"							"0"
						"YPos"							"32"
						"ZPos"							"0"
						"Wide"							"260"
						"Tall"							"1"
						"Visible"						"1"
						"Enabled"						"1"
						"ProportionalToParent"			"1"
						"paintBackground"				"1"
						"paintBackgroundtype"			"3"
						"BGcolor_Override"				"Background_Bright"

						"Pin_To_Sibling"				"Separator_5"
						"Pin_Corner_To_Sibling"			"PIN_TOPLEFT"
						"Pin_To_Sibling_Corner"			"PIN_BOTTOMLEFT"
					}
					"Location_Label"
					{
						"ControlName"					"CExLabel"
						"FieldName"						"Location_Label"
						"XPos"							"-2"
						"YPos"							"5"
						"ZPos"							"21"
						"Wide"							"150"
						"Tall"							"12"
						"Visible"						"1"
						"Enabled"						"1"
						"MouseInputEnabled"				"0"
						"ProportionalToParent"			"1"
						"AllCaps"						"1"
						"Font"							"HudFontSmallest"
						"LabelText"						"#HudCustomization_Health_TargetID_Spec"
						"TextAlignment"					"west"
						"FGColor"						"Gray"

						"Pin_To_Sibling"				"Separator_6"
						"Pin_Corner_To_Sibling"			"PIN_TOPLEFT"
						"Pin_To_Sibling_Corner"			"PIN_BOTTOMLEFT"
					}
					"Location_Default_Button"
					{
						"ControlName"					"CExButton"
						"FieldName"						"Location_Default_Button"
						"XPos"							"-2"
						"YPos"							"20"
						"ZPos"							"20"
						"Wide"							"90"
						"Tall"							"15"
						"Visible"						"1"
						"Enabled"						"1"
						"ActionSignalLevel"				"5"
						"ProportionalToParent"			"1"
						"AllCaps"						"1"
						"Font"							"HudFontSmallestBold"
						"LabelText"						"#HudCustomization_Default"
						"TextAlignment"					"center"
						"Command"						"engine tf_spectator_target_location 0"
						"Sound_Depressed"				"UI/buttonclick.wav"
						"PaintBackground"				"1"

						"Pin_To_Sibling"				"Separator_6"
						"Pin_Corner_To_Sibling"			"PIN_TOPLEFT"
						"Pin_To_Sibling_Corner"			"PIN_BOTTOMLEFT"
					}
					"Location_BottomCenter_Button"
					{
						"ControlName"					"CExButton"
						"FieldName"						"Location_BottomCenter_Button"
						"XPos"							"3"
						"YPos"							"0"
						"ZPos"							"20"
						"Wide"							"90"
						"Tall"							"15"
						"Visible"						"1"
						"Enabled"						"1"
						"ActionSignalLevel"				"5"
						"ProportionalToParent"			"1"
						"AllCaps"						"1"
						"Font"							"HudFontSmallestBold"
						"LabelText"						"#HudCustomization_Health_TID_Setting1"
						"TextAlignment"					"center"
						"Command"						"engine tf_spectator_target_location 2"
						"Sound_Depressed"				"UI/buttonclick.wav"
						"PaintBackground"				"1"

						"Pin_To_Sibling"				"Location_Default_Button"
						"Pin_Corner_To_Sibling"			"PIN_TOPLEFT"
						"Pin_To_Sibling_Corner"			"PIN_TOPRIGHT"
					}
					"Location_BottomLeft_Button"
					{
						"ControlName"					"CExButton"
						"FieldName"						"Location_BottomLeft_Button"
						"XPos"							"0"
						"YPos"							"3"
						"ZPos"							"20"
						"Wide"							"90"
						"Tall"							"15"
						"Visible"						"1"
						"Enabled"						"1"
						"ActionSignalLevel"				"5"
						"ProportionalToParent"			"1"
						"AllCaps"						"1"
						"Font"							"HudFontSmallestBold"
						"LabelText"						"#HudCustomization_Health_Style1"
						"TextAlignment"					"center"
						"Command"						"engine tf_spectator_target_location 1"
						"Sound_Depressed"				"UI/buttonclick.wav"
						"PaintBackground"				"1"

						"Pin_To_Sibling"				"Location_Default_Button"
						"Pin_Corner_To_Sibling"			"PIN_TOPLEFT"
						"Pin_To_Sibling_Corner"			"PIN_BOTTOMLEFT"
					}
					"Location_BottomRight_Button"
					{
						"ControlName"					"CExButton"
						"FieldName"						"Location_BottomRight_Button"
						"XPos"							"3"
						"YPos"							"0"
						"ZPos"							"20"
						"Wide"							"90"
						"Tall"							"15"
						"Visible"						"1"
						"Enabled"						"1"
						"ActionSignalLevel"				"5"
						"ProportionalToParent"			"1"
						"AllCaps"						"1"
						"Font"							"HudFontSmallestBold"
						"LabelText"						"#HudCustomization_Health_TID_Setting2"
						"TextAlignment"					"center"
						"Command"						"engine tf_spectator_target_location 3"
						"Sound_Depressed"				"UI/buttonclick.wav"
						"PaintBackground"				"1"

						"Pin_To_Sibling"				"Location_BottomLeft_Button"
						"Pin_Corner_To_Sibling"			"PIN_TOPLEFT"
						"Pin_To_Sibling_Corner"			"PIN_TOPRIGHT"
					}
					"Separator_7"
					{
						"ControlName"					"EditablePanel"
						"FieldName"						"Separator_7"
						"XPos"							"0"
						"YPos"							"60"
						"ZPos"							"0"
						"Wide"							"260"
						"Tall"							"1"
						"Visible"						"1"
						"Enabled"						"1"
						"ProportionalToParent"			"1"
						"paintBackground"				"1"
						"paintBackgroundtype"			"3"
						"BGcolor_Override"				"Background_Bright"

						"Pin_To_Sibling"				"Separator_6"
						"Pin_Corner_To_Sibling"			"PIN_TOPLEFT"
						"Pin_To_Sibling_Corner"			"PIN_BOTTOMLEFT"
					}
					"Setting_Label"
					{
						"ControlName"					"CExLabel"
						"FieldName"						"Setting_Label"
						"XPos"							"-2"
						"YPos"							"5"
						"ZPos"							"1"
						"Wide"							"160"
						"Tall"							"12"
						"Visible"						"1"
						"Enabled"						"1"
						"MouseInputEnabled"				"0"
						"ProportionalToParent"			"1"
						"AllCaps"						"1"
						"Font"							"HudFontSmallest"
						"LabelText"						"#HudCustomization_Health_TeamBar"
						"TextAlignment"					"west"
						"FGColor"						"Gray"

						"Pin_To_Sibling"				"Separator_7"
						"Pin_Corner_To_Sibling"			"PIN_TOPLEFT"
						"Pin_To_Sibling_Corner"			"PIN_BOTTOMLEFT"
					}
					"Setting_Slider"
					{
						"ControlName"					"CCvarSlider"
						"FieldName"						"Setting_Slider"
						"XPos"							"-5"
						"YPos"							"2"
						"ZPos"							"2"
						"Wide"							"160"
						"Tall"							"30"
						"Visible"						"1"
						"Enabled"						"1"
						"ProportionalToParent"			"1"
						"minvalue"						"0"
						"maxvalue"						"255"
						"cvar_name"						"tf_hud_target_id_alpha"

						"Pin_To_Sibling"				"Setting_Label"
						"Pin_Corner_To_Sibling"			"PIN_TOPLEFT"
						"Pin_To_Sibling_Corner"			"PIN_BOTTOMLEFT"
					}
				}
















































				"Health_Icon2"
				{
					"ControlName"						"CExLabel"
					"FieldName"							"Health_Icon2"
					"XPos"								"4"
					"YPos"								"82+120+300"
					"ZPos"								"0"
					"Wide"								"20"
					"Tall"								"25"
					"Visible"							"1"
					"Enabled"							"1"
					"ProportionalToParent"				"1"
					"LabelText"							"g"
					"Font"								"Symbols24"
					"TextAlignment"						"center"
					"FGColor"							"Gray"
				}
				"Health2"
				{
					"ControlName"						"CExLabel"
					"FieldName"							"Health2"
					"XPos"								"30"
					"YPos"								"82+120+300"
					"ZPos"								"0"
					"Wide"								"f25"
					"Tall"								"27"
					"Visible"							"1"
					"Enabled"							"1"
					"ProportionalToParent"				"1"
					"LabelText"							"Circle Frame"
					"Font"								"HudFontMediumbold"
					"TextAlignment"						"west"
					"FGColor"							"Gray"
				}
				"Separator_22"
				{
					"ControlName"						"EditablePanel"
					"FieldName"							"Separator_22"
					"XPos"								"3"
					"YPos"								"109+120+300"
					"ZPos"								"0"
					"Wide"								"f40"
					"Tall"								"2"
					"Visible"							"1"
					"Enabled"							"1"
					"ProportionalToParent"				"1"
					"paintBackground"					"1"
					"paintBackgroundtype"				"3"
					"BGcolor_Override"					"Background_Bright"
				}
				"Health_Options2"
				{
					"ControlName"						"EditablePanel"
					"FieldName"							"Health_Options2"
					"XPos"								"3"
					"YPos"								"117+120+300"
					"ZPos"								"22"
					"Wide"								"f0"
					"Tall"								"300"
					"Visible"							"1"
					"Enabled"							"1"
					"ProportionalToParent"				"1"

//=================================================================================
// HEALTH WARNING LEVEL
//=================================================================================
					"Health_Warning"
					{
						"ControlName"					"CExLabel"
						"FieldName"						"Health_Warning"
						"XPos"							"0"
						"YPos"							"2"
						"ZPos"							"0"
						"Wide"							"160"
						"Tall"							"15"
						"Visible"						"1"
						"Enabled"						"1"
						"ProportionalToParent"			"1"
						"AllCaps"						"1"
						"LabelText"						"From MagnumHud"
						"Font"							"HudFontSmallBold"
						"TextAlignment"					"west"
						"FGColor"						"Gray"
					}
					"Separator_2"
					{
						"ControlName"					"EditablePanel"
						"FieldName"						"Separator_2"
						"XPos"							"2"
						"YPos"							"1"
						"ZPos"							"0"
						"Wide"							"160"
						"Tall"							"1"
						"Visible"						"1"
						"Enabled"						"1"
						"ProportionalToParent"			"1"
						"paintBackground"				"1"
						"paintBackgroundtype"			"3"
						"BGcolor_Override"				"Background_Bright"

						"Pin_To_Sibling"				"Health_Warning"
						"Pin_Corner_To_Sibling"			"PIN_TOPLEFT"
						"Pin_To_Sibling_Corner"			"PIN_BOTTOMLEFT"
					}
// WARNING 50% ---------------------------------------------------------------------------------
					"Warning_50"
					{
						"ControlName"					"EditablePanel"
						"FieldName"						"Warning_50"
						"XPos"							"-2"
						"YPos"							"5"
						"ZPos"							"1"
						"Wide"							"90"
						"Tall"							"44"
						"Visible"						"1"
						"Enabled"						"1"
						"ProportionalToParent"			"1"
						"PaintBackground"				"1"
						"BGcolor_Override"				"104 101 100 255"

						"Pin_To_Sibling"				"Separator_2"
						"Pin_Corner_To_Sibling"			"PIN_TOPLEFT"
						"Pin_To_Sibling_Corner"			"PIN_BOTTOMLEFT"

						"Style_Image"
						{
							"ControlName"				"ImagePanel"
							"FieldName"					"Style_Image"
							"XPos"						"cs-0.5-5"
							"YPos"						"cs-0.5-7"
							"ZPos"						"0"
							"Wide"						"54"
							"Tall"						"44"
							"Visible"					"1"
							"Enabled"					"1"
							"MouseInputEnabled"			"0"
							"ScaleImage"				"1"
							"ProportionalToParent"		"1"
							"Image"						"replay/thumbnails/hp/whiteam2"
						}
						"Health_Warning_Label2"
						{
							"ControlName"	"Label"
							"fieldName"		"Health_Warning_Label2"
							"xpos"			"-29"
							"ypos"			"-5"
							"zpos"			"0"
							"wide"			"150"
							"tall"			"40"
							"visible"		"1"
							"enabled"		"1"
							"labelText"		"-125-"
							"textAlignment"	"center"	
							"font"			"HealthAndAmmo"
							"fgcolor_override"		"1 1 1 255"
						}						
						"Health_Warning_Label"
						{
							"ControlName"				"CExLabel"
							"FieldName"					"Health_Warning_Label"
							"XPos"						"0"
							"YPos"						"rs1"
							"ZPos"						"1"
							"Wide"						"f0"
							"Tall"						"12"
							"Visible"					"1"
							"Enabled"					"1"
							"MouseInputEnabled"			"0"
							"ProportionalToParent"		"1"
							"AllCaps"					"1"
							"Font"						"FontStoreOriginalPrice"
							"LabelText"					"None"
							"TextAlignment"				"center"
							"FGColor"					"Gray"
							"PaintBackground"			"1"
							"PaintBackgroundType"		"0"
							"BGColor_Override"			"Background_Darkest"
						}
						"Health_Warning_Button"
						{
							"ControlName"				"CExButton"
							"FieldName"					"Health_Warning_Button"
							"XPos"						"0"
							"YPos"						"0"
							"ZPos"						"5"
							"Wide"						"f0"
							"Tall"						"f0"
							"Visible"					"1"
							"Enabled"					"1"
							"Font"						""
							"Command"					"engine jp_hp_frame_clear"
							"LabelText"					""
							"Sound_Depressed"			"UI/buttonclick.wav"
							"ProportionalToParent"		"1"
							"ActionSignalLevel"			"6"

							"PaintBackground"			"0"
							"PaintBorder"				"1"

							"border_default"			"NoBorder"
							"border_armed"				"BorderSelectionGray"
						}
					}
// WARNING 75% ---------------------------------------------------------------------------------
					"Warning_75"
					{
						"ControlName"					"EditablePanel"
						"FieldName"						"Warning_75"
						"XPos"							"5"
						"YPos"							"0"
						"ZPos"							"1"
						"Wide"							"90"
						"Tall"							"44"
						"Visible"						"1"
						"Enabled"						"1"
						"ProportionalToParent"			"1"
						"PaintBackground"				"1"
						"BGcolor_Override"				"104 101 100 255"

						"Pin_To_Sibling"				"Warning_50"
						"Pin_Corner_To_Sibling"			"PIN_TOPLEFT"
						"Pin_To_Sibling_Corner"			"PIN_TOPRIGHT"

						"Style_Image"
						{
							"ControlName"				"ImagePanel"
							"FieldName"					"Style_Image"
							"XPos"						"cs-0.5-5"
							"YPos"						"cs-0.5-7"
							"ZPos"						"0"
							"Wide"						"54"
							"Tall"						"54"
							"Visible"					"1"
							"Enabled"					"1"
							"MouseInputEnabled"			"0"
							"ScaleImage"				"1"
							"ProportionalToParent"		"1"
							"Image"						"replay\thumbnails\hp\REFRACTcircle"
						}
						"Health_Warning_Label"
						{
							"ControlName"				"CExLabel"
							"FieldName"					"Health_Warning_Label"
							"XPos"						"0"
							"YPos"						"rs1"
							"ZPos"						"1"
							"Wide"						"f0"
							"Tall"						"12"
							"Visible"					"1"
							"Enabled"					"1"
							"MouseInputEnabled"			"0"
							"ProportionalToParent"		"1"
							"AllCaps"					"1"
							"Font"						"FontStoreOriginalPrice"
							"LabelText"					"Circle"
							"TextAlignment"				"center"
							"FGColor"					"Gray"
							"PaintBackground"			"1"
							"PaintBackgroundType"		"0"
							"BGColor_Override"			"Background_Darkest"
						}
						"Health_Warning_Label2"
						{
							"ControlName"	"Label"
							"fieldName"		"Health_Warning_Label2"
							"xpos"			"-30"
							"ypos"			"-5"
							"zpos"			"0"
							"wide"			"150"
							"tall"			"40"
							"visible"		"1"
							"enabled"		"1"
							"labelText"		"-125-"
							"textAlignment"	"center"	
							"font"			"HealthAndAmmo"
							"fgcolor_override"		"1 1 1 255"
						}													
						"Health_Warning_Button"
						{
							"ControlName"				"CExButton"
							"FieldName"					"Health_Warning_Button"
							"XPos"						"0"
							"YPos"						"0"
							"ZPos"						"5"
							"Wide"						"f0"
							"Tall"						"f0"
							"Visible"					"1"
							"Enabled"					"1"
							"Font"						""
							"Command"					"engine jp_hp_circle"
							"LabelText"					""
							"Sound_Depressed"			"UI/buttonclick.wav" 
							"ProportionalToParent"		"1"
							"ActionSignalLevel"			"6"

							"PaintBackground"			"0"
							"PaintBorder"				"1"

							"border_default"			"NoBorder"
							"border_armed"				"BorderSelectionGray"
						}
					}						
				}
			}
		}
	}
}