"Resource/UI/Customizations/#Customization_Menu/HUD_Customization_Miscellaneous.res"
{
	"SafeMode"
	{
		"Customizations_Panel"
		{
			"HUD_Miscellaneous_Selection"
			{
				"ControlName"							"CScrollableList"
				"FieldName"								"HUD_Miscellaneous_Selection"
				"XPos"									"cs-0.5"
				"YPos"									"cs-0.5"
				"ZPos"									"0"
				"Wide"									"f0"
				"Tall"									"f0"
				"Visible"								"0"
				"Enabled"								"1"
				"ProportionalToParent"					"1"
				"PaintBackground"						"0"
				"paintBackgroundType"					"0"
				"BGColor_Override"						"Black"

				"Scrollbar"
				{
					"XPos"								"rs1+1"
					"YPos"								"0"
					"Wide"								"6"
					"Tall"								"f0"
					"ZPos"								"1000"
					"ProportionalToParent"				"1"

					"Slider"
					{
						"PaintBackgroundType"			"0"
						"FGColor_Override"				"Gray"
					}

					"nobuttons"							"1"
				}
//===============================================================================================================
// SCOREBOARDS
//===============================================================================================================
				"Scoreboards_Icon"
				{
					"ControlName"						"CExLabel"
					"FieldName"							"Scoreboards_Icon"
					"XPos"								"4"
					"YPos"								"2"
					"ZPos"								"0"
					"Wide"								"20"
					"Tall"								"25"
					"Visible"							"1"
					"Enabled"							"1"
					"ProportionalToParent"				"1"
					"LabelText"							"'"
					"Font"								"Symbols24"
					"TextAlignment"						"center"
					"FGColor"							"Gray"
				}
				"Scoreboard_Label"
				{
					"ControlName"						"CExLabel"
					"FieldName"							"Scoreboard_Label"
					"XPos"								"30"
					"YPos"								"0"
					"ZPos"								"0"
					"Wide"								"f25"
					"Tall"								"27"
					"Visible"							"1"
					"Enabled"							"1"
					"ProportionalToParent"				"1"
					"AllCaps"							"1"
					"LabelText"							"#HudCustomization_Misc_Scoreboard"
					"Font"								"itemfontnamesmall"
					"TextAlignment"						"west"
					"FGColor"							"Gray"
				}
				"Separator_1"
				{
					"ControlName"						"EditablePanel"
					"FieldName"							"Separator_1"
					"XPos"								"3"
					"YPos"								"26"
					"ZPos"								"0"
					"Wide"								"f40"
					"Tall"								"2"
					"Visible"							"1"
					"Enabled"							"1"
					"ProportionalToParent"				"1"
					"paintBackground"					"1"
					"paintBackgroundtype"				"3"
					"BGcolor_Override"					"Background_Bright"
				}
// SCOREBOARD STYLES -------------------------------------------------------------------------------------------------------
				"Scoreboard_Styles"
				{
					"ControlName"						"EditablePanel"
					"FieldName"							"Scoreboard_Styles"
					"XPos"								"4"
					"YPos"								"31"
					"ZPos"								"20"
					"Wide"								"250"
					"Tall"								"110"
					"Visible"							"0"
					"Enabled"							"1"
					"ProportionalToParent"				"1"

					"Style_Label"
					{
						"ControlName"					"CExLabel"
						"FieldName"						"Style_Label"
						"XPos"							"0"
						"YPos"							"0"
						"ZPos"							"0"
						"Wide"							"f25"
						"Tall"							"15"
						"Visible"						"1"
						"Enabled"						"1"
						"ProportionalToParent"			"1"
						"AllCaps"						"1"
						"LabelText"						"#HudCustomization_Misc_Scoreboard_Style"
						"Font"							"HudFontSmallBold"
						"TextAlignment"					"west"
						"FGColor"						"Gray"
					}
					"Separator"
					{
						"ControlName"					"EditablePanel"
						"FieldName"						"Separator"
						"XPos"							"2"
						"YPos"							"1"
						"ZPos"							"0"
						"Wide"							"f15"
						"Tall"							"1"
						"Visible"						"1"
						"Enabled"						"1"
						"ProportionalToParent"			"1"
						"paintBackground"				"1"
						"paintBackgroundtype"			"3"
						"BGcolor_Override"				"Background_Bright"

						"Pin_To_Sibling"				"Style_Label"
						"Pin_Corner_To_Sibling"			"PIN_TOPLEFT"
						"Pin_To_Sibling_Corner"			"PIN_BOTTOMLEFT"
					}
					"Scoreboard_m0re"
					{
						"ControlName"					"EditablePanel"
						"FieldName"						"Scoreboard_m0re"
						"XPos"							"-2"
						"YPos"							"5"
						"ZPos"							"1"
						"Wide"							"120"
						"Tall"							"82"
						"Visible"						"1"
						"Enabled"						"1"
						"ProportionalToParent"			"1"
						"PaintBackground"				"1"
						"BGcolor_Override"				"104 101 100 255"

						"Pin_To_Sibling"				"Separator"
						"Pin_Corner_To_Sibling"			"PIN_TOPLEFT"
						"Pin_To_Sibling_Corner"			"PIN_BOTTOMLEFT"

						"Scoreboard_Image"
						{
							"ControlName"				"Panel"
							"FieldName"					"Scoreboard_Image"
							"XPos"						"cs-0.5"
							"YPos"						"cs-0.5-6"
							"ZPos"						"0"
							"Wide"						"120"
							"Tall"						"70"
							"Visible"					"1"
							"Enabled"					"1"
							"MouseInputEnabled"			"0"
							"ScaleImage"				"1"
							"ProportionalToParent"		"1"
						}
						"Scoreboard_Label"
						{
							"ControlName"				"CExLabel"
							"FieldName"					"Scoreboard_Label"
							"XPos"						"0"
							"YPos"						"rs1"
							"ZPos"						"1"
							"Wide"						"f0"
							"Tall"						"12"
							"Visible"					"1"
							"Enabled"					"1"
							"MouseInputEnabled"			"0"
							"ProportionalToParent"		"1"
							"AllCaps"					"1"
							"Font"						"FontStorePrice"
							"LabelText"					"m0re"
							"TextAlignment"				"center"
							"FGColor"					"Gray"
							"PaintBackground"			"1"
							"PaintBackgroundType"		"0"
							"BGColor_Override"			"Background_Darkest"
						}
						"Scoreboard_Button"
						{
							"ControlName"				"CExButton"
							"FieldName"					"Scoreboard_Button"
							"XPos"						"0"
							"YPos"						"0"
							"ZPos"						"5"
							"Wide"						"f0"
							"Tall"						"f0"
							"Visible"					"1"
							"Enabled"					"1"
							"Font"						""
							"Command"					"engine m0_scoreboard_style_clear"
							"LabelText"					""
							"Sound_Depressed"			"UI/buttonclick.wav"
							"ProportionalToParent"		"1"
							"ActionSignalLevel"			"6"

							"PaintBackground"			"0"
							"PaintBorder"				"1"

							"border_default"			"NoBorder"
							"border_armed"				"BorderSelectionGray"
						}
					}
					"Scoreboard_Foster"
					{
						"ControlName"					"EditablePanel"
						"FieldName"						"Scoreboard_Foster"
						"XPos"							"5"
						"YPos"							"0"
						"ZPos"							"1"
						"Wide"							"120"
						"Tall"							"82"
						"Visible"						"1"
						"Enabled"						"1"
						"ProportionalToParent"			"1"
						"PaintBackground"				"1"
						"BGcolor_Override"				"104 101 100 255"

						"Pin_To_Sibling"				"Scoreboard_m0re"
						"Pin_Corner_To_Sibling"			"PIN_TOPLEFT"
						"Pin_To_Sibling_Corner"			"PIN_TOPRIGHT"

						"Scoreboard_Image"
						{
							"ControlName"				"ImagePanel"
							"FieldName"					"Scoreboard_Image"
							"XPos"						"cs-0.5"
							"YPos"						"cs-0.5-3"
							"ZPos"						"0"
							"Wide"						"130"
							"Tall"						"130"
							"Visible"					"1"
							"Enabled"					"1"
							"MouseInputEnabled"			"0"
							"ScaleImage"				"1"
							"ProportionalToParent"		"1"
							"Image"						""
						}
						"Scoreboard_Label"
						{
							"ControlName"				"CExLabel"
							"FieldName"					"Scoreboard_Label"
							"XPos"						"0"
							"YPos"						"rs1"
							"ZPos"						"1"
							"Wide"						"f0"
							"Tall"						"12"
							"Visible"					"1"
							"Enabled"					"1"
							"MouseInputEnabled"			"0"
							"ProportionalToParent"		"1"
							"AllCaps"					"1"
							"Font"						"FontStorePrice"
							"LabelText"					"Foster"
							"TextAlignment"				"center"
							"FGColor"					"Gray"
							"PaintBackground"			"1"
							"PaintBackgroundType"		"0"
							"BGColor_Override"			"Background_Darkest"
						}
						"Scoreboard_Button"
						{
							"ControlName"				"CExButton"
							"FieldName"					"Scoreboard_Button"
							"XPos"						"0"
							"YPos"						"0"
							"ZPos"						"5"
							"Wide"						"f0"
							"Tall"						"f0"
							"Visible"					"1"
							"Enabled"					"1"
							"Font"						""
							"Command"					"engine m0_scoreboard_foster"
							"LabelText"					""
							"Sound_Depressed"			"UI/buttonclick.wav"
							"ProportionalToParent"		"1"
							"ActionSignalLevel"			"6"

							"PaintBackground"			"0"
							"PaintBorder"				"1"

							"border_default"			"NoBorder"
							"border_armed"				"BorderSelectionGray"
						}
					}
				}
// SCOREBOARD SIZES -------------------------------------------------------------------------------------------------------
				"Scoreboard_Sizes"
				{
					"ControlName"						"EditablePanel"
					"FieldName"							"Scoreboard_Sizes"
					"XPos"								"4"
					"YPos"								"31"
					"ZPos"								"20"
					"Wide"								"500"
					"Tall"								"42"
					"Visible"							"1"
					"Enabled"							"1"
					"ProportionalToParent"				"1"

					"Size_Label"
					{
						"ControlName"					"CExLabel"
						"FieldName"						"Size_Label"
						"XPos"							"0"
						"YPos"							"0"
						"ZPos"							"0"
						"Wide"							"f25"
						"Tall"							"15"
						"Visible"						"1"
						"Enabled"						"1"
						"ProportionalToParent"			"1"
						"AllCaps"						"1"
						"LabelText"						"#HudCustomization_Misc_Scoreboard_Size"
						"Font"							"HudFontSmallBold"
						"TextAlignment"					"west"
						"FGColor"						"Gray"
					}
					"Separator"
					{
						"ControlName"					"EditablePanel"
						"FieldName"						"Separator"
						"XPos"							"2"
						"YPos"							"1"
						"ZPos"							"0"
						"Wide"							"f15"
						"Tall"							"1"
						"Visible"						"1"
						"Enabled"						"1"
						"ProportionalToParent"			"1"
						"paintBackground"				"1"
						"paintBackgroundtype"			"3"
						"BGcolor_Override"				"Background_Bright"

						"Pin_To_Sibling"				"Size_Label"
						"Pin_Corner_To_Sibling"			"PIN_TOPLEFT"
						"Pin_To_Sibling_Corner"			"PIN_BOTTOMLEFT"
					}

					"Scoreboard_6v6"
					{
						"ControlName"					"CExButton"
						"FieldName"						"Scoreboard_6v6"
						"XPos"							"-2"
						"YPos"							"5"
						"ZPos"							"5"
						"Wide"							"60"
						"Tall"							"18"
						"Visible"						"1"
						"Enabled"						"1"
						"Font"							"HudFontSmallBold"
						"TextAlignment"					"center"
						"Command"						"engine m0_scoreboard_6v6"
						"LabelText"						"6 v 6"
						"AllCaps"						"1"
						"Sound_Depressed"				"UI/buttonclick.wav"
						"ProportionalToParent"			"1"
						"ActionSignalLevel"				"5"
						"PaintBackground"				"1"

						"Pin_To_Sibling"				"Separator"
						"Pin_Corner_To_Sibling"			"PIN_TOPLEFT"
						"Pin_To_Sibling_Corner"			"PIN_BOTTOMLEFT"						

					}
					"Scoreboard_12V12"
					{
						"ControlName"					"CExButton"
						"FieldName"						"Scoreboard_12V12"
						"XPos"							"5"
						"YPos"							"0"
						"ZPos"							"5"
						"Wide"							"60"
						"Tall"							"18"
						"Visible"						"1"
						"Enabled"						"1"
						"Font"							"HudFontSmallBold"
						"TextAlignment"					"center"
						"Command"						"engine m0_scoreboard_9v9"
						"LabelText"						"9 v 9"
						"AllCaps"						"1"
						"Sound_Depressed"				"UI/buttonclick.wav"
						"ProportionalToParent"			"1"
						"ActionSignalLevel"				"5"
						"PaintBackground"				"1"

						"Pin_To_Sibling"				"Scoreboard_6v6"
						"Pin_Corner_To_Sibling"			"PIN_TOPLEFT"
						"Pin_To_Sibling_Corner"			"PIN_TOPRIGHT"
					}					
					"Scoreboard_12V12v2"
					{
						"ControlName"					"CExButton"
						"FieldName"						"Scoreboard_12V12v2"
						"XPos"							"5"
						"YPos"							"0"
						"ZPos"							"5"
						"Wide"							"60"
						"Tall"							"18"
						"Visible"						"1"
						"Enabled"						"1"
						"Font"							"HudFontSmallBold"
						"TextAlignment"					"center"
						"Command"						"engine m0_scoreboard_size_clear"
						"LabelText"						"12 v 12"
						"AllCaps"						"1"
						"Sound_Depressed"				"UI/buttonclick.wav"
						"ProportionalToParent"			"1"
						"ActionSignalLevel"				"5"
						"PaintBackground"				"1"

						"Pin_To_Sibling"				"Scoreboard_12V12"
						"Pin_Corner_To_Sibling"			"PIN_TOPLEFT"
						"Pin_To_Sibling_Corner"			"PIN_TOPRIGHT"
					}		
					"Scoreboard_24v24"
					{
						"ControlName"					"CExButton"
						"FieldName"						"Scoreboard_24v24"
						"XPos"							"5"
						"YPos"							"0"
						"ZPos"							"5"
						"Wide"							"60"
						"Tall"							"18"
						"Visible"						"1"
						"Enabled"						"1"
						"Font"							"HudFontSmallBold"
						"TextAlignment"					"center"
						"Command"						"engine m0_scoreboard_24v24"
						"LabelText"						"24 v 24"
						"AllCaps"						"1"
						"Sound_Depressed"				"UI/buttonclick.wav"
						"ProportionalToParent"			"1"
						"ActionSignalLevel"				"5"
						"PaintBackground"				"1"

						"Pin_To_Sibling"				"Scoreboard_12V12v2"
						"Pin_Corner_To_Sibling"			"PIN_TOPLEFT"
						"Pin_To_Sibling_Corner"			"PIN_TOPRIGHT"
					}	
					"Scoreboard_32v32"
					{
						"ControlName"					"CExButton"
						"FieldName"						"Scoreboard_32v32"
						"XPos"							"5"
						"YPos"							"0"
						"ZPos"							"5"
						"Wide"							"60"
						"Tall"							"18"
						"Visible"						"1"
						"Enabled"						"1"
						"Font"							"HudFontSmallBold"
						"TextAlignment"					"center"
						"Command"						"engine m0_scoreboard_32v32"
						"LabelText"						"32 v 32"
						"AllCaps"						"1"
						"Sound_Depressed"				"UI/buttonclick.wav"
						"ProportionalToParent"			"1"
						"ActionSignalLevel"				"5"
						"PaintBackground"				"1"

						"Pin_To_Sibling"				"Scoreboard_24v24"
						"Pin_Corner_To_Sibling"			"PIN_TOPLEFT"
						"Pin_To_Sibling_Corner"			"PIN_TOPRIGHT"
					}														
				}
// SCOREBOARD SETTINGS -------------------------------------------------------------------------------------------------------
				"Scoreboard_Settings"
				{
					"ControlName"						"EditablePanel"
					"FieldName"							"Scoreboard_Settings"
					"XPos"								"4"
					"YPos"								"75"
					"ZPos"								"20"
					"Wide"								"160"
					"Tall"								"60"
					"Visible"							"1"
					"Enabled"							"1"
					"ProportionalToParent"				"1"

					"Settings_Label"
					{
						"ControlName"					"CExLabel"
						"FieldName"						"Settings_Label"
						"XPos"							"0"
						"YPos"							"0"
						"ZPos"							"0"
						"Wide"							"f5"
						"Tall"							"15"
						"Visible"						"1"
						"Enabled"						"1"
						"ProportionalToParent"			"1"
						"AllCaps"						"1"
						"LabelText"						"#HudCustomization_Misc_Scoreboard_Settings"
						"Font"							"HudFontSmallBold"
						"TextAlignment"					"west"
						"FGColor"						"Gray"
					}
					"Separator"
					{
						"ControlName"					"EditablePanel"
						"FieldName"						"Separator"
						"XPos"							"2"
						"YPos"							"1"
						"ZPos"							"0"
						"Wide"							"f15"
						"Tall"							"1"
						"Visible"						"1"
						"Enabled"						"1"
						"ProportionalToParent"			"1"
						"paintBackground"				"1"
						"paintBackgroundtype"			"3"
						"BGcolor_Override"				"Background_Bright"

						"Pin_To_Sibling"				"Settings_Label"
						"Pin_Corner_To_Sibling"			"PIN_TOPLEFT"
						"Pin_To_Sibling_Corner"			"PIN_BOTTOMLEFT"
					}
					"Scoreboard_Mouse_Input"
					{
						"ControlName"					"EditablePanel"
						"FieldName"						"Scoreboard_Mouse_Input"
						"XPos"							"-2"
						"YPos"							"4"
						"ZPos"							"1"
						"Wide"							"130"
						"Tall"							"16"
						"Visible"						"1"
						"Enabled"						"1"
						"ProportionalToParent"			"1"
						"PaintBackground"				"0"

						"Pin_To_Sibling"				"Separator"
						"Pin_Corner_To_Sibling"			"PIN_TOPLEFT"
						"Pin_To_Sibling_Corner"			"PIN_BOTTOMLEFT"

						"Toggle_Button"
						{
							"ControlName"				"CExButton"
							"FieldName"					"Toggle_Button"
							"XPos"						"cs-0.5"
							"YPos"						"cs-0.5"
							"ZPos"						"20"
							"Wide"						"f0"
							"Tall"						"f0"
							"Visible"					"1"
							"Enabled"					"1"
							"ActionSignalLevel"			"6"
							"ProportionalToParent"		"1"
							"LabelText"					""
							"TextAlignment"				"west"
							"Command"					"engine toggle tf_scoreboard_mouse_mode 0 2"
							"Sound_Depressed"			"UI/buttonclick.wav"
							"PaintBackground"			"1"
							"PaintBorder"				"0"

							"border_default"			"NoBorder"
							"border_armed"				"BorderSelectionWhite"

							"DefaultBGColor_Override"	"Blank"
							"ArmedBGColor_Override"		"Button_Hover"
							"DepressedBGColor_Override"	"Button_Hover"
						}
						"Setting_Checkbox"
						{
							"ControlName"				"CvarToggleCheckButton"
							"FieldName"					"Setting_Checkbox"
							"XPos"						"-2"
							"YPos"						"cs-0.5"
							"ZPos"						"21"
							"Wide"						"19"
							"Tall"						"f0"
							"ProportionalToParent"		"1"
							"LabelText"					""
							"TextAlignment"				"west"
							"SmallCheckImage"			"1"
							"button_activation_type"	"1"
							"cvar_name"					"tf_scoreboard_mouse_mode"
							"MouseInputEnabled"			"0"
						}
						"Setting_Label"
						{
							"ControlName"				"CExLabel"
							"FieldName"					"Setting_Label"
							"XPos"						"19"
							"YPos"						"cs-0.5"
							"ZPos"						"21"
							"Wide"						"f24"
							"Tall"						"f0"
							"Visible"					"1"
							"Enabled"					"1"
							"AllCaps"					"1"
							"MouseInputEnabled"			"0"
							"ProportionalToParent"		"1"
							"Font"						"FontStoreOriginalPrice"
							"LabelText"					"#HudCustomization_Misc_Scoreboard_Setting1"
							"TextAlignment"				"west"
							"Wrap"						"0"
							"FGColor"					"White"
						}
					}
					"Scoreboard_Ping_Style"
					{
						"ControlName"					"EditablePanel"
						"FieldName"						"Scoreboard_Ping_Style"
						"XPos"							"0"
						"YPos"							"4"
						"ZPos"							"1"
						"Wide"							"130"
						"Tall"							"16"
						"Visible"						"1"
						"Enabled"						"1"
						"ProportionalToParent"			"1"
						"PaintBackground"				"0"

						"Pin_To_Sibling"				"Scoreboard_Mouse_Input"
						"Pin_Corner_To_Sibling"			"PIN_TOPLEFT"
						"Pin_To_Sibling_Corner"			"PIN_BOTTOMLEFT"

						"Toggle_Button"
						{
							"ControlName"				"CExButton"
							"FieldName"					"Toggle_Button"
							"XPos"						"cs-0.5"
							"YPos"						"cs-0.5"
							"ZPos"						"20"
							"Wide"						"f0"
							"Tall"						"f0"
							"Visible"					"1"
							"Enabled"					"1"
							"ActionSignalLevel"			"6"
							"ProportionalToParent"		"1"
							"LabelText"					""
							"TextAlignment"				"west"
							"Command"					"engine toggle tf_scoreboard_ping_as_text"
							"Sound_Depressed"			"UI/buttonclick.wav"
							"PaintBackground"			"1"
							"PaintBorder"				"0"

							"border_default"			"NoBorder"
							"border_armed"				"BorderSelectionWhite"

							"DefaultBGColor_Override"	"Blank"
							"ArmedBGColor_Override"		"Button_Hover"
							"DepressedBGColor_Override"	"Button_Hover"
						}
						"Setting_Checkbox"
						{
							"ControlName"				"CvarToggleCheckButton"
							"FieldName"					"Setting_Checkbox"
							"XPos"						"-2"
							"YPos"						"cs-0.5"
							"ZPos"						"21"
							"Wide"						"19"
							"Tall"						"f0"
							"ProportionalToParent"		"1"
							"LabelText"					""
							"TextAlignment"				"west"
							"SmallCheckImage"			"1"
							"button_activation_type"	"1"
							"cvar_name"					"tf_scoreboard_ping_as_text"
							"MouseInputEnabled"			"0"
						}
						"Setting_Label"
						{
							"ControlName"				"CExLabel"
							"FieldName"					"Setting_Label"
							"XPos"						"19"
							"YPos"						"cs-0.5"
							"ZPos"						"21"
							"Wide"						"f24"
							"Tall"						"f0"
							"Visible"					"1"
							"Enabled"					"1"
							"AllCaps"					"1"
							"MouseInputEnabled"			"0"
							"ProportionalToParent"		"1"
							"Font"						"FontStoreOriginalPrice"
							"LabelText"					"#HudCustomization_Misc_Scoreboard_Setting2"
							"TextAlignment"				"west"
							"Wrap"						"0"
							"FGColor"					"White"
						}
					}
				}
//===============================================================================================================
// VIEWMODELS
//===============================================================================================================
				"Viewmodel_Icon"
				{
					"ControlName"						"CExLabel"
					"FieldName"							"Viewmodel_Icon"
					"XPos"								"4"
					"YPos"								"146"
					"ZPos"								"0"
					"Wide"								"22"
					"Tall"								"25"
					"Visible"							"1"
					"Enabled"							"1"
					"ProportionalToParent"				"1"
					"LabelText"							"@"
					"Font"								"Symbols24"
					"TextAlignment"						"center"
					"FGColor"							"Gray"
				}
				"Viewmodel_Label"
				{
					"ControlName"						"CExLabel"
					"FieldName"							"Viewmodel_Label"
					"XPos"								"32"
					"YPos"								"145"
					"ZPos"								"0"
					"Wide"								"f25"
					"Tall"								"27"
					"Visible"							"1"
					"Enabled"							"1"
					"ProportionalToParent"				"1"
					"AllCaps"							"1"
					"LabelText"							"#HudCustomization_Misc_Viewmodel"
					"Font"								"itemfontnamesmall"
					"TextAlignment"						"west"
					"FGColor"							"Gray"
				}
				"Separator_2"
				{
					"ControlName"						"EditablePanel"
					"FieldName"							"Separator_2"
					"XPos"								"3"
					"YPos"								"172"
					"ZPos"								"0"
					"Wide"								"f40"
					"Tall"								"2"
					"Visible"							"1"
					"Enabled"							"1"
					"ProportionalToParent"				"1"
					"paintBackground"					"1"
					"paintBackgroundtype"				"3"
					"BGcolor_Override"					"Background_Bright"
				}
// TRANSPARENT VIEWMODELS ----------------------------------------------------------------------------------------
				"Transparent_Viewmodels"
				{
					"ControlName"						"EditablePanel"
					"FieldName"							"Transparent_Viewmodels"
					"XPos"								"4"
					"YPos"								"178"
					"ZPos"								"20"
					"Wide"								"200"
					"Tall"								"100"
					"Visible"							"1"
					"Enabled"							"1"
					"ProportionalToParent"				"1"

					"Style_Label"
					{
						"ControlName"					"CExLabel"
						"FieldName"						"Style_Label"
						"XPos"							"0"
						"YPos"							"0"
						"ZPos"							"0"
						"Wide"							"f25"
						"Tall"							"15"
						"Visible"						"1"
						"Enabled"						"1"
						"ProportionalToParent"			"1"
						"AllCaps"						"1"
						"LabelText"						"#HudCustomization_Misc_Viewmodel_Style"
						"Font"							"HudFontSmallBold"
						"TextAlignment"					"west"
						"FGColor"						"Gray"
					}
					"Separator"
					{
						"ControlName"					"EditablePanel"
						"FieldName"						"Separator"
						"XPos"							"2"
						"YPos"							"1"
						"ZPos"							"0"
						"Wide"							"f15"
						"Tall"							"1"
						"Visible"						"1"
						"Enabled"						"1"
						"ProportionalToParent"			"1"
						"paintBackground"				"1"
						"paintBackgroundtype"			"3"
						"BGcolor_Override"				"Background_Bright"

						"Pin_To_Sibling"				"Style_Label"
						"Pin_Corner_To_Sibling"			"PIN_TOPLEFT"
						"Pin_To_Sibling_Corner"			"PIN_BOTTOMLEFT"
					}
					"Style_Normal"
					{
						"ControlName"					"EditablePanel"
						"FieldName"						"Style_Normal"
						"XPos"							"-2"
						"YPos"							"5"
						"ZPos"							"1"
						"Wide"							"80"
						"Tall"							"70"
						"Visible"						"1"
						"Enabled"						"1"
						"ProportionalToParent"			"1"
						"PaintBackground"				"1"
						"BGcolor_Override"				"104 101 100 255"

						"Pin_To_Sibling"				"Separator"
						"Pin_Corner_To_Sibling"			"PIN_TOPLEFT"
						"Pin_To_Sibling_Corner"			"PIN_BOTTOMLEFT"

						"Style_Name"
						{
							"ControlName"				"CExLabel"
							"FieldName"					"Style_Name"
							"XPos"						"cs-0.5"
							"YPos"						"rs1"
							"ZPos"						"1"
							"Wide"						"f0"
							"Tall"						"12"
							"Visible"					"1"
							"Enabled"					"1"
							"AllCaps"					"1"
							"MouseInputEnabled"			"0"
							"ProportionalToParent"		"1"
							"Font"						"FontStorePrice"
							"LabelText"					"#HudCustomization_Normal"
							"TextAlignment"				"center"
							"FGColor"					"Gray"
							"PaintBackground"			"1"
							"PaintBackgroundType"		"0"
							"BGColor_Override"			"Background_Darkest"
						}
						"Style_Image"
						{
							"ControlName"				"ImagePanel"
							"FieldName"					"Style_Image"
							"XPos"						"cs-0.5"
							"YPos"						"cs-0.5-7"
							"ZPos"						"0"
							"Wide"						"60"
							"Tall"						"60"
							"Visible"					"1"
							"Enabled"					"1"
							"MouseInputEnabled"			"0"
							"ScaleImage"				"1"
							"ProportionalToParent"		"1"
							"Image"						"replay/thumbnails/customizations/transparent_viewmodels/transparent_viewmodels_off"
						}
						"Style_Button"
						{
							"ControlName"				"CExButton"
							"FieldName"					"Style_Button"
							"XPos"						"0"
							"YPos"						"0"
							"ZPos"						"5"
							"Wide"						"f0"
							"Tall"						"f0"
							"Visible"					"1"
							"Enabled"					"1"
							"Font"						""
							"Command"					"engine m0_trans_viewmodels_clear"
							"LabelText"					""
							"Sound_Depressed"			"UI/buttonclick.wav"
							"ProportionalToParent"		"1"
							"ActionSignalLevel"			"6"

							"PaintBackground"			"0"
							"PaintBorder"				"1"

							"border_default"			"NoBorder"
							"border_armed"				"BorderSelectionGray"
						}
					}
					"Style_Transparent"
					{
						"ControlName"					"EditablePanel"
						"FieldName"						"Style_Transparent"
						"XPos"							"5"
						"YPos"							"0"
						"ZPos"							"1"
						"Wide"							"80"
						"Tall"							"70"
						"Visible"						"1"
						"Enabled"						"1"
						"ProportionalToParent"			"1"
						"PaintBackground"				"1"
						"BGcolor_Override"				"104 101 100 255"

						"Pin_To_Sibling"				"Style_Normal"
						"Pin_Corner_To_Sibling"			"PIN_TOPLEFT"
						"Pin_To_Sibling_Corner"			"PIN_TOPRIGHT"

						"Style_Name"
						{
							"ControlName"				"CExLabel"
							"FieldName"					"Style_Name"
							"XPos"						"cs-0.5"
							"YPos"						"rs1"
							"ZPos"						"1"
							"Wide"						"f0"
							"Tall"						"12"
							"Visible"					"1"
							"Enabled"					"1"
							"AllCaps"					"1"
							"MouseInputEnabled"			"0"
							"ProportionalToParent"		"1"
							"Font"						"FontStorePrice"
							"LabelText"					"#HudCustomization_Damage_Alpha_Style2"
							"TextAlignment"				"center"
							"FGColor"					"Gray"
							"PaintBackground"			"1"
							"PaintBackgroundType"		"0"
							"BGColor_Override"			"Background_Darkest"
						}
						"Style_Image"
						{
							"ControlName"				"ImagePanel"
							"FieldName"					"Style_Image"
							"XPos"						"cs-0.5"
							"YPos"						"cs-0.5-7"
							"ZPos"						"0"
							"Wide"						"60"
							"Tall"						"60"
							"Visible"					"1"
							"Enabled"					"1"
							"MouseInputEnabled"			"0"
							"ScaleImage"				"1"
							"ProportionalToParent"		"1"
							"Image"						"replay/thumbnails/customizations/transparent_viewmodels/transparent_viewmodels_on"
						}
						"Style_Button"
						{
							"ControlName"				"CExButton"
							"FieldName"					"Style_Button"
							"XPos"						"0"
							"YPos"						"0"
							"ZPos"						"5"
							"Wide"						"f0"
							"Tall"						"f0"
							"Visible"					"1"
							"Enabled"					"1"
							"Font"						""
							"Command"					"engine m0_trans_viewmodels_on"
							"LabelText"					""
							"Sound_Depressed"			"UI/buttonclick.wav"
							"ProportionalToParent"		"1"
							"ActionSignalLevel"			"6"

							"PaintBackground"			"0"
							"PaintBorder"				"1"

							"border_default"			"NoBorder"
							"border_armed"				"BorderSelectionGray"
						}
					}
				}
// VIEWMODEL SETTINGS ----------------------------------------------------------------------------------------
				"Viewmodel_Settings"
				{
					"ControlName"						"EditablePanel"
					"FieldName"							"Viewmodel_Settings"
					"XPos"								"200"
					"YPos"								"178"
					"ZPos"								"20"
					"Wide"								"250"
					"Tall"								"100"
					"Visible"							"1"
					"Enabled"							"1"
					"ProportionalToParent"				"1"

					"Settings_Label"
					{
						"ControlName"					"CExLabel"
						"FieldName"						"Settings_Label"
						"XPos"							"0"
						"YPos"							"0"
						"ZPos"							"0"
						"Wide"							"f25"
						"Tall"							"15"
						"Visible"						"1"
						"Enabled"						"1"
						"ProportionalToParent"			"1"
						"AllCaps"						"1"
						"LabelText"						"#HudCustomization_Misc_Viewmodel_Settings"
						"Font"							"HudFontSmallBold"
						"TextAlignment"					"west"
						"FGColor"						"Gray"
					}
					"Separator"
					{
						"ControlName"					"EditablePanel"
						"FieldName"						"Separator"
						"XPos"							"2"
						"YPos"							"1"
						"ZPos"							"0"
						"Wide"							"f15"
						"Tall"							"1"
						"Visible"						"1"
						"Enabled"						"1"
						"ProportionalToParent"			"1"
						"paintBackground"				"1"
						"paintBackgroundtype"			"3"
						"BGcolor_Override"				"Background_Bright"

						"Pin_To_Sibling"				"Settings_Label"
						"Pin_Corner_To_Sibling"			"PIN_TOPLEFT"
						"Pin_To_Sibling_Corner"			"PIN_BOTTOMLEFT"
					}
					"Viewmodel_Toggle"
					{
						"ControlName"					"EditablePanel"
						"FieldName"						"Viewmodel_Toggle"
						"XPos"							"-2"
						"YPos"							"5"
						"ZPos"							"1"
						"Wide"							"110"
						"Tall"							"22"
						"Visible"						"1"
						"Enabled"						"1"
						"ProportionalToParent"			"1"
						"PaintBackground"				"0"

						"Pin_To_Sibling"				"Separator"
						"Pin_Corner_To_Sibling"			"PIN_TOPLEFT"
						"Pin_To_Sibling_Corner"			"PIN_BOTTOMLEFT"

						"Toggle_Button"
						{
							"ControlName"				"CExButton"
							"FieldName"					"Toggle_Button"
							"XPos"						"cs-0.5"
							"YPos"						"cs-0.5"
							"ZPos"						"20"
							"Wide"						"f0"
							"Tall"						"f0"
							"Visible"					"1"
							"Enabled"					"1"
							"ActionSignalLevel"			"6"
							"ProportionalToParent"		"1"
							"LabelText"					""
							"TextAlignment"				"west"
							"Command"					"engine toggle r_drawviewmodel"
							"Sound_Depressed"			"UI/buttonclick.wav"
							"PaintBackground"			"1"
							"PaintBorder"				"0"

							"border_default"			"NoBorder"
							"border_armed"				"BorderSelectionWhite"

							"DefaultBGColor_Override"	"Blank"
							"ArmedBGColor_Override"		"Button_Hover"
							"DepressedBGColor_Override"	"Button_Hover"
						}
						"Setting_Checkbox"
						{
							"ControlName"				"CvarToggleCheckButton"
							"FieldName"					"Setting_Checkbox"
							"XPos"						"-2"
							"YPos"						"cs-0.5"
							"ZPos"						"21"
							"Wide"						"22"
							"Tall"						"22"
							"ProportionalToParent"		"1"
							"LabelText"					""
							"TextAlignment"				"west"
							"SmallCheckImage"			"0"
							"button_activation_type"	"1"
							"cvar_name"					"r_drawviewmodel"
							"MouseInputEnabled"			"0"
						}
						"Setting_Label"
						{
							"ControlName"				"CExLabel"
							"FieldName"					"Setting_Label"
							"XPos"						"24"
							"YPos"						"cs-0.5"
							"ZPos"						"21"
							"Wide"						"f24"
							"Tall"						"f0"
							"Visible"					"1"
							"Enabled"					"1"
							"AllCaps"					"1"
							"MouseInputEnabled"			"0"
							"ProportionalToParent"		"1"
							"Font"						"FontStoreOriginalPrice"
							"LabelText"					"#HudCustomization_Misc_Viewmodel_Setting1"
							"TextAlignment"				"west"
							"Wrap"						"0"
							"FGColor"					"White"
						}
					}
					"Viewmodel_Minimal"
					{
						"ControlName"					"EditablePanel"
						"FieldName"						"Viewmodel_Minimal"
						"XPos"							"5"
						"YPos"							"0"
						"ZPos"							"1"
						"Wide"							"115"
						"Tall"							"22"
						"Visible"						"1"
						"Enabled"						"1"
						"ProportionalToParent"			"1"
						"PaintBackground"				"0"

						"Pin_To_Sibling"				"Viewmodel_Toggle"
						"Pin_Corner_To_Sibling"			"PIN_TOPLEFT"
						"Pin_To_Sibling_Corner"			"PIN_TOPRIGHT"

						"Toggle_Button"
						{
							"ControlName"				"CExButton"
							"FieldName"					"Toggle_Button"
							"XPos"						"cs-0.5"
							"YPos"						"cs-0.5"
							"ZPos"						"20"
							"Wide"						"f0"
							"Tall"						"f0"
							"Visible"					"1"
							"Enabled"					"1"
							"ActionSignalLevel"			"6"
							"ProportionalToParent"		"1"
							"LabelText"					""
							"TextAlignment"				"west"
							"Command"					"engine toggle tf_use_min_viewmodels"
							"Sound_Depressed"			"UI/buttonclick.wav"
							"PaintBackground"			"1"
							"PaintBorder"				"0"

							"border_default"			"NoBorder"
							"border_armed"				"BorderSelectionWhite"

							"DefaultBGColor_Override"	"Blank"
							"ArmedBGColor_Override"		"Button_Hover"
							"DepressedBGColor_Override"	"Button_Hover"
						}
						"Setting_Checkbox"
						{
							"ControlName"				"CvarToggleCheckButton"
							"FieldName"					"Setting_Checkbox"
							"XPos"						"-2"
							"YPos"						"cs-0.5"
							"ZPos"						"21"
							"Wide"						"22"
							"Tall"						"22"
							"ProportionalToParent"		"1"
							"LabelText"					""
							"TextAlignment"				"west"
							"SmallCheckImage"			"0"
							"button_activation_type"	"1"
							"cvar_name"					"tf_use_min_viewmodels"
							"MouseInputEnabled"			"0"
						}
						"Setting_Label"
						{
							"ControlName"				"CExLabel"
							"FieldName"					"Setting_Label"
							"XPos"						"24"
							"YPos"						"cs-0.5"
							"ZPos"						"21"
							"Wide"						"f24"
							"Tall"						"f0"
							"Visible"					"1"
							"Enabled"					"1"
							"AllCaps"					"1"
							"MouseInputEnabled"			"0"
							"ProportionalToParent"		"1"
							"Font"						"FontStoreOriginalPrice"
							"LabelText"					"#HudCustomization_Misc_Viewmodel_Setting2"
							"TextAlignment"				"west"
							"Wrap"						"0"
							"FGColor"					"White"
						}
					}
					"Viewmodel_Flip"
					{
						"ControlName"					"EditablePanel"
						"FieldName"						"Viewmodel_Flip"
						"XPos"							"0"
						"YPos"							"5"
						"ZPos"							"1"
						"Wide"							"111"
						"Tall"							"22"
						"Visible"						"1"
						"Enabled"						"1"
						"ProportionalToParent"			"1"
						"PaintBackground"				"0"

						"Pin_To_Sibling"				"Viewmodel_Toggle"
						"Pin_Corner_To_Sibling"			"PIN_TOPLEFT"
						"Pin_To_Sibling_Corner"			"PIN_BOTTOMLEFT"

						"Toggle_Button"
						{
							"ControlName"				"CExButton"
							"FieldName"					"Toggle_Button"
							"XPos"						"cs-0.5"
							"YPos"						"cs-0.5"
							"ZPos"						"20"
							"Wide"						"f0"
							"Tall"						"f0"
							"Visible"					"1"
							"Enabled"					"1"
							"ActionSignalLevel"			"6"
							"ProportionalToParent"		"1"
							"LabelText"					""
							"TextAlignment"				"west"
							"Command"					"engine toggle cl_flipviewmodels"
							"Sound_Depressed"			"UI/buttonclick.wav"
							"PaintBackground"			"1"
							"PaintBorder"				"0"

							"border_default"			"NoBorder"
							"border_armed"				"BorderSelectionWhite"

							"DefaultBGColor_Override"	"Blank"
							"ArmedBGColor_Override"		"Button_Hover"
							"DepressedBGColor_Override"	"Button_Hover"
						}
						"Setting_Checkbox"
						{
							"ControlName"				"CvarToggleCheckButton"
							"FieldName"					"Setting_Checkbox"
							"XPos"						"-2"
							"YPos"						"cs-0.5"
							"ZPos"						"21"
							"Wide"						"22"
							"Tall"						"22"
							"ProportionalToParent"		"1"
							"LabelText"					""
							"TextAlignment"				"west"
							"SmallCheckImage"			"0"
							"button_activation_type"	"1"
							"cvar_name"					"cl_flipviewmodels"
							"MouseInputEnabled"			"0"
						}
						"Setting_Label"
						{
							"ControlName"				"CExLabel"
							"FieldName"					"Setting_Label"
							"XPos"						"24"
							"YPos"						"cs-0.5"
							"ZPos"						"21"
							"Wide"						"f24"
							"Tall"						"f0"
							"Visible"					"1"
							"Enabled"					"1"
							"AllCaps"					"1"
							"MouseInputEnabled"			"0"
							"ProportionalToParent"		"1"
							"Font"						"FontStoreOriginalPrice"
							"LabelText"					"#HudCustomization_Misc_Viewmodel_Setting3"
							"TextAlignment"				"west"
							"Wrap"						"0"
							"FGColor"					"White"
						}
					}
					"FOV_Slider"
					{
						"ControlName"					"EditablePanel"
						"FieldName"						"FOV_Slider"
						"XPos"							"5"
						"YPos"							"0"
						"ZPos"							"1"
						"Wide"							"115"
						"Tall"							"30"
						"Visible"						"1"
						"Enabled"						"1"
						"ProportionalToParent"			"1"
						"PaintBackground"				"0"

						"Pin_To_Sibling"				"Viewmodel_Flip"
						"Pin_Corner_To_Sibling"			"PIN_TOPLEFT"
						"Pin_To_Sibling_Corner"			"PIN_TOPRIGHT"

						"Setting_Label"
						{
							"ControlName"				"CExLabel"
							"FieldName"					"Setting_Label"
							"XPos"						"0"
							"YPos"						"0"
							"ZPos"						"1"
							"Wide"						"50"
							"Tall"						"20"
							"Visible"					"1"
							"Enabled"					"1"
							"MouseInputEnabled"			"0"
							"ProportionalToParent"		"1"
							"AllCaps"					"1"
							"Font"						"FontStoreOriginalPriceBold"
							"LabelText"					"#HudCustomization_Misc_Viewmodel_FOV"
							"TextAlignment"				"west"
							"FGColor"					"White"
						}
						"Setting_Slider"
						{
							"ControlName"				"CCvarSlider"
							"FieldName"					"Setting_Slider"
							"XPos"						"rs1"
							"YPos"						"0"
							"ZPos"						"2"
							"Wide"						"80"
							"Tall"						"30"
							"Visible"					"1"
							"Enabled"					"1"
							"ProportionalToParent"		"1"
							"minvalue"					"0"
							"maxvalue"					"120"
							"cvar_name"					"viewmodel_fov"
						}
					}
				}

//===============================================================================================================
// SPEEDOMETER
//===============================================================================================================
				"Speedometer_Icon"
				{
					"ControlName"						"CExLabel"
					"FieldName"							"Speedometer_Icon"
					"XPos"								"4"
					"YPos"								"280"
					"ZPos"								"0"
					"Wide"								"22"
					"Tall"								"25"
					"Visible"							"1"
					"Enabled"							"1"
					"ProportionalToParent"				"1"
					"LabelText"							"7"
					"Font"								"Symbols24"
					"TextAlignment"						"center"
					"FGColor"							"Gray"
				}
				"Speedometer_Label"
				{
					"ControlName"						"CExLabel"
					"FieldName"							"Speedometer_Label"
					"XPos"								"32"
					"YPos"								"280"
					"ZPos"								"0"
					"Wide"								"f25"
					"Tall"								"27"
					"Visible"							"1"
					"Enabled"							"1"
					"ProportionalToParent"				"1"
					"AllCaps"							"1"
					"LabelText"							"#HudCustomization_Misc_Speedometer"
					"Font"								"itemfontnamesmall"
					"TextAlignment"						"west"
					"FGColor"							"Gray"
				}
				"Separator_7"
				{
					"ControlName"						"EditablePanel"
					"FieldName"							"Separator_7"
					"XPos"								"3"
					"YPos"								"305"
					"ZPos"								"0"
					"Wide"								"f40"
					"Tall"								"2"
					"Visible"							"1"
					"Enabled"							"1"
					"ProportionalToParent"				"1"
					"paintBackground"					"1"
					"paintBackgroundtype"				"3"
					"BGcolor_Override"					"Background_Bright"
				}
// SPEEDOMETER STYLE ----------------------------------------------------------------------------------------
				"Speedometer_Style"
				{
					"ControlName"						"EditablePanel"
					"FieldName"							"Speedometer_Style"
					"XPos"								"4"
					"YPos"								"310"
					"ZPos"								"20"
					"Wide"								"f0"
					"Tall"								"60"
					"Visible"							"1"
					"Enabled"							"1"
					"ProportionalToParent"				"1"

					"Speedo_Disabled"
					{
						"ControlName"					"EditablePanel"
						"FieldName"						"Speedo_Disabled"
						"XPos"							"0"
						"YPos"							"2"
						"ZPos"							"1"
						"Wide"							"85"
						"Tall"							"40"
						"Visible"						"1"
						"Enabled"						"1"
						"ProportionalToParent"			"1"
						"PaintBackground"				"1"
						"BGcolor_Override"				"104 101 100 255"

						"Style_Name"
						{
							"ControlName"				"CExLabel"
							"FieldName"					"Style_Name"
							"XPos"						"cs-0.5"
							"YPos"						"rs1"
							"ZPos"						"1"
							"Wide"						"f0"
							"Tall"						"12"
							"Visible"					"1"
							"Enabled"					"1"
							"AllCaps"					"1"
							"MouseInputEnabled"			"0"
							"ProportionalToParent"		"1"
							"Font"						"FontStorePrice"
							"LabelText"					"#HudCustomization_Disable"
							"TextAlignment"				"center"
							"FGColor"					"Gray"
							"PaintBackground"			"1"
							"PaintBackgroundType"		"0"
							"BGColor_Override"			"Background_Darkest"
						}
						"Style_Image"
						{
							"ControlName"				"ImagePanel"
							"FieldName"					"Style_Image"
							"XPos"						"cs-0.5"
							"YPos"						"rs1-8"
							"ZPos"						"0"
							"Wide"						"72"
							"Tall"						"36"
							"Visible"					"0"
							"Enabled"					"1"
							"MouseInputEnabled"			"0"
							"ScaleImage"				"1"
							"ProportionalToParent"		"1"
							"Image"						"replay/thumbnails/customizations/speedometer/speedometer_absolute"
						}
						"Style_Name2"
						{
							"ControlName"				"CExLabel"
							"FieldName"					"Style_Name2"
							"XPos"						"cs-0.5"
							"YPos"						"0"
							"ZPos"						"1"
							"Wide"						"f0"
							"Tall"						"30"
							"Visible"					"1"
							"Enabled"					"1"
							"AllCaps"					"1"
							"MouseInputEnabled"			"0"
							"ProportionalToParent"		"1"
							"Font"						"HudFontMediumBigBold"
							"LabelText"					"670"
							"TextAlignment"				"center"
							"FGColor"					"white"
							"PaintBackground"			"0"
							"PaintBackgroundType"		"0"
							"BGColor_Override"			"Background_Darkest"
						}		
						"Style_Name3"
						{
							"ControlName"				"CExLabel"
							"FieldName"					"Style_Name3"
							"XPos"						"cs-0.5+2"
							"YPos"						"2"
							"ZPos"						"1"
							"Wide"						"f0"
							"Tall"						"30"
							"Visible"					"1"
							"Enabled"					"1"
							"AllCaps"					"1"
							"MouseInputEnabled"			"0"
							"ProportionalToParent"		"1"
							"Font"						"HudFontMediumBigBold"
							"LabelText"					"670"
							"TextAlignment"				"center"
							"FGColor"					"0 0 0 255"
							"PaintBackground"			"0"
							"PaintBackgroundType"		"0"
							"BGColor_Override"			"Background_Darkest"
						}															
						"Style_Disabled"
						{
							"ControlName"				"ImagePanel"
							"FieldName"					"Style_Disabled"
							"XPos"						"cs-0.5"
							"YPos"						"cs-0.5-6"
							"ZPos"						"300"
							"Wide"						"70"
							"Tall"						"24"
							"Visible"					"1"
							"Enabled"					"1"
							"MouseInputEnabled"			"0"
							"ProportionalToParent"		"1"
							"Image"						"replay/thumbnails/customizations/general/disabled_cross"
							"ScaleImage"				"1"
							"Drawcolor"					"Red"
							"Alpha"						"200"
						}
						"Style_Button"
						{
							"ControlName"				"CExButton"
							"FieldName"					"Style_Button"
							"XPos"						"0"
							"YPos"						"0"
							"ZPos"						"5"
							"Wide"						"f0"
							"Tall"						"f0"
							"Visible"					"1"
							"Enabled"					"1"
							"Font"						""
							"Command"					"engine m0_speedometer_clear"
							"LabelText"					""
							"Sound_Depressed"			"UI/buttonclick.wav"
							"ProportionalToParent"		"1"
							"ActionSignalLevel"			"6"

							"PaintBackground"			"0"
							"PaintBorder"				"1"

							"border_default"			"NoBorder"
							"border_armed"				"BorderSelectionGray"
						}
					}
					"Speedo_Absolute"
					{
						"ControlName"					"EditablePanel"
						"FieldName"						"Speedo_Absolute"
						"XPos"							"5"
						"YPos"							"0"
						"ZPos"							"1"
						"Wide"							"85"
						"Tall"							"40"
						"Visible"						"1"
						"Enabled"						"1"
						"ProportionalToParent"			"1"
						"PaintBackground"				"1"
						"BGcolor_Override"				"104 101 100 255"

						"Pin_To_Sibling"				"Speedo_Disabled"
						"Pin_Corner_To_Sibling"			"PIN_TOPLEFT"
						"Pin_To_Sibling_Corner"			"PIN_TOPRIGHT"

						"Style_Name"
						{
							"ControlName"				"CExLabel"
							"FieldName"					"Style_Name"
							"XPos"						"cs-0.5"
							"YPos"						"rs1"
							"ZPos"						"1"
							"Wide"						"f0"
							"Tall"						"12"
							"Visible"					"1"
							"Enabled"					"1"
							"AllCaps"					"1"
							"MouseInputEnabled"			"0"
							"ProportionalToParent"		"1"
							"Font"						"FontStorePrice"
							"LabelText"					"#HudCustomization_Enable"
							"TextAlignment"				"center"
							"FGColor"					"Gray"
							"PaintBackground"			"1"
							"PaintBackgroundType"		"0"
							"BGColor_Override"			"Background_Darkest"
						}
						"Style_Name2"
						{
							"ControlName"				"CExLabel"
							"FieldName"					"Style_Name2"
							"XPos"						"cs-0.5"
							"YPos"						"0"
							"ZPos"						"1"
							"Wide"						"f0"
							"Tall"						"30"
							"Visible"					"1"
							"Enabled"					"1"
							"AllCaps"					"1"
							"MouseInputEnabled"			"0"
							"ProportionalToParent"		"1"
							"Font"						"HudFontMediumBigBold"
							"LabelText"					"670"
							"TextAlignment"				"center"
							"FGColor"					"white"
							"PaintBackground"			"0"
							"PaintBackgroundType"		"0"
							"BGColor_Override"			"Background_Darkest"
						}	
						"Style_Name3"
						{
							"ControlName"				"CExLabel"
							"FieldName"					"Style_Name3"
							"XPos"						"cs-0.5+2"
							"YPos"						"2"
							"ZPos"						"1"
							"Wide"						"f0"
							"Tall"						"30"
							"Visible"					"1"
							"Enabled"					"1"
							"AllCaps"					"1"
							"MouseInputEnabled"			"0"
							"ProportionalToParent"		"1"
							"Font"						"HudFontMediumBigBold"
							"LabelText"					"670"
							"TextAlignment"				"center"
							"FGColor"					"0 0 0 255"
							"PaintBackground"			"0"
							"PaintBackgroundType"		"0"
							"BGColor_Override"			"Background_Darkest"
						}													
						"Style_Image"
						{
							"ControlName"				"ImagePanel"
							"FieldName"					"Style_Image"
							"XPos"						"cs-0.5"
							"YPos"						"rs1-8"
							"ZPos"						"0"
							"Wide"						"72"
							"Tall"						"36"
							"Visible"					"0"
							"Enabled"					"1"
							"MouseInputEnabled"			"0"
							"ScaleImage"				"1"
							"ProportionalToParent"		"1"
							"Image"						"replay/thumbnails/customizations/speedometer/speedometer_absolute"
						}
						"Style_Button"
						{
							"ControlName"				"CExButton"
							"FieldName"					"Style_Button"
							"XPos"						"0"
							"YPos"						"0"
							"ZPos"						"5"
							"Wide"						"f0"
							"Tall"						"f0"
							"Visible"					"1"
							"Enabled"					"1"
							"Font"						""
							"Command"					"engine m0_speedometer_absolute"
							"LabelText"					""
							"Sound_Depressed"			"UI/buttonclick.wav"
							"ProportionalToParent"		"1"
							"ActionSignalLevel"			"6"

							"PaintBackground"			"0"
							"PaintBorder"				"1"

							"border_default"			"NoBorder"
							"border_armed"				"BorderSelectionGray"
						}
					}
				}
//===============================================================================================================
// DISGUISE
//===============================================================================================================
				"Disguise_Icon"
				{
					"ControlName"						"CExLabel"
					"FieldName"							"Disguise_Icon"
					"XPos"								"4"
					"YPos"								"360"
					"ZPos"								"0"
					"Wide"								"22"
					"Tall"								"25"
					"Visible"							"1"
					"Enabled"							"1"
					"ProportionalToParent"				"1"
					"LabelText"							"i"
					"Font"								"Symbols24"
					"TextAlignment"						"center"
					"FGColor"							"Gray"
				}
				"Disguise_Label"
				{
					"ControlName"						"CExLabel"
					"FieldName"							"Disguise_Label"
					"XPos"								"32"
					"YPos"								"360"
					"ZPos"								"0"
					"Wide"								"f25"
					"Tall"								"27"
					"Visible"							"1"
					"Enabled"							"1"
					"ProportionalToParent"				"1"
					"AllCaps"							"1"
					"LabelText"							"#HudCustomization_Misc_Disguise"
					"Font"								"itemfontnamesmall"
					"TextAlignment"						"west"
					"FGColor"							"Gray"
				}
				"Separator_3"
				{
					"ControlName"						"EditablePanel"
					"FieldName"							"Separator_3"
					"XPos"								"3"
					"YPos"								"385"
					"ZPos"								"0"
					"Wide"								"f40"
					"Tall"								"2"
					"Visible"							"1"
					"Enabled"							"1"
					"ProportionalToParent"				"1"
					"paintBackground"					"1"
					"paintBackgroundtype"				"3"
					"BGcolor_Override"					"Background_Bright"
				}
// DISGUISE TOGGLE ----------------------------------------------------------------------------------------
				"Disguise_Toggle"
				{
					"ControlName"						"EditablePanel"
					"FieldName"							"Disguise_Toggle"
					"XPos"								"4"
					"YPos"								"390"
					"ZPos"								"20"
					"Wide"								"200"
					"Tall"								"100"
					"Visible"							"1"
					"Enabled"							"1"
					"ProportionalToParent"				"1"

					"Visibility_Label"
					{
						"ControlName"					"CExLabel"
						"FieldName"						"Visibility_Label"
						"XPos"							"0"
						"YPos"							"0"
						"ZPos"							"0"
						"Wide"							"f25"
						"Tall"							"15"
						"Visible"						"1"
						"Enabled"						"1"
						"ProportionalToParent"			"1"
						"AllCaps"						"1"
						"LabelText"						"#HudCustomization_Misc_Disguise_Alpha"
						"Font"							"HudFontSmallBold"
						"TextAlignment"					"west"
						"FGColor"						"Gray"
					}
					"Separator"
					{
						"ControlName"					"EditablePanel"
						"FieldName"						"Separator"
						"XPos"							"2"
						"YPos"							"1"
						"ZPos"							"0"
						"Wide"							"f15"
						"Tall"							"1"
						"Visible"						"1"
						"Enabled"						"1"
						"ProportionalToParent"			"1"
						"paintBackground"				"1"
						"paintBackgroundtype"			"3"
						"BGcolor_Override"				"Background_Bright"

						"Pin_To_Sibling"				"Visibility_Label"
						"Pin_Corner_To_Sibling"			"PIN_TOPLEFT"
						"Pin_To_Sibling_Corner"			"PIN_BOTTOMLEFT"
					}
					"Disguise_ON"
					{
						"ControlName"					"EditablePanel"
						"FieldName"						"Disguise_ON"
						"XPos"							"-2"
						"YPos"							"5"
						"ZPos"							"1"
						"Wide"							"80"
						"Tall"							"70"
						"Visible"						"1"
						"Enabled"						"1"
						"ProportionalToParent"			"1"
						"PaintBackground"				"1"
						"BGcolor_Override"				"104 101 100 255"

						"Pin_To_Sibling"				"Separator"
						"Pin_Corner_To_Sibling"			"PIN_TOPLEFT"
						"Pin_To_Sibling_Corner"			"PIN_BOTTOMLEFT"

						"Style_Name"
						{
							"ControlName"				"CExLabel"
							"FieldName"					"Style_Name"
							"XPos"						"cs-0.5"
							"YPos"						"rs1"
							"ZPos"						"1"
							"Wide"						"f0"
							"Tall"						"12"
							"Visible"					"1"
							"Enabled"					"1"
							"AllCaps"					"1"
							"MouseInputEnabled"			"0"
							"ProportionalToParent"		"1"
							"Font"						"FontStorePrice"
							"LabelText"					"#HudCustomization_Enable"
							"TextAlignment"				"center"
							"FGColor"					"Gray"
							"PaintBackground"			"1"
							"PaintBackgroundType"		"0"
							"BGColor_Override"			"Background_Darkest"
						}
						"Style_Image"
						{
							"ControlName"				"ImagePanel"
							"FieldName"					"Style_Image"
							"XPos"						"cs-0.5"
							"YPos"						"cs-0.5-5"
							"ZPos"						"0"
							"Wide"						"54"
							"Tall"						"54"
							"Visible"					"1"
							"Enabled"					"1"
							"MouseInputEnabled"			"0"
							"ScaleImage"				"1"
							"ProportionalToParent"		"1"
							"Image"						"../hud/class_spy_outline"
						}
						"Style_Button"
						{
							"ControlName"				"CExButton"
							"FieldName"					"Style_Button"
							"XPos"						"0"
							"YPos"						"0"
							"ZPos"						"5"
							"Wide"						"f0"
							"Tall"						"f0"
							"Visible"					"1"
							"Enabled"					"1"
							"Font"						""
							"Command"					"engine m0_disguise_anim_on"
							"LabelText"					""
							"Sound_Depressed"			"UI/buttonclick.wav"
							"ProportionalToParent"		"1"
							"ActionSignalLevel"			"6"

							"PaintBackground"			"0"
							"PaintBorder"				"1"

							"border_default"			"NoBorder"
							"border_armed"				"BorderSelectionGray"
						}
					}
					"Disguise_OFF"
					{
						"ControlName"					"EditablePanel"
						"FieldName"						"Disguise_OFF"
						"XPos"							"5"
						"YPos"							"0"
						"ZPos"							"1"
						"Wide"							"80"
						"Tall"							"70"
						"Visible"						"1"
						"Enabled"						"1"
						"ProportionalToParent"			"1"
						"PaintBackground"				"1"
						"BGcolor_Override"				"104 101 100 255"

						"Pin_To_Sibling"				"Disguise_ON"
						"Pin_Corner_To_Sibling"			"PIN_TOPLEFT"
						"Pin_To_Sibling_Corner"			"PIN_TOPRIGHT"

						"Style_Name"
						{
							"ControlName"				"CExLabel"
							"FieldName"					"Style_Name"
							"XPos"						"cs-0.5"
							"YPos"						"rs1"
							"ZPos"						"1"
							"Wide"						"f0"
							"Tall"						"12"
							"Visible"					"1"
							"Enabled"					"1"
							"AllCaps"					"1"
							"MouseInputEnabled"			"0"
							"ProportionalToParent"		"1"
							"Font"						"FontStorePrice"
							"LabelText"					"#HudCustomization_Disable"
							"TextAlignment"				"center"
							"FGColor"					"Gray"
							"PaintBackground"			"1"
							"PaintBackgroundType"		"0"
							"BGColor_Override"			"Background_Darkest"
						}
						"Style_Image"
						{
							"ControlName"				"ImagePanel"
							"FieldName"					"Style_Image"
							"XPos"						"cs-0.5"
							"YPos"						"cs-0.5-5"
							"ZPos"						"0"
							"Wide"						"54"
							"Tall"						"54"
							"Visible"					"1"
							"Enabled"					"1"
							"MouseInputEnabled"			"0"
							"ScaleImage"				"1"
							"ProportionalToParent"		"1"
							"Image"						"../hud/class_spy_outline"
						}
						"Style_Disabled"
						{
							"ControlName"				"ImagePanel"
							"FieldName"					"Style_Disabled"
							"XPos"						"cs-0.5"
							"YPos"						"cs-0.5-6"
							"ZPos"						"3"
							"Wide"						"72"
							"Tall"						"45"
							"Visible"					"1"
							"Enabled"					"1"
							"MouseInputEnabled"			"0"
							"ProportionalToParent"		"1"
							"Image"						"replay/thumbnails/customizations/general/disabled_cross"
							"ScaleImage"				"1"
							"Drawcolor"					"Red"
							"Alpha"						"200"
						}
						"Style_Button"
						{
							"ControlName"				"CExButton"
							"FieldName"					"Style_Button"
							"XPos"						"0"
							"YPos"						"0"
							"ZPos"						"5"
							"Wide"						"f0"
							"Tall"						"f0"
							"Visible"					"1"
							"Enabled"					"1"
							"Font"						""
							"Command"					"engine m0_disguise_anim_clear"
							"LabelText"					""
							"Sound_Depressed"			"UI/buttonclick.wav"
							"ProportionalToParent"		"1"
							"ActionSignalLevel"			"6"

							"PaintBackground"			"0"
							"PaintBorder"				"1"

							"border_default"			"NoBorder"
							"border_armed"				"BorderSelectionGray"
						}
					}
				}
// DISGUISE POSITIONING ----------------------------------------------------------------------------------------
				"Disguise_Positioning"
				{
					"ControlName"						"EditablePanel"
					"FieldName"							"Disguise_Positioning"
					"XPos"								"200"
					"YPos"								"318"
					"ZPos"								"20"
					"Wide"								"200"
					"Tall"								"100"
					"Visible"							"0"
					"Enabled"							"1"
					"ProportionalToParent"				"1"

					"Style_Label"
					{
						"ControlName"					"CExLabel"
						"FieldName"						"Style_Label"
						"XPos"							"0"
						"YPos"							"0"
						"ZPos"							"0"
						"Wide"							"f25"
						"Tall"							"15"
						"Visible"						"1"
						"Enabled"						"1"
						"ProportionalToParent"			"1"
						"AllCaps"						"1"
						"LabelText"						"#HudCustomization_Misc_Disguise_Position"
						"Font"							"HudFontSmallBold"
						"TextAlignment"					"west"
						"FGColor"						"Gray"
					}
					"Separator"
					{
						"ControlName"					"EditablePanel"
						"FieldName"						"Separator"
						"XPos"							"2"
						"YPos"							"1"
						"ZPos"							"0"
						"Wide"							"f15"
						"Tall"							"1"
						"Visible"						"1"
						"Enabled"						"1"
						"ProportionalToParent"			"1"
						"paintBackground"				"1"
						"paintBackgroundtype"			"3"
						"BGcolor_Override"				"Background_Bright"

						"Pin_To_Sibling"				"Style_Label"
						"Pin_Corner_To_Sibling"			"PIN_TOPLEFT"
						"Pin_To_Sibling_Corner"			"PIN_BOTTOMLEFT"
					}
					"Disguise_Center"
					{
						"ControlName"					"EditablePanel"
						"FieldName"						"Disguise_Center"
						"XPos"							"-2"
						"YPos"							"5"
						"ZPos"							"1"
						"Wide"							"80"
						"Tall"							"70"
						"Visible"						"1"
						"Enabled"						"1"
						"ProportionalToParent"			"1"
						"PaintBackground"				"1"
						"BGcolor_Override"				"104 101 100 255"

						"Pin_To_Sibling"				"Separator"
						"Pin_Corner_To_Sibling"			"PIN_TOPLEFT"
						"Pin_To_Sibling_Corner"			"PIN_BOTTOMLEFT"

						"Style_Name"
						{
							"ControlName"				"CExLabel"
							"FieldName"					"Style_Name"
							"XPos"						"cs-0.5"
							"YPos"						"rs1"
							"ZPos"						"1"
							"Wide"						"f0"
							"Tall"						"12"
							"Visible"					"1"
							"Enabled"					"1"
							"AllCaps"					"1"
							"MouseInputEnabled"			"0"
							"ProportionalToParent"		"1"
							"Font"						"FontStorePrice"
							"LabelText"					"#HudCustomization_Centered"
							"TextAlignment"				"center"
							"FGColor"					"Gray"
							"PaintBackground"			"1"
							"PaintBackgroundType"		"0"
							"BGColor_Override"			"Background_Darkest"
						}
						"Style_Image"
						{
							"ControlName"				"ImagePanel"
							"FieldName"					"Style_Image"
							"XPos"						"cs-0.5"
							"YPos"						"cs-0.5-5"
							"ZPos"						"0"
							"Wide"						"80"
							"Tall"						"80"
							"Visible"					"1"
							"Enabled"					"1"
							"MouseInputEnabled"			"0"
							"ScaleImage"				"1"
							"ProportionalToParent"		"1"
							"Image"						""
						}
						"Style_Button"
						{
							"ControlName"				"CExButton"
							"FieldName"					"Style_Button"
							"XPos"						"0"
							"YPos"						"0"
							"ZPos"						"5"
							"Wide"						"f0"
							"Tall"						"f0"
							"Visible"					"1"
							"Enabled"					"1"
							"Font"						""
							"Command"					"engine m0_disguise_pos_clear"
							"LabelText"					""
							"Sound_Depressed"			"UI/buttonclick.wav"
							"ProportionalToParent"		"1"
							"ActionSignalLevel"			"6"

							"PaintBackground"			"0"
							"PaintBorder"				"1"

							"border_default"			"NoBorder"
							"border_armed"				"BorderSelectionGray"
						}
					}
					"Disguise_Bottom"
					{
						"ControlName"					"EditablePanel"
						"FieldName"						"Disguise_Bottom"
						"XPos"							"5"
						"YPos"							"0"
						"ZPos"							"1"
						"Wide"							"80"
						"Tall"							"70"
						"Visible"						"1"
						"Enabled"						"1"
						"ProportionalToParent"			"1"
						"PaintBackground"				"1"
						"BGcolor_Override"				"104 101 100 255"

						"Pin_To_Sibling"				"Disguise_Center"
						"Pin_Corner_To_Sibling"			"PIN_TOPLEFT"
						"Pin_To_Sibling_Corner"			"PIN_TOPRIGHT"

						"Style_Name"
						{
							"ControlName"				"CExLabel"
							"FieldName"					"Style_Name"
							"XPos"						"cs-0.5"
							"YPos"						"rs1"
							"ZPos"						"1"
							"Wide"						"f0"
							"Tall"						"12"
							"Visible"					"1"
							"Enabled"					"1"
							"AllCaps"					"1"
							"MouseInputEnabled"			"0"
							"ProportionalToParent"		"1"
							"Font"						"FontStorePrice"
							"LabelText"					"#HudCustomization_Health_Style1"
							"TextAlignment"				"center"
							"FGColor"					"Gray"
							"PaintBackground"			"1"
							"PaintBackgroundType"		"0"
							"BGColor_Override"			"Background_Darkest"
						}
						"Style_Image"
						{
							"ControlName"				"ImagePanel"
							"FieldName"					"Style_Image"
							"XPos"						"cs-0.5+2"
							"YPos"						"rs1-12"
							"ZPos"						"0"
							"Wide"						"84"
							"Tall"						"84"
							"Visible"					"1"
							"Enabled"					"1"
							"MouseInputEnabled"			"0"
							"ScaleImage"				"1"
							"ProportionalToParent"		"1"
							"Image"						""
						}
						"Style_Button"
						{
							"ControlName"				"CExButton"
							"FieldName"					"Style_Button"
							"XPos"						"0"
							"YPos"						"0"
							"ZPos"						"5"
							"Wide"						"f0"
							"Tall"						"f0"
							"Visible"					"1"
							"Enabled"					"1"
							"Font"						""
							"Command"					"engine m0_disguise_bottom"
							"LabelText"					""
							"Sound_Depressed"			"UI/buttonclick.wav"
							"ProportionalToParent"		"1"
							"ActionSignalLevel"			"6"

							"PaintBackground"			"0"
							"PaintBorder"				"1"

							"border_default"			"NoBorder"
							"border_armed"				"BorderSelectionGray"
						}
					}
				}
			}
		}
	}
}