"resource\BaseActionSkipAheadDialog.res"
{
	"SkipAhead"
	{
		"ControlName"		"CBaseActionEditDialog"
		"fieldName"		"SkipAhead"
		"xpos"		"136"
		"ypos"		"261"
		"wide"		"400"
		"tall"		"300"
		//		"0"
		//		"0"
		"visible"		"1"
		"enabled"		"1"
		//		"0"
	}

	"OK"
	{
		"ControlName"		"Button"
		"fieldName"		"OK"
		"xpos"		"16"
		"ypos"		"146"
		"wide"		"64"
		"tall"		"24"
		//		"0"
		//		"0"
		"visible"		"1"
		"enabled"		"1"
		//		"0"
		"labelText"		"OK"
		"textAlignment"		"west"
		////		"0"
		////		"0"
		"Default"		"0"
		"command"		"OK"
	}
	"Cancel"
	{
		"ControlName"		"Button"
		"fieldName"		"Cancel"
		"xpos"		"86"
		"ypos"		"146"
		"wide"		"64"
		"tall"		"24"
		//		"0"
		//		"0"
		"visible"		"1"
		"enabled"		"1"
		//		"0"
		"labelText"		"Cancel"
		"textAlignment"		"west"
		////		"0"
		////		"0"
		"Default"		"0"
		"command"		"Cancel"
	}
	"actionname"
	{
		"ControlName"		"TextEntry"
		"fieldName"		"ActionName"
		"xpos"		"85"
		"ypos"		"37"
		"wide"		"251"
		"tall"		"24"
		//		"0"
		//		"0"
		"visible"		"1"
		"enabled"		"1"
		//		"0"
		"textHidden"		"0"
		"editable"		"1"
		"maxchars"		"-1"
	}
	"actionstart"
	{
		"ControlName"		"TextEntry"
		"fieldName"		"ActionStart"
		"xpos"		"233"
		"ypos"		"70"
		"wide"		"103"
		"tall"		"24"
		//		"0"
		//		"0"
		"visible"		"1"
		"enabled"		"1"
		//		"0"
		"textHidden"		"0"
		"editable"		"1"
		"maxchars"		"-1"
	}
	"ActionStartType"
	{
		"ControlName"		"ComboBox"
		"fieldName"		"ActionStartType"
		"xpos"		"84"
		"ypos"		"70"
		"wide"		"143"
		"tall"		"24"
		//		"0"
		//		"0"
		"visible"		"1"
		"enabled"		"1"
		//		"0"
		"textHidden"		"0"
		"editable"		"0"
		"maxchars"		"-1"
	}
	"ActionSkip"
	{
		"ControlName"		"TextEntry"
		"fieldName"		"ActionSkip"
		"xpos"		"233"
		"ypos"		"104"
		"wide"		"103"
		"tall"		"24"
		//		"0"
		//		"0"
		"visible"		"1"
		"enabled"		"1"
		//		"0"
		"textHidden"		"0"
		"editable"		"1"
		"maxchars"		"-1"
	}
	"ActionSkipType"
	{
		"ControlName"		"ComboBox"
		"fieldName"		"ActionSkipType"
		"xpos"		"83"
		"ypos"		"104"
		"wide"		"144"
		"tall"		"24"
		//		"0"
		//		"0"
		"visible"		"1"
		"enabled"		"1"
		//		"0"
		"textHidden"		"0"
		"editable"		"0"
		"maxchars"		"-1"
	}
	"Label1"
	{
		"ControlName"		"Label"
		"fieldName"		"Label1"
		"xpos"		"17"
		"ypos"		"37"
		"wide"		"64"
		"tall"		"24"
		//		"0"
		//		"0"
		"visible"		"1"
		"enabled"		"1"
		//		"0"
		"labelText"		"Name:"
		"textAlignment"		"west"
		////		"0"
		////		"0"
	}
	"Label2"
	{
		"ControlName"		"Label"
		"fieldName"		"Label2"
		"xpos"		"16"
		"ypos"		"70"
		"wide"		"64"
		"tall"		"24"
		//		"0"
		//		"0"
		"visible"		"1"
		"enabled"		"1"
		//		"0"
		"labelText"		"Start on:"
		"textAlignment"		"west"
		////		"0"
		////		"0"
	}
	"Label3"
	{
		"ControlName"		"Label"
		"fieldName"		"Label3"
		"xpos"		"17"
		"ypos"		"106"
		"wide"		"64"
		"tall"		"24"
		//		"0"
		//		"0"
		"visible"		"1"
		"enabled"		"1"
		//		"0"
		"labelText"		"Skip to:"
		"textAlignment"		"west"
		////		"0"
		////		"0"
	}
}
