"resource/BxRecordGame.res"
{
	"RecordGame"
	{
		"ControlName"		"CRecordDialog"
		"fieldName"		"RecordGame"
		"xpos"		"575"
		"ypos"		"382"
		"wide"		"480"
		"tall"		"270"
		//		"0"
		//		"0"
		"visible"		"1"
		"enabled"		"1"
		//		"0"
		"settitlebarvisible"		"1"
		"title"		"#Frame_Untitled"
	}

	"Record"
	{
		"ControlName"		"Button"
		"fieldName"		"Record"
		"xpos"		"100"
		"ypos"		"235"
		"wide"		"64"
		"tall"		"24"
		//		"0"
		//		"0"
		"visible"		"1"
		"enabled"		"1"
		//		"0"
		"labelText"		"Record"
		"textAlignment"		"west"
		////		"0"
		////		"0"
		//"wrap"		"0"
		"Command"		"RecordGame"
		"Default"		"0"
	}
	"Cancel"
	{
		"ControlName"		"Button"
		"fieldName"		"Cancel"
		"xpos"		"270"
		"ypos"		"235"
		"wide"		"64"
		"tall"		"24"
		//		"0"
		//		"0"
		"visible"		"1"
		"enabled"		"1"
		//		"0"
		"labelText"		"Cancel"
		"textAlignment"		"west"
		////		"0"
		////		"0"
		//"wrap"		"0"
		"Command"		"CancelRecord"
		"Default"		"0"
	}
	"ChooseDemLabel"
	{
		"ControlName"		"Label"
		"fieldName"		"ChooseDemLabel"
		"xpos"		"10"
		"ypos"		"25"
		"wide"		"80"
		"tall"		"24"
		//		"0"
		//		"0"
		"visible"		"1"
		"enabled"		"1"
		//		"0"
		"labelText"		"Choose Dem:"
		"textAlignment"		"west"
		////		"0"
		////		"0"
		//"wrap"		"0"
	}
	"ChooseDemText"
	{
		"ControlName"		"TextEntry"
		"fieldName"		"ChooseDemText"
		"xpos"		"75"
		"ypos"		"25"
		"wide"		"250"
		"tall"		"24"
		//		"0"
		//		"0"
		"visible"		"1"
		"enabled"		"1"
		//		"0"
		"textHidden"		"0"
		"editable"		"1"
		"maxchars"		"-1"
		"NumericInputOnly"		"0"
		"unicode"		"0"
	}
	"ChooseMapLabel"
	{
		"ControlName"		"Label"
		"fieldName"		"ChooseMapLabel"
		"xpos"		"10"
		"ypos"		"50"
		"wide"		"80"
		"tall"		"24"
		//		"0"
		//		"0"
		"visible"		"1"
		"enabled"		"1"
		//		"0"
		"labelText"		"Choose Map:"
		"textAlignment"		"west"
		////		"0"
		////		"0"
		//"wrap"		"0"
	}
	"ChooseMapText"
	{
		"ControlName"		"TextEntry"
		"fieldName"		"ChooseMapText"
		"xpos"		"75"
		"ypos"		"50"
		"wide"		"250"
		"tall"		"24"
		//		"0"
		//		"0"
		"visible"		"1"
		"enabled"		"1"
		//		"0"
		"textHidden"		"0"
		"editable"		"1"
		"maxchars"		"-1"
		"NumericInputOnly"		"0"
		"unicode"		"0"
	}
	"ChooseMapButton"
	{
		"ControlName"		"Button"
		"fieldName"		"ChooseMapButton"
		"xpos"		"336"
		"ypos"		"50"
		"wide"		"80"
		"tall"		"24"
		//		"0"
		//		"0"
		"visible"		"1"
		"enabled"		"1"
		//		"0"
		"labelText"		"Choose Map"
		"textAlignment"		"center"
		////		"0"
		////		"0"
		//"wrap"		"0"
		"Command"		"ChooseMap"
		"Default"		"0"
	}
	"RecordCameraPos"
	{
		"ControlName"		"CheckButton"
		"fieldName"		"RecordCameraPos"
		"xpos"		"10"
		"ypos"		"75"
		"wide"		"145"
		"tall"		"24"
		//		"0"
		//		"0"
		"visible"		"1"
		"enabled"		"1"
		//		"0"
		"labelText"		"Record Camera Position"
		"textAlignment"		"west"
		////		"0"
		////		"0"
		//"wrap"		"0"
		"Default"		"0"
		"selected"		"1"
	}
	"RecordCameraRot"
	{
		"ControlName"		"CheckButton"
		"fieldName"		"RecordCameraRot"
		"xpos"		"160"
		"ypos"		"75"
		"wide"		"145"
		"tall"		"24"
		//		"0"
		//		"0"
		"visible"		"1"
		"enabled"		"1"
		//		"0"
		"labelText"		"Record Camera Angles"
		"textAlignment"		"west"
		////		"0"
		////		"0"
		//"wrap"		"0"
		"Default"		"0"
		"selected"		"1"
	}
	"RecordCameraFOV"
	{
		"ControlName"		"CheckButton"
		"fieldName"		"RecordCameraFOV"
		"xpos"		"330"
		"ypos"		"75"
		"wide"		"140"
		"tall"		"24"
		//		"0"
		//		"0"
		"visible"		"1"
		"enabled"		"1"
		//		"0"
		"labelText"		"Record Camera FOV"
		"textAlignment"		"west"
		////		"0"
		////		"0"
		//"wrap"		"0"
		"Default"		"0"
		"selected"		"1"
	}
	"ViewPlayerCam"
	{
		"ControlName"		"CheckButton"
		"fieldName"		"ViewPlayerCam"
		"xpos"		"10"
		"ypos"		"100"
		"wide"		"145"
		"tall"		"24"
		//		"0"
		//		"0"
		"visible"		"1"
		"enabled"		"0"
		//		"0"
		"labelText"		"View From Player"
		"textAlignment"		"west"
		////		"0"
		////		"0"
		//"wrap"		"0"
		"Default"		"0"
		"selected"		"1"
	}
	"TeleportPlayer"
	{
		"ControlName"		"CheckButton"
		"fieldName"		"TeleportPlayer"
		"xpos"		"160"
		"ypos"		"100"
		"wide"		"175"
		"tall"		"24"
		//		"0"
		//		"0"
		"visible"		"1"
		"enabled"		"1"
		//		"0"
		"labelText"		"Snap Player To Tool Camera"
		"textAlignment"		"west"
		////		"0"
		////		"0"
		//"wrap"		"0"
		"Default"		"0"
		"selected"		"0"
	}
	"Noclip"
	{
		"ControlName"		"CheckButton"
		"fieldName"		"NoClip"
		"xpos"		"330"
		"ypos"		"100"
		"wide"		"100"
		"tall"		"24"
		//		"0"
		//		"0"
		"visible"		"1"
		"enabled"		"1"
		//		"0"
		"labelText"		"Enable noclip"
		"textAlignment"		"west"
		////		"0"
		////		"0"
		//"wrap"		"0"
		"Default"		"0"
		"selected"		"0"
	}
	"RecordWorld"
	{
		"ControlName"		"CheckButton"
		"fieldName"		"RecordWorld"
		"xpos"		"10"
		"ypos"		"125"
		"wide"		"120"
		"tall"		"24"
		//		"0"
		//		"0"
		"visible"		"1"
		"enabled"		"1"
		//		"0"
		"labelText"		"Record World"
		"textAlignment"		"west"
		////		"0"
		////		"0"
		//"wrap"		"0"
		"Default"		"0"
		"selected"		"1"
	}
	"RecordStationary"
	{
		"ControlName"		"CheckButton"
		"fieldName"		"RecordStationary"
		"xpos"		"160"
		"ypos"		"125"
		"wide"		"150"
		"tall"		"24"
		//		"0"
		//		"0"
		"visible"		"1"
		"enabled"		"1"
		//		"0"
		"labelText"		"Record Stationary Ents"
		"textAlignment"		"west"
		////		"0"
		////		"0"
		//"wrap"		"0"
		"Default"		"0"
		"selected"		"0"
	}
	"RecordSprites"
	{
		"ControlName"		"CheckButton"
		"fieldName"		"RecordSprites"
		"xpos"		"330"
		"ypos"		"125"
		"wide"		"150"
		"tall"		"24"
		//		"0"
		//		"0"
		"visible"		"1"
		"enabled"		"1"
		//		"0"
		"labelText"		"Record Sprites"
		"textAlignment"		"west"
		////		"0"
		////		"0"
		//"wrap"		"0"
		"Default"		"0"
		"selected"		"0"
	}
	"RecordSounds"
	{
		"ControlName"		"CheckButton"
		"fieldName"		"RecordSounds"
		"xpos"		"10"
		"ypos"		"150"
		"wide"		"120"
		"tall"		"24"
		//		"0"
		//		"0"
		"visible"		"1"
		"enabled"		"1"
		//		"0"
		"labelText"		"Record Sounds"
		"textAlignment"		"west"
		////		"0"
		////		"0"
		//"wrap"		"0"
		"Default"		"0"
		"selected"		"1"
	}
	"RecordNarration"
	{
		"ControlName"		"CheckButton"
		"fieldName"		"RecordNarration"
		"xpos"		"160"
		"ypos"		"150"
		"wide"		"130"
		"tall"		"24"
		//		"0"
		//		"0"
		"visible"		"1"
		"enabled"		"1"
		//		"0"
		"labelText"		"Record Narration"
		"textAlignment"		"west"
		////		"0"
		////		"0"
		//"wrap"		"0"
		"Default"		"0"
		"selected"		"0"
	}
	"RecordNarrationFromStart"
	{
		"ControlName"		"CheckButton"
		"fieldName"		"RecordNarrationFromStart"
		"xpos"		"330"
		"ypos"		"150"
		"wide"		"150"
		"tall"		"24"
		//		"0"
		//		"0"
		"visible"		"1"
		"enabled"		"0"
		//		"0"
		"labelText"		"From Start of Sequence"
		"textAlignment"		"west"
		////		"0"
		////		"0"
		//"wrap"		"0"
		"Default"		"0"
		"selected"		"0"
	}
	"SequenceLabel"
	{
		"ControlName"		"Label"
		"fieldName"		"SequenceLabel"
		"xpos"		"30"
		"ypos"		"175"
		"wide"		"119"
		"tall"		"24"
		//		"0"
		//		"0"
		"visible"		"1"
		"enabled"		"1"
		//		"0"
		"labelText"		"Sequence Name"
		"textAlignment"		"east"
		////		"0"
		////		"0"
		//"wrap"		"0"
	}
	"SequenceText"
	{
		"ControlName"		"TextEntry"
		"fieldName"		"SequenceText"
		"xpos"		"153"
		"ypos"		"175"
		"wide"		"200"
		"tall"		"24"
		//		"0"
		//		"0"
		"visible"		"1"
		"enabled"		"1"
		//		"0"
		"textHidden"		"0"
		"editable"		"1"
		"maxchars"		"-1"
		"NumericInputOnly"		"0"
		"unicode"		"0"
	}
	"ShotLabel"
	{
		"ControlName"		"Label"
		"fieldName"		"ShotLabel"
		"xpos"		"30"
		"ypos"		"200"
		"wide"		"119"
		"tall"		"24"
		//		"0"
		//		"0"
		"visible"		"1"
		"enabled"		"1"
		//		"0"
		"labelText"		"Shot Name"
		"textAlignment"		"east"
		////		"0"
		////		"0"
		//"wrap"		"0"
	}
	"ShotText"
	{
		"ControlName"		"TextEntry"
		"fieldName"		"ShotText"
		"xpos"		"153"
		"ypos"		"200"
		"wide"		"200"
		"tall"		"24"
		//		"0"
		//		"0"
		"visible"		"1"
		"enabled"		"1"
		//		"0"
		"textHidden"		"0"
		"editable"		"1"
		"maxchars"		"-1"
		"NumericInputOnly"		"0"
		"unicode"		"0"
	}
	"AssetPickerFrame"
	{
		"ControlName"		"CAssetPickerFrame"
		"fieldName"		"AssetPickerFrame"
		"xpos"		"147"
		"ypos"		"128"
		"wide"		"268"
		"tall"		"380"
		//		"0"
		//		"0"
		"visible"		"0"
		"enabled"		"1"
		//		"0"
		"settitlebarvisible"		"1"
		"title"		"#Frame_Untitled"
	}
}
