"Resource/CommentaryExplanationDialog.res"
{
	"CommentaryExplanationDialog"
	{
		"ControlName"		"CCommentaryExplanationDialog"
		"xpos"		"278"
		"ypos"		"357"
		"wide"		"400"
		"tall"		"330"
		//		"0"
		//		"0"
		//		"0"
		"title"		"#GameUI_CommentaryDialogTitle"
	}
	"CommentaryIsOn"
	{
		"ControlName"		"Label"
		"xpos"		"48"
		"ypos"		"44"
		"wide"		"320"
		"tall"		"24"
		//		"0"
		//		"0"
		//		"0"
		"labelText"		"#GAMEUI_Commentary_LabelOn"
	}
	"WhatIsCommentary"
	{
		"ControlName"		"Label"
		"xpos"		"48"
		"ypos"		"76"
		"wide"		"320"
		"tall"		"54"
		//		"0"
		//		"0"
		//		"0"
		"labelText"		"#GAMEUI_Commentary_WhatIs"
		"wrap"		"1"
	}
	"HowToUseCommentary"
	{
		"ControlName"		"Label"
		"xpos"		"48"
		"ypos"		"145"
		"wide"		"306"
		"tall"		"58"
		//		"0"
		//		"0"
		//		"0"
		"labelText"		"#GAMEUI_Commentary_HowToUse"
		"wrap"		"1"
	}
	"CommentaryGod"
	{
		"ControlName"		"Label"
		"xpos"		"48"
		"ypos"		"210"
		"wide"		"320"
		"tall"		"58"
		//		"0"
		//		"0"
		//		"0"
		"labelText"		"#GAMEUI_COMMENTARY_GOD"
		"wrap"		"1"
	}
	"OkClose"
	{
		"ControlName"		"Button"
		"xpos"		"162"
		"ypos"		"276"
		"wide"		"88"
		"tall"		"24"
		//		"0"
		//		"0"
		//		"0"
		"labelText"		"#vgui_ok"
		"Command"		"ok"
		"Default"		"1"
	}
	"Cancel"
	{
		"ControlName"		"Button"
		"xpos"		"276"
		"ypos"		"276"
		"wide"		"88"
		"tall"		"24"
		//		"0"
		//		"0"
		//		"0"
		"labelText"		"#vgui_cancel"
		"Command"		"cancel"
		"Default"		"1"
	}
}
