"Resource\ContentControlDialog.r"
{
	"ContentControlDialog"
	{
		"ControlName"		"Frame"
		"xpos"		"158"
		"ypos"		"197"
		"wide"		"328"
		"tall"		"250"
		//		"0"
		//		"0"
		//		"0"
	}
	"ContentStatus"
	{
		"ControlName"		"Label"
		"xpos"		"30"
		"ypos"		"30"
		"wide"		"280"
		"tall"		"28"
		//		"0"
		//		"0"
		//		"0"
		"labelText"	"#GameUI_ContentStatusDisabled"
	}
	"PasswordPrompt"
	{
		"ControlName"		"Label"
		"xpos"		"32"
		"ypos"		"68"
		"wide"		"166"
		"tall"		"28"
		//		"0"
		//		"0"
		//		"0"
		"labelText"		"#GameUI_PasswordPrompt"
	}
	"PasswordReentryPrompt"
	{
		"ControlName"		"Label"
		"xpos"		"32"
		"ypos"		"124"
		"wide"		"166"
		"tall"		"28"
		//		"0"
		//		"0"
		//		"0"
		"labelText"		"#GameUI_PasswordReentryPrompt"
	}
	"ContentControlExplain"
	{
		"ControlName"		"Label"
		"xpos"		"30"
		"ypos"		"182"
		"wide"		"272"
		"tall"		"28"
		//		"0"
		//		"0"
		//		"0"
		"labelText"		""
	}
	"Password"
	{
		"ControlName"		"TextEntry"
		"xpos"		"32"
		"ypos"		"98"
		"wide"		"166"
		"tall"		"24"
		//		"0"
		//		"0"
		//		"1"
		"textHidden"		"1"
		"editable"		"1"
		"maxchars"		"-1"
	}
	"Password2"
	{
		"ControlName"		"TextEntry"
		"xpos"		"32"
		"ypos"		"154"
		"wide"		"166"
		"tall"		"24"
		//		"0"
		//		"0"
		//		"2"
		"textHidden"		"1"
		"editable"		"1"
		"maxchars"		"-1"
	}
	"Ok"
	{
		"ControlName"		"Button"
		"xpos"		"184"
		"ypos"		"216"
		"wide"		"64"
		"tall"		"24"
		//		"0"
		//		"0"
		//		"3"
		"labelText"		"#GameUI_OK"
		"command"		"Ok"
		"default"		"1"
	}
	"Cancel"
	{
		"ControlName"		"Button"
		"xpos"		"256"
		"ypos"		"216"
		"wide"		"64"
		"tall"		"24"
		//		"0"
		//		"0"
		//		"4"
		"labelText"		"#GameUI_Cancel"
		"command"		"Cancel"
	}
	"BuildDialog"
	{
		"ControlName"		"BuildModeDialog"
		"xpos"		"504"
		"ypos"		"51"
		"wide"		"285"
		"tall"		"590"
		//		"0"
		//		"0"
		//		"0"
	}
}
