"//PLATFORM/resource/picker.res"
{
	"Picker"
	{
		"ControlName"	"CPicker"
		"fieldName"		"Picker"
		"xpos"			"147"
		"ypos"			"128"
		"wide"			"268"
		"tall"			"380"
		//	"0"
		//		"0"
		"visible"		"1"
		"enabled"		"1"
		//	"0"
		"settitlebarvisible"	"1"
		"title"		"#Frame_Untitled"
		
		"Browser"
		{
			"ControlName"	"ListPanel"
			"fieldName"		"Browser"
			"xpos"			"6"
			"ypos"			"6"
			"wide"			"256"
			"tall"			"212"
			//	"3"
			//		"0"
			//"PinnedCornerOffsetY" "-6"
			//"UnpinnedCornerOffsetY" "-34"
			"visible"		"1"
			"enabled"		"1"
			//	"1"
		}
		
		"FilterLabel"
		{
			"ControlName"	"Label"
			"fieldName"		"FilterLabel"
			"xpos"			"6"
			"ypos"			"210"
			"wide"			"75"
			"tall"			"24"
			//	"0"
			//		"2"
			//"PinnedCornerOffsetX" "6"
			//"PinnedCornerOffsetY" "-6"
			"visible"		"1"
			"enabled"		"1"
			//	"0"
			"labelText"		"Filter"
			"textAlignment"	"east"
			"dulltext"		"1"
			
		}
		
		"FilterList"
		{
			"ControlName"	"TextEntry"
			"fieldName"		"FilterList"
			"xpos"			"70"
			"ypos"			"210"
			"wide"			"256"
			"tall"			"24"
			//	"1"
			//		"2"
			//"PinnedCornerOffsetX" "85"
			//"PinnedCornerOffsetY" "-6"
			//"PinnedCornerOffsetY" "-6"
			"visible"		"1"
			"enabled"		"1"
			//	"2"
			"textHidden"	"0"
			"editable"		"1"
			"maxchars"		"-1"
			"NumericInputOnly"		"0"
			"unicode"		"0"
		}
	}
}
