"//PLATFORM/resource/presetremappanel.res"
{
	"DmePresetRemapPanel"
	{
		"ControlName"	"CDmePresetRemapPanel"
		"fieldName"		"DmePresetRemapPanel"
		"xpos"			"147"
		"ypos"			"128"
		"wide"			"368"
		"tall"			"380"
		//	"0"
		//		"0"
		"visible"		"1"
		"enabled"		"1"
		//	"0"
		"settitlebarvisible"	"1"
		"title"		"Select Presets"
		
		"SourcePresetGroupLabel"
		{
			"ControlName"		"Label"
			"fieldName"		"SourcePresetGroupLabel"
			"xpos"		"6"
			"ypos"		"32"
			"wide"		"110"
			"tall"		"24"
			//		"0"
			//		"0"
			"visible"		"1"
			"enabled"		"1"
			//		"0"
			"labelText"		"Source Preset Group:"
			"textAlignment"		"east"
			//"dulltext"		"0"
			//"brighttext"		"0"
			//"wrap"		"0"
		}
		"SourcePresetGroup"
		{
			"ControlName"		"ComboBox"
			"fieldName"		"SourcePresetGroup"
			"xpos"		"120"
			"ypos"		"32"
			"wide"		"242"
			"tall"		"24"
			//"PinnedCornerOffsetX" "120"
			//"PinnedCornerOffsetY" "-6"
			//		"1"
			//		"0"
			"visible"		"1"
			"enabled"		"1"
			//		"0"
			"textHidden"		"0"
			"editable"		"0"
			"maxchars"		"-1"
			"NumericInputOnly"		"0"
			"unicode"		"0"
		}

		"OkButton"
		{
			"ControlName"		"Button"
			"fieldName"		"OkButton"
			"xpos"		"6"
			"ypos"		"350"
			"wide"		"122"
			"tall"		"24"
			//		"0"
			//		"2"
			"visible"		"1"
			"enabled"		"1"
			//		"2"
			"labelText"		"Ok"
			"command"		"ok"
			"textAlignment"		"center"
			//"dulltext"		"0"
			//"brighttext"		"0"
			"Default"		"1"
		}

		"CancelButton"
		{
			"ControlName"		"Button"
			"fieldName"		"CancelButton"
			"xpos"		"140"
			"ypos"		"350"
			"wide"		"122"
			"tall"		"24"
			//	"0"
			//		"2"
			"visible"		"1"
			"enabled"		"1"
			//	"3"
			"labelText"		"Cancel"
			"command"		"Cancel"
			"textAlignment"	"center"
			//"dulltext"		"0"
			//"brighttext"		"0"
			"Default"		"0"
		}
		
		"PresetRemapList"
		{
			"ControlName"	"ListPanel"
			"fieldName"		"PresetRemapList"
			"xpos"			"6"
			"ypos"			"60"
			"wide"			"356"
			"tall"			"284"
			//	"3"
			//		"0"
			//"PinnedCornerOffsetX" "6"
			//"PinnedCornerOffsetY" "60"
			//"PinnedCornerOffsetY" "-6"
			//"UnpinnedCornerOffsetY" "-36"
			"visible"		"1"
			"enabled"		"1"
			//	"1"
		}
	}
}
