"resource/sfm_setprogressiverefinementdialog.res"
{
	"ProgressiveRefinementSettings"
	{
		"ControlName"		"CSetProgressiveRefinementDialog"
		"fieldName"		"ProgressiveRefinementSettings"
		"xpos"		"635"
		"ypos"		"427"
		"wide"		"350"
		"tall"		"170"
		//		"0"
		//		"0"
		"visible"		"1"
		"enabled"		"1"
		//		"0"
		"settitlebarvisible"		"1"
		"title"		"#SFM_Progressive_Refinement_Settings"
	}

	"OkButton"
	{
		"ControlName"		"Button"
		"fieldName"		"OkButton"
		"xpos"		"90"
		"ypos"		"132"
		"wide"		"64"
		"tall"		"24"
		//		"0"
		//		"0"
		"visible"		"1"
		"enabled"		"1"
		//		"7"
		"labelText"		"#vgui_ok"
		"textAlignment"		"west"
		////		"0"
		////		"0"
		//"wrap"		"0"
		"Command"		"Ok"
		"Default"		"0"
	}
	"CancelButton"
	{
		"ControlName"		"Button"
		"fieldName"		"CancelButton"
		"xpos"		"180"
		"ypos"		"132"
		"wide"		"64"
		"tall"		"24"
		//		"0"
		//		"0"
		"visible"		"1"
		"enabled"		"1"
		//		"8"
		"labelText"		"#vgui_Cancel"
		"textAlignment"		"west"
		////		"0"
		////		"0"
		//"wrap"		"0"
		"Command"		"Cancel"
		"Default"		"0"
	}
	"ProgressiveRefinementEnabled"
	{
		"ControlName"		"CheckButton"
		"fieldName"		"ProgressiveRefinementEnabled"
		"xpos"		"10"
		"ypos"		"29"
		"wide"		"150"
		"tall"		"24"
		//		"0"
		//		"0"
		"visible"		"1"
		"enabled"		"1"
		//		"1"
		"labelText"		"Progressive Refinement"
		"textAlignment"		"west"
		////		"0"
		////		"0"
		//"wrap"		"0"
		"Default"		"0"
	}
	"DoFEnabled"
	{
		"ControlName"		"CheckButton"
		"fieldName"		"DoFEnabled"
		"xpos"		"30"
		"ypos"		"53"
		"wide"		"110"
		"tall"		"24"
		//		"0"
		//		"0"
		"visible"		"1"
		"enabled"		"1"
		//		"2"
		"labelText"		"Depth of Field"
		"textAlignment"		"west"
		////		"0"
		////		"0"
		//"wrap"		"0"
		"Default"		"0"
	}
	"DoFQualityLabel"
	{
		"ControlName"		"Label"
		"fieldName"		"DoFQualityLabel"
		"xpos"		"150"
		"ypos"		"53"
		"wide"		"60"
		"tall"		"24"
		//		"0"
		//		"0"
		"visible"		"1"
		"enabled"		"1"
		//		"0"
		"labelText"		"# Samples:"
		"textAlignment"		"west"
		////		"0"
		////		"0"
		//"wrap"		"0"
	}
	"DoFQuality"
	{
		"ControlName"		"ComboBox"
		"fieldName"		"DoFQuality"
		"xpos"		"210"
		"ypos"		"53"
		"wide"		"120"
		"tall"		"24"
		//		"0"
		//		"0"
		"visible"		"1"
		"enabled"		"1"
		//		"3"
		"textHidden"		"0"
		"editable"		"0"
		"maxchars"		"-1"
		"NumericInputOnly"		"0"
		"unicode"		"0"
	}
	"MotionBlurEnabled"
	{
		"ControlName"		"CheckButton"
		"fieldName"		"MotionBlurEnabled"
		"xpos"		"30"
		"ypos"		"77"
		"wide"		"110"
		"tall"		"24"
		//		"0"
		//		"0"
		"visible"		"1"
		"enabled"		"1"
		//		"4"
		"labelText"		"Motion Blur"
		"textAlignment"		"west"
		////		"0"
		////		"0"
		//"wrap"		"0"
		"Default"		"0"
	}
	"MotionBlurQualityLabel"
	{
		"ControlName"		"Label"
		"fieldName"		"MotionBlurQualityLabel"
		"xpos"		"150"
		"ypos"		"77"
		"wide"		"60"
		"tall"		"24"
		//		"0"
		//		"0"
		"visible"		"1"
		"enabled"		"1"
		//		"0"
		"labelText"		"# Samples:"
		"textAlignment"		"west"
		////		"0"
		////		"0"
		//"wrap"		"0"
	}
	"MotionBlurQuality"
	{
		"ControlName"		"ComboBox"
		"fieldName"		"MotionBlurQuality"
		"xpos"		"210"
		"ypos"		"77"
		"wide"		"120"
		"tall"		"24"
		//		"0"
		//		"0"
		"visible"		"1"
		"enabled"		"1"
		//		"5"
		"textHidden"		"0"
		"editable"		"0"
		"maxchars"		"-1"
		"NumericInputOnly"		"0"
		"unicode"		"0"
	}
	"AntialiasingEnabled"
	{
		"ControlName"		"CheckButton"
		"fieldName"		"AntialiasingEnabled"
		"xpos"		"30"
		"ypos"		"101"
		"wide"		"150"
		"tall"		"24"
		//		"0"
		//		"0"
		"visible"		"1"
		"enabled"		"1"
		//		"6"
		"labelText"		"Subpixel Jitter AA"
		"textAlignment"		"west"
		////		"0"
		////		"0"
		//"wrap"		"0"
		"Default"		"0"
	}
}
