"resource/IFM_AnimationSetPickerFame.res"
{
	"AnimationSetPickerFrame"
	{
		"ControlName"		"CAnimationSetPickerFrame"
		"fieldName"		"AnimationSetPickerFrame"
		"xpos"		"350"
		"ypos"		"200"
		"wide"		"400"
		"tall"		"420"
		//		"0"
		//		"0"
		"visible"		"1"
		"enabled"		"1"
		//		"0"
		"settitlebarvisible"		"1"
		"title"		"#BxAnimationSetChooser"
	}

	"AnimationSetPicker"
	{
		"ControlName"		"CAnimationSetPicker"
		"fieldName"		"AnimationSetPicker"
		"xpos"		"5"
		"ypos"		"29"
		"wide"		"390"
		"tall"		"340"
		//		"3"
		//		"0"
		"visible"		"1"
		"enabled"		"1"
		//		"0"
	}
	"OpenButton"
	{
		"ControlName"		"Button"
		"fieldName"		"OpenButton"
		"xpos"		"135"
		"ypos"		"383"
		"wide"		"64"
		"tall"		"24"
		//		"0"
		//		"2"
		"visible"		"1"
		"enabled"		"1"
		//		"0"
		"labelText"		"#FileOpenDialog_Open"
		"textAlignment"		"west"
		////		"0"
		////		"0"
		//"wrap"		"0"
		"Command"		"Open"
		"Default"		"0"
		"selected"		"0"
	}
	"CancelButton"
	{
		"ControlName"		"Button"
		"fieldName"		"CancelButton"
		"xpos"		"207"
		"ypos"		"383"
		"wide"		"64"
		"tall"		"24"
		//		"0"
		//		"2"
		"visible"		"1"
		"enabled"		"1"
		//		"0"
		"labelText"		"#FileOpenDialog_Cancel"
		"textAlignment"		"west"
		////		"0"
		////		"0"
		//"wrap"		"0"
		"Command"		"Cancel"
		"Default"		"1"
		"selected"		"0"
	}
}
