"resource/SkillSelectionDialog.res"
{
	"SkillSelection"
	{
		"ControlName"		"CSkillSelectionDialog"
		"fieldName"		"SkillSelection"
		"xpos"		"388"
		"ypos"		"200"
		"wide"		"248"
		"tall"		"180"
		//		"0"
		//		"0"
		//		"0"
	}
	"EasyRadio"
	{
		"ControlName"		"RadioButton"
		"fieldName"		"EasyRadio"
		"xpos"		"52"
		"ypos"		"42"
		"wide"		"120"
		"tall"		"24"
		//		"0"
		//		"0"
		//		"1"
		"labelText"		"#GameUI_Easy"
		////		"0"
		////		"0"
		//"wrap"		"0"
		"SubTabPosition"		"1"
	}
	"MediumRadio"
	{
		"ControlName"		"RadioButton"
		"fieldName"		"MediumRadio"
		"xpos"		"52"
		"ypos"		"68"
		"wide"		"120"
		"tall"		"24"
		//		"0"
		//		"0"
		//		"1"
		"labelText"		"#GameUI_Medium"
		////		"0"
		////		"0"
		//"wrap"		"0"
		"SubTabPosition"		"2"
	}
	"HardRadio"
	{
		"ControlName"		"RadioButton"
		"fieldName"		"HardRadio"
		"xpos"		"52"
		"ypos"		"94"
		"wide"		"120"
		"tall"		"24"
		//		"0"
		//		"0"
		//		"1"
		"labelText"		"#GameUI_Hard"
		////		"0"
		////		"0"
		//"wrap"		"0"
		"SubTabPosition"		"3"
	}
	"CancelButton"
	{
		"ControlName"		"Button"
		"fieldName"		"CancelButton"
		"xpos"		"142"
		"ypos"		"132"
		"wide"		"80"
		"tall"		"24"
		//		"0"
		//		"0"
		//		"3"
		"labelText"		"#GameUI_Cancel"
		////		"0"
		////		"0"
		//"wrap"		"0"
		"Command"		"Close"
	}
	"StartButton"
	{
		"ControlName"		"Button"
		"fieldName"		"StartButton"
		"xpos"		"52"
		"ypos"		"132"
		"wide"		"80"
		"tall"		"24"
		//		"0"
		//		"0"
		//		"2"
		"labelText"		"#GameUI_Start"
		////		"0"
		////		"0"
		//"wrap"		"0"
		"Command"		"Play"
	}
}
