"//PLATFORM/resource/soundpickerwavpage.res"
{
	"WavPage"
	{
		"ControlName"	"PropertyPage"
		"fieldName"		"WavPage"
		"xpos"			"6"
		"ypos"			"6"
		"wide"			"256"
		"tall"			"256"
		//	"3"
		//		"0"
		//"PinnedCornerOffsetX" "6"
		//"PinnedCornerOffsetY" "6"
		//"PinnedCornerOffsetY" "-6"
		//"UnpinnedCornerOffsetY" "-6"
		"visible"		"1"
		"enabled"		"1"
		//	"0"
		
		"AssetSplitter"
		{
			"ControlName"	"Splitter"
			"fieldName"		"AssetSplitter"
			"visible"		"1"
			"enabled"		"1"
			//		"0"
			//	"3"
			//"PinnedCornerOffsetX" "0"
			//"PinnedCornerOffsetX" "0"
			//"PinnedCornerOffsetY" "0"
			//"UnpinnedCornerOffsetY" "0"
					
			"child0"
			{
				"ModFilterLabel"
				{
					"ControlName"	"Label"
					"fieldName"		"ModFilterLabel"
					"xpos"			"6"
					"ypos"			"6"
					"wide"			"65"
					"tall"			"24"
					//	"0"
					//		"0"
					//"PinnedCornerOffsetX" "6"
					"visible"		"1"
					"enabled"		"1"
					//	"0"
					"labelText"		"Mod Filter"
					"textAlignment"	"east"
					"dulltext"		"1"
					
				}
				
				"ModFilter"
				{
					"ControlName"	"ComboBox"
					"fieldName"		"ModFilter"
					"xpos"			"75"
					"ypos"			"6"
					"wide"			"256"
					"tall"			"24"
					//	"1"
					//		"0"
					//"PinnedCornerOffsetX" "75"
					//"PinnedCornerOffsetY" "-70"
					"visible"		"1"
					"enabled"		"1"
					//	"0"
					"textHidden"	"0"
					"editable"		"0"
					"maxchars"		"-1"
					"NumericInputOnly"		"0"
					"unicode"		"0"
				}

				"RescanButton"
				{
					"ControlName"	"Button"
					"fieldName"		"RescanButton"
					"xpos"			"212"
					"ypos"			"6"
					"wide"			"60"
					"tall"			"24"
					//"PinnedCornerOffsetX" "-6"
					//	"0"
					//		"1"
					"labelText"		"#AssetPicker_Rescan"
					"textAlignment"	"center"
					"visible"		"1"
					"enabled"		"1"
					//	"0"
					"textHidden"	"0"
					"Default"		"0"
					"command"		"AssetRescan"
				}
		
				"FolderFilter"
				{
					"ControlName"	"CAssetTreeView"
					"fieldName"		"FolderFilter"
					"xpos"			"6"
					"ypos"			"36"
					"wide"			"65"
					"tall"			"24"
					//	"3"
					//		"0"
					//"PinnedCornerOffsetY" "-6"
					//"UnpinnedCornerOffsetY" "-6"
					"visible"		"1"
					"enabled"		"1"
					//	"0"
				}						
			}

			"child1"
			{
				"AssetBrowser"
				{
					"ControlName"	"ListPanel"
					"fieldName"		"AssetBrowser"
					"xpos"			"6"
					"ypos"			"6"
					"wide"			"256"
					"tall"			"212"
					//	"3"
					//		"0"
					//"PinnedCornerOffsetY" "-6"
					//"UnpinnedCornerOffsetY" "-64"
					"visible"		"1"
					"enabled"		"1"
					//	"1"
				}
				
				"FullPathLabel"
				{
					"ControlName"	"Label"
					"fieldName"		"FullPathLabel"
					"xpos"			"6"
					"ypos"			"210"
					"wide"			"65"
					"tall"			"24"
					//	"0"
					//		"2"
					//"PinnedCornerOffsetX" "6"
					//"PinnedCornerOffsetY" "-34"
					"visible"		"1"
					"enabled"		"1"
					//	"0"
					"labelText"		"Full Path"
					"textAlignment"	"east"
					"dulltext"		"1"
					
				}
								
				"FullPath"
				{
					"ControlName"	"TextEntry"
					"fieldName"		"FullPath"
					"xpos"			"6"
					"ypos"			"210"
					"wide"			"75"
					"tall"			"24"
					//	"1"
					//		"2"
					//"PinnedCornerOffsetX" "75"
					//"PinnedCornerOffsetY" "-34"
					//"PinnedCornerOffsetY" "-6"
					"visible"		"1"
					"enabled"		"0"
					"editable"		"0"
					//	"0"
					"labelText"		""
					"textAlignment"	"west"
					"dulltext"		"1"
					
				}
					
				"FilterLabel"
				{
					"ControlName"	"Label"
					"fieldName"		"FilterLabel"
					"xpos"			"6"
					"ypos"			"210"
					"wide"			"65"
					"tall"			"24"
					//	"0"
					//		"2"
					//"PinnedCornerOffsetX" "6"
					//"PinnedCornerOffsetY" "-6"
					"visible"		"1"
					"enabled"		"1"
					//	"2"
					"labelText"		"Filter"
					"textAlignment"	"east"
					"dulltext"		"1"
					
				}
				
				"FilterList"
				{
					"ControlName"	"TextEntry"
					"fieldName"		"FilterList"
					"xpos"			"70"
					"ypos"			"210"
					"wide"			"256"
					"tall"			"24"
					//	"1"
					//		"2"
					//"PinnedCornerOffsetX" "75"
					//"PinnedCornerOffsetY" "-6"
					//"PinnedCornerOffsetY" "-6"
					"visible"		"1"
					"enabled"		"1"
					//	"2"
					"textHidden"	"0"
					"editable"		"1"
					"maxchars"		"-1"
					"NumericInputOnly"		"0"
					"unicode"		"0"
				}
			}
		}	
	}
}
