#base "../_jofrenew/ui_overrides/system-tray-icon/file.res"
#base "../_jofrenew/ui_overrides/net_font/file.res"
#base "../_jofrenew/resource/sourcescheme.res"
#base "../_jofrehud/resource/sourcescheme.res"
#base "../_jofrehud/_tf2exp/sourcescheme.res"
#base "../_jofrehud/_tf2exp/sourceschemebase.res"
