"resource/ToolPerforceQuery.res"
{
	"PerforceQuery"
	{
		"ControlName"		"CPerforceQuery"
		"fieldName"		"PerforceQuery"
		"xpos"		"362"
		"ypos"		"324"
		"wide"		"500"
		"tall"		"120"
		//		"0"
		//		"0"
		"visible"		"1"
		"enabled"		"1"
		//		"0"
		"settitlebarvisible"		"1"
		"title"		"#ToolSaveChanges"
	}
	"PerforceLabel"
	{
		"ControlName"		"Label"
		"fieldName"		"PerforceLabel"
		"xpos"		"17"
		"ypos"		"30"
		"wide"		"464"
		"tall"		"30"
		//		"0"
		//		"0"
		"visible"		"1"
		"enabled"		"1"
		//		"0"
		"labelText"		"Open for edit?"
		"textAlignment"		"center"
		////		"0"
		////		"0"
		//"wrap"		"0"
	}
	"FileNameLabel"
	{
		"ControlName"		"Label"
		"fieldName"		"FileNameLabel"
		"xpos"		"17"
		"ypos"		"46"
		"wide"		"464"
		"tall"		"24"
		//		"0"
		//		"0"
		"visible"		"1"
		"enabled"		"1"
		//		"0"
		"labelText"		""
		"textAlignment"		"center"
		////		"0"
		////		"0"
		//"wrap"		"0"
		"font" "defaultverysmall"
	}
	"Yes"
	{
		"ControlName"		"Button"
		"fieldName"		"Yes"
		"xpos"		"128"
		"ypos"		"80"
		"wide"		"64"
		"tall"		"24"
		//		"0"
		//		"0"
		"visible"		"1"
		"enabled"		"1"
		//		"0"
		"labelText"		"Yes"
		"textAlignment"		"center"
		////		"0"
		////		"0"
		//"wrap"		"0"
		"Command"		"yes"
		"Default"		"1"
	}
	"No"
	{
		"ControlName"		"Button"
		"fieldName"		"No"
		"xpos"		"292"
		"ypos"		"80"
		"wide"		"64"
		"tall"		"24"
		//		"0"
		//		"0"
		"visible"		"1"
		"enabled"		"1"
		//		"0"
		"labelText"		"No"
		"textAlignment"		"center"
		////		"0"
		////		"0"
		//"wrap"		"0"
		"Command"		"no"
		"Default"		"0"
	}
}
