@echo off
TITLE Localization Copier

echo Copying localization
copy "vgui_english.txt" "vgui_brazilian.txt"

copy "vgui_english.txt" "vgui_bulgarian.txt"
copy "vgui_english.txt" "vgui_czech.txt"
copy "vgui_english.txt" "vgui_danish.txt"
copy "vgui_english.txt" "vgui_dutch.txt"
copy "vgui_english.txt" "vgui_finnish.txt"
copy "vgui_english.txt" "vgui_french.txt"
copy "vgui_english.txt" "vgui_german.txt"
copy "vgui_english.txt" "vgui_greek.txt"
copy "vgui_english.txt" "vgui_hungarian.txt"
copy "vgui_english.txt" "vgui_italian.txt"
copy "vgui_english.txt" "vgui_japanese.txt"
copy "vgui_english.txt" "vgui_korean.txt"
copy "vgui_english.txt" "vgui_koreana.txt"
copy "vgui_english.txt" "vgui_norwegian.txt"
copy "vgui_english.txt" "vgui_polish.txt"
copy "vgui_english.txt" "vgui_portuguese.txt"
copy "vgui_english.txt" "vgui_romanian.txt"
copy "vgui_english.txt" "vgui_russian.txt"
copy "vgui_english.txt" "vgui_schinese.txt"
copy "vgui_english.txt" "vgui_spanish.txt"
copy "vgui_english.txt" "vgui_swedish.txt"
copy "vgui_english.txt" "vgui_tchinese.txt"
copy "vgui_english.txt" "vgui_thai.txt"
copy "vgui_english.txt" "vgui_turkish.txt"
copy "vgui_english.txt" "vgui_latam.txt"
copy "vgui_english.txt" "vgui_vietnamese.txt"
copy "vgui_english.txt" "vgui_ukrainian.txt"