#base "base/okbutton.res"
#base "../#uni_base/filesv1/cancelbutton/main.res"
#base "../#uni_base/filesv1/cancelbutton/text/west.res"
#base "../#uni_base/filesv1/cancelbutton/def0.res"
#base "../#uni_base/filesv1/cancelbutton/ctrl/btn.res"
#base "../#uni_base/filesv1/cancelbutton/autoresize_pin.res"
#base "../#uni_base/filesv1/cancelbutton/vis1.res"
#base "../#uni_base/filesv1/cancelbutton/wrap0.res"
#base "../#uni_base/filesv1/cancelbutton/tab4.res"
#base "../#uni_base/filesv1/cancelbutton/paintbg_1.res"
#base "../#uni_base/filesv1/cancelbutton/cmd/close.res"
#base "../#uni_base/filesv1/cancelbutton/position/w64.res"
#base "../#uni_base/filesv1/cancelbutton/position/t24.res"
#base "base/gametabs.res"
#base "base/infolabel_main.res"
#base "base/l-serverbrowser.res"
"huhd.res"
{
	"InfoLabel"
	{
		"xpos"		"22"
		"ypos"		"46"
		"wide"		"330"
		"tall"		"20"
	}
}	