"Resource/UI/huditemeffectmeter.res"
{
"ItemEffectMeterBG"
{
"ControlName""CTFImagePanel"
"fieldName""ItemEffectMeterBG"
////"xpos""0"
//"ypos""0"
////"zpos""0"
//"wide""0"
//"tall""0"
//"visible""0"
//"enabled""0"
//"image""../hud/misc_ammo_area_horiz1_blue"
"scaleImage""1"
//"teambg_2""../hud/misc_ammo_area_horiz1_red"
//"teambg_3""../hud/misc_ammo_area_horiz1_blue"
}
}
