"Friends/DialogAbout.res"
{
	"DialogAbout"
	{
		"ControlName"		"Frame"
		"fieldName"		"DialogAbout"
		"xpos"		"452"
		"ypos"		"331"
		"wide"		"374"
		"tall"		"243"
		//		"0"
		//		"0"
		"visible"		"1"
		"enabled"		"1"
		//		"0"
	}
	"SysMenu"
	{
		"ControlName"		"Menu"
		"fieldName"		"SysMenu"
		"xpos"		"0"
		"ypos"		"0"
		"wide"		"64"
		"tall"		"24"
		//		"0"
		//		"0"
		"visible"		"0"
		"enabled"		"1"
		//		"0"
	}
	"CloseButton"
	{
		"ControlName"		"Button"
		"fieldName"		"CloseButton"
		"xpos"		"300"
		"ypos"		"203"
		"wide"		"64"
		"tall"		"24"
		//		"0"
		//		"3"
		"visible"		"1"
		"enabled"		"1"
		//		"1"
		"labelText"		"#TrackerUI_Close"
		"textAlignment"		"west"
		//"dulltext"		"0"
		//"brighttext"		"0"
		"Command"		"Close"
		"Default"		"1"
	}
	"AboutText"
	{
		"ControlName"		"RichText"
		"fieldName"		"AboutText"
		"xpos"		"10"
		"ypos"		"40"
		"wide"		"354"
		"tall"		"155"
		//		"3"
		//		"0"
		"visible"		"1"
		"enabled"		"1"
		//		"0"
		"maxchars"		"-1"
	}
}
