//#base "../#uni_base/filesv1/timeremaininglabel/main.res"
//#base "../#uni_base/filesv1/timeremaininglabel/vis1.res"
//#base "../#uni_base/filesv1/timeremaininglabel/dull0.res"
//#base "../#uni_base/filesv1/timeremaininglabel/xpos20.res"

#base "../#uni_base/filesv1/cancelbutton/ctrl/btn.res"
#base "../#uni_base/filesv1/cancelbutton/autoresize_pin.res"
#base "../#uni_base/filesv1/cancelbutton/def0.res"
#base "../#uni_base/filesv1/cancelbutton/vis1.res"

#base "../#uni_base/filesv1/cancelbutton/autoresize_pin.res"
#base "../#uni_base/filesv1/cancelbutton/ctrl/btn.res"
#base "../#uni_base/filesv1/cancelbutton/def0.res"
#base "../#uni_base/filesv1/cancelbutton/main.res"
#base "../#uni_base/filesv1/cancelbutton/vis1.res"
#base "../#uni_base/filesv1/cancelbutton/enabled.res"
#base "../#uni_base/filesv1/cancelbutton/text/west.res"
#base "../#uni_base/filesv1/cancelbutton/label/just_cancel.res"
#base "../#uni_base/filesv1/cancelbutton/bright0.res"
#base "../#uni_base/filesv1/cancelbutton/cmd/cancel.res"
#base "../#uni_base/filesv1/cancelbutton/dull0.res"
#base "../#uni_base/filesv1/cancelbutton/wrap0.res"
#base "../#uni_base/filesv1/cancelbutton/tab0.res"
#base "../#uni_base/filesv1/cancelbutton/position/x75.res"
#base "../#uni_base/filesv1/cancelbutton/position/y65.res"
#base "../#uni_base/filesv1/cancelbutton/position/w50.res"
#base "../#uni_base/filesv1/cancelbutton/position/t24.res"