#base "../#uni_base/filesv1/loadinglabel/ctrl/cloading.res"
#base "../#uni_base/filesv1/loadinglabel/main.res"
#base "../#uni_base/filesv1/loadinglabel/set.res"
#base "../#uni_base/filesv1/loadinglabel/position/x600.res"
#base "../#uni_base/filesv1/loadinglabel/position/y360.res"
#base "../#uni_base/filesv1/loadinglabel/position/w400.res"
#base "../#uni_base/filesv1/loadinglabel/position/t180.res"

#base "base/filesv1/progress/main.res"
#base "base/filesv1/progress/tab0.res"
#base "base/filesv1/progress/vis0.res"
#base "base/filesv1/progress/controlname.res"
#base "base/filesv1/progress/progress00.res"
#base "base/filesv1/progress/position/x20.res"
#base "base/filesv1/progress/position/y88.res"
#base "base/filesv1/progress/position/w260.res"
#base "base/filesv1/progress/position/t24.res"

//#base "../#uni_base/filesv1/progress2/main.res"
//#base "../#uni_base/filesv1/progress2/content64.res"

#base "../#uni_base/filesv1/cancelbutton/autoresize_pin.res"
#base "../#uni_base/filesv1/cancelbutton/ctrl/btn.res"
#base "../#uni_base/filesv1/cancelbutton/def0.res"
#base "../#uni_base/filesv1/cancelbutton/main.res"
#base "../#uni_base/filesv1/cancelbutton/vis1.res"
#base "../#uni_base/filesv1/cancelbutton/text/west.res"
#base "../#uni_base/filesv1/cancelbutton/enabled.res"
#base "../#uni_base/filesv1/cancelbutton/bright0.res"
#base "../#uni_base/filesv1/cancelbutton/dull0.res"
#base "../#uni_base/filesv1/cancelbutton/tab0.res"
#base "../#uni_base/filesv1/cancelbutton/wrap0.res"
#base "../#uni_base/filesv1/cancelbutton/position/x300.res"
#base "../#uni_base/filesv1/cancelbutton/position/y142.res"
#base "../#uni_base/filesv1/cancelbutton/position/w72.res"
#base "../#uni_base/filesv1/cancelbutton/position/t24.res"


#base "../#uni_base/filesv1/infolabel/main.res"
#base "../#uni_base/filesv1/infolabel/ctrl/label.res"
#base "../#uni_base/filesv1/infolabel/auto.res"
#base "../#uni_base/filesv1/infolabel/pin.res"
#base "../#uni_base/filesv1/infolabel/vis1.res"
#base "../#uni_base/filesv1/infolabel/wrap1.res"
#base "../#uni_base/filesv1/infolabel/enabled.res"
#base "../#uni_base/filesv1/infolabel/bright1.res"
#base "../#uni_base/filesv1/infolabel/dull0.res"
#base "../#uni_base/filesv1/infolabel/text/west.res"
#base "../#uni_base/filesv1/infolabel/special/x26.res"
#base "../#uni_base/filesv1/infolabel/special/y34.res"
#base "../#uni_base/filesv1/infolabel/special/w340.res"
#base "../#uni_base/filesv1/infolabel/special/t88.res"

//#base "../#uni_base/filesv1/timeremaininglabel/main.res"
//#base "../#uni_base/filesv1/timeremaininglabel/xypos0.res"
//#base "../#uni_base/filesv1/timeremaininglabel/wide64.res"
//#base "../#uni_base/filesv1/timeremaininglabel/vis0.res"
//#base "../#uni_base/filesv1/timeremaininglabel/dull1.res"


//#base "../#uni_base/filesv1/bannerad/main.res"
//#base "../#uni_base/filesv1/bannerad/vis0.res"