#base "base/playerlist.res"
#base "../#uni_base/filesv1/mutebutton/main.res"

#base "../#uni_base/filesv2/button1/main.res"
#base "../#uni_base/filesv2/button1/position/wide86.res"
#base "../#uni_base/filesv2/button1/position/tall24.res"
#base "../#uni_base/filesv2/button1/extra/auto0.res"
#base "../#uni_base/filesv2/button1/extra/pin3.res"
#base "../#uni_base/filesv2/button1/vis0.res"
#base "../#uni_base/filesv2/button1/enabled.res"
#base "../#uni_base/filesv2/button1/direccion/west.res"
#base "../#uni_base/filesv2/button1/extra/tab4.res"
#base "../#uni_base/filesv2/button1/extra/dull0.res"
#base "../#uni_base/filesv2/button1/extra/bright0.res"
#base "../#uni_base/filesv2/button1/extra/cmd/close.res"
#base "../#uni_base/filesv2/button1/extra/def0.res"
#base "../#uni_base/filesv2/button1/label/gameui.res"

#base "../#uni_base/filesv2/button1/position/x352.res"