#base "base/filesv1/filenamelabel/main.res"
#base "base/filesv1/filenamelabel/control-label.res"
#base "base/filesv1/filenamelabel/tab0.res"
#base "base/filesv1/filenamelabel/tall24.res"
#base "base/filesv1/filenamelabel/west.res"
#base "../#uni_base/filesv1/divider1/divider1_main.res"
#base "../#uni_base/filesv1/divider1/divider1_auto-pin0.res"
