#base "../base/build-more/mainbg/main.res"
#base "../base/build-more/mainbg/position/wide450.res"
#base "../base/build-more/mainbg/position/xpos0.res"
#base "../base/build-more/mainbg/position/tall170.res"
#base "../base/build-more/mainbg/ctrl_other.res"
#base "../base/build-more/mainbg/image/scale.res"
#base "../base/build-more/mainbg/image/color1.res"
#base "../base/build-more/mainbg/image/content1.res"
#base "../base/divider/main.res"
#base "../base/divider/main2.res"
#base "../base/divider/zpos1.res"
#base "../base/divider/xpos8.res"
#base "../base/divider/wide436.res"

#base "../base/build-more/destroyicon/main.res"
#base "../base/build-more/destroyicon/content2.res"
#base "../base/build-more/destroyicon/color_1.res"

#base "../base/build-more/titlelabel/main.res"
#base "../base/build-more/titlelabel/font/giantbold.res"
#base "../base/build-more/titlelabel/content1.res"
#base "../base/build-more/titlelabel/position/tall38.res"
#base "../base/build-more/titlelabel/text/left.res"

#base "../base/build-more/titlelabelshadow/main.res"
#base "../base/build-more/titlelabelshadow/font/giantbold.res"
#base "../base/build-more/titlelabelshadow/position/content1.res"
#base "../base/build-more/titlelabelshadow/position/tall35.res"
#base "../base/build-more/titlelabelshadow/text/left.res"


#base "../base/build-more/inactive_item/1/ctrl_edit.res"
#base "../base/build-more/inactive_item/1/vis1.res"
#base "../base/build-more/inactive_item/1/main.res"
#base "../base/build-more/inactive_item/1/ypos51.res"

#base "../base/build-more/unavailable_item/1/ctrl_edit.res"
#base "../base/build-more/unavailable_item/1/vis0.res"
#base "../base/build-more/unavailable_item/1/main.res"
#base "../base/build-more/unavailable_item/1/ypos51.res"

#base "../base/build-more/cancellabel/main.res"
#base "../base/build-more/cancellabel/ctrl/cex.res"
#base "../base/build-more/cancellabel/autopin0.res"
#base "../base/build-more/cancellabel/dullbright.res"
#base "../base/build-more/cancellabel/visenabled1.res"
#base "../base/build-more/cancellabel/position/zpos1.res"
#base "../base/build-more/cancellabel/position/wide200.res"
#base "../base/build-more/cancellabel/position/tall13.res"
#base "../base/build-more/cancellabel/position/ypos39.res"
#base "../base/build-more/cancellabel/font/spec.res"
#base "../base/build-more/cancellabel/text/east.res"