#base "../../base/1sysmenu.res"
#base "../base/1shadedbar.res"
#base "../base/1menubg.res"
#base "../base/1footer.res"
"Resource/UI/ClassSelection.res"
{
    "class"
    {
        "ControlName"   "Frame"
        "fieldName"     "class"
        "xpos"          "0"
        "ypos"          "0"
        "wide"          "f0"
        "tall"          "480"
        "autoResize"    "0"
        "pinCorner"     "0"
        "visible"       "1"
        "enabled"       "1"
        "tabPosition"   "0"
    }
    "MainBG"
    {
        "ControlName"   "ImagePanel"
        "fieldName"     "MainBG"
        "xpos"          "0"
        "ypos"          "0"
        "zpos"          "-11"
        "wide"          "f0"
        "tall"          "480"
        "fillcolor"     "10 10 10 120"
        "visible"       "1"
        "enabled"       "1"
    }
	"ClassMenuSelect"
	{
		"ControlName"	"CExLabel"
		"fieldName"		"ClassMenuSelect"
		"xpos"			"c-180"
		"ypos"			"c-105"
		"zpos"			"99"
		"wide"			"365"
		"tall"			"15"
		"visible"		"1"
		//"enabled"		"1"
        "tabPosition"	"0"
		"labelText"		"Select Class"
		"textAlignment"	"center"
		"font"			"CustomSegundo"
		"fgcolor"		"10 10 10 255"
	}
	"ClassMenuSelectBG"
	{
		"ControlName"			"ImagePanel"
		"fieldName"			"ClassMenuSelectBG"
		"xpos"				"c-180"
		"ypos"				"c-105"
		"zpos"				"0"
		"wide"				"365"
		"tall"				"15"
		"visible"			"1"		
		"enabled"			"1"
		"fillcolor"		"255 255 255 200"
	}
    "ClassSelectBG"
    {
        "ControlName"       "ImagePanel"
        "fieldName"     "ClassSelectBG"
        "xpos"          "c10"
        "ypos"          "c-90"
        "zpos"          "-10"
        "wide"          "170"
        "tall"          "215"
        "autoResize"        "0"
        "pinCorner"     "0"
        "visible"       "1"
        "enabled"       "1"
		"fillcolor"		"40 40 40 255"
    }
	"ClassModelBG"
    {
        "ControlName"       "ImagePanel"
        "fieldName"     "ClassSelectBG"
        "xpos"          "c-175"
        "ypos"          "c-90"
        "zpos"          "-10"
        "wide"          "355"
        "tall"          "216"
        "autoResize"        "0"
        "pinCorner"     "0"
        "visible"       "1"
        "enabled"       "1"
		"fillcolor"		"40 40 40 255"
    }
	 "ClassTeamSelectBG"
    {
        "ControlName"       "CTFImagePanel"
        "fieldName"     "ClassTeamSelectBG"
        "xpos"          "c-180"
        "ypos"          "c-90"
        "zpos"          "-11"
        "wide"          "365"
        "tall"          "222"
		"autoResize"		"0"
		"pinCorner"			"0"
		"visible"			"1"
		"enabled"			"1"
		"image"				"loadout_header"
		"scaleImage"		"0"
		"teambg_1"			"../hud/color_panel_brown"
		"teambg_2"			"../HUD/tournament_panel_red"
		"teambg_3"			"../HUD/tournament_panel_blu"
	
		"src_corner_height"		"15"				// pixels inside the image
		"src_corner_width"		"15"
		
		"draw_corner_width"		"0"				// screen size of the corners ( and sides ), proportional
		"draw_corner_height" 	"0"	
	}
    "LabelsBG"
    {
        "ControlName"   "ImagePanel"
        "fieldName"     "LabelsBG"
        "xpos"          "0"
        "ypos"          "r24"
        "zpos"          "-4"
        "wide"          "f0"
        "tall"          "480"
        "fillcolor"     "Blank"
        "visible"       "1"
        "enabled"       "1"
    }
    "random"
    {
        "ControlName"       "CExImageButton"
        "fieldName"         "random"
        "xpos"              "c10"
		"ypos"          "c108"       
        "zpos"          "16"
        "wide"          "170"
        "tall"          "18"
        "autoResize"    "0"
        "pinCorner"     "3"
        "visible"       "1"
        "enabled"       "1"
        "tabPosition"   "0"
		"use_proportional_insets" "1"
        "labelText"     "Random"
        "textAlignment" "center"
        "Command"       "select 12"
		"dulltext"		"0"
		"brighttext"	"0"
		"default"		"1"
		"sound_depressed"	"sound_menu/button.wav"
		"sound_released"	"sound_menu/button2.wav"
        "paintbackground"   "1"
        "font"          "CustomSegundo"
        "defaultBgColor_override"	"20 20 20 255"
		"armedBgColor_override"		"30 30 30 255"
		"depressedBgColor_override"	"20 20 20 255"
		"defaultFgColor_override"	"255 255 255 255"
		"armedFgColor_override" 	"255 255 255 255"
		"depressedFgColor_override" "Gray"
		"border_default"			"NoBorder"
		"border_armed"				"NoBorder"
        
       
        
        "SubImage"
        {
            "ControlName"   "ImagePanel"
            "fieldName"     "SubImage"
            "xpos"          "0"
            "ypos"          "0"
            "zpos"          "7"
            "wide"          "50"
            "tall"          "100"
            "visible"       "0"
            "enabled"       "1"
            "image"         "class_sel_sm_random_inactive"
            "scaleImage"    "1"
        }               
    }
        
    "Offense"
    {
        "ControlName"   "CExLabel"
        "fieldName"     "Offense"
        "xpos"          "0"
        "ypos"          "9999"
        "zpos"          "0"
        "wide"          "0"
        "tall"          "0"
        "visible"       "0"
        "enabled"       "0"
        "tabPosition"   "0"
    }
    "ScoutBG"
    {
        "ControlName"       "ImagePanel"
        "fieldname"         "ScoutBG"
        "xpos"              "c15"
        "ypos"              "c-85"
        "zpos"              "8"
        "wide"              "50"
        "tall"              "60"
        "visible"           "1"
        "enabled"           "1"
		"fillcolor"	"30 30 30 245"		
    }
	"ScoutLabel"
	{
		"ControlName"	"CExLabel"
		"fieldName"		"ScoutLabel"
		"xpos"			"c15"
		"ypos"			"c-35"
		"zpos"			"9"
		"wide"			"50"
		"tall"			"10"
		"autoResize"	"1"
		"pinCorner"		"2"
		"visible"		"1"
		//"enabled"		"1"
		"tabPosition"	"0"
		"labelText"		"Scout"
		"textAlignment"	"center"
		"font"			"CustomPrimero"
		"fgcolor"		"255 255 255 255"
	}
    "scout"
    {
        "ControlName"       "CExImageButton"
        "fieldName"         "scout"
        "textinsetx"    "17"
        "use_proportional_insets" "1"
        "xpos"              "c15"
        "ypos"              "c-85"
        "zpos"              "10"
        "wide"              "50"
        "tall"              "60"
        "autoResize"        "0"
        "pinCorner"         "2"
        "visible"           "1"
        "enabled"           "1"
        "tabPosition"       "0"
        "labelText"         "a" 
        "textAlignment"     "center"
        "Command"           "select 1"
        "Default"           "0"
        "font"              "NewIcons57"
        "scaleImage"        "1"
        
        "image_default"     ""
        "image_armed"       ""
        
        "fgcolor"           			"230 230 230 255"
        "defaultFgColor_override" 		"230 230 230 255"
        "armedFgColor_override" 		"255 255 255 255"
        "depressedFgColor_override" 	"230 230 230 255"
        "selectedFgColor_override" 		"255 255 255 255"
            
        "sound_depressed"   "sound_menu/button.wav"
        "sound_released"    "sound_menu/button2.wav"
        "sound_armed"       "UI/buttonrollover.wav"
        
        "paintbackground"   "0"
        
        "image_drawcolor"       "255 255 255 255"
        "image_armedcolor"      "255 255 255 255"
        "image_selectedcolor"   "255 255 255 255"
        
        "stayselectedonclick"   "1"
        "selectonhover"         "1"
        "keyboardinputenabled"  "0"
        
        "SubImage"
        {
            "ControlName"   "ImagePanel"
            "fieldName"     "SubImage"
            "xpos"          "9999"
            "ypos"          "9999"
            "zpos"          "7"
            "wide"          "50"
            "tall"          "100"
            "visible"       "0"
            "enabled"       "1"
            "image"         "class_sel_sm_scout_inactive"
            "scaleImage"    "1"
        }               
    } 
    "SoldierBG"
    {
        "ControlName"       "ImagePanel"
        "fieldname"         "SoldierBG"
        "xpos"              "c70"
        "ypos"              "c-85"
        "zpos"              "8"
        "wide"              "50"
        "tall"              "60"
        "visible"           "1"
        "enabled"           "1"
		"fillcolor"	"30 30 30 245"
    }
	"SoldierLabel"
	{
		"ControlName"	"CExLabel"
		"fieldName"		"SoldierLabel"
		"xpos"			"c70"
		"ypos"			"c-35"
		"zpos"			"9"
		"wide"			"50"
		"tall"			"10"
		"autoResize"	"1"
		"pinCorner"		"2"
		"visible"		"1"
		//"enabled"		"1"
		"tabPosition"	"0"
		"labelText"		"Soldier"
		"textAlignment"	"center"
		"font"			"CustomPrimero"
		"fgcolor"		"255 255 255 255"
	}
    "soldier"
    {
        "ControlName"       "CExImageButton"
        "fieldName"         "soldier"
        "textinsetx"    "17"
        "use_proportional_insets" "1"
        "xpos"              "c70"
        "ypos"              "c-85"
        "zpos"              "10"
        "wide"              "50"
        "tall"              "60"
        "autoResize"        "0"
        "pinCorner"         "2"
        "visible"           "1"
        "enabled"           "1"
        "tabPosition"       "0"
        "labelText"         "b"   
        "textAlignment"     "center"
        "Command"           "select 3"
        "Default"           "0"
        "font"              "NewIcons57"
        "scaleImage"        "1"
        
        "image_default"     "class_sel_sm_soldier_inactive"
        "image_armed"       "class_sel_sm_soldier_inactive"
        
        "fgcolor"           "230 230 230 255"
        "defaultFgColor_override" "230 230 230 255"
        "armedFgColor_override" "255 255 255 255"
        "depressedFgColor_override" "230 230 230 255"
        "selectedFgColor_override" "255 255 255 255"
        
        "sound_depressed"   "sound_menu/button.wav"
        "sound_released"    "sound_menu/button2.wav"
        "sound_armed"       "UI/buttonrollover.wav"
        
        "paintbackground"   "0"
        
        "image_drawcolor"       "255 255 255 255"
        "image_armedcolor"      "255 255 255 255"
        "image_selectedcolor"   "255 255 255 255"
        
        "stayselectedonclick"   "1"
        "selectonhover"         "1"
        "keyboardinputenabled"  "0"
        
        "SubImage"
        {
            "ControlName"   "ImagePanel"
            "fieldName"     "SubImage"
            "xpos"          "9999"
            "ypos"          "9999"
            "zpos"          "7"
            "wide"          "50"
            "tall"          "100"
            "visible"       "0"
            "enabled"       "1"
            "image"         "class_sel_sm_soldier_inactive"
            "scaleImage"    "1"
        }               
    }
    "PyroBG"
    {
        "ControlName"       "ImagePanel"
        "fieldname"         "PyroBG"
        "xpos"              "c125"
        "ypos"              "c-85"
        "zpos"              "8"
        "wide"              "50"
        "tall"              "60"
        "visible"           "1"
        "enabled"           "1"
        "fillcolor"			"30 30 30 245"
	}
	"PyroLabel"
	{
		"ControlName"	"CExLabel"
		"fieldName"		"PyroLabel"
		"xpos"			"c125"
		"ypos"			"c-35"
		"zpos"			"9"
		"wide"			"50"
		"tall"			"10"
		"autoResize"	"1"
		"pinCorner"		"2"
		"visible"		"1"
		//"enabled"		"1"
		"tabPosition"	"0"
		"labelText"		"Pyro"
		"textAlignment"	"center"
		"font"			"CustomPrimero"
		"fgcolor"		"255 255 255 255"
	}
    "pyro"
    {
        "ControlName"       "CExImageButton"
        "fieldName"         "pyro"
        "textinsetx"    "17"
        "use_proportional_insets" "1"
        "xpos"              "c125"
        "ypos"              "c-85"
        "zpos"              "10"
        "wide"              "50"
        "tall"              "60"
        "autoResize"        "0"
        "pinCorner"         "2"
        "visible"           "1"
        "enabled"           "1"
        "tabPosition"       "0"
        "labelText"         "c"  
        "textAlignment"     "center"
        "Command"           "select 7"
        "Default"           "0"
        "font"              "NewIcons57"
        "scaleImage"        "1"
        
        "image_default"     "class_sel_sm_pyro_inactive"
        "image_armed"       "class_sel_sm_pyro_inactive"
        
        "fgcolor"           "230 230 230 255"
        "defaultFgColor_override" "230 230 230 255"
        "armedFgColor_override" "255 255 255 255"
        "depressedFgColor_override" "230 230 230 255"
        "selectedFgColor_override" "255 255 255 255"
        
        "sound_depressed"   "sound_menu/button.wav"
        "sound_released"    "sound_menu/button2.wav"
        "sound_armed"       "UI/buttonrollover.wav"
        
        "paintbackground"   "0"
        
        "image_drawcolor"       "255 255 255 255"
        "image_armedcolor"      "255 255 255 255"
        "image_selectedcolor"   "255 255 255 255"
        
        "stayselectedonclick"   "1"
        "selectonhover"         "1"
        "keyboardinputenabled"  "0"
        
        "SubImage"
        {
            "ControlName"   "ImagePanel"
            "fieldName"     "SubImage"
            "xpos"          "9999"
            "ypos"          "9999"
            "zpos"          "7"
            "wide"          "50"
            "tall"          "100"
            "visible"       "0"
            "enabled"       "1"
            "image"         "class_sel_sm_pyro_inactive"
            "scaleImage"    "1"
        }               
    }
    
    "Defense"
    {
        "ControlName"   "CExLabel"
        "fieldName"     "Defense"
        "xpos"          "0"
        "ypos"          "9999"
        "zpos"          "0"
        "wide"          "0"
        "tall"          "0"
        "visible"       "0"
        "enabled"       "0"
        "tabPosition"   "0"
    }
    "DemomanBG"
    {
        "ControlName"       "ImagePanel"
        "fieldname"         "DemomanBG"
        "xpos"              "c15"
        "ypos"              "c-20"
        "zpos"              "8"
        "wide"              "50"
        "tall"              "60"
        "visible"           "1"
        "enabled"           "1"
       "fillcolor"	"30 30 30 245"
	}
	"DemoLabel"
	{
		"ControlName"	"CExLabel"
		"fieldName"		"DemoLabel"
		"xpos"			"c15"
		"ypos"			"c30"
		"zpos"			"9"
		"wide"			"50"
		"tall"			"10"
		"autoResize"	"1"
		"pinCorner"		"2"
		"visible"		"1"
		//"enabled"		"1"
		"tabPosition"	"0"
		"labelText"		"Demo"
		"textAlignment"	"center"
		"font"			"CustomPrimero"
		"fgcolor"		"255 255 255 255"
	}
    "demoman"
    {
        "ControlName"       "CExImageButton"
        "fieldName"         "demoman"
        "textinsetx"    "17"
        "use_proportional_insets" "1"
        "xpos"              "c15"
        "ypos"              "c-20"
        "zpos"              "10"
        "wide"              "50"
        "tall"              "60"
        "autoResize"        "0"
        "pinCorner"         "2"
        "visible"           "1"
        "enabled"           "1"
        "tabPosition"       "0"
        "labelText"         "d"   
        "textAlignment"     "center"
        "Command"           "select 4"
        "Default"           "0"
        "font"              "NewIcons57"
        "scaleImage"        "1"
        
        "image_default"     "class_sel_sm_demo_inactive"
        "image_armed"       "class_sel_sm_demo_inactive"
        
        "fgcolor"           "230 230 230 255"
        "defaultFgColor_override" "230 230 230 255"
        "armedFgColor_override" "255 255 255 255"
        "depressedFgColor_override" "230 230 230 255"
        "selectedFgColor_override" "255 255 255 255"
        
        "sound_depressed"   "sound_menu/button.wav"
        "sound_released"    "sound_menu/button2.wav"
        "sound_armed"       "UI/buttonrollover.wav"
        
        "paintbackground"   "0"
        
        "image_drawcolor"       "255 255 255 255"
        "image_armedcolor"      "255 255 255 255"
        "image_selectedcolor"   "255 255 255 255"
        
        "stayselectedonclick"   "1"
        "selectonhover"         "1"
        "keyboardinputenabled"  "0"
        
        "SubImage"
        {
            "ControlName"   "ImagePanel"
            "fieldName"     "SubImage"
            "xpos"          "9999"
            "ypos"          "9999"
            "zpos"          "7"
            "wide"          "50"
            "tall"          "100"
            "visible"       "0"
            "enabled"       "1"
            "image"         "class_sel_sm_demo_inactive"
            "scaleImage"    "1"
        }               
    }   
    "HeavyBG"
    {
        "ControlName"       "ImagePanel"
        "fieldname"         "HeavyBG"
        "xpos"              "c70"
        "ypos"              "c-20"
        "zpos"              "8"
        "wide"              "50"
        "tall"              "60"
        "visible"           "1"
        "enabled"           "1"
        "fillcolor"			"30 30 30 245"
    }
	"HeavyLabel"
	{
		"ControlName"	"CExLabel"
		"fieldName"		"HeavyLabel"
		"xpos"			"c70"
		"ypos"			"c30"
		"zpos"			"9"
		"wide"			"50"
		"tall"			"10"
		"autoResize"	"1"
		"pinCorner"		"2"
		"visible"		"1"
		//"enabled"		"1"
		"tabPosition"	"0"
		"labelText"		"Heavy"
		"textAlignment"	"center"
		"font"			"CustomPrimero"
		"fgcolor"		"255 255 255 255"
	}
    "heavyweapons"
    {
        "ControlName"       "CExImageButton"
        "fieldName"         "heavyweapons"
        "textinsetx"    "17"
        "use_proportional_insets" "1"
        "xpos"              "c70"
        "ypos"              "c-20"
        "zpos"              "10"
        "wide"              "50"
        "tall"              "60"
        "autoResize"        "0"
        "pinCorner"         "2"
        "visible"           "1"
        "enabled"           "1"
        "tabPosition"       "0"
        "labelText"         "e" 
        "textAlignment"     "center"
        "Command"           "select 6"
        "Default"           "0"
        "font"              "NewIcons57"
        "scaleImage"        "1"
        
        "image_default"     "class_sel_sm_heavy_inactive"
        "image_armed"       "class_sel_sm_heavy_inactive"
        
        "fgcolor"           "230 230 230 255"
        "defaultFgColor_override" "230 230 230 255"
        "armedFgColor_override" "255 255 255 255"
        "depressedFgColor_override" "230 230 230 255"
        "selectedFgColor_override" "255 255 255 255"
        
        "sound_depressed"   "sound_menu/button.wav"
        "sound_released"    "sound_menu/button2.wav"
        "sound_armed"       "UI/buttonrollover.wav"
        
        "paintbackground"   "0"
        
        "image_drawcolor"       "255 255 255 255"
        "image_armedcolor"      "255 255 255 255"
        "image_selectedcolor"   "255 255 255 255"
        
        "stayselectedonclick"   "1"
        "selectonhover"         "1"
        "keyboardinputenabled"  "0"
        
        "SubImage"
        {
            "ControlName"   "ImagePanel"
            "fieldName"     "SubImage"
            "xpos"          "9999"
            "ypos"          "9999"
            "zpos"          "7"
            "wide"          "50"
            "tall"          "100"
            "visible"       "0"
            "enabled"       "1"
            "image"         "class_sel_sm_heavy_inactive"
            "scaleImage"    "1"
        }               
    }
    "EngineerBG"
    {
        "ControlName"       "ImagePanel"
        "fieldname"         "EngineerBG"
        "xpos"              "c125"
        "ypos"              "c-20"
        "zpos"              "8"
        "wide"              "50"
        "tall"              "60"
        "visible"           "1"
        "enabled"           "1"
        "fillcolor"	"30 30 30 245"
    }
	"EngieLabel"
	{
		"ControlName"	"CExLabel"
		"fieldName"		"EngieLabel"
		"xpos"			"c125"
		"ypos"			"c30"
		"zpos"			"9"
		"wide"			"50"
		"tall"			"10"
		"autoResize"	"1"
		"pinCorner"		"2"
		"visible"		"1"
		//"enabled"		"1"
		"tabPosition"	"0"
		"labelText"		"Engineer"
		"textAlignment"	"center"
		"font"			"CustomPrimero"
		"fgcolor"		"255 255 255 255"
	}
    "engineer"
    {
        "ControlName"       "CExImageButton"
        "fieldName"         "engineer"
        "textinsetx"    "17"
        "use_proportional_insets" "1"
        "xpos"              "c125"
        "ypos"              "c-20"
        "zpos"              "10"
        "wide"              "50"
        "tall"              "60"
        "autoResize"        "0"
        "pinCorner"         "2"
        "visible"           "1"
        "enabled"           "1"
        "tabPosition"       "0"
        "labelText"         "f"  
        "textAlignment"     "center"
        "Command"           "select 9"
        "Default"           "0"
        "font"              "NewIcons57"
        "scaleImage"        "1"
        
        "image_default"     "class_sel_sm_engineer_inactive"
        "image_armed"       "class_sel_sm_engineer_inactive"
        
        "fgcolor"           "230 230 230 255"
        "defaultFgColor_override" "230 230 230 255"
        "armedFgColor_override" "255 255 255 255"
        "depressedFgColor_override" "230 230 230 255"
        "selectedFgColor_override" "255 255 255 255"
        
        "sound_depressed"   "sound_menu/button.wav"
        "sound_released"    "sound_menu/button2.wav"
        "sound_armed"       "UI/buttonrollover.wav"
        
        "paintbackground"   "0"
        
        "image_drawcolor"       "255 255 255 255"
        "image_armedcolor"      "255 255 255 255"
        "image_selectedcolor"   "255 255 255 255"
        
        "stayselectedonclick"   "1"
        "selectonhover"         "1"
        "keyboardinputenabled"  "0"
        
        "SubImage"
        {
            "ControlName"   "ImagePanel"
            "fieldName"     "SubImage"
            "xpos"          "9999"
            "ypos"          "9999"
            "zpos"          "7"
            "wide"          "50"
            "tall"          "100"
            "visible"       "0"
            "enabled"       "1"
            "image"         "class_sel_sm_engineer_inactive"
            "scaleImage"    "1"
        }               
    }
    
    "Support"
    {
        "ControlName"   "CExLabel"
        "fieldName"     "Support"
        "xpos"          "0"
        "ypos"          "9999"
        "zpos"          "0"
        "wide"          "0"
        "tall"          "0"
        "visible"       "0"
        "enabled"       "0"
        "tabPosition"   "0"
    }
    "MedicBG"
    {
        "ControlName"       "ImagePanel"
        "fieldname"         "MedicBG"
        "xpos"              "c15"
        "ypos"              "c45"
        "zpos"              "8"
        "wide"              "50"
        "tall"              "60"
        "visible"           "1"
        "enabled"           "1"
        "fillcolor"	"30 30 30 245"
    }
	"MedicLabel"
	{
		"ControlName"	"CExLabel"
		"fieldName"		"MedicLabel"
		"xpos"			"c15"
		"ypos"			"c95"
		"zpos"			"9"
		"wide"			"50"
		"tall"			"10"
		"autoResize"	"1"
		"pinCorner"		"2"
		"visible"		"1"
		//"enabled"		"1"
		"tabPosition"	"0"
		"labelText"		"Medic"
		"textAlignment"	"center"
		"font"			"CustomPrimero"
		"fgcolor"		"255 255 255 255"
	}
    "medic"
    {
        "ControlName"       "CExImageButton"
        "textinsetx"    "17"
        "use_proportional_insets" "1"
        "fieldName"         "medic"
        "xpos"              "c15"
        "ypos"              "c45"
        "zpos"              "10"
        "wide"              "50"
        "tall"              "60"
        "autoResize"        "0"
        "pinCorner"         "2"
        "visible"           "1"
        "enabled"           "1"
        "tabPosition"       "0"
        "labelText"         "g" 
        "textAlignment"     "center"
        "Command"           "select 5"
        "Default"           "0"
        "font"              "NewIcons57"
        "scaleImage"        "1"
        
        "image_default"     "class_sel_sm_medic_inactive"
        "image_armed"       "class_sel_sm_medic_inactive"
        
        "fgcolor"           "230 230 230 255"
        "defaultFgColor_override" "230 230 230 255"
        "armedFgColor_override" "255 255 255 255"
        "depressedFgColor_override" "230 230 230 255"
        "selectedFgColor_override" "255 255 255 255"
        
        "sound_depressed"   "sound_menu/button.wav"
        "sound_released"    "sound_menu/button2.wav"
        "sound_armed"       "UI/buttonrollover.wav"
        
        "paintbackground"   "0"
        
        "image_drawcolor"       "255 255 255 255"
        "image_armedcolor"      "255 255 255 255"
        "image_selectedcolor"   "255 255 255 255"
        
        "stayselectedonclick"   "1"
        "selectonhover"         "1"
        "keyboardinputenabled"  "0"
        
        "SubImage"
        {
            "ControlName"   "ImagePanel"
            "fieldName"     "SubImage"
            "xpos"          "9999"
            "ypos"          "9999"
            "zpos"          "7"
            "wide"          "50"
            "tall"          "100"
            "visible"       "0"
            "enabled"       "1"
            "image"         "class_sel_sm_medic_inactive"
            "scaleImage"    "1"
        }               
    }
    "SniperBG"
    {
        "ControlName"       "ImagePanel"
        "fieldname"         "SniperBG"
        "xpos"              "c70"
        "ypos"              "c45"
        "zpos"              "8"
        "wide"              "50"
        "tall"              "60"
        "visible"           "1"
        "enabled"           "1"
		"fillcolor"	"30 30 30 245"
    }
	"SniperLabel"
	{
		"ControlName"	"CExLabel"
		"fieldName"		"SniperLabel"
		"xpos"			"c70"
		"ypos"			"c95"
		"zpos"			"9"
		"wide"			"50"
		"tall"			"10"
		"autoResize"	"1"
		"pinCorner"		"2"
		"visible"		"1"
		//"enabled"		"1"
		"tabPosition"	"0"
		"labelText"		"Sniper"
		"textAlignment"	"center"
		"font"			"CustomPrimero"
		"fgcolor"		"255 255 255 255"
	}
    "sniper"
    {
        "ControlName"       "CExImageButton"
        "fieldName"         "sniper"
        "textinsetx"    "17"
        "use_proportional_insets" "1"
        "xpos"              "c70"
        "ypos"              "c45"
        "zpos"              "10"
        "wide"              "50"
        "tall"              "60"
        "autoResize"        "0"
        "pinCorner"         "2"
        "visible"           "1"
        "enabled"           "1"
        "tabPosition"       "0"
        "labelText"         "h"    
        "textAlignment"     "center"
        "Command"           "select 2"
        "Default"           "0"
        "font"              "NewIcons57"
        "scaleImage"        "1"
        
        "image_default"     "class_sel_sm_sniper_inactive"
        "image_armed"       "class_sel_sm_sniper_inactive"
        
        "fgcolor"           "230 230 230 255"
        "defaultFgColor_override" "230 230 230 255"
        "armedFgColor_override" "255 255 255 255"
        "depressedFgColor_override" "230 230 230 255"
        "selectedFgColor_override" "255 255 255 255"
        
        "sound_depressed"   "sound_menu/button.wav"
        "sound_released"    "sound_menu/button2.wav"
        "sound_armed"       "UI/buttonrollover.wav"
        
        "paintbackground"   "0"
        
        "image_drawcolor"       "255 255 255 255"
        "image_armedcolor"      "255 255 255 255"
        "image_selectedcolor"   "255 255 255 255"
        
        "stayselectedonclick"   "1"
        "selectonhover"         "1"
        "keyboardinputenabled"  "0"
        
        "SubImage"
        {
            "ControlName"   "ImagePanel"
            "fieldName"     "SubImage"
            "xpos"          "9999"
            "ypos"          "9999"
            "zpos"          "7"
            "wide"          "50"
            "tall"          "100"
            "visible"       "0"
            "enabled"       "1"
            "image"         "class_sel_sm_sniper_inactive"
            "scaleImage"    "1"
        }               
    }
    "SpyBG"
    {
        "ControlName"       "ImagePanel"
        "fieldname"         "SpyBG"
        "xpos"              "c125"
        "ypos"              "c45"
        "zpos"              "8"
        "wide"              "50"
        "tall"              "60"
        "visible"           "1"
        "enabled"           "1"
		"fillcolor"	"30 30 30 245"
    }
	"SpyLabel"
	{
		"ControlName"	"CExLabel"
		"fieldName"		"SpyLabel"
		"xpos"			"c125"
		"ypos"			"c95"
		"zpos"			"9"
		"wide"			"50"
		"tall"			"10"
		"autoResize"	"1"
		"pinCorner"		"2"
		"visible"		"1"
		//"enabled"		"1"
		"tabPosition"	"0"
		"labelText"		"Spy"
		"textAlignment"	"center"
		"font"			"CustomPrimero"
		"fgcolor"		"255 255 255 255"
	}
    "spy"
    {
        "ControlName"       "CExImageButton"
        "fieldName"         "spy"
        "textinsetx"    "17"
        "use_proportional_insets" "1"
        "xpos"              "c125"
        "ypos"              "c45"
        "zpos"              "10"
        "wide"              "50"
        "tall"              "60"
        "autoResize"        "0"
        "pinCorner"         "2"
        "visible"           "1"
        "enabled"           "1"
        "tabPosition"       "0"
        "labelText"         "i"   
        "textAlignment"     "center"
        "Command"           "select 8"
        "Default"           "0"
        "font"              "NewIcons57"
        "scaleImage"        "1"
        
        "image_default"     "class_sel_sm_spy_inactive"
        "image_armed"       "class_sel_sm_spy_inactive"
        
        "fgcolor"           "230 230 230 255"
        "defaultFgColor_override" "230 230 230 255"
        "armedFgColor_override" "255 255 255 255"
        "depressedFgColor_override" "230 230 230 255"
        "selectedFgColor_override" "255 255 255 255"
        
        "sound_depressed"   "sound_menu/button.wav"
        "sound_released"    "sound_menu/button2.wav"
        "sound_armed"       "UI/buttonrollover.wav"
        
        "paintbackground"   "0"
        
        "image_drawcolor"       "255 255 255 255"
        "image_armedcolor"      "255 255 255 255"
        "image_selectedcolor"   "255 255 255 255"
        
        "stayselectedonclick"   "1"
        "selectonhover"         "1"
        "keyboardinputenabled"  "0"
        
        "SubImage"
        {
            "ControlName"   "ImagePanel"
            "fieldName"     "SubImage"
            "xpos"          "9999"
            "ypos"          "9999"
            "zpos"          "7"
            "wide"          "50"
            "tall"          "100"
            "visible"       "0"
            "enabled"       "1"
            "image"         "class_sel_sm_spy_inactive"
            "scaleImage"    "1"
        }               
    }   
   
    "QuitButton"
    {
        "ControlName"   "CExButton"
        "fieldName"     "QuitButton"
        "xpos"          "c-180"        
        "ypos"          "c132"       
        "zpos"          "6"
        "wide"          "365"
        "tall"          "20"
        "autoResize"    "0"
        "pinCorner"     "2"
        "visible"       "1"
        "enabled"       "1"
        "tabPosition"   "0"
        "labelText"     "Cancel"
        "textAlignment" "center"
        "Command"       "vguicancel"
        "dulltext"		"0"
		"brighttext"	"0"
		"default"		"1"
		"sound_depressed"	"sound_menu/button.wav"
		"sound_released"	"sound_menu/button2.wav"
        "paintbackground"   "1"
        "font"          "CustomSegundo"
        "defaultBgColor_override"	"20 20 20 255"
		"armedBgColor_override"		"30 30 30 255"
		"depressedBgColor_override"	"20 20 20 255"
		"defaultFgColor_override"	"255 255 255 255"
		"armedFgColor_override" 	"255 255 255 255"
		"depressedFgColor_override" "Gray"
		"border_default"			"NoBorder"
		"border_armed"				"NoBorder"
	}
    "EditLoadoutButton"
    {
        "ControlName"   "CExImageButton"
        "fieldName"     "EditLoadoutButton"
        "xpos"          "c-175"     
        "ypos"          "c108"       
        "zpos"          "16"
        "wide"          "170"
        "tall"          "18"
        "autoResize"    "0"
        "pinCorner"     "3"
        "visible"       "1"
        "enabled"       "1"
        "tabPosition"   "0"
		"use_proportional_insets" "1"
        "labelText"     "Loadout"
        "textAlignment" "center"
        "Command"       "openloadout"
		"dulltext"		"0"
		"brighttext"	"0"
		"default"		"1"
		"sound_depressed"	"sound_menu/button.wav"
		"sound_released"	"sound_menu/button2.wav"
        "paintbackground"   "1"
        "font"          "CustomSegundo"
        "defaultBgColor_override"	"20 20 20 255"
		"armedBgColor_override"		"30 30 30 255"
		"depressedBgColor_override"	"20 20 20 255"
		"defaultFgColor_override"	"255 255 255 255"
		"armedFgColor_override" 	"255 255 255 255"
		"depressedFgColor_override" "Gray"
		"border_default"			"NoBorder"
		"border_armed"				"NoBorder"
    }
    "ResetButton"  
    {
        "ControlName"   "CExButton"
        "fieldName"     "ResetButton"
        "xpos"          "0"
        "ypos"          "0"
        "zpos"          "0"
        "wide"          "0"
        "tall"          "0"
        "autoResize"    "0"
        "pinCorner"     "2"
        "visible"       "0"
        "enabled"       "0"
        "tabPosition"   "0"
        "labelText"     "#TF_ClassMenu_Reset"
        "textAlignment" "center"
        "Command"       "resetclass"
        "font"          "HudFontSmallBold"
    }
    "MenuBG"
    {
        "ControlName"   "CModelPanel"
        "fieldName"     "MenuBG"
        "xpos"          "0"
        "ypos"          "0"
        "zpos"          "0"     
        "wide"          "0"
        "tall"          "0"
        "autoResize"    "0"
        "pinCorner"     "0"
        "visible"       "0"
        "enabled"       "0"
        "fov"           "0"
        
        "model"
        {
            "modelname" "models/vgui/UI_class01.mdl"
            "skin"      "0"
            "angles_x" "0"
            "angles_y" "180"
            "angles_z" "0"
            "origin_x" "365"
            "origin_x_lodef" "415"
            "origin_x_hidef" "380"
            "origin_y" "0"
            "origin_z" "-40"
        }
    }   

    "Hint"
    {   
        "ControlName"   "CExLabel"
        "fieldName"     "Hint"
        "xpos"          "0"
        "ypos"          "0"
        "zpos"          "0"
        "wide"          "0"
        "tall"          "0"
        "autoResize"    "0"
        "pinCorner"     "0"
        "visible"       "0"
        "enabled"       "0"
        "tabPosition"   "0"
        "labelText"     "%hint%"
        "textAlignment" "left"
        "wrap"          "0"
        "font"          "CustomSegundo"
        "fgcolor"       "HudTrainingHint"
    }     
    
    "localPlayerImage" 
    {
        "ControlName"   "CTFImagePanel"
        "fieldName"     "localPlayerImage"
        "xpos"          "0"
        "ypos"          "0"
        "zpos"          "0"
        "wide"          "0"
        "tall"          "0"
        "visible"       "0"
        "enabled"       "0"
        "image"         ""  
        "scaleImage"    "1" 
    }
    
    "localPlayerBG"
    {
        "ControlName"   "CTFImagePanel"
        "fieldName"     "localPlayerBG"
        "xpos"          "0"
        "ypos"          "0"
        "zpos"          "0"
        "wide"          "0"
        "tall"          "0"
        "autoResize"    "0"
        "pinCorner"     "0"
        "visible"       "0"
        "enabled"       "0"
        "image"         "../hud/color_panel_clear"
        "scaleImage"    "0" 
        "teambg_2"      "../hud/color_panel_clear"
        "teambg_3"      "../hud/color_panel_clear"
            
        "src_corner_height"     "23"            // pixels inside the image
        "src_corner_width"      "23"
                
        "draw_corner_width"     "5"             // screen size of the corners ( and sides ), proportional
        "draw_corner_height"    "5" 
    }
    
    "countImage0" 
    {
        "ControlName"   "CTFImagePanel"
        "fieldName"     "countImage0"
        "xpos"          "0"
        "ypos"          "0"
        "zpos"          "0"
        "wide"          "0"
        "tall"          "0"
        "visible"       "0"
        "enabled"       "0"
        "image"         ""  
        "scaleImage"    "0" 
    }                           
    
    "countImage1" 
    {
        "ControlName"   "CTFImagePanel"
        "fieldName"     "countImage1"
        "xpos"          "0"
        "ypos"          "0"
        "zpos"          "0"
        "wide"          "0"
        "tall"          "0"
        "visible"       "0"
        "enabled"       "0"
        "image"         ""  
        "scaleImage"    "0" 
    }
    
    "countImage2" 
    {
        "ControlName"   "CTFImagePanel"
        "fieldName"     "countImage2"
        "xpos"          "0"
        "ypos"          "0"
        "zpos"          "0"
        "wide"          "0"
        "tall"          "0"
        "visible"       "0"
        "enabled"       "0"
        "image"         ""  
        "scaleImage"    "0" 
    }
    
    "countImage3" 
    {
        "ControlName"   "CTFImagePanel"
        "fieldName"     "countImage3"
        "xpos"          "0"
        "ypos"          "0"
        "zpos"          "0"
        "wide"          "0"
        "tall"          "0"
        "visible"       "0"
        "enabled"       "0"
        "image"         ""  
        "scaleImage"    "0" 
    }
    
    "countImage4" 
    {
        "ControlName"   "CTFImagePanel"
        "fieldName"     "countImage4"
        "xpos"          "0"
        "ypos"          "0"
        "zpos"          "0"
        "wide"          "0"
        "tall"          "0"
        "visible"       "0"
        "enabled"       "0"
        "image"         ""  
        "scaleImage"    "0" 
    }
    
    "countImage5" 
    {
        "ControlName"   "CTFImagePanel"
        "fieldName"     "countImage5"
        "xpos"          "0"
        "ypos"          "0"
        "zpos"          "0"
        "wide"          "0"
        "tall"          "0"
        "visible"       "0"
        "enabled"       "0"
        "image"         ""  
        "scaleImage"    "0" 
    }
    
    "countImage6" 
    {
        "ControlName"   "CTFImagePanel"
        "fieldName"     "countImage6"
        "xpos"          "0"
        "ypos"          "0"
        "zpos"          "0"
        "wide"          "0"
        "tall"          "0"
        "visible"       "0"
        "enabled"       "0"
        "image"         ""  
        "scaleImage"    "0" 
    }
    
    "countImage7" 
    {
        "ControlName"   "CTFImagePanel"
        "fieldName"     "countImage7"
        "xpos"          "0"
        "ypos"          "0"
        "zpos"          "0"
        "wide"          "0"
        "tall"          "0"
        "visible"       "0"
        "enabled"       "0"
        "image"         ""  
        "scaleImage"    "0" 
    }
    
    "countImage8" 
    {
        "ControlName"   "CTFImagePanel"
        "fieldName"     "countImage8"
        "xpos"          "0"
        "ypos"          "0"
        "zpos"          "0"
        "wide"          "0"
        "tall"          "0"
        "visible"       "0"
        "enabled"       "0"
        "image"         ""  
        "scaleImage"    "0" 
    }
    
    "countImage9" 
    {
        "ControlName"   "CTFImagePanel"
        "fieldName"     "countImage9"
        "xpos"          "0"
        "ypos"          "0"
        "zpos"          "0"
        "wide"          "0"
        "tall"          "0"
        "visible"       "0"
        "enabled"       "0"
        "image"         ""  
        "scaleImage"    "0" 
    }
    
    "countImage10" 
    {
        "ControlName"   "CTFImagePanel"
        "fieldName"     "countImage10"
        "xpos"          "0"
        "ypos"          "0"
        "zpos"          "0"
        "wide"          "0"
        "tall"          "0"
        "visible"       "0"
        "enabled"       "0"
        "image"         ""  
        "scaleImage"    "0" 
    }
    
    "CountLabel" 
    {
        "ControlName"   "CExLabel"
        "fieldName"     "CountLabel"
        "xpos"          "0"
        "ypos"          "0"
        "zpos"          "0"
        "wide"          "0"
        "tall"          "0"
        "autoResize"    "0"
        "pinCorner"     "0"
        "visible"       "0"
        "enabled"       "0"
        "tabPosition"   "0"
        "labelText"     ""
        "textAlignment" "left"
        "font"          "CustomSegundo"
        "fgcolor"       "TanLight"
    }
    
    "numScout" 
    {
        "ControlName"   "CExLabel"
        "fieldName"     "numScout"
        "xpos"          "c15"
        "ypos"          "c-85"
        "zpos"          "11"
        "wide"          "50"
        "tall"          "12"
        "autoResize"    "1"
        "pinCorner"     "2"
        "visible"       "1"
        "enabled"       "1"
        "tabPosition"   "0"
		"textinsetx"	"5"
        "labelText"     "%numScout%"
        "textAlignment" "west"
        "font"          "CustomPrimero"
        "fgcolor"       "255 255 255 225"
    } 
    
    "numSoldier" 
    {
        "ControlName"   "CExLabel"
        "fieldName"     "numSoldier"
        "xpos"          "c70"
		"ypos"          "c-85"
        "zpos"          "11"
        "wide"          "50"
        "tall"          "12"
        "autoResize"    "1"
        "pinCorner"     "2"
        "visible"       "1"
        "enabled"       "1"
        "tabPosition"   "0"
		"textinsetx"	"5"
        "labelText"     "%numSoldier%"
        "textAlignment" "west"
        "font"          "CustomSegundo"
        "fgcolor"       "255 255 255 225"
    }    
    
    "numPyro" 
    {
        "ControlName"   "CExLabel"
        "fieldName"     "numPyro"
        "xpos"          "c125"
        "ypos"          "c-85"
        "zpos"          "11"
        "wide"          "50"
        "tall"          "12"
        "autoResize"    "1"
        "pinCorner"     "2"
        "visible"       "1"
        "enabled"       "1"
        "tabPosition"   "0"
		"textinsetx"	"5"
        "labelText"     "%numPyro%"
        "textAlignment" "west"
        "font"          "CustomSegundo"
        "fgcolor"       "255 255 255 225"
    }          
    
    "numDemoman" 
    {
        "ControlName"   "CExLabel"
        "fieldName"     "numDemoman"
        "xpos"          "c15"
        "ypos"          "c-20"
        "zpos"          "11"
        "wide"          "50"
        "tall"          "12"
        "autoResize"    "1"
        "pinCorner"     "2"
        "visible"       "1"
        "enabled"       "1"
        "tabPosition"   "0"
		"textinsetx"	"5"
        "labelText"     "%numDemoman%"
        "textAlignment" "west"
        "font"          "CustomSegundo"
        "fgcolor"       "255 255 255 225"
    }            
    
    "numHeavy" 
    {
        "ControlName"   "CExLabel"
        "fieldName"     "numHeavy"
        "xpos"          "c70"
        "ypos"          "c-20"
        "zpos"          "11"
        "wide"          "50"
        "tall"          "12"
        "autoResize"    "1"
        "pinCorner"     "2"
        "visible"       "1"
        "enabled"       "1"
        "tabPosition"   "0"
		"textinsetx"	"5"
        "labelText"     "%numHeavy%"
        "textAlignment" "west"
        "font"          "CustomSegundo"
        "fgcolor"       "255 255 255 225"
    }                   
    
    "numEngineer" 
    {
        "ControlName"   "CExLabel"
        "fieldName"     "numEngineer"
        "xpos"          "c125"
        "ypos"          "c-20"
        "zpos"          "11"
        "wide"          "50"
        "tall"          "12"
        "autoResize"    "1"
        "pinCorner"     "2"
        "visible"       "1"
        "enabled"       "1"
        "tabPosition"   "0"
		"textinsetx"	"5"
        "labelText"     "%numEngineer%"
        "textAlignment" "west"
        "font"          "CustomSegundo"
        "fgcolor"       "255 255 255 225"
    }                      
    
    "numMedic" 
    {
        "ControlName"   "CExLabel"
        "fieldName"     "numMedic"
        "xpos"          "c15"
        "ypos"          "c45"
        "zpos"          "11"
        "wide"          "50"
        "tall"          "12"
        "autoResize"    "1"
        "pinCorner"     "2"
        "visible"       "1"
        "enabled"       "1"
        "tabPosition"   "0"
		"textinsetx"	"5"
        "labelText"     "%numMedic%"
        "textAlignment" "west"
        "font"          "CustomSegundo"
        "fgcolor"       "255 255 255 225"
    }                         
    
    "numSniper" 
    {
        "ControlName"   "CExLabel"
        "fieldName"     "numSniper"
        "xpos"          "c70"
        "ypos"          "c45"
        "zpos"          "11"
        "wide"          "50"
        "tall"          "12"
        "autoResize"    "1"
        "pinCorner"     "2"
        "visible"       "1"
        "enabled"       "1"
        "tabPosition"   "0"
		"textinsetx"	"5"
        "labelText"     "%numSniper%"
        "textAlignment" "west"
        "font"          "CustomSegundo"
        "fgcolor"       "255 255 255 225"
    }                     
    
    "numSpy" 
    {
        "ControlName"   "CExLabel"
        "fieldName"     "numSpy"
        "xpos"          "c125"
        "ypos"          "c45"
        "zpos"          "11"
        "wide"          "50"
        "tall"          "12"
        "autoResize"    "1"
        "pinCorner"     "2"
        "visible"       "1"
        "enabled"       "1"
        "tabPosition"   "0"
		"textinsetx"	"5"
        "labelText"     "%numSpy%"
        "textAlignment" "west"
        "font"          "CustomSegundo"
        "fgcolor"       "255 255 255 225"
    }                               
    
    "MvMUpgradeImageScout"
    {
        "ControlName"   "ImagePanel"
        "fieldName"     "MvMUpgradeImageScout"
        "xpos"          "0"
        "ypos"          "0"
        "zpos"          "0"
        "wide"          "0"
        "tall"          "0"
        "visible"       "0"
        "enabled"       "0"
        "image"         "mvm/class_upgraded"
        "scaleImage"    "0"
    }
    
    "MvMUpgradeImageSolider"
    {
        "ControlName"   "ImagePanel"
        "fieldName"     "MvMUpgradeImageSolider"
        "xpos"          "0"
        "ypos"          "0"
        "zpos"          "0"
        "wide"          "0"
        "tall"          "0"
        "visible"       "0"
        "enabled"       "0"
        "image"         "mvm/class_upgraded"
        "scaleImage"    "0"
    }
    
    "MvMUpgradeImagePyro" 
    {
        "ControlName"   "ImagePanel"
        "fieldName"     "MvMUpgradeImagePyro" 
        "xpos"          "0"
        "ypos"          "0"
        "zpos"          "0"
        "wide"          "0"
        "tall"          "0"
        "visible"       "0"
        "enabled"       "0"
        "image"         "mvm/class_upgraded"
        "scaleImage"    "0"
    }
    
    "MvMUpgradeImageDemoman" 
    {
        "ControlName"   "ImagePanel"
        "fieldName"     "MvMUpgradeImageDemoman" 
        "xpos"          "0"
        "ypos"          "0"
        "zpos"          "0"
        "wide"          "0"
        "tall"          "0"
        "visible"       "0"
        "enabled"       "0"
        "image"         "mvm/class_upgraded"
        "scaleImage"    "0"
    }
    
    "MvMUpgradeImageHeavy"
    {
        "ControlName"   "ImagePanel"
        "fieldName"     "MvMUpgradeImageHeavy" 
        "xpos"          "0"
        "ypos"          "0"
        "zpos"          "0"
        "wide"          "0"
        "tall"          "0"
        "visible"       "0"
        "enabled"       "0"
        "image"         "mvm/class_upgraded"
        "scaleImage"    "0"
    }
    
    "MvMUpgradeImageEngineer"
    {
        "ControlName"   "ImagePanel"
        "fieldName"     "MvMUpgradeImageEngineer"
        "xpos"          "0"
        "ypos"          "0"
        "zpos"          "0"
        "wide"          "0"
        "tall"          "0"
        "visible"       "0"
        "enabled"       "0"
        "image"         "mvm/class_upgraded"
        "scaleImage"    "0"
    }
    
    "MvMUpgradeImageMedic"
    {
        "ControlName"   "ImagePanel"
        "fieldName"     "MvMUpgradeImageMedic"
        "xpos"          "0"
        "ypos"          "0"
        "zpos"          "0"
        "wide"          "0"
        "tall"          "0"
        "visible"       "0"
        "enabled"       "0"
        "image"         "mvm/class_upgraded"
        "scaleImage"    "0"
    }
    
    "MvMUpgradeImageSniper"
    {
        "ControlName"   "ImagePanel"
        "fieldName"     "MvMUpgradeImageSniper"
        "xpos"          "0"
        "ypos"          "0"
        "zpos"          "0"
        "wide"          "0"
        "tall"          "0"
        "visible"       "0"
        "enabled"       "0"
        "image"         "mvm/class_upgraded"
        "scaleImage"    "0"
    }
    
    "MvMUpgradeImageSpy"
    {
        "ControlName"   "ImagePanel"
        "fieldName"     "MvMUpgradeImageSpy"
        "xpos"          "0"
        "ypos"          "0"
        "zpos"          "0"
        "wide"          "0"
        "tall"          "0"
        "visible"       "0"
        "enabled"       "0"
        "image"         "mvm/class_upgraded"
        "scaleImage"    "0"
    }

    "StartExplanation"
    {
        "ControlName"   "CExplanationPopup"
        "fieldName"     "StartExplanation"
        "xpos"          "0"
        "ypos"          "0"
        "zpos"          "0"
        "wide"          "0"
        "tall"          "0"
        "visible"       "0"
        "PaintBackgroundType"   "0"
        "paintbackground" "0"
        "border"        "MainMenuHighlightBorder"
        
        "force_close"   "0"
        "end_x"         "0"
        "end_y"         "0"
        "end_wide"      "0"
        "end_tall"      "0"
        "callout_inparents_x"   "0"
        "callout_inparents_y"   "0"
        "next_explanation"      "VoucherExplanation"
        
        "TitleLabel"
        {
            "ControlName"   "CExLabel"
            "fieldName"     "TitleLabel"
            "font"          "CustomSegundo"
            "labelText"     "#TF_MvM_UpgradeExplanation_Title"
            "textAlignment" "north"
            "xpos"          "0"
            "ypos"          "0"
            "wide"          "0"
            "tall"          "0"
            "autoResize"    "0"
            "pinCorner"     "0"
            "visible"       "0"
            "enabled"       "0"
            "wrap"          "0"
            "fgcolor_override" "0 0 0 0"
        }
        
        "TextLabel"
        {
            "ControlName"   "CExLabel"
            "fieldName"     "TextLabel"
            "font"          "CustomSegundo"
            "labelText"     "#TF_MvM_UpgradeExplanation_Text"
            "textAlignment" "north-west"
            "xpos"          "0"
            "ypos"          "0"
            "wide"          "0"
            "tall"          "0"
            "autoResize"    "0"
            "pinCorner"     "0"
            "visible"       "0"
            "enabled"       "0"
            "wrap"          "0"
            "fgcolor_override" "0 0 0 0"
        }
        
        "CloseButton"
        {
            "ControlName"   "CExImageButton"
            "fieldName"     "CloseButton"
            "xpos"          "0"
            "ypos"          "0"
            "zpos"          "0"
            "wide"          "0"
            "tall"          "0"
            "autoResize"    "0"
            "pinCorner"     "0"
            "visible"       "0"
            "enabled"       "0"
            "tabPosition"   "0"
            "labeltext"     ""
            "font"          "CustomSegundo"
            "textAlignment" "center"
            "dulltext"      "0"
            "brighttext"    "0"
            "default"       "0"
            "sound_depressed"   "sound_menu/button.wav"
            "sound_released"    "sound_menu/button2.wav"
            "Command"       "close"
            
            "paintbackground"   "0"
            
            "defaultFgColor_override" "0 0 0 0"
            "armedFgColor_override" "0 0 0 0"
            "depressedFgColor_override" "0 0 0 0"
            
            "image_drawcolor"   "0 0 0 0"
            "image_armedcolor"  "0 0 0 0"
            "SubImage"
            {
                "ControlName"   "ImagePanel"
                "fieldName"     "SubImage"
                "xpos"          "0"
                "ypos"          "0"
                "zpos"          "0"
                "wide"          "0"
                "tall"          "0"
                "visible"       "0"
                "enabled"       "0"
                "image"         "close_button"
                "scaleImage"    "0"
            }               
        }
    }
    
    "TFPlayerModel"
    {
        "ControlName"   "CTFPlayerModelPanel"
        "fieldName"     "TFPlayerModel"
        
        "xpos"          "c-175"
        "ypos"          "c-90"
        "zpos"          "0"     
        "wide"          "170"
        "tall"          "215"
        
        "autoResize"    "1"
        "pinCorner"     "0"
        "visible"       "1"
        "enabled"       "1"
        
        "render_texture"    "0"
        "fov"           "15"
        "allow_rot"     "1"

        "paintbackground" "0"       
        "paintbackgroundenabled" "0"
        "bgcolor_override" "0 0 0 0"
        
        "model"
        {
            "force_pos"	"1"

			"angles_x" "0"
			"angles_y" "180"
			"angles_z" "0"
			"origin_x" "280"
			"origin_y" "0"
			"origin_z" "-45"
			"frame_origin_x"	"0"
			"frame_origin_y"	"0"
			"frame_origin_z"	"0"
			"spotlight" "1"
        
            "modelname"     ""
            "vcd"       "class_select.vcd"      
            
            "animation"
            {
                "name"      "PRIMARY"
                "activity"  "ACT_MP_STAND_PRIMARY"
                "default"   "1"
            }
            "animation"
            {
                "name"      "SECONDARY"
                "activity"  "ACT_MP_STAND_SECONDARY"
            }
            "animation"
            {
                "name"      "MELEE"
                "activity"  "ACT_MP_STAND_MELEE"
            }
            "animation"
            {
                "name"      "BUILDING"
                "activity"  "ACT_MP_STAND_BUILDING"
            }
            "animation"
            {
                "name"      "PDA"
                "activity"  "ACT_MP_STAND_PDA"
            }
            "animation"
            {
                "name"      "ITEM1"
                "activity"  "ACT_MP_STAND_ITEM1"
            }                       
            "animation"
            {
                "name"      "ITEM2"
                "activity"  "ACT_MP_STAND_ITEM2"
            }   
            "animation"
            {
                "name"      "MELEE_ALLCLASS"
                "activity"  "ACT_MP_STAND_MELEE_ALLCLASS"
            }                               
        }
    }
    
    "ClassTipsPanel"
    {
        "ControlName"   "CTFClassTipsPanel"
        "fieldName"     "ClassTipsPanel"
        "xpos"          "0"
        "ypos"          "0"
        "zpos"          "0"
        "wide"          "0"
        "tall"          "0"
        "autoResize"    "0"
        "pinCorner"     "0"
        "visible"       "0"
        "enabled"       "0"
        "tabPosition"   "0"
    }
    
    "ClassHighlightPanel"
    {
        "ControlName"   "CExplanationPopup"
        "fieldName"     "ClassHighlightPanel"
        "xpos"          "0"
        "ypos"          "0"
        "zpos"          "0"
        "wide"          "0"
        "tall"          "0"
        "visible"       "0"
        "PaintBackgroundType"   "0"
        "paintbackground" "0"
        "border"        "MainMenuHighlightBorder"
        
        "start_x"       "0"
        "start_y"       "0"
        "start_wide"    "0"
        "start_tall"    "0"
        "end_x"         "0"
        "end_y"         "0"
        "end_wide"      "0"
        "end_tall"      "0"
        "callout_inparents_x"   "0"
        "callout_inparents_y"   "0"
        
        "TitleLabel"
        {
            "ControlName"   "CExLabel"
            "fieldName"     "TitleLabel"
            "font"          "CustomSegundo"
            "labelText"     "#CMenu_ClassHighlightPanel_Title"
            "textAlignment" "north-west"
            "xpos"          "0"
            "ypos"          "0"
            "wide"          "0"
            "tall"          "0"
            "autoResize"    "0"
            "pinCorner"     "0"
            "visible"       "0"
            "enabled"       "0"
            "wrap"          "0"
            "fgcolor_override" "0 0 0 0"
        }
        
        "ClassHighlightText"
        {
            "ControlName"   "CExLabel"
            "fieldName"     "ClassHighlightText"
            "font"          "CustomSegundo"
            "labelText"     "%ClassHighlightText%"
            "textAlignment" "north-west"
            "xpos"          "0"
            "ypos"          "0"
            "wide"          "0"
            "tall"          "0"
            "autoResize"    "0"
            "pinCorner"     "0"
            "visible"       "0"
            "enabled"       "0"
            "wrap"          "0"
            "fgcolor_override" "0 0 0 0"
        }
        
        "CloseButton"
        {
            "ControlName"   "CExImageButton"
            "fieldName"     "CloseButton"
            "xpos"          "0"
            "ypos"          "0"
            "zpos"          "0"
            "wide"          "0"
            "tall"          "0"
            "autoResize"    "0"
            "pinCorner"     "0"
            "visible"       "0"
            "enabled"       "0"
            "tabPosition"   "0"
            "labeltext"     ""
            "font"          "CustomSegundo"
            "textAlignment" "center"
            "dulltext"      "0"
            "brighttext"    "0"
            "default"       "0"
            "sound_depressed"   "sound_menu/button.wav"
            "sound_released"    "sound_menu/button2.wav"
            "Command"       "close"
            
            "paintbackground"   "0"
            
            "defaultFgColor_override" "0 0 0 0"
            "armedFgColor_override" "0 0 0 0"
            "depressedFgColor_override" "0 0 0 0"
            
            "image_drawcolor"   "0 0 0 0"
            "image_armedcolor"  "0 0 0 0"
            "SubImage"
            {
                "ControlName"   "ImagePanel"
                "fieldName"     "SubImage"
                "xpos"          "0"
                "ypos"          "0"
                "zpos"          "0"
                "wide"          "0"
                "tall"          "0"
                "visible"       "0"
                "enabled"       "0"
                "image"         "close_button"
                "scaleImage"    "0"
            }               
        }
    }       
}
