#base "csc/main.res"
"resource/ui/hudplayerclass.res"
{
"NumberLabel"
{
"ControlName""CExLabel"
//"fieldName""NumberLabel"
"fgcolor""Black"
//"xpos""0"
"ypos""98"
//"zpos""1"
"wide""100"
"tall""18"
//////"autoResize""0"
////"pinCorner""0"
////"visible""1"
//////"enabled""1"
"textAlignment""Center"
"dulltext""1"
"brighttext""0"
}
}