"Resource/NewOperationDialog.res"
{
"RightSideBG"
{
"ControlName""ImagePanel"
"fieldName""RightSideBG"
"zpos""1"
"wide""280"
"tall""80"
"visible""1"
////"enabled""1"
"image""../hud/objectives_flagpanel_bg_right"
"scaleImage""1"
}}