"resource/BaseActionCDTrackStartDialog.res"
{
"BannerAd"
{
"ControlName""HTML"
"fieldName""BannerAd"
"xpos""20"
"ypos""144"
"wide""340"
"tall""56"
//"autoResize""0"
//"pinCorner""0"
////"enabled""1"
"tabPosition""0"
}}