#base "../../#uni_base/filesv2/button1/main.res"
#base "../../#uni_base/filesv2/button1/position/tall24.res"
#base "../../#uni_base/filesv2/button1/extra/auto0.res"
#base "../../#uni_base/filesv2/button1/extra/pin0.res"
#base "../../#uni_base/filesv2/button1/vis1.res"
#base "../../#uni_base/filesv2/button1/enabled.res"
#base "../../#uni_base/filesv2/button1/direccion/west.res"
#base "../../#uni_base/filesv2/button1/extra/tab3.res"
#base "../../#uni_base/filesv2/button1/extra/paintbg.res"
#base "../../#uni_base/filesv2/button1/extra/wrap0.res"
#base "../../#uni_base/filesv2/button1/extra/cmd/close.res"
#base "../../#uni_base/filesv2/button1/extra/def0.res"
"friends/AddFriendResultSubPanel.res"
{
	"Button1"
	{
	//	"ControlName"		"Button"
	//	"fieldName"		"Button1"
	//	"tall"		"24"
	//	//"autoResize"		"0"
	//	//"pinCorner"		"0"
	//	"visible"		"1"
	//	////"enabled"		"1"
	//	"tabPosition"		"3"
	//	"paintbackground"		"1"
	//	"labelText"		"#vgui_Cancel"
	//	"textAlignment"		"west"
	//	"wrap"		"0"
	//	"Command"		"Close"
	//	"Default"		"0"
	}
}
