#base "../../resource/ui/base/build-more/cancellabel/main.res"
#base "../../resource/ui/base/build-more/cancellabel/autopin0.res"
#base "../../resource/ui/base/build-more/cancellabel/dullbright.res"
#base "../../resource/ui/base/build-more/cancellabel/visenabled1.res"
#base "../../resource/ui/base/build-more/cancellabel/font/def.res"
#base "../../resource/ui/base/build-more/cancellabel/text/center.res"