"Resource/EngineVGuiLayout.res"
{
"Entities"
{
"ControlName""ListPanel"
"fieldName""Entities"
"xpos""10"
"ypos""30"
"autoResize""3"
//"pinCorner""0"
"visible""1"
////"enabled""1"
"tabPosition""1"
}
"EntitiesLabel"
{
"ControlName""Label"
"fieldName""EntitiesLabel"
"xpos""10"
"ypos""8"
"wide""64"
"tall""24"
//"autoResize""0"
//"pinCorner""0"
"visible""1"
////"enabled""1"
"tabPosition""0"
"labelText""Entities:"
"textAlignment""west"
//"dulltext""0"
//"brighttext""0"
"wrap""0"
}
}