"Admin\ServerConfigPanel.res"
{
	"ServerConfigPanel"
	{
		"ControlName"		"CVarListPropertyPage"
		"fieldName"		"ServerConfigPanel"
		"xpos"		"0"
		"ypos"		"28"
		"wide"		"520"
		"tall"		"332"
		//		"0"
		//		"0"
		"visible"		"1"
		"enabled"		"1"
		//		"0"
	}
	"RulesList"
	{
		"ControlName"		"ListPanel"
		"fieldName"		"RulesList"
		"xpos"		"12"
		"ypos"		"12"
		"wide"		"496"
		"tall"		"276"
		//		"3"
		//		"0"
		"visible"		"1"
		"enabled"		"1"
		//		"1"
	}
	"EditButton"
	{
		"ControlName"		"Button"
		"fieldName"		"EditButton"
		"xpos"		"12"
		"ypos"		"298"
		"wide"		"80"
		"tall"		"24"
		//		"0"
		//		"2"
		"visible"		"1"
		"enabled"		"1"
		//		"2"
		"labelText"		"Edit..."
		"textAlignment"		"west"
		////		"0"
		////		"0"
		//"wrap"		"0"
		"Default"		"1"
	}
}
