#base "../../#uni_base/filesv1/cancelbutton/main.res"
#base "../../#uni_base/filesv1/cancelbutton/def0.res"
#base "../../#uni_base/filesv1/cancelbutton/ctrl/btn.res"
#base "../../#uni_base/filesv1/cancelbutton/autoresize_pin.res"
#base "../../#uni_base/filesv1/cancelbutton/vis1.res"
#base "../../#uni_base/filesv1/cancelbutton/position/t24.res"