#base "../../#uni_base/filesv1/label1/main.res"
#base "../../#uni_base/filesv1/label1/auto.res"
#base "../../#uni_base/filesv1/label1/pin.res"
#base "../../#uni_base/filesv1/label1/enabled.res"
#base "../../#uni_base/filesv1/label1/dull1.res"
#base "../../#uni_base/filesv1/label1/bright0.res"