#base "../../../../../#uni_base/filesv1/titlelabel/controlname/cex.res"
#base "../../../../../#uni_base/filesv1/titlelabel/main.res"
#base "../../../../../#uni_base/filesv1/titlelabel/auto.res"
#base "../../../../../#uni_base/filesv1/titlelabel/pin.res"
#base "../../../../../#uni_base/filesv1/titlelabel/vis1.res"
#base "../../../../../#uni_base/filesv1/titlelabel/enabled.res"
#base "../../../../../#uni_base/filesv1/titlelabel/text/left.res"
#base "../../../../../#uni_base/filesv1/titlelabel/dull0.res"
#base "../../../../../#uni_base/filesv1/titlelabel/bright.res"
"resource/ui/hudplayerclass.res"
{
"TitleLabel"
{
//"ControlName""CExLabel"
//"fieldName""TitleLabel"
"wide""300"
//////"autoResize""0"
////"pinCorner""0"
////"visible""1"
//////"enabled""1"
//"textAlignment""Left"
////"dulltext""0"
//"brighttext""0"
}
}