#base "is-pin1.res"
#base "is-vis1.res"
#base "is-enabled1.res"
"Resource/CommentaryItem.res"
{
"DeleteButton"
{
"wide""64"
"tall""24"
//"autoResize""0"
//"pinCorner""1"
//"visible""1"
//////"enabled""1"
"tabPosition""0"
"labelText""Delete"
"textAlignment""west"
//"dulltext""0"
//"brighttext""0"
"wrap""0"
"Default""0"
"selected""0"
}}