"AddOns/Common/TwoPlayerColorChoiceDialog.res"
{
	"TwoPlayerColorChoiceDialog"
	{
		"ControlName"		"CTwoPlayerColorChoiceDialog"
		"fieldName"		"TwoPlayerColorChoiceDialog"
		"xpos"		"519"
		"ypos"		"306"
		"wide"		"400"
		"tall"		"140"
		//		"0"
		//		"0"
		"visible"		"1"
		"enabled"		"1"
		//		"0"
	}
	"TextLabel"
	{
		"ControlName"		"Label"
		"fieldName"		"TextLabel"
		"xpos"		"35"
		"ypos"		"30"
		"wide"		"350"
		"tall"		"40"
		//		"0"
		//		"0"
		"visible"		"1"
		"enabled"		"1"
		//		"0"
		"labelText"		"main text"
	}
	"ColorOneBtn"
	{
		"ControlName"		"Button"
		"fieldName"		"ColorOneBtn"
		"xpos"		"50"
		"ypos"		"70"
		"wide"		"128"
		"tall"		"24"
		//		"0"
		//		"0"
		"visible"		"1"
		"enabled"		"1"
		//		"0"
		"labelText"		"Color One"
	}
	"ColorTwoBtn"
	{
		"ControlName"		"Button"
		"fieldName"		"ColorTwoBtn"
		"xpos"		"210"
		"ypos"		"70"
		"wide"		"128"
		"tall"		"24"
		//		"0"
		//		"0"
		"visible"		"1"
		"enabled"		"1"
		//		"0"
		"labelText"		"Color Two"
	}
	"AbortBtn"
	{
		"ControlName"		"Button"
		"fieldName"		"AbortBtn"
		"xpos"		"320"
		"ypos"		"110"
		"wide"		"60"
		"tall"		"24"
		//		"0"
		//		"0"
		"visible"		"1"
		"enabled"		"1"
		//		"0"
		"labelText"		"Abort"
	}
}
