"Resource/baseaction_sys.res"
{
"NextOptionHintIcon"
{
"ControlName""CSCHintIcon"
"fieldName""NextOptionHintIcon"
"zpos""4"
////"autoResize""0"
//"visible""1"
////"enabled""1"
//"pinCorner""0"
"actionSet""InGameHUDControls"
"actionName""menu_right"
}
"PrevOptionHintIcon"
{
"ControlName""CSCHintIcon"
"fieldName""PrevOptionHintIcon"
"zpos""4"
////"autoResize""0"
//"visible""1"
////"enabled""1"
//"pinCorner""0"
"actionSet""InGameHUDControls"
"actionName""menu_left"
}
}
