"Resource/EngineVGuiLayout.res"
{
"ExplanationLabel"
{
"ControlName""Label"
"fieldName""ExplanationLabel"
"font""HudFontSmall"
"xpos""20"
"ypos""35"
"zpos""1"
"wide""290"
"tall""85"
//"autoResize""0"
//"pinCorner""0"
//"visible""1"
////"enabled""1"
"wrap""1"
"textAlignment""North"
}
}