"Resource/EngineVGuiLayout.res"
{
"RankTooltipPanel"
{
"ControlName""ImagePanel"
"fieldName""RankTooltipPanel"
"wide""8"
"tall""8"
//"visible""1"
"proportionaltoparent""1"
//"mouseinputenabled""1"
"image""info"
"scaleImage""1"
"alpha""75"
}
}