////#base "../base/filesv3-hint/buttonlegend.res"
//#base "../base/filesv3-hint/cancel/main.res"
//#base "../base/filesv3-hint/cancel/is_label.res"
//#base "../base/filesv3-hint/cancel/vis1.res"
//#base "../base/filesv3-hint/cancel/pin0.res"
//#base "../base/filesv3-hint/teamtoggle.res"

//#base "../base/filesv3-hint/cancel-label/main.res"
//#base "../base/filesv3-hint/cancel-label/x_pos40.res"
//#base "../base/filesv3-hint/cancel-label/ypos129.res"
#base "../base/filesv2/shadedbar/main_special.res"
#base "../base/filesv2/shadedbar/disguise/main.res"
#base "../base/build-more/mainbg/main.res"
#base "../base/build-more/mainbg/position/wide470.res"
#base "../base/build-more/mainbg/position/xpos0.res"
#base "../base/build-more/mainbg/position/tall170.res"
#base "../base/build-more/mainbg/ctrl_other.res"
#base "../base/build-more/mainbg/image/scale.res"
#base "../base/build-more/mainbg/image/color1.res"
#base "../base/build-more/mainbg/image/content1.res"
// hud_menu_item_bg
#base "../base/build-more/titlelabel/main.res"
#base "../base/build-more/titlelabel/font/giantbold.res"
#base "../base/build-more/titlelabel/position/content2.res"
#base "../base/build-more/titlelabel/text/north-west.res"

#base "../base/build-more/titlelabelshadow/main.res"
#base "../base/build-more/titlelabelshadow/font/giantbold.res"
#base "../base/build-more/titlelabelshadow/position/content2.res"
#base "../base/build-more/titlelabelshadow/text/north-west.res"

#base "../base/active_sel/main.res"
#base "../base/active_sel/ctrl_edit.res"
#base "../base/active_sel/content2.res"

#base "../base/class_item/main.res"
#base "../base/class_item/content1.res"