"resource/BaseActionCDTrackStartDialog.res"
{
"LevelPicBorder"
{
"ControlName""ImagePanel"
"fieldName""LevelPicBorder"
//"autoResize""0"
//"pinCorner""0"
"visible""1"
////"enabled""1"
}
"LevelPic"
{
"ControlName""ImagePanel"
"fieldName""LevelPic"
//"autoResize""0"
//"pinCorner""0"
"visible""1"
////"enabled""1"
}}