"j"
{
	"CustomizationMenu"
	{
		"MainPanel"
		{
			"MenuContainer"
			{
				"MiscSizeButtons"
				{
					"AWSD_ON"
					{
						"ControlName"			"CExButton"
						"fieldName"				"AWSD_ON"
						"xpos"					"0"
						"ypos"					"0"
						"wide"					"p0.5"
						"tall"					"40"
						"proportionaltoparent"	"1"
						"labeltext"				"AWSD Screen Keyboard ON"
						"font"					"Size 14"
						"textalignment"			"center"
						"command"				"engine jp_custom_alias_awsd;host_writeconfig config_before_awsd; exec screen-keyboard; jp_reload"
						"actionsignallevel"		"5"
						"paintbackground"		"0"
						"border_default"		"FLAT_Black_4"
						"border_armed"			"FLAT_Black_2"
						"sound_depressed"		"UI/buttonclick.wav"
						"sound_released"		"UI/buttonclickrelease.wav"
					}		
					"AWSD_OFF"
					{
						"ControlName"			"CExButton"
						"fieldName"				"AWSD_OFF"
						"xpos"					"0+p0.5"
						"ypos"					"0"
						"wide"					"p0.5"
						"tall"					"40"
						"proportionaltoparent"	"1"
						"labeltext"				"AWSD Screen Keyboard OFF"
						"font"					"Size 14"
						"textalignment"			"center"
						"command"				"engine jp_custom_awsd_clear; showconsole; echo I have exec screen-keyboard.cfg for reset your awsd stuff; exec screen-keyboard-off; jp_reload"
						"actionsignallevel"		"5"
						"paintbackground"		"0"
						"border_default"		"FLAT_Black_4"
						"border_armed"			"FLAT_Black_2"
						"sound_depressed"		"UI/buttonclick.wav"
						"sound_released"		"UI/buttonclickrelease.wav"
					}	
					"CrosshairScale"
					{
						"ControlName"	"CExLabel"
						"fieldName"		"CrosshairScale"
						"font"		"Regular16"
						"labelText"		"Size:"
						"textAlignment"	"center"
						"xpos"		"0"
						"ypos"		"40"
						"zpos"		"20"
						"wide"		"60"
						"tall"		"40"
						"visible"		"1"
						"enabled"		"1"
						"fgcolor"		"white"
					}
					"CrosshairBG"
					{
						"ControlName"	"Panel"
						"fieldName"		"CrosshairBG"
						"font"		"Regular16"
						"xpos"		"0"
						"ypos"		"0"
						"zpos"		"15"
						"wide"		"f0"
						"tall"		"40"
						"border"		"FLAT_Black_4"
						"pin_to_sibling"	"CrosshairScale"
					}
					"CrosshairScaleSlider"
					{
						"ControlName"		"CCvarSlider"
						"fieldName"		"CrosshairScaleSlider"
						"xpos"		"0"
						"ypos"		"3"
						"zpos"		"100"
						"wide"		"p0.45"
						"tall"		"16"
						"minvalue"		"0"
						"maxvalue"		"50"
						"cvar_name"		"cl_crosshair_scale"
		
						"pin_to_sibling" "CrosshairScale"	
						"pin_corner_to_sibling" "7"
						"pin_to_sibling_corner" "5"
					}		
					"CustomChargeSniperOFF"
					{
						"ControlName"			"CExButton"
						"fieldName"				"CustomChargeSniperOFF"
						"xpos"					"0"
						"ypos"					"80"
						"wide"					"p0.5"
						"tall"					"40"
						"proportionaltoparent"	"1"
						"labeltext"				"Sniper Charge: Default"
						"font"					"Size 14"
						"textalignment"			"center"
						"command"				"engine jp_custom_alias_snchar_def; jp_reload"
						"actionsignallevel"		"5"
						"paintbackground"		"0"
						"border_default"		"FLAT_Black_4"
						"border_armed"			"FLAT_Black_2"
						"sound_depressed"		"UI/buttonclick.wav"
						"sound_released"		"UI/buttonclickrelease.wav"
					}			
					"CustomChargeSniperON"
					{
						"ControlName"			"CExButton"
						"fieldName"				"CustomChargeSniperON"
						"xpos"					"0+p0.5"
						"ypos"					"80"
						"wide"					"p0.5"
						"tall"					"40"
						"proportionaltoparent"	"1"
						"labeltext"				"Sniper Charge: Custom"
						"font"					"Size 14"
						"textalignment"			"center"
						"command"				"engine jp_custom_alias_snchar_custom; jp_reload"
						"actionsignallevel"		"5"
						"paintbackground"		"0"
						"border_default"		"FLAT_Black_4"
						"border_armed"			"FLAT_Black_2"
						"sound_depressed"		"UI/buttonclick.wav"
						"sound_released"		"UI/buttonclickrelease.wav"
					}			

					"Cartglow_on"
					{
						"ControlName"			"CExButton"
						"fieldName"				"Cartglow_on"
						"xpos"					"0"
						"ypos"					"120"
						"wide"					"p0.5"
						"tall"					"40"
						"proportionaltoparent"	"1"
						"labeltext"				"Cart Glow ON"
						"font"					"Size 14"
						"textalignment"			"center"
						"command"				"engine sixense_clear_bindings; sixense_write_bindings jp_anim_cartglow.txt; con_logfile cfg/jp_anim_cartglow.txt; echo event AddToCartBlink {}; con_logfile ."
						"actionsignallevel"		"5"
						"paintbackground"		"0"
						"border_default"		"FLAT_Black_4"
						"border_armed"			"FLAT_Black_2"
						"sound_depressed"		"UI/buttonclick.wav"
						"sound_released"		"UI/buttonclickrelease.wav"
					}		
					"Cartglow_off"
					{
						"ControlName"			"CExButton"
						"fieldName"				"Cartglow_off"
						"xpos"					"0+p0.5"
						"ypos"					"120"
						"wide"					"p0.5"
						"tall"					"40"
						"proportionaltoparent"	"1"
						"labeltext"				"Cart Glow OFF"
						"font"					"Size 14"
						"textalignment"			"center"
						"command"				"engine sixense_clear_bindings; sixense_write_bindings jp_anim_cartglow.txt"
						"actionsignallevel"		"5"
						"paintbackground"		"0"
						"border_default"		"FLAT_Black_4"
						"border_armed"			"FLAT_Black_2"
						"sound_depressed"		"UI/buttonclick.wav"
						"sound_released"		"UI/buttonclickrelease.wav"
					}			
					"Pilotbars_on"
					{
						"ControlName"			"CExButton"
						"fieldName"				"Pilotbars_on"
						"xpos"					"0"
						"ypos"					"160"
						"wide"					"p0.5"
						"tall"					"40"
						"proportionaltoparent"	"1" 
						"labeltext"				"Pilot Bars ON"
						"font"					"Size 14"
						"textalignment"			"center"
						"command"				"engine sixense_clear_bindings; sixense_write_bindings jp_hudplayerclass_pilotbars.txt; con_logfile cfg/jp_hudplayerclass_pilotbars.txt; echo #base ../custom/jofrehud-main/new/ui_overrides/pilot-bars/file.res; con_logfile ."
						"actionsignallevel"		"5"
						"paintbackground"		"0"
						"border_default"		"FLAT_Black_4"
						"border_armed"			"FLAT_Black_2"
						"sound_depressed"		"UI/buttonclick.wav"
						"sound_released"		"UI/buttonclickrelease.wav"
					}		
					"Pilotbars_off"
					{
						"ControlName"			"CExButton"
						"fieldName"				"Pilotbars_off"
						"xpos"					"0+p0.5"
						"ypos"					"160"
						"wide"					"p0.5"
						"tall"					"40"
						"proportionaltoparent"	"1"
						"labeltext"				"Pilot Bars OFF"
						"font"					"Size 14"
						"textalignment"			"center"
						"command"				"engine sixense_clear_bindings; sixense_write_bindings jp_hudplayerclass_pilotbars.txt"
						"actionsignallevel"		"5"
						"paintbackground"		"0"
						"border_default"		"FLAT_Black_4"
						"border_armed"			"FLAT_Black_2"
						"sound_depressed"		"UI/buttonclick.wav"
						"sound_released"		"UI/buttonclickrelease.wav"
					}			
								"glowingfont"
					{
						"ControlName"	"CExLabel"
						"fieldName"		"glowingfont"
						"font"		"Regular12"
						"labelText"		"Glowing Damage Text Font (doesnt work on casual)"
						"textAlignment"	"center"
						"xpos"		"0"
						"ypos"		"260-40"
						"zpos"		"20"
						"wide"		"p0.55"
						"tall"		"20"
						"border"		"FLAT_Black_4"
						"enabled"		"1"
						"fgcolor"		"black"
						"bgcolor_override"	"purple"
					}																														
						"glowingfont_on"
					{
						"ControlName"			"CExButton"
						"fieldName"				"glowingfont_on"
						"xpos"					"0"
						"ypos"					"280-40"
						"wide"					"p0.5"
						"tall"					"40"
						"proportionaltoparent"	"1" 
						"labeltext"				"ON"
						"font"					"Size 14"
						"textalignment"			"center"
						"command"				"engine sixense_clear_bindings; sixense_write_bindings jp_afbik_dmg.txt; con_logfile cfg/jp_afbik_dmg.txt; echo #base ../custom/jofrehud-main/new/ui_overrides/damage/glowingfont.res; con_logfile ."
						"actionsignallevel"		"5"
						"paintbackground"		"0"
						"border_default"		"FLAT_Black_4"
						"border_armed"			"FLAT_Black_2"
						"sound_depressed"		"UI/buttonclick.wav"
						"sound_released"		"UI/buttonclickrelease.wav"
					}		
					"glowingfont_off"
					{
						"ControlName"			"CExButton"
						"fieldName"				"glowingfont_off"
						"xpos"					"0+p0.5"
						"ypos"					"280-40"
						"wide"					"p0.5"
						"tall"					"40"
						"proportionaltoparent"	"1"
						"labeltext"				"OFF"
						"font"					"Size 14"
						"textalignment"			"center"
						"command"				"engine sixense_clear_bindings; sixense_write_bindings jp_afbik_dmg.txt"
						"actionsignallevel"		"5"
						"paintbackground"		"0"
						"border_default"		"FLAT_Black_4"
						"border_armed"			"FLAT_Black_2"
						"sound_depressed"		"UI/buttonclick.wav"
						"sound_released"		"UI/buttonclickrelease.wav"
					}	





								"hudradarlabel"
					{
						"ControlName"	"CExLabel"
						"fieldName"		"hudradarlabel"
						"font"		"Regular12"
						"labelText"		"HUD Radar (Only for Upward / Toggleable with contract progress)"
						"textAlignment"	"center"
						"xpos"		"0"
						"ypos"		"320-40"
						"zpos"		"20"
						"wide"		"p0.55"
						"tall"		"20"
						"border"		"FLAT_Black_4"
						"enabled"		"1"
						"fgcolor"		"black"
						"bgcolor_override"	"purple"
					}																														
						"radar_on"
					{
						"ControlName"			"CExButton"
						"fieldName"				"radar_on"
						"xpos"					"0"
						"ypos"					"340-40"
						"wide"					"p0.5"
						"tall"					"40"
						"proportionaltoparent"	"1" 
						"labeltext"				"ON & you need to rename /materials/overviews_ to /overviews/ for avoid shit"
						"font"					"Size 14"
						"textalignment"			"center"
						"command"				"engine jp_anim_radar_on"
						"actionsignallevel"		"5"
						"paintbackground"		"0"
						"border_default"		"FLAT_Black_4"
						"border_armed"			"FLAT_Black_2"
						"sound_depressed"		"UI/buttonclick.wav"
						"sound_released"		"UI/buttonclickrelease.wav"
					}		
					"radar_off"
					{
						"ControlName"			"CExButton"
						"fieldName"				"radar_off"
						"xpos"					"0+p0.5"
						"ypos"					"340-40"
						"wide"					"p0.5"
						"tall"					"40"
						"proportionaltoparent"	"1"
						"labeltext"				"OFF"
						"font"					"Size 14"
						"textalignment"			"center"
						"command"				"engine jp_anim_radar_off"
						"actionsignallevel"		"5"
						"paintbackground"		"0"
						"border_default"		"FLAT_Black_4"
						"border_armed"			"FLAT_Black_2"
						"sound_depressed"		"UI/buttonclick.wav"
						"sound_released"		"UI/buttonclickrelease.wav"
					}						
				}

			}
		}
	}
}