"Resource/UI/CharInfoPanel.res"
{
"PlayerStatusHealthImageBG"
{
"ControlName""ImagePanel"
"fieldName""PlayerStatusHealthImageBG"
"image""../hud/health_bg"
//"visible""1"
////"enabled""1"
"scaleImage""1"
}
}