"Resource/baseaction_sys.res"
{
"ItemEffectMeterLabel"
{
"ControlName""CExLabel"
"fieldName""ItemEffectMeterLabel"
//"xpos""40"
//"ypos""25"
"zpos""2"
//"wide""0"
"tall""15"
//"autoResize""1"
//"pinCorner""2"
//"visible""1"
//"enabled""1"
//"tabPosition""0"
"textAlignment""center"
//"dulltext""0"
//"brighttext""0"
"font""ScoreboardVerySmall"
}
}
