"Resource/baseaction_sys.res"
{
"ItemEffectMeter"
{
"ControlName""ContinuousProgressBar"
"fieldName""ItemEffectMeter"
//"font""Default"
//"xpos""0"
//"ypos""-41"
"zpos""2"
//"wide""40"
//"tall""6"
//"autoResize""0"
//"pinCorner""0"
//"textAlignment""Left"
//"dulltext""0"
//"brighttext""0"
}
}
