	//#base	"../../_stream/resource/ui/charinfopanel.res"
	//#base	"../../_opt/resource/#beta/menu_reloadbutton.res"	
	#base	"../../_jofrenew/resource/ui/charinfopanel.res"
//	#base	"../../_opt/resource/ui/charinfopanel.res"
	#base	"../../z_tf2/resource/ui/charinfopanel.res"