	//#base	"../../_stream/resource/ui/charinfopanel.res"
	//#base	"../../_jofrehud/resource/#beta/menu_reloadbutton.res"	
	#base	"../../_jofrenew/resource/ui/charinfopanel.res"
	//#base	"../../_jofrehud/resource/ui/charinfopanel.res"
	//#base	"../../z_tf2/resource/ui/charinfopanel.res"