	//#base	"../../_stream/resource/ui/classselection.res"
	#base	"../../_jofrenew/resource/ui/classselection.res"
	#base	"../../_opt/resource/ui/classselection.res"
	#base	"../../_library/lighterhud-edit/resource/ui/classselection.res"	
	//#base	"../../z_tf2/resource/ui/classselection.res"