	#base	"../../custom/resource/ui/freezepanelkillerhealth.res"
	#base	"../../_jofrenew/resource/ui/freezepanelkillerhealth.res"
	#base	"../../_jofrehud/resource/ui/freezepanelkillerhealth.res"
	#base	"../../_jofrehud/_tf2fix/resource/ui/freezepanelkillerhealth.res"	
//	#base	"../../_tf2hud/resource/ui/freezepanelkillerhealth.res"