	//#base	"../../_stream/resource/ui/freezepanelkillerhealth.res"
	#base	"../../_jofrenew/resource/ui/freezepanelkillerhealth.res"
	//#base	"../../_opt/resource/ui/freezepanelkillerhealth.res"
	//#base	"../../_opt/_tf2fix/resource/ui/freezepanelkillerhealth.res"	
	#base	"../../z_tf2/resource/ui/freezepanelkillerhealth.res"