	#base	"../../_mainstream/scream-fortress/globalchat.txt"
	#base	"../../_mainstream/global-chat/file.txt"
	#base	"../../_stream/resource/ui/globalchat.res"
	#base	"../../_jofrenew/resource/ui/globalchat.res"
//	#base	"../../_opt/resource/ui/globalchat.res"
	#base	"../../z_tf2/resource/ui/globalchat.res"