	#base	"../../_mainstream/global-chat/file.txt"
	#base	"../../_stream/resource/ui/globalchat.res"
	#base	"../../_jofrenew/resource/ui/globalchat.res"
	//#base	"../../_jofrehud/resource/ui/globalchat.res"
	//#base	"../../z_tf2/resource/ui/globalchat.res"