	#base 	"../../_mainstream/floating-achievement/file.txt"
	//#base	"../../_stream/resource/ui/hudachievementfloatingnumber.res"
	#base	"../../_jofrenew/resource/ui/hudachievementfloatingnumber.res"
	#base	"../../_opt/resource/ui/hudachievementfloatingnumber.res"
	#base	"../../z_tf2/resource/ui/hudachievementfloatingnumber.res"