// same as huditemeffectmeter.res"
#base "../../_jofrenew/resource/ui/huditemeffectmeter_pyro.res"
#base "../../_jofrehud/resource/ui/huditemeffectmeter_pyro.res"
#base "../../_tf2hud/resource/ui/huditemeffectmeter_pyro.res"
#base "../../_tf2hud/resource/ui/huditemeffectmeter.res"