	#base	"../../custom/resource/ui/huditemeffectmeter_engineer.res"
	#base	"../../custom/resource/ui/huditemeffectmeter_engineer.res"
	#base	"../../_jofrenew/resource/ui/huditemeffectmeter_engineer.res"
	#base	"../../_jofrehud/resource/ui/huditemeffectmeter_engineer.res"
	#base	"../../_tf2hud/resource/ui/huditemeffectmeter_engineer.res"