"x"
{	

	"HudPlayerHealth"
	{
		"ControlName"	"EditablePanel"
		"fieldName"		"HudPlayerHealth"
		"xpos"			"c-230"
		"ypos"			"325"
		"zpos"			"0"
		"wide"			"124"
		"tall"			"80" //36
		"visible"		"1"
		"enabled"		"1"	
		"HealthBonusPosAdj"	"73"//51
		"HealthDeathWarning"		"1"
		"HealthDeathWarningColor"	"HUDDeathWarning" // never change this
	}	
	"PlayerStatusHealthImage"
	{
		"ControlName"	"Panel"
		"visible"		"0"
	}	
	"PlayerStatusHealthImageBG"
	{
		"ControlName"	"Panel"
		"fieldName"		"PlayerStatusHealthImageBG"
		"visible"		"0"	
	}	
	"TeamColoredAmmoTextBG" // where the plus icons is
	{
		"ControlName"	"CTFImagePanel"
		"fieldName"		"TeamColoredAmmoTextBG"
		"xpos"			"0"
		"ypos"			"0"
		"wide"			"34"
		"tall"			"34"
		"visible"		"1"
		"enabled"		"1"
		"image"			"replay/thumbnails/hp/cover"
		"scaleImage"		"1"
		"teambg_2"		"replay/thumbnails/backpacktf/spectral_spectrum_30"
		"teambg_3"		"replay/thumbnails/backpacktf/spectral_spectrum_blu_30"	
	}	
	"border0"
	{
		"ControlName"		"editablePanel"
		"fieldName"		"border0"
		"xpos"		"0"
		"ypos"		"0"
		zpos 9999
		"wide"		"34"
		"tall"		"34" 
		border noborder
		"bgcolor_override"	"0 0 0 0"
		"visible"		"1"
	}		
	"border1"
	{
		"ControlName"		"editablePanel"
		"fieldName"		"border1"
		"xpos"		"39"
		"ypos"		"0"
		zpos 999
		"wide"		"85+p0.002"
		"tall"		"36" 
		border noborder
		"bgcolor_override"	"0 0 0 0"
		"visible"		"1"
	}	
	"border1a"
	{
		"ControlName"		"editablePanel"
		"fieldName"		"border1a"
		"xpos"		"33"
		"ypos"		"0"
		zpos 9991
		"wide"		"6"
		"tall"		"36" 
		border cleanup
		"bgcolor_override"	"0 0 0 1"
		"visible"		"1"
	}		
	"BarShadow"
	{
		"ControlName"	"ImagePanel"
		"fieldName"		"BarShadow"
		"xpos"			"0"
		"ypos"			"34"
		"wide"			"150"
		"tall"			"2"
		"zpos"	"5"
		"visible"		"1"
		"enabled"		"1"
		"fillcolor"		"0 0 0 0"
		border blurborder
	}
	"overhealthclean"
	{
		"ControlName"	"ImagePanel"
		"fieldName"		"overhealthclean"
		"xpos"			"0-p0.001"
		"ypos"			"35"
		"wide"			"f0"
		"tall"			"f0"
		"zpos"	"5"
		"visible"		"0"
		"enabled"		"1"
		"fillcolor"		"0 0 0 1"
		border cleanup
	}
	"TeamColoredAmmoTextBG2"
	{
		"ControlName"	"CTFImagePanel"
		"fieldName"		"TeamColoredAmmoTextBG2"
		"xpos"			"35"
		"ypos"			"0"
		"zpos"			"1"
		"wide"			"150"
		"tall"			"34"
		"visible"		"1"
		"enabled"		"1"
		"image"			"replay/thumbnails/hp/cover"
		"scaleImage"		"1"
		"teambg_2"		"replay/thumbnails/backpacktf/spectral_spectrum_30"
		"teambg_3"		"replay/thumbnails/backpacktf/spectral_spectrum_blu_30"	
	}
	"HealthBarOverheal"
	{
		"ControlName"		"ImagePanel"
		"fieldName"		"HealthBarOverheal"
		"xpos"			"0-p0.55"
		"ypos"			"-120"
		"zpos"		"5"
		"wide"		"200"
		"tall"		"38"
		"visible"		"0"
		"enabled"		"1"
		"drawcolor"	"100 226 13 255"
		"image"		"replay/thumbnails/materialpanel"
		"scaleimage"	"1"
		"alpha" "255"
		"pin_to_sibling"		"PlayerStatusHealthBonusImage"
		"pin_corner_to_sibling"		"6"
		"pin_to_sibling_corner"		"4"		
	}
	"Healthcrossicon"
	{
		"ControlName"		"ImagePanel"
		"fieldName"		"healthcrossicon"
		"xpos"			"2"
		"ypos"			"2"
		"zpos"			"22"
		"wide"			"30"
		"tall"			"30"
		"visible"		"1"
		"enabled"		"1"
		"image"			"replay/thumbnails/hp/healthcrossicon"
		"scaleimage"	"1"
	}
	"PlayerStatusHealthBonusImage"
	{
		"ControlName"	"CTFImagePanel"
		"fieldName"		"PlayerStatusHealthBonusImage"
		"xpos"			"0"
		"ypos"			"-49"
		"zpos"			"3"
		"wide"			"1000"
		"tall"			"50"
		"visible"		"0"
		"enabled"		"1"
		"image"			"replay/thumbnails/hp/cover"
		"scaleImage"	"1"	
	}
	"PlayerStatusHealthValue"
	{
		"ControlName"	"CExLabel"
		"fieldName"		"PlayerStatusHealthValue"
		"xpos"			"-2421"
		"ypos"			"-5"
		"zpos"			"10"
		"wide"			"5000"
		"tall"			"40"
		"visible"		"1"
		"enabled"		"1"
		"labelText"		"#healthpadded"
		"textAlignment"	"center"	
		"font"			"HealthAndAmmo"
		"fgcolor"		"35 35 35 255"
	}
	"PlayerStatusHealthValueS"
	{
		"ControlName"	"CExLabel"
		"fieldName"		"PlayerStatusHealthValueS"
		"xpos"			"-2421"
		"ypos"			"-5"
		"zpos"			"10"
		"wide"			"5000"
		"tall"			"40"
		"visible"		"1"
		"enabled"		"1"
		"labelText"		"#healthpadded"
		"textAlignment"	"center"	
		"font"			"HealthAndAmmoShadow1" [$WINDOWS]
		"font" 	"blank"	[$LINUX]			
		"fgcolor"		"0 0 0 185"
	}	
	"linuxcover"	[$LINUX]
	{
		"ControlName"	"editablepanel"
		"fieldName"		"linuxcover"
		"xpos"			"36"
		"ypos"			"32"
		"zpos"			"9"
		"wide"			"80"
		"tall"			"2"	
		"bgcolor_override"		"35 35 35 255"
	}		

	"PlayerStatusHealthValueLowester"
	{
		"ControlName"	"CExLabel"
		"fieldName"		"PlayerStatusHealthValueLowester"
		"xpos"			"-139"
		"ypos"			"0"
		"zpos"			"200"
		"wide"			"1"
		"tall"			"0"
		"visible"		"1"
		"enabled"		"1"
		"labelText"		"#3health"
		"textAlignment"	"left"	
		"font"			"1HealthPusherFont"
		"fgcolor"		"10 255 0 200"
		"alpha" 		"0"
		"auto_wide_tocontents" "1"
	}
	"PlayerStatusHealthValueLowestImage3"
	{
		"ControlName"		"ImagePanel"
		"fieldName"		"PlayerStatusHealthValueLowestImage3"
		"xpos"			"34"
		"ypos"			"0"
		"zpos"			"199"
		"wide"			"95"
		"tall"			"34"
		"visible"		"1" [$WINDOWS]
		"visible"		"0" 	[$LINUX]
		"enabled"		"1"
		"fillcolor" 	"0 0 0 40"
		"additive"		"1"
		
		"pin_to_sibling" 	"PlayerStatusHealthValueLowester"
		"pin_corner_to_sibling" "1"
		"pin_to_sibling_corner" "1"
	}
	"PlayerStatusHealthValueLowestImage2"
	{
		"ControlName"		"ImagePanel"
		"fieldName"		"PlayerStatusHealthValueLowestImage2"
		"xpos"			"34"
		"ypos"			"0"
		"zpos"			"5"
		"wide"			"95"
		"tall"			"34"
		"visible"		"1" [$WINDOWS]
		"visible"		"0" 	[$LINUX]
		"enabled"		"1"
		"fillcolor" 	"255 0 0 255"
		"additive"		"1"
		
		"pin_to_sibling" 	"PlayerStatusHealthValueLowester"
		"pin_corner_to_sibling" "1"
		"pin_to_sibling_corner" "1"
	}
	"PlayerStatusHealthValueLowestImage"
	{
		"ControlName"		"ImagePanel"
		"fieldName"		"PlayerStatusHealthValueLowestImage"
		"xpos"			"34"
		"ypos"			"0"
		"zpos"			"205"
		"wide"			"95"
		"tall"			"34"
		"visible"		"1" [$WINDOWS]
		"visible"		"0" 	[$LINUX]
		"enabled"		"1"
		"image" 		"replay/thumbnails/hp/medical_flatline_not_the_hud_guy_add"
		"scaleimage"	"1"
		"alpha"			"255"
		"additive"		"1"
		
		"pin_to_sibling" 	"PlayerStatusHealthValueLowester"
		"pin_corner_to_sibling" "1"
		"pin_to_sibling_corner" "1"
	}
	
	"PlayerStatusHealthValueLowest"
	{
		"ControlName"	"CExLabel"
		"fieldName"		"PlayerStatusHealthValueLowest"
		"xpos"			"-20"
		"ypos"			"-5"
		"zpos"			"5"
		"wide"			"116"//148
		"tall"			"40"
		"visible"		"1"
		"enabled"		"1"
		"labelText"		"#healthlow"
		"textAlignment"	"west"	
		"font"			"LowHealthFont" [$WINDOWS]
		"font" 	"blank"	[$LINUX]	
		"fgcolor"		"255 0 0 255"
		"alpha"			"0" //for the kunai
	}
	"PlayerStatusHealthValueLower"
	{
		"ControlName"	"CExLabel"
		"fieldName"		"PlayerStatusHealthValueLower"
		"xpos"			"-375"//-215    //-302
		"ypos"			"-5"//-5
		"tall"			"0"//35		//38
		"zpos"			"5"
		"wide"			"1000"
		"visible"		"1"
		"enabled"		"1"
		"labelText"		"#healthlow"
		"textAlignment"	"center"	
		"font"			"LowerHealthFont" [$WINDOWS]
		"font" 	"blank"	[$LINUX]	
		"fgcolor"		"255 30 0 100"
		"alpha"			"0" //for the kunai
	}
	"PlayerStatusHealthValueLow"
	{
		"ControlName"	"CExLabel"
		"fieldName"		"PlayerStatusHealthValueLow"
		"xpos"			"-20"
		"ypos"			"-5"
		"zpos"			"5"
		"wide"			"117"
		"tall"			"40"
		"visible"		"1"
		"enabled"		"1"
		"labelText"		"#healthlow"
		"textAlignment"	"west"	
		"font"			"LowHealthFont" [$WINDOWS]
		"font" 	"blank"	[$LINUX]	
		"fgcolor"		"255 135 0 255"
		"alpha"			"0" //for the kunai
	}
	"PlayerStatusHealthValueLowest2"
	{
		"ControlName"	"CExLabel"
		"fieldName"		"PlayerStatusHealthValueLowest2"
		"xpos"			"-80"//-110
		"ypos"			"3"//0
		"wide"			"116"//148
		"tall"			"39"//37
		"zpos" "1"
		"visible"		"1"
		"enabled"		"1"
		"labelText"		"#healthlow"
		"textAlignment"	"west"	
		"font"			"LowHealthFont" [$WINDOWS]
		"font" 	"blank"	[$LINUX]	
		"fgcolor"		"255 0 0 255"
		"alpha"			"0" //for the kunai
	}
	"PlayerStatusHealthValueLower2"
	{
		"ControlName"	"CExLabel"
		"fieldName"		"PlayerStatusHealthValueLower2"
		"xpos"			"-0"//-285
		"ypos"			"2"//0
		"wide"			"1001"//1000
		"visible" "0"
		"labelText"		"#healthlow"
		"textAlignment"	"center"	
		"font"			"LowerHealthFont" [$WINDOWS]
		"font" 	"blank"	[$LINUX]	
		"fgcolor"		"255 30 0 255"
		"alpha"			"0" //for the kunai
	}
	"PlayerStatusHealthValueLow2"
	{
		"ControlName"	"CExLabel"
		"fieldName"		"PlayerStatusHealthValueLow2"
		"xpos"			"-82"//-110
		"ypos"			"4"//0
		"wide"			"117"//150
		"tall"			"36"//36
		"zpos" "1"
		"visible"		"1"
		"enabled"		"1"
		"labelText"		"#healthlow"
		"textAlignment"	"west"	
		"font"			"LowHealthFont" [$WINDOWS]
		"font" 	"blank"	[$LINUX]	
		"fgcolor"		"255 105 0 255"
		"alpha"			"0" //for the kunai
	}

	"HealthDivider"
	{
		"ControlName"		"ImagePanel"
		"fieldName"		"HealthDivider"
		"xpos"			"34"
		"ypos"			"0"
		"zpos"			"200"
		"wide"			"5"
		"tall"			"34"
		"visible"		"1"
		"enabled"		"1"
		"image" 		"replay/thumbnails/hp/REFRACTnormal"
		"scaleimage"	"1"
	}
	"HealthDivider2"
	{
		"ControlName"		"ImagePanel"
		"fieldName"		"HealthDivider2"
		"xpos"			"34"
		"ypos"			"0"
		"zpos"			"79"
		"wide"			"5"
		"tall"			"34"
		"visible"		"1"
		"enabled"		"1"
		"fillcolor"		"TransparentLightBlack"	
	}
	"HealthWhiteCover"
	{
		"ControlName"		"ImagePanel"
		"fieldName"		"HealthWhiteCover"
		"xpos"			"34"
		"ypos"			"0"
		"zpos"			"6"
		"wide"			"19"
		"tall"			"34"
		"visible"		"1"
		"enabled"		"1"
		"fillcolor"		"35 35 35 255"
	}
	"HealthWhiteCover2"
	{
		"ControlName"		"ImagePanel"
		"fieldName"		"HealthWhiteCover2"
		"xpos"			"107"
		"ypos"			"0"
		"zpos"			"6"
		"wide"			"28"
		"tall"			"34"
		"visible"		"1"
		"enabled"		"1"
		"fillcolor"		"35 35 35 255"
	}
	"PlayerStatusBleedImage"
	{
		"ControlName"	"ImagePanel"
		"fieldName"		"PlayerStatusBleedImage"
		"xpos"			"85"
		"xpos_minmode"	"70"
		"ypos"			"0"
		"zpos"			"7"
		"wide"			"32"
		"tall"			"32"
		"visible"		"1"
		"enabled"		"1"
		"scaleImage"	"1"	
		"image"			"../vgui/bleed_drop"
		"fgcolor"		"TanDark"
	}
	"PlayerStatusHookBleedImage"
	{
		"ControlName"	"ImagePanel"
		"fieldName"		"PlayerStatusHookBleedImage"
		"xpos"			"85"
		"xpos_minmode"	"70"
		"ypos"			"0"
		"zpos"			"8"
		"wide"			"32"
		"tall"			"32"
		"visible"		"1"
		"enabled"		"1"
		"scaleImage"	"1"	
		"image"			"../vgui/bleed_drop_grapple"
		"fgcolor"		"TanDark"
	}
	"PlayerStatusMilkImage"
	{
		"ControlName"	"ImagePanel"
		"fieldName"		"PlayerStatusMilkImage"
		"xpos"			"117"
		"xpos_minmode"	"102"
		"ypos"			"0"
		"zpos"			"7"
		"wide"			"32"
		"tall"			"32"
		"visible"		"1"
		"enabled"		"1"
		"scaleImage"	"1"	
		"image"			"../vgui/bleed_drop"
		"fgcolor"		"TanDark"
	}
	"PlayerStatusGasImage"
	{
		"ControlName"	"ImagePanel"
		"fieldName"		"PlayerStatusGasImage"
		"xpos"			"117"
		"xpos_minmode"	"102"
		"ypos"			"0"
		"zpos"			"7"
		"wide"			"32"
		"tall"			"32"
		"visible"		"1"
		"enabled"		"1"
		"scaleImage"	"1"	
		"image"			"../vgui/covered_in_gas"
		"fgcolor"		"TanDark"
	}
	"PlayerStatusMarkedForDeathImage"
	{
		"ControlName"	"ImagePanel"
		"fieldName"		"PlayerStatusMarkedForDeathImage"
		"xpos"			"85"
		"xpos_minmode"	"70"
		"ypos"			"0"
		"zpos"			"7"
		"wide"			"32"
		"tall"			"32"
		"visible"		"1"
		"enabled"		"1"
		"scaleImage"	"1"	
		"image"			"../vgui/marked_for_death"
		"fgcolor"		"TanDark"
	}
	"PlayerStatusMarkedForDeathSilentImage"
	{
		"ControlName"	"ImagePanel"
		"fieldName"		"PlayerStatusMarkedForDeathSilentImage"
		"xpos"			"85"
		"xpos_minmode"	"70"
		"ypos"			"0"
		"zpos"			"7"
		"wide"			"31"
		"tall"			"31"
		"visible"		"1"
		"enabled"		"1"
		"scaleImage"	"1"	
		"image"			"../vgui/marked_for_death"
		"fgcolor"		"TanDark"
	}
	"PlayerStatus_MedicUberBulletResistImage"
	{
		"ControlName"	"ImagePanel"
		"fieldName"		"PlayerStatus_MedicUberBulletResistImage"
		"xpos"			"85"
		"xpos_minmode"	"70"
		"ypos"			"0"
		"zpos"			"7"
		"wide"			"31"
		"tall"			"31"
		"visible"		"1"
		"enabled"		"1"
		"scaleImage"	"1"	
		"image"			"../HUD/defense_buff_bullet_blue"
		"fgcolor"		"TanDark"
	}
	"PlayerStatus_MedicUberBlastResistImage"
	{
		"ControlName"	"ImagePanel"
		"fieldName"		"PlayerStatus_MedicUberBlastResistImage"
		"xpos"			"85"
		"xpos_minmode"	"70"
		"ypos"			"0"
		"zpos"			"7"
		"wide"			"31"
		"tall"			"31"
		"visible"		"1"
		"enabled"		"1"
		"scaleImage"	"1"	
		"image"			"../HUD/defense_buff_explosion_blue"
		"fgcolor"		"TanDark"
	}
	"PlayerStatus_MedicUberFireResistImage"
	{
		"ControlName"	"ImagePanel"
		"fieldName"		"PlayerStatus_MedicUberFireResistImage"
		"xpos"			"85"
		"xpos_minmode"	"70"
		"ypos"			"0"
		"zpos"			"7"
		"wide"			"31"
		"tall"			"31"
		"visible"		"1"
		"enabled"		"1"
		"scaleImage"	"1"	
		"image"			"../HUD/defense_buff_fire_blue"
		"fgcolor"		"TanDark"
	}

	"PlayerStatus_MedicSmallBulletResistImage"
	{
		"ControlName"	"ImagePanel"
		"fieldName"		"PlayerStatus_MedicSmallBulletResistImage"
		"xpos"			"85"
		"xpos_minmode"	"70"
		"ypos"			"0"
		"zpos"			"7"
		"wide"			"31"
		"tall"			"31"
		"visible"		"1"
		"enabled"		"1"
		"scaleImage"	"1"	
		"image"			"../HUD/defense_buff_bullet_blue"
		"fgcolor"		"TanDark"
	}
	"PlayerStatus_MedicSmallBlastResistImage"
	{
		"ControlName"	"ImagePanel"
		"fieldName"		"PlayerStatus_MedicSmallBlastResistImage"
		"xpos"			"85"
		"xpos_minmode"	"70"
		"ypos"			"0"
		"zpos"			"7"
		"wide"			"31"
		"tall"			"31"
		"visible"		"1"
		"enabled"		"1"
		"scaleImage"	"1"	
		"image"			"../HUD/defense_buff_explosion_blue"
		"fgcolor"		"TanDark"
	}
	"PlayerStatus_MedicSmallFireResistImage"
	{
		"ControlName"	"ImagePanel"
		"fieldName"		"PlayerStatus_MedicSmallFireResistImage"
		"xpos"			"85"
		"xpos_minmode"	"70"
		"ypos"			"0"
		"zpos"			"7"
		"wide"			"31"
		"tall"			"31"
		"visible"		"1"
		"enabled"		"1"
		"scaleImage"	"1"	
		"image"			"../HUD/defense_buff_fire_blue"
		"fgcolor"		"TanDark"
	}
	

	"PlayerStatus_WheelOfDoom"
	{
		"ControlName"	"ImagePanel"
		"fieldName"		"PlayerStatus_WheelOfDoom"
		"xpos"			"130"
		"xpos_minmode"	"145"
		"ypos"			"38"
		"ypos_minmode"	"55"
		"zpos"			"7"
		"wide"			"32"
		"tall"			"32"
		"visible"		"1"
		"enabled"		"1"
		"scaleImage"	"1"	
		"image"			"../signs/death_wheel_whammy"
		"fgcolor"		"TanDark"
	}

	"PlayerStatus_SoldierOffenseBuff"
	{
		"ControlName"	"ImagePanel"
		"fieldName"		"PlayerStatus_SoldierOffenseBuff"
		"xpos"			"85"
		"xpos_minmode"	"70"
		"ypos"			"0"
		"zpos"			"7"
		"wide"			"31"
		"tall"			"31"
		"visible"		"1"
		"enabled"		"1"
		"scaleImage"	"1"	
		"image"			"../HUD/defense_buff_bullet_blue"
		"fgcolor"		"TanDark"
	}

	"PlayerStatus_SoldierDefenseBuff"
	{
		"ControlName"	"ImagePanel"
		"fieldName"		"PlayerStatus_SoldierDefenseBuff"
		"xpos"			"85"
		"xpos_minmode"	"70"
		"ypos"			"0"
		"zpos"			"7"
		"wide"			"31"
		"tall"			"31"
		"visible"		"1"
		"enabled"		"1"
		"scaleImage"	"1"	
		"image"			"../HUD/defense_buff_bullet_blue"
		"fgcolor"		"TanDark"
	}

	"PlayerStatus_SoldierHealOnHitBuff"
	{
		"ControlName"	"ImagePanel"
		"fieldName"		"PlayerStatus_SoldierHealOnHitBuff"
		"xpos"			"85"
		"xpos_minmode"	"70"
		"ypos"			"0"
		"zpos"			"7"
		"wide"			"31"
		"tall"			"31"
		"visible"		"1"
		"enabled"		"1"
		"scaleImage"	"1"	
		"image"			"../HUD/defense_buff_bullet_blue"
		"fgcolor"		"TanDark"
	}
	"PlayerStatus_SpyMarked"
	{
		"ControlName"	"ImagePanel"
		"fieldName"		"PlayerStatus_SpyMarked"
		"xpos"			"115"
		"xpos_minmode"	"70"
		"ypos"			"0"
		"zpos"			"7"
		"wide"			"31"
		"tall"			"31"
		"visible"		"0"
		"enabled"		"1"
		"scaleImage"	"1"	
		"image"			""
		"fgcolor"		"TanDark"
	}
	"PlayerStatus_Parachute"
	{
		"ControlName"	"ImagePanel"
		"fieldName"		"PlayerStatus_Parachute"
		"xpos"			"85"
		"xpos_minmode"	"70"
		"ypos"			"0"
		"zpos"			"7"
		"wide"			"31"
		"tall"			"31"
		"visible"		"0"
		"enabled"		"1"
		"scaleImage"	"1"	
		"image"			""
		"fgcolor"		"TanDark"
	}
	"PlayerStatus_RuneStrength"
	{
		"ControlName"	"ImagePanel"
		"fieldName"		"PlayerStatus_RuneStrength"
		"xpos"			"85"
		"xpos_minmode"	"70"
		"ypos"			"0"
		"zpos"			"7"
		"wide"			"31"
		"tall"			"31"
		"visible"		"1"
		"enabled"		"1"
		"scaleImage"	"1"	
		"image"			"../Effects/powerup_strength_hud"
		"fgcolor"		"TanDark"
	}
	"PlayerStatus_RuneHaste"
	{
		"ControlName"	"ImagePanel"
		"fieldName"		"PlayerStatus_RuneHaste"
		"xpos"			"85"
		"xpos_minmode"	"70"
		"ypos"			"0"
		"zpos"			"7"
		"wide"			"31"
		"tall"			"31"
		"visible"		"1"
		"enabled"		"1"
		"scaleImage"	"1"	
		"image"			"../Effects/powerup_haste_hud"
		"fgcolor"		"TanDark"
	}
	"PlayerStatus_RuneRegen"
	{
		"ControlName"	"ImagePanel"
		"fieldName"		"PlayerStatus_RuneRegen"
		"xpos"			"85"
		"xpos_minmode"	"70"
		"ypos"			"0"
		"zpos"			"7"
		"wide"			"31"
		"tall"			"31"
		"visible"		"1"
		"enabled"		"1"
		"scaleImage"	"1"	
		"image"			"../Effects/powerup_regen_hud"
		"fgcolor"		"TanDark"
	}
	"PlayerStatus_RuneResist"
	{
		"ControlName"	"ImagePanel"
		"fieldName"		"PlayerStatus_RuneResist"
		"xpos"			"85"
		"xpos_minmode"	"70"
		"ypos"			"0"
		"zpos"			"7"
		"wide"			"31"
		"tall"			"31"
		"visible"		"1"
		"enabled"		"1"
		"scaleImage"	"1"	
		"image"			"../Effects/powerup_resist_hud"
		"fgcolor"		"TanDark"
	}
	"PlayerStatus_RuneVampire"
	{
		"ControlName"	"ImagePanel"
		"fieldName"		"PlayerStatus_RuneVampire"
		"xpos"			"85"
		"xpos_minmode"	"70"
		"ypos"			"0"
		"zpos"			"7"
		"wide"			"31"
		"tall"			"31"
		"visible"		"1"
		"enabled"		"1"
		"scaleImage"	"1"	
		"image"			"../Effects/powerup_vampire_hud"
		"fgcolor"		"TanDark"
	}
	"PlayerStatus_RuneReflect"
	{
		"ControlName"	"ImagePanel"
		"fieldName"		"PlayerStatus_RuneReflect"
		"xpos"			"85"
		"xpos_minmode"	"70"
		"ypos"			"0"
		"zpos"			"7"
		"wide"			"31"
		"tall"			"31"
		"visible"		"1"
		"enabled"		"1"
		"scaleImage"	"1"	
		"image"			"../Effects/powerup_reflect_hud"
		"fgcolor"		"TanDark"
	}
	"PlayerStatus_RunePrecision"
	{
		"ControlName"	"ImagePanel"
		"fieldName"		"PlayerStatus_RunePrecision"
		"xpos"			"85"
		"xpos_minmode"	"70"
		"ypos"			"0"
		"zpos"			"7"
		"wide"			"31"
		"tall"			"31"
		"visible"		"1"
		"enabled"		"1"
		"scaleImage"	"1"	
		"image"			"../Effects/powerup_precision_hud"
		"fgcolor"		"TanDark"
	}
	"PlayerStatus_RuneAgility"
	{
		"ControlName"	"ImagePanel"
		"fieldName"		"PlayerStatus_RuneAgility"
		"xpos"			"85"
		"xpos_minmode"	"70"
		"ypos"			"0"
		"zpos"			"7"
		"wide"			"31"
		"tall"			"31"
		"visible"		"1"
		"enabled"		"1"
		"scaleImage"	"1"	
		"image"			"../Effects/powerup_agility_hud"
		"fgcolor"		"TanDark"
	}
	"PlayerStatus_RuneKnockout"
	{
		"ControlName"	"ImagePanel"
		"fieldName"		"PlayerStatus_RuneKnockout"
		"xpos"			"85"
		"xpos_minmode"	"70"
		"ypos"			"0"
		"zpos"			"7"
		"wide"			"31"
		"tall"			"31"
		"visible"		"1"
		"enabled"		"1"
		"scaleImage"	"1"	
		"image"			"../Effects/powerup_knockout_hud"
		"fgcolor"		"TanDark"
	}
	"PlayerStatus_RuneKing"
	{
		"ControlName"	"ImagePanel"
		"fieldName"		"PlayerStatus_RuneKing"
		"xpos"			"85"
		"xpos_minmode"	"70"
		"ypos"			"0"
		"zpos"			"7"
		"wide"			"31"
		"tall"			"31"
		"visible"		"1"
		"enabled"		"1"
		"scaleImage"	"1"	
		"image"			"../Effects/powerup_king_hud"
		"fgcolor"		"TanDark"
	}
	"PlayerStatus_RunePlague"
	{
		"ControlName"	"ImagePanel"
		"fieldName"		"PlayerStatus_RunePlague"
		"xpos"			"85"
		"xpos_minmode"	"70"
		"ypos"			"0"
		"zpos"			"7"
		"wide"			"31"
		"tall"			"31"
		"visible"		"1"
		"enabled"		"1"
		"scaleImage"	"1"	
		"image"			"../Effects/powerup_plague_hud"
		"fgcolor"		"TanDark"
	}
	"PlayerStatus_RuneSupernova"
	{
		"ControlName"	"ImagePanel"
		"fieldName"		"PlayerStatus_RuneSupernova"
		"xpos"			"85"
		"xpos_minmode"	"70"
		"ypos"			"0"
		"zpos"			"7"
		"wide"			"31"
		"tall"			"31"
		"visible"		"1"
		"enabled"		"1"
		"scaleImage"	"1"	
		"image"			"../Effects/powerup_supernova_hud"
		"fgcolor"		"TanDark"
	}
	"PlayerStatusSlowed"
	{
		"ControlName"	"ImagePanel"
		"fieldName"		"PlayerStatusSlowed"
		"xpos"			"85"
		"xpos_minmode"	"70"
		"ypos"			"0"
		"zpos"			"7"
		"wide"			"32"
		"tall"			"32"
		"visible"		"1"
		"enabled"		"1"
		"scaleImage"	"1"	
		"image"			"../vgui/slowed"
		"fgcolor"		"TanDark"
	}
}
