//#base "../../../../cfg/jp_custom_resolution.txt"
#base	"../../_jofrenew/resource/ui/hudplayerhealth.res"
//	#base "../../../../cfg/jp_ui_hudplayerhealth.txt"
//	#base	"../../_jofrenew/fallbackhud/hudplayerhealth.res"
	//#base	"../../custom/resource/ui/hudplayerhealth.res"
//	#base	"../../_jofrenew/resource/ui_overrides/!res_health.res"
//	#base	"../../_jofrenew/resource/ui/hudplayerhealth.res"
//	//#base	"../../_jofrehud/resource/ui/hudplayerhealth.res"
//	#base	"_tf2hud/hudplayerhealth.res"

