	#base	"../../custom/resource/ui/hudplayerclass.res"
	#base	"../../_jofrenew/ui_overrides/playerclass-image/file.res"
	#base	"../../_jofrenew/resource/ui/hudplayerclass.res"
	#base	"../../_jofrehud/resource/ui/hudplayerclass.res"
	#base	"../../_tf2hud/resource/ui/hudplayerclass.res"