#base "../../_jofrehud/resource/ui/base/meters/huditemeffectmeter.res"
#base "../../_jofrehud/resource/ui/base/meters/huditemeffectmeter/main_main.res"
#base "../../_jofrehud/resource/ui/base/meters/itemeffectmeter_bg.res"
//#base "../../_jofrehud/resource/ui/base/meters/itemeffectmeterlabel.res"
#base "../../_jofrehud/resource/ui/base/meters/itemeffectmeterlabel/tf_ball.res"
#base "../../_jofrehud/resource/ui/base/meters/itemeffectmeter.res"
#base "../../_jofrehud/resource/ui/base/image/itemeffecticon.res"

#base "../../z_tf2/resource/ui/hudrocketpack.res"
#base "../../z_tf2/resource/ui/huditemeffectmeter.res"