	#base	"../../custom/resource/ui/hudtournament.res"
	#base	"../../custom/resource/ui/hudtournament.res"
	#base	"../../_jofrenew/resource/ui/hudtournament.res"
	#base	"../../_jofrehud/resource/ui/hudtournament.res"
	#base	"../../_tf2hud/resource/ui/hudtournament.res"