	//#base	"../../_stream/resource/ui/spectator.res"
	#base 	"../../_jofrehud/resource/#beta/spec.res"		
	#base 	"../../_jofrenew/resource/ui/spectator_sc.res"
	#base 	"../../_jofrehud/resource/ui/spectator_sc.res"
	#base	"../../z_tf2/resource/ui/spectator_sc.res"