	#base	"../../#users/custom/resource/ui/spectator.res"
	#base 	"../../_jofrehud/resource/#beta/spec.res"		
	#base 	"../../_stream/resource/ui/spectator_sc.res"
	#base 	"../../_jofrehud/resource/ui/spectator_sc.res"
	#base	"../../_tf2hud/resource/ui/spectator_sc.res"