	#base	"../../_stream/resource/ui/surveypanel_matchquality.res"
	#base	"../../_jofrenew/resource/ui/surveypanel_matchquality.res"
	//#base	"../../_jofrehud/resource/ui/surveypanel_matchquality.res"
	//#base	"../../_jofrehud/_tf2fix/resource/ui/surveypanel_matchquality.res"
//	//#base	"../../_tf2hud/resource/ui/surveypanel_matchquality.res"