	//#base	"../../_stream/resource/ui/vrcalibration.res"
	#base	"../../_jofrenew/resource/ui/vrcalibration.res"
//	#base	"../../_opt/resource/ui/vrcalibration.res"
	//#base	"../../_opt/_tf2fix/resource/ui/vrcalibration.res"	
	#base	"../../z_tf2/resource/ui/vrcalibration.res"