"Resource/EngineVGuiLayout.res"
{
"BuildModeDialog"
{
"ControlName""BuildModeDialog"
"fieldName""BuildModeDialog"
"wide""300"
"tall""420"
//"autoResize""0"
//"pinCorner""0"
"visible""1"
////"enabled""1"
"tabPosition""0"
"settitlebarvisible""1"
"title""#Frame_Untitled"
}
}