"_jofrehud/resource/#jofre/charbg.res"
{
	"BlurMainBG"
	{
	"ControlName""ImagePanel"
	"fieldName""BlurMainBG"
	"xpos""0"
	"ypos""0"
	"zpos""-10"
	"wide""f0"
	"tall""f0"
	"image""replay/thumbnails/hp/REFRACTnormal"
	"visible""1"
	"enabled""1"
	"scaleimage""1"
	}
}