"_jofrehud/resource/#jofre/blur_bg.res"
{
	"BlurMainBG1"
	{
	"ControlName""ImagePanel"
	"fieldName""BlurMainBG1"
	"xpos""rs1"
	"ypos""rs1"
	"zpos""-5"
	"wide""400"
	"tall""o1"
	"image""replay/thumbnails/l4d2/noskill_tank_t"
	"visible""1"
	"enabled""1"
	"scaleimage""1"
	}
}