"AddOns/Hearts/HeartsSetupDialog.res"
{
"SummaryLabel"
{
"ControlName""Label"
"fieldName""SummaryLabel"
//"autoResize""0"
//"pinCorner""0"
"visible""1"
////"enabled""1"
"textAlignment""west"
//"dulltext""0"
//"brighttext""0"
}}