"Admin\DialogAdminServer.res"
{
	"FavoriteGames"
	{
		"ControlName"		"CServerPage"
		"fieldName"		"FavoriteGames"
		"xpos"		"412"
		"ypos"		"182"
		"wide"		"646"
		"tall"		"418"
		//		"0"
		//		"0"
		"visible"		"1"
		"enabled"		"1"
		//		"0"
	}
	"SysMenu"
	{
		"ControlName"		"Menu"
		"fieldName"		"SysMenu"
		"xpos"		"0"
		"ypos"		"0"
		"wide"		"64"
		"tall"		"24"
		//		"0"
		//		"0"
		"visible"		"0"
		"enabled"		"1"
		//		"8"
	}
	"RefreshButton"
	{
		"ControlName"		"Button"
		"fieldName"		"RefreshButton"
		"xpos"		"424"
		"ypos"		"38"
		"wide"		"110"
		"tall"		"24"
		//	"0"
		//		"1"
		"visible"		"1"
		"enabled"		"1"
		//		"1"
		"labelText"		"#BaseGames_Refresh"
		"Command"		"refresh"
		"Default"		"1"
	}
	"AddIPButton"
	{
		"ControlName"		"Button"
		"fieldName"		"AddIPButton"
		"xpos"		"22"
		"ypos"		"364"
		"wide"		"150"
		"tall"		"24"
		//		"0"
		//		"2"
		"visible"		"1"
		"enabled"		"1"
		//		"4"
		"labelText"		"#BaseGames_AddIP"
		"Command"		"addip"
	}
	"ManageButton"
	{
		"ControlName"		"Button"
		"fieldName"		"ManageButton"
		"xpos"		"522"
		"ypos"		"364"
		"wide"		"90"
		"tall"		"24"
		//		"0"
		//		"3"
		"visible"		"1"
		"enabled"		"1"
		//		"7"
		"labelText"		"#BaseGames_Manage"
	}
	"GameList"
	{
		"ControlName"		"ListPanel"
		"fieldName"		"gamelist"
		"xpos"		"26"
		"ypos"		"66"
		"wide"		"600"
		"tall"		"290"
		//	"3"
		//		"0"
		"visible"		"1"
		"enabled"		"1"
		//		"3"
	}
	"StatusLabel"
	{
		"ControlName"		"Label"
		"fieldName"		"StatusLabel"
		"xpos"		"11"
		"ypos"		"395"
		"wide"		"630"
		"tall"		"20"
		//		"0"
		//		"2"
		"visible"		"1"
		"enabled"		"1"
		//		"0"
		"textAlignment"		"north-west"
		"dulltext"		"1"
	}
	"ServerContextMenu"
	{
		"ControlName"		"Menu"
		"fieldName"		"ServerContextMenu"
		"xpos"		"0"
		"ypos"		"0"
		"wide"		"64"
		"tall"		"24"
		//	"0"
		//		"0"
		"visible"		"0"
		"enabled"		"1"
	}
	"Config"
	{
		"ControlName"		"Button"
		"fieldName"		"Config"
		"xpos"		"542"
		"ypos"		"38"
		"wide"		"90"
		"tall"		"24"
		//	"0"
		//		"1"
		"visible"		"1"
		"enabled"		"1"
		//		"2"
		"labelText"		"#BaseGames_Options"
		"Command"		"config"
	}
	"Launch"
	{
		"ControlName"		"Button"
		"fieldName"		"Launch"
		"xpos"		"176"
		"ypos"		"364"
		"wide"		"150"
		"tall"		"24"
		//	"0"
		//		"2"
		"visible"		"1"
		"enabled"		"0"
		//		"5"
		"labelText"		"#BaseGames_Start_Local"
		"Command"		"launch"
	}
	"RemoveButton"
	{
		"ControlName"		"Button"
		"fieldName"		"RemoveButton"
		"xpos"		"422"
		"ypos"		"364"
		"wide"		"90"
		"tall"		"24"
		//	"0"
		//		"3"
		"visible"		"1"
		"enabled"		"1"
		//		"6"
		"labelText"		"#BaseGames_Remove"
		"Command"		"remove"
	}
}
