"Admin/GamePanelInfo.res"
{
	"RulesList"
	{
		"ControlName"		"ListPanel"
		"fieldName"		"RulesList"
		"xpos"		"12"
		"ypos"		"72"
		"wide"		"496"
		"tall"		"216"
		//		"3"
		//		"0"
		"visible"		"1"
		"enabled"		"1"
		//		"1"
	}
	"EditButton"
	{
		"ControlName"		"Button"
		"fieldName"		"EditButton"
		"xpos"		"12"
		"ypos"		"298"
		"wide"		"80"
		"tall"		"24"
		//		"0"
		//		"2"
		"visible"		"1"
		"enabled"		"0"
		//		"2"
		"labelText"		"Edit..."
		"Default"		"1"
	}
	"GameLabel"
	{
		"ControlName"		"Label"
		"fieldName"		"GameLabel"
		"xpos"		"0"
		"ypos"		"12"
		"wide"		"84"
		"tall"		"24"
		//		"0"
		//		"0"
		"visible"		"1"
		"enabled"		"1"
		//		"0"
		"labelText"		"#Dialog_Game_Info_Game_Label"
		"textAlignment"		"east"
	}
	"ServerIPLabel"
	{
		"ControlName"		"Label"
		"fieldName"		"ServerIPLabel"
		"xpos"		"0"
		"ypos"		"40"
		"wide"		"84"
		"tall"		"24"
		//		"0"
		//		"0"
		"visible"		"1"
		"enabled"		"1"
		//		"0"
		"labelText"		"#Dialog_Game_Info_IP_Label"
		"textAlignment"		"east"
	}
	"PlayersLabel"
	{
		"ControlName"		"Label"
		"fieldName"		"PlayersLabel"
		"xpos"		"330"
		"ypos"		"12"
		"wide"		"84"
		"tall"		"24"
		//		"0"
		//		"0"
		"visible"		"1"
		"enabled"		"1"
		//		"0"
		"labelText"		"#Dialog_Game_Info_Players_Label"
		"textAlignment"		"east"
	}
	"UptimeLabel"
	{
		"ControlName"		"Label"
		"fieldName"		"UptimeLabel"
		"xpos"		"330"
		"ypos"		"40"
		"wide"		"84"
		"tall"		"24"
		//		"0"
		//		"0"
		"visible"		"1"
		"enabled"		"1"
		//		"0"
		"labelText"		"Uptime"
		"textAlignment"		"east"
	}
	"GameText"
	{
		"ControlName"		"TextEntry"
		"fieldName"		"GameText"
		"xpos"		"92"
		"ypos"		"12"
		"wide"		"164"
		"tall"		"24"
		//		"0"
		//		"0"
		"visible"		"1"
		"enabled"		"0"
		//		"0"
		"maxchars"		"-1"
		"NumericInputOnly"		"0"
	}
	"ServerIPText"
	{
		"ControlName"		"TextEntry"
		"fieldName"		"ServerIPText"
		"xpos"		"92"
		"ypos"		"40"
		"wide"		"164"
		"tall"		"24"
		//		"0"
		//		"0"
		"visible"		"1"
		"enabled"		"0"
		//		"0"
		"maxchars"		"-1"
		"NumericInputOnly"		"0"
	}
	"PlayersText"
	{
		"ControlName"		"TextEntry"
		"fieldName"		"PlayersText"
		"xpos"		"420"
		"ypos"		"12"
		"wide"		"88"
		"tall"		"24"
		//		"0"
		//		"0"
		"visible"		"1"
		"enabled"		"0"
		//		"0"
		"maxchars"		"-1"
		"NumericInputOnly"		"0"
	}
	"UptimeText"
	{
		"ControlName"		"TextEntry"
		"fieldName"		"UptimeText"
		"xpos"		"420"
		"ypos"		"40"
		"wide"		"88"
		"tall"		"24"
		//		"0"
		//		"0"
		"visible"		"1"
		"enabled"		"0"
		//		"0"
		"maxchars"		"-1"
		"NumericInputOnly"		"0"
	}
}
