"Resource/EngineVGuiLayout.res"
{
"AssetPicker"
{
"fieldName""AssetPicker"
"xpos""147"
"ypos""128"
////"autoResize""0"
//"pinCorner""0"
"visible""1"
////"enabled""1"
//"tabposition""0"
"settitlebarvisible""1"
"title""#Frame_Untitled"
}
}