"Resource/EngineVGuiLayout.res"
{
"Gradient"
{
"ControlName""ImagePanel"
"fieldName""Gradient"
//"visible""1"
////"enabled""1"
"proportionaltoparent""1"
"scaleimage""1"
"mouseinputenabled""0"
"image""gradient_pure_black"
}
}