"Resource/UI/disguise_menu/HudMenuSpyDisguise.res"
{
"ButtonLegendBG"
{
"ControlName""ImagePanel"
"fieldName""ButtonLegendBG"
"xpos""15"
"ypos""134"
"zpos""1"
"wide""442"
"tall""30"
////"autoResize""0"
//"pinCorner""0"
//"visible""1"
////"enabled""1"
//"tabposition""0"
"fillcolor""0 0 0 190"
"PaintBackgroundType""0"
}
}