"Resource/UI/disguise_menu/HudMenuSpyDisguise.res"
{
"TeamToggleHintIcon"
{
"fieldName""TeamToggleHintIcon"
"zpos""1"
////"autoResize""0"
//"pinCorner""0"
//"visible""1"
////"enabled""1"
}
"DisguiseHintIcon"
{
"ControlName""CSCHintIcon"
"fieldName""DisguiseHintIcon"
"xpos""275"
"ypos""136"
"zpos""1"
"wide""25"
"tall""25"
////"autoResize""0"
//"pinCorner""0"
//"visible""1"
////"enabled""1"
"actionSet""InGameHUDControls"
"actionName""menu_select"
}
}