"resource/ui/hudplayerclass.res"
{
"CostLabel"
{
"ControlName""CExLabel"
"fieldName""CostLabel"
"xpos""23"
//"ypos""17"
"zpos""1"
"wide""84"
//"tall""19"
////"autoResize""0"
//"pinCorner""0"
////"enabled""1"
"labelText""%metal%"
"textAlignment""Left"
}
}