"Resource/UI/DashboardPartyMember.res"
{
"Spinner"
{
"ControlName""CTFLogoPanel"
"fieldName""Spinner"
"zpos""104"
//"visible""1"
"proportionaltoparent""1"
"mouseinputenabled""0"
"alpha""200"
"fgcolor_override""Orange"
}
}
