"resource/BaseActionCDTrackStartDialog.res"
{
"DialogFrame"
{
"DetailsView"
{
"ControlName""EditablePanel"
"fieldName""DetailsView"
"ypos""30"
"zpos""100"
"wide""230"
//"visible""1"
"PaintBackgroundType""0"
"bgcolor_override""0 0 0 0"
"skip_autoresize""1"
//"autoResize""0"
}
}
}