"resource/BxBookmarkDialog.res"
{
	"BookmarkDialog"
	{
		"ControlName"		"CBookmarkDialog"
		"fieldName"		"BookmarkDialog"
		"xpos"		"645"
		"ypos"		"370"
		"wide"		"310"
		"tall"		"160"
		//		"3"
		//		"0"
		"visible"		"1"
		"enabled"		"1"
		//		"0"
		"settitlebarvisible"		"1"
		"title"		"Edit Bookmark"
	}
	"NameTextEntry"
	{
		"ControlName"		"TextEntry"
		"fieldName"		"NameTextEntry"
		"xpos"		"50"
		"ypos"		"25"
		"wide"		"250"
		"tall"		"24"
		//		"1"
		//		"0"
		"visible"		"1"
		"enabled"		"1"
		//		"1"
		"maxchars"		"-1"
	}
	"TimeTextEntry"
	{
		"ControlName"		"TextEntry"
		"fieldName"		"TimeTextEntry"
		"xpos"		"50"
		"ypos"		"50"
		"wide"		"60"
		"tall"		"24"
		//		"0"
		//		"0"
		"visible"		"1"
		"enabled"		"1"
		//		"2"
		"editable"		"1"
		"maxchars"		"-1"
		"NumericInputOnly"		"1"
	}
	"NoteTextEntry"
	{
		"ControlName"		"TextEntry"
		"fieldName"		"NoteTextEntry"
		"xpos"		"50"
		"ypos"		"75"
		"wide"		"250"
		"tall"		"44"
		//		"3"
		//		"0"
		"visible"		"1"
		"enabled"		"1"
		//		"3"
		"editable"		"1"
		"maxchars"		"-1"
	}
	"NameLabel"
	{
		"ControlName"		"Label"
		"fieldName"		"NameLabel"
		"xpos"		"10"
		"ypos"		"25"
		"wide"		"40"
		"tall"		"24"
		//		"0"
		//		"0"
		"visible"		"1"
		"enabled"		"1"
		//		"0"
		"labelText"		"Name:"
	}
	"TimeLabel"
	{
		"ControlName"		"Label"
		"fieldName"		"TimeLabel"
		"xpos"		"10"
		"ypos"		"50"
		"wide"		"40"
		"tall"		"24"
		//		"0"
		//		"0"
		"visible"		"1"
		"enabled"		"1"
		//		"0"
		"labelText"		"Time:"
	}
	"NoteLabel"
	{
		"ControlName"		"Label"
		"fieldName"		"NoteLabel"
		"xpos"		"10"
		"ypos"		"75"
		"wide"		"40"
		"tall"		"24"
		//		"0"
		//		"0"
		"visible"		"1"
		"enabled"		"1"
		//		"0"
		"labelText"		"Note:"
	}
	"PrevButton"
	{
		"ControlName"		"Button"
		"fieldName"		"PrevButton"
		"xpos"		"10"
		"ypos"		"125"
		"wide"		"24"
		"tall"		"24"
		//		"0"
		//		"2"
		"visible"		"1"
		"enabled"		"1"
		//		"4"
		"labelText"		"Y"
		"textAlignment"		"center"
		"font"		"VCRControls"
		"Command"		"PrevBookmark"
	}
	"NextButton"
	{
		"ControlName"		"Button"
		"fieldName"		"NextButton"
		"xpos"		"275"
		"ypos"		"125"
		"wide"		"24"
		"tall"		"24"
		//		"0"
		//		"3"
		"visible"		"1"
		"enabled"		"1"
		"labelText"		"X"
		"textAlignment"		"center"
		"font"		"VCRControls"
		"Command"		"NextBookmark"
	}
	"Okay"
	{
		"ControlName"		"Button"
		"fieldName"		"Okay"
		"xpos"		"75"
		"ypos"		"125"
		"wide"		"64"
		"tall"		"24"
		//		"0"
		//		"2"
		"visible"		"1"
		"enabled"		"1"
		//		"6"
		"labelText"		"Okay"
		"Command"		"EditBookmark"
		"Default"		"1"
	}
	"Cancel"
	{
		"ControlName"		"Button"
		"fieldName"		"Cancel"
		"xpos"		"150"
		"ypos"		"125"
		"wide"		"64"
		"tall"		"24"
		//		"0"
		//		"2"
		"visible"		"1"
		"enabled"		"1"
		//		"7"
		"labelText"		"Cancel"
		"Command"		"CancelEditBookmark"
	}
}
