"Resource\BxClipPlayer.res"
{
	"Clip Player"
	{
		"ControlName"		"ClipPlayer"
		"fieldName"		"Clip Player"
		"xpos"		"76"
		"ypos"		"979"
		"zpos"		"1"
		"wide"		"1100"
		"tall"		"36"
		//		"1"
		//		"2"
		"visible"		"1"
		"enabled"		"1"
		//		"0"
	}
	"FirstFrame"
	{
		"ControlName"		"Button"
		"fieldName"		"FirstFrame"
		"xpos"		"407"
		"ypos"		"6"
		"wide"		"24"
		"tall"		"24"
		//		"0"
		//		"0"
		"visible"		"1"
		"enabled"		"1"
		//		"0"
		"labelText"		"W"
		"textAlignment"		"center"
		"font"		"VCRControls"
		"Command"		"OnFirstFrame"
	}
	"PrevClipTop"
	{
		"ControlName"		"Button"
		"fieldName"		"PrevClipTop"
		"xpos"		"434"
		"ypos"		"6"
		"wide"		"24"
		"tall"		"24"
		//		"0"
		//		"0"
		"visible"		"1"
		"enabled"		"1"
		//		"0"
		"labelText"		"["
		"textAlignment"		"center"
		"Command"		"OnPrevClipTop"
	}
	"PrevFrame"
	{
		"ControlName"		"Button"
		"fieldName"		"PrevFrame"
		"xpos"		"461"
		"ypos"		"6"
		"wide"		"24"
		"tall"		"24"
		//		"0"
		//		"0"
		"visible"		"1"
		"enabled"		"1"
		//		"0"
		"labelText"		"Y"
		"textAlignment"		"center"
		"font"		"VCRControls"
		"Command"		"OnPrevFrame"
	}
	"GameRec"
	{
		"ControlName"		"Button"
		"fieldName"		"GameRec"
		"xpos"		"495"
		"ypos"		"3"
		"wide"		"30"
		"tall"		"30"
		//		"0"
		//		"0"
		"visible"		"1"
		"enabled"		"1"
		//		"0"
		"labelText"		"Z"
		"textAlignment"		"center"
		"font"		"VCRControls"
		"Command"		"OnShowRecordGameDialog"
	}
	"PlayPause"
	{
		"ControlName"		"Button"
		"fieldName"		"PlayPause"
		"xpos"		"533"
		"ypos"		"3"
		"wide"		"30"
		"tall"		"30"
		//		"0"
		//		"0"
		"visible"		"1"
		"enabled"		"1"
		//		"0"
		"labelText"		"R"
		"textAlignment"		"center"
		"font"		"VCRControls"
		"Command"		"OnPlayPause"
	}
	"NextFrame"
	{
		"ControlName"		"Button"
		"fieldName"		"NextFrame"
		"xpos"		"574"
		"ypos"		"6"
		"wide"		"24"
		"tall"		"24"
		//		"0"
		//		"0"
		"visible"		"1"
		"enabled"		"1"
		//		"0"
		"labelText"		"X"
		"textAlignment"		"center"
		"font"		"VCRControls"
		"Command"		"OnNextFrame"
	}
	"NextClipTop"
	{
		"ControlName"		"Button"
		"fieldName"		"NextClipTop"
		"xpos"		"601"
		"ypos"		"6"
		"wide"		"24"
		"tall"		"24"
		//		"0"
		//		"0"
		"visible"		"1"
		"enabled"		"1"
		//		"0"
		"labelText"		"]"
		"textAlignment"		"center"
		"Command"		"OnNextClipTop"
	}
	"LastFrame"
	{
		"ControlName"		"Button"
		"fieldName"		"LastFrame"
		"xpos"		"628"
		"ypos"		"6"
		"wide"		"24"
		"tall"		"24"
		//		"0"
		//		"0"
		"visible"		"1"
		"enabled"		"1"
		//		"0"
		"labelText"		"S"
		"textAlignment"		"center"
		"font"		"VCRControls"
		"Command"		"OnLastFrame"
	}
	"TrackMidiTime"
	{
		"ControlName"		"Button"
		"fieldName"		"TrackMidiTime"
		"xpos"		"1049"
		"ypos"		"6"
		"wide"		"24"
		"tall"		"24"
		//		"0"
		//		"1"
		"visible"		"1"
		"enabled"		"1"
		//		"0"
		"labelText"		"R"
		"textAlignment"		"center"
		"font"		"VCRControls"
		"Command"		"TrackMidiTime"
	}
	"RepeatType"
	{
		"ControlName"		"Button"
		"fieldName"		"RepeatType"
		"xpos"		"1076"
		"ypos"		"6"
		"wide"		"24"
		"tall"		"24"
		//		"0"
		//		"1"
		"visible"		"1"
		"enabled"		"1"
		//		"0"
		"labelText"		"+"
		"textAlignment"		"center"
		"font"		"VCRControls"
		"Command"		"RepeatType"
	}
}
