"resource/BxFullscreenViewport.res"
{
	"FullscreenViewport"
	{
		"ControlName"		"CToolViewportFullscreenPanel"
		"xpos"		"0"
		"ypos"		"0"
		"wide"		"784"
		"tall"		"590"
		//		"0"
		//		"0"
		//		"0"
	}
	"Engine"
	{
		"ControlName"		"CToolViewportPage"
		"xpos"		"0"
		"ypos"		"0"
		"wide"		"784"
		"tall"		"590"
		//		"3"
		//		"0"
		//		"0"
	}
	"Clip Player"
	{
		"ControlName"		"ClipPlayer"
		"xpos"		"6"
		"ypos"		"572"
		"zpos"		"1"
		"wide"		"770"
		"tall"		"36"
		//		"1"
		//		"2"
		//		"0"
		//"PinnedCornerOffsetX" "6"
		//"PinnedCornerOffsetY" "-6"
		//"PinnedCornerOffsetY" "-6"
		//"UnpinnedCornerOffsetY" "-42"
	}
	"TimeCode"
	{
		"ControlName"		"CTimeCode"
		"xpos"		"500"
		"ypos"		"5"
		"zpos"		"1"
		"wide"		"300"
		"tall"		"24"
		//		"0"
		//		"0"
		//		"0"
	}
	"ActiveClipLabel"
	{
		"ControlName"		"Label"
		"xpos"		"20"
		"ypos"		"5"
		"wide"		"80"
		"tall"		"12"
		//		"0"
		//		"0"
		//		"0"
		"labelText"		"Active Clip:"
	}
	"ActiveClip"
	{
		"ControlName"		"Label"
		"xpos"		"110"
		"ypos"		"5"
		"wide"		"280"
		"tall"		"12"
		//		"0"
		//		"0"
		//		"0"
		"labelText"		"???"
	}
	"ActiveCameraButton"
	{
		"ControlName"		"Button"
		"xpos"		"16"
		"ypos"		"18"
		"wide"		"88"
		"tall"		"16"
		//		"0"
		//		"0"
		//		"0"
		"labelText"		"Active Camera:"
		"Command"		"ToggleWorkCamera"
		"Default"		"1"
	}
	"ActiveCamera"
	{
		"ControlName"		"Label"
		"xpos"		"110"
		"ypos"		"20"
		"wide"		"280"
		"tall"		"12"
		//		"0"
		//		"0"
		//		"0"
		"labelText"		"???"
	}
	"Clip Slider"
	{
		"ControlName"		"CClipScrubber"
		"xpos"		"16"
		"ypos"		"507"
		"zpos"		"1"
		"wide"		"754"
		"tall"		"34"
		//		"1"
		//		"2"
		//		"0"
		"leftText"		"0.0 s."
		"rightText"		"96.7 s."
	}
}
