"resource/BxInteractiveFilmMakerInfo.res"
{
	"BxMovieInfo"
	{
		"ControlName"		"CInteractiveFilmMakerInfo"
		"fieldName"		"BxMovieInfo"
		"xpos"		"0"
		"ypos"		"0"
		"zpos"		"140"
		"wide"		"1600"
		"tall"		"900"
		//		"0"
		//		"0"
		"visible"		"0"
		"enabled"		"1"
		//		"0"
	}
	"position"
	{
		"ControlName"		"Label"
		"fieldName"		"Position"
		"xpos"		"r400"
		"ypos"		"460"
		"wide"		"400"
		"tall"		"24"
		//		"0"
		//		"0"
		"visible"		"1"
		"enabled"		"1"
		//		"0"
		"labelText"		"pos:  -9820 -5600 21"
		"font"		"Trebuchet20"
	}
	"Angles"
	{
		"ControlName"		"Label"
		"fieldName"		"Angles"
		"xpos"		"r400"
		"ypos"		"485"
		"wide"		"400"
		"tall"		"24"
		//		"0"
		//		"0"
		"visible"		"1"
		"enabled"		"1"
		//		"0"
		"labelText"		"roll: 0 pitch 3 yaw -3"
		"font"		"Trebuchet20"
	}
	"Skipping"
	{
		"ControlName"		"Label"
		"fieldName"		"Skipping"
		"xpos"		"0"
		"ypos"		"450"
		"wide"		"1600"
		"tall"		"30"
		//		"0"
		//		"0"
		"visible"		"0"
		"enabled"		"1"
		//		"0"
		"labelText"		"#Seeking"
		"textAlignment"		"center"
		"font"		"Trebuchet24"
	}
}
