"resource/BxRecordGame.res"
{
	"RecordGame"
	{
		"ControlName"		"CRecordDialog"
		"fieldName"		"RecordGame"
		"xpos"		"575"
		"ypos"		"382"
		"wide"		"480"
		"tall"		"270"
		//		"0"
		//		"0"
		"visible"		"1"
		"enabled"		"1"
		//		"0"
		"settitlebarvisible"		"1"
		"title"		"#Frame_Untitled"
	}
	"frame_topGrip"
	{
		"ControlName"		"Panel"
		"fieldName"		"frame_topGrip"
		"xpos"		"6"
		"ypos"		"0"
		"wide"		"468"
		"tall"		"3"
		//		"0"
		//		"0"
		"visible"		"1"
		"enabled"		"1"
		//		"0"
	}
	"frame_bottomGrip"
	{
		"ControlName"		"Panel"
		"fieldName"		"frame_bottomGrip"
		"xpos"		"6"
		"ypos"		"267"
		"wide"		"462"
		"tall"		"3"
		//		"0"
		//		"0"
		"visible"		"1"
		"enabled"		"1"
		//		"0"
	}
	"frame_leftGrip"
	{
		"ControlName"		"Panel"
		"fieldName"		"frame_leftGrip"
		"xpos"		"0"
		"ypos"		"6"
		"wide"		"3"
		"tall"		"258"
		//		"0"
		//		"0"
		"visible"		"1"
		"enabled"		"1"
		//		"0"
	}
	"frame_rightGrip"
	{
		"ControlName"		"Panel"
		"fieldName"		"frame_rightGrip"
		"xpos"		"477"
		"ypos"		"6"
		"wide"		"3"
		"tall"		"252"
		//		"0"
		//		"0"
		"visible"		"1"
		"enabled"		"1"
		//		"0"
	}
	"frame_tlGrip"
	{
		"ControlName"		"Panel"
		"fieldName"		"frame_tlGrip"
		"xpos"		"0"
		"ypos"		"0"
		"wide"		"6"
		"tall"		"6"
		//		"0"
		//		"0"
		"visible"		"1"
		"enabled"		"1"
		//		"0"
	}
	"frame_trGrip"
	{
		"ControlName"		"Panel"
		"fieldName"		"frame_trGrip"
		"xpos"		"474"
		"ypos"		"0"
		"wide"		"6"
		"tall"		"6"
		//		"0"
		//		"0"
		"visible"		"1"
		"enabled"		"1"
		//		"0"
	}
	"frame_blGrip"
	{
		"ControlName"		"Panel"
		"fieldName"		"frame_blGrip"
		"xpos"		"0"
		"ypos"		"264"
		"wide"		"6"
		"tall"		"6"
		//		"0"
		//		"0"
		"visible"		"1"
		"enabled"		"1"
		//		"0"
	}
	"frame_brGrip"
	{
		"ControlName"		"Panel"
		"fieldName"		"frame_brGrip"
		"xpos"		"468"
		"ypos"		"258"
		"wide"		"12"
		"tall"		"12"
		//		"0"
		//		"0"
		"visible"		"1"
		"enabled"		"1"
		//		"0"
	}
	"frame_caption"
	{
		"ControlName"		"Panel"
		"fieldName"		"frame_caption"
		"xpos"		"0"
		"ypos"		"0"
		"wide"		"470"
		"tall"		"12"
		//		"0"
		//		"0"
		"visible"		"1"
		"enabled"		"1"
		//		"0"
	}
	"frame_minimize"
	{
		"ControlName"		"Button"
		"fieldName"		"frame_minimize"
		"xpos"		"0"
		"ypos"		"0"
		"wide"		"18"
		"tall"		"18"
		//		"0"
		//		"0"
		"visible"		"0"
		"enabled"		"1"
		//		"0"
		"labelText"		"0"
		"textAlignment"		"north-west"
	}
	"frame_maximize"
	{
		"ControlName"		"Button"
		"fieldName"		"frame_maximize"
		"xpos"		"0"
		"ypos"		"0"
		"wide"		"18"
		"tall"		"18"
		//		"0"
		//		"0"
		"visible"		"0"
		"enabled"		"1"
		//		"0"
		"labelText"		"1"
		"textAlignment"		"north-west"
	}
	"frame_mintosystray"
	{
		"ControlName"		"Button"
		"fieldName"		"frame_mintosystray"
		"xpos"		"0"
		"ypos"		"0"
		"wide"		"18"
		"tall"		"18"
		//		"0"
		//		"0"
		"visible"		"0"
		"enabled"		"1"
		//		"0"
		"labelText"		"o"
		"textAlignment"		"north-west"
		"Command"		"MinimizeToSysTray"
	}
	"frame_close"
	{
		"ControlName"		"Button"
		"fieldName"		"frame_close"
		"xpos"		"0"
		"ypos"		"0"
		"wide"		"18"
		"tall"		"18"
		//		"0"
		//		"0"
		"visible"		"0"
		"enabled"		"1"
		//		"0"
		"labelText"		"r"
		"textAlignment"		"north-west"
	}
	"frame_menu"
	{
		"ControlName"		"FrameSystemButton"
		"fieldName"		"frame_menu"
		"xpos"		"7"
		"ypos"		"8"
		"wide"		"7"
		"tall"		"7"
		//		"0"
		//		"0"
		"visible"		"1"
		"enabled"		"1"
		//		"0"
	}
	"Record"
	{
		"ControlName"		"Button"
		"fieldName"		"Record"
		"xpos"		"100"
		"ypos"		"235"
		"wide"		"64"
		"tall"		"24"
		//		"0"
		//		"0"
		"visible"		"1"
		"enabled"		"1"
		//		"0"
		"labelText"		"Record"
		"Command"		"RecordGame"
	}
	"Cancel"
	{
		"ControlName"		"Button"
		"fieldName"		"Cancel"
		"xpos"		"270"
		"ypos"		"235"
		"wide"		"64"
		"tall"		"24"
		//		"0"
		//		"0"
		"visible"		"1"
		"enabled"		"1"
		//		"0"
		"labelText"		"Cancel"
		"Command"		"CancelRecord"
	}
	"ChooseDemLabel"
	{
		"ControlName"		"Label"
		"fieldName"		"ChooseDemLabel"
		"xpos"		"10"
		"ypos"		"25"
		"wide"		"80"
		"tall"		"24"
		//		"0"
		//		"0"
		"visible"		"1"
		"enabled"		"1"
		//		"0"
		"labelText"		"Choose Dem:"
	}
	"ChooseDemText"
	{
		"ControlName"		"TextEntry"
		"fieldName"		"ChooseDemText"
		"xpos"		"75"
		"ypos"		"25"
		"wide"		"250"
		"tall"		"24"
		//		"0"
		//		"0"
		"visible"		"1"
		"enabled"		"1"
		//		"0"
		"editable"		"1"
		"maxchars"		"-1"
	}
	"ChooseMapLabel"
	{
		"ControlName"		"Label"
		"fieldName"		"ChooseMapLabel"
		"xpos"		"10"
		"ypos"		"50"
		"wide"		"80"
		"tall"		"24"
		//		"0"
		//		"0"
		"visible"		"1"
		"enabled"		"1"
		//		"0"
		"labelText"		"Choose Map:"
	}
	"ChooseMapText"
	{
		"ControlName"		"TextEntry"
		"fieldName"		"ChooseMapText"
		"xpos"		"75"
		"ypos"		"50"
		"wide"		"250"
		"tall"		"24"
		//		"0"
		//		"0"
		"visible"		"1"
		"enabled"		"1"
		//		"0"
		"editable"		"1"
		"maxchars"		"-1"
	}
	"ChooseMapButton"
	{
		"ControlName"		"Button"
		"fieldName"		"ChooseMapButton"
		"xpos"		"336"
		"ypos"		"50"
		"wide"		"80"
		"tall"		"24"
		//		"0"
		//		"0"
		"visible"		"1"
		"enabled"		"1"
		//		"0"
		"labelText"		"Choose Map"
		"textAlignment"		"center"
		"Command"		"ChooseMap"
	}
	"RecordCameraPos"
	{
		"ControlName"		"CheckButton"
		"fieldName"		"RecordCameraPos"
		"xpos"		"10"
		"ypos"		"75"
		"wide"		"145"
		"tall"		"24"
		//		"0"
		//		"0"
		"visible"		"1"
		"enabled"		"1"
		//		"0"
		"labelText"		"Record Camera Position"
		"selected"		"1"
	}
	"RecordCameraRot"
	{
		"ControlName"		"CheckButton"
		"fieldName"		"RecordCameraRot"
		"xpos"		"160"
		"ypos"		"75"
		"wide"		"145"
		"tall"		"24"
		//		"0"
		//		"0"
		"visible"		"1"
		"enabled"		"1"
		//		"0"
		"labelText"		"Record Camera Angles"
		"selected"		"1"
	}
	"RecordCameraFOV"
	{
		"ControlName"		"CheckButton"
		"fieldName"		"RecordCameraFOV"
		"xpos"		"330"
		"ypos"		"75"
		"wide"		"140"
		"tall"		"24"
		//		"0"
		//		"0"
		"visible"		"1"
		"enabled"		"1"
		//		"0"
		"labelText"		"Record Camera FOV"
		"selected"		"1"
	}
	"ViewPlayerCam"
	{
		"ControlName"		"CheckButton"
		"fieldName"		"ViewPlayerCam"
		"xpos"		"10"
		"ypos"		"100"
		"wide"		"145"
		"tall"		"24"
		//		"0"
		//		"0"
		"visible"		"1"
		//		"0"
		"labelText"		"View From Player"
		"selected"		"1"
	}
	"TeleportPlayer"
	{
		"ControlName"		"CheckButton"
		"fieldName"		"TeleportPlayer"
		"xpos"		"160"
		"ypos"		"100"
		"wide"		"175"
		"tall"		"24"
		//		"0"
		//		"0"
		"visible"		"1"
		"enabled"		"1"
		//		"0"
		"labelText"		"Snap Player To Tool Camera"
	}
	"Noclip"
	{
		"ControlName"		"CheckButton"
		"fieldName"		"NoClip"
		"xpos"		"330"
		"ypos"		"100"
		"wide"		"100"
		"tall"		"24"
		//		"0"
		//		"0"
		"visible"		"1"
		"enabled"		"1"
		//		"0"
		"labelText"		"Enable noclip"
	}
	"RecordWorld"
	{
		"ControlName"		"CheckButton"
		"fieldName"		"RecordWorld"
		"xpos"		"10"
		"ypos"		"125"
		"wide"		"120"
		"tall"		"24"
		//		"0"
		//		"0"
		"visible"		"1"
		"enabled"		"1"
		//		"0"
		"labelText"		"Record World"
		"selected"		"1"
	}
	"RecordStationary"
	{
		"ControlName"		"CheckButton"
		"fieldName"		"RecordStationary"
		"xpos"		"160"
		"ypos"		"125"
		"wide"		"150"
		"tall"		"24"
		//		"0"
		//		"0"
		"visible"		"1"
		"enabled"		"1"
		//		"0"
		"labelText"		"Record Stationary Ents"
	}
	"RecordSprites"
	{
		"ControlName"		"CheckButton"
		"fieldName"		"RecordSprites"
		"xpos"		"330"
		"ypos"		"125"
		"wide"		"150"
		"tall"		"24"
		//		"0"
		//		"0"
		"visible"		"1"
		"enabled"		"1"
		//		"0"
		"labelText"		"Record Sprites"
	}
	"RecordSounds"
	{
		"ControlName"		"CheckButton"
		"fieldName"		"RecordSounds"
		"xpos"		"10"
		"ypos"		"150"
		"wide"		"120"
		"tall"		"24"
		//		"0"
		//		"0"
		"visible"		"1"
		"enabled"		"1"
		//		"0"
		"labelText"		"Record Sounds"
		"selected"		"1"
	}
	"RecordNarration"
	{
		"ControlName"		"CheckButton"
		"fieldName"		"RecordNarration"
		"xpos"		"160"
		"ypos"		"150"
		"wide"		"130"
		"tall"		"24"
		//		"0"
		//		"0"
		"visible"		"1"
		"enabled"		"1"
		//		"0"
		"labelText"		"Record Narration"
	}
	"RecordNarrationFromStart"
	{
		"ControlName"		"CheckButton"
		"fieldName"		"RecordNarrationFromStart"
		"xpos"		"330"
		"ypos"		"150"
		"wide"		"150"
		"tall"		"24"
		//		"0"
		//		"0"
		"visible"		"1"
		//		"0"
		"labelText"		"From Start of Sequence"
	}
	"SequenceLabel"
	{
		"ControlName"		"Label"
		"fieldName"		"SequenceLabel"
		"xpos"		"30"
		"ypos"		"175"
		"wide"		"119"
		"tall"		"24"
		//		"0"
		//		"0"
		"visible"		"1"
		"enabled"		"1"
		//		"0"
		"labelText"		"Sequence Name"
		"textAlignment"		"east"
	}
	"SequenceText"
	{
		"ControlName"		"TextEntry"
		"fieldName"		"SequenceText"
		"xpos"		"153"
		"ypos"		"175"
		"wide"		"200"
		"tall"		"24"
		//		"0"
		//		"0"
		"visible"		"1"
		"enabled"		"1"
		//		"0"
		"editable"		"1"
		"maxchars"		"-1"
	}
	"ShotLabel"
	{
		"ControlName"		"Label"
		"fieldName"		"ShotLabel"
		"xpos"		"30"
		"ypos"		"200"
		"wide"		"119"
		"tall"		"24"
		//		"0"
		//		"0"
		"visible"		"1"
		"enabled"		"1"
		//		"0"
		"labelText"		"Shot Name"
		"textAlignment"		"east"
	}
	"ShotText"
	{
		"ControlName"		"TextEntry"
		"fieldName"		"ShotText"
		"xpos"		"153"
		"ypos"		"200"
		"wide"		"200"
		"tall"		"24"
		//		"0"
		//		"0"
		"visible"		"1"
		"enabled"		"1"
		//		"0"
		"editable"		"1"
		"maxchars"		"-1"
	}
	"AssetPickerFrame"
	{
		"ControlName"		"CAssetPickerFrame"
		"fieldName"		"AssetPickerFrame"
		"xpos"		"147"
		"ypos"		"128"
		"wide"		"268"
		"tall"		"380"
		//		"0"
		//		"0"
		"visible"		"0"
		"enabled"		"1"
		//		"0"
		"settitlebarvisible"		"1"
		"title"		"#Frame_Untitled"
	}
	"BuildModeDialog"
	{
		"ControlName"		"BuildModeDialog"
		"fieldName"		"BuildModeDialog"
		"xpos"		"0"
		"ypos"		"0"
		"wide"		"300"
		"tall"		"420"
		//		"0"
		//		"0"
		"visible"		"1"
		"enabled"		"1"
		//		"0"
		"settitlebarvisible"		"1"
		"title"		"#Frame_Untitled"
	}
}
