"resource/BxSaveDocumentQuery.res"
{
	"SaveDocumentQuery"
	{
		"ControlName"		"CSaveDocumentQuery"
		"fieldName"		"SaveDocumentQuery"
		"xpos"		"362"
		"ypos"		"324"
		"wide"		"300"
		"tall"		"120"
		//		"0"
		//		"0"
		"visible"		"1"
		"enabled"		"1"
		//		"0"
		"settitlebarvisible"		"1"
		"title"		"#BxSaveChanges"
	}
	"SaveChangesLabel"
	{
		"ControlName"		"Label"
		"fieldName"		"SaveChangesLabel"
		"xpos"		"17"
		"ypos"		"43"
		"wide"		"264"
		"tall"		"24"
		//		"0"
		//		"0"
		"visible"		"1"
		"enabled"		"1"
		//		"0"
		"labelText"		"Save changes to test.dme"
	}
	"Yes"
	{
		"ControlName"		"Button"
		"fieldName"		"Yes"
		"xpos"		"47"
		"ypos"		"87"
		"wide"		"64"
		"tall"		"24"
		//		"0"
		//		"0"
		"visible"		"1"
		"enabled"		"1"
		//		"0"
		"labelText"		"Yes"
		"Command"		"yes"
	}
	"No"
	{
		"ControlName"		"Button"
		"fieldName"		"No"
		"xpos"		"120"
		"ypos"		"87"
		"wide"		"64"
		"tall"		"24"
		//		"0"
		//		"0"
		"visible"		"1"
		"enabled"		"1"
		//		"0"
		"labelText"		"No"
		"Command"		"no"
	}
	"Cancel"
	{
		"ControlName"		"Button"
		"fieldName"		"Cancel"
		"xpos"		"193"
		"ypos"		"87"
		"wide"		"64"
		"tall"		"24"
		//		"0"
		//		"0"
		"visible"		"1"
		"enabled"		"1"
		//		"0"
		"labelText"		"Cancel"
		"Command"		"cancel"
	}
}
