"resource/CustomBindingProperties.res"
{
	"CustomBindingProperties"
	{
		"ControlName"		"CCustomBindingProperties"
		"fieldName"		"CustomBindingProperties"
		"xpos"		"600"
		"ypos"		"325"
		"wide"		"400"
		"tall"		"175"
		//		"0"
		//		"0"
		"visible"		"1"
		"enabled"		"1"
		//		"0"
		"settitlebarvisible"		"1"
		"title"		"#KBCustomBindingEdit"
	}
	"Ok"
	{
		"ControlName"		"Button"
		"fieldName"		"Ok"
		"xpos"		"122"
		"ypos"		"140"
		"wide"		"64"
		"tall"		"24"
		//		"0"
		//		"0"
		"visible"		"1"
		//		"0"
		"labelText"		"#vgui_ok"
		"Command"		"ok"
		"Default"		"1"
	}
	"Cancel"
	{
		"ControlName"		"Button"
		"fieldName"		"Cancel"
		"xpos"		"199"
		"ypos"		"140"
		"wide"		"64"
		"tall"		"24"
		//		"0"
		//		"0"
		"visible"		"1"
		"enabled"		"1"
		//		"0"
		"labelText"		"#vgui_Cancel"
		"Command"		"close"
	}
	"BindingName"
	{
		"ControlName"		"TextEntry"
		"fieldName"		"BindingName"
		"xpos"		"15"
		"ypos"		"50"
		"wide"		"372"
		"tall"		"24"
		//		"0"
		//		"0"
		"visible"		"1"
		"enabled"		"1"
		//		"0"
		"editable"		"1"
		"maxchars"		"-1"
	}
	"Command"
	{
		"ControlName"		"TextEntry"
		"fieldName"		"Command"
		"xpos"		"15"
		"ypos"		"108"
		"wide"		"372"
		"tall"		"24"
		//		"0"
		//		"0"
		"visible"		"1"
		"enabled"		"1"
		//		"0"
		"editable"		"1"
		"maxchars"		"-1"
	}
	"Label1"
	{
		"ControlName"		"Label"
		"fieldName"		"Label1"
		"xpos"		"15"
		"ypos"		"24"
		"wide"		"372"
		"tall"		"24"
		//		"0"
		//		"0"
		"visible"		"1"
		"enabled"		"1"
		//		"0"
		"labelText"		"#KBCustomBindingName"
	}
	"Label2"
	{
		"ControlName"		"Label"
		"fieldName"		"Label2"
		"xpos"		"15"
		"ypos"		"80"
		"wide"		"372"
		"tall"		"24"
		//		"0"
		//		"0"
		"visible"		"1"
		"enabled"		"1"
		//		"0"
		"labelText"		"#KBCustomBindingCommand"
	}
}
