"Resource\DemoUIPanel2.res"
{
	"DemoUIPanel2"
	{
		"ControlName"		"CDemoUIPanel2"
		"fieldName"		"DemoUIPanel2"
		"xpos"		"57"
		"ypos"		"698"
		"wide"		"600"
		"tall"		"85"
		//		"0"
		//		"0"
		"visible"		"1"
		"enabled"		"1"
		//		"0"
		"settitlebarvisible"		"1"
		"title"		"Demo Playback - "
	}
	"DemoPlayPauseResume"
	{
		"ControlName"		"Button"
		"fieldName"		"DemoPlayPauseResume"
		"xpos"		"419"
		"ypos"		"58"
		"wide"		"58"
		"tall"		"24"
		//		"0"
		//		"0"
		"visible"		"1"
		//		"0"
		"labelText"		"Play"
		"textAlignment"		"center"
		"Command"		"play"
	}
	"DemoStop"
	{
		"ControlName"		"Button"
		"fieldName"		"DemoStop"
		"xpos"		"498"
		"ypos"		"5"
		"wide"		"47"
		"tall"		"24"
		//		"0"
		//		"0"
		"visible"		"1"
		//		"0"
		"labelText"		"Stop"
		"textAlignment"		"center"
		"Command"		"stop"
	}
	"DemoLoad"
	{
		"ControlName"		"Button"
		"fieldName"		"DemoLoad"
		"xpos"		"419"
		"ypos"		"5"
		"wide"		"75"
		"tall"		"24"
		//		"0"
		//		"0"
		"visible"		"1"
		"enabled"		"1"
		//		"0"
		"labelText"		"Load..."
		"textAlignment"		"center"
		"Command"		"load"
		"Default"		"1"
	}
	"DemoGoStart"
	{
		"ControlName"		"ToggleButton"
		"fieldName"		"DemoGoStart"
		"xpos"		"315"
		"ypos"		"58"
		"wide"		"32"
		"tall"		"24"
		//		"0"
		//		"0"
		"visible"		"1"
		//		"0"
		"labelText"		"|<"
		"Command"		"reload"
	}
	"DemoGoEnd"
	{
		"ControlName"		"Button"
		"fieldName"		"DemoGoEnd"
		"xpos"		"550"
		"ypos"		"58"
		"wide"		"32"
		"tall"		"24"
		//		"0"
		//		"0"
		"visible"		"1"
		//		"0"
		"labelText"		">|"
	}
	"DemoFastForward"
	{
		"ControlName"		"Button"
		"fieldName"		"DemoFastForward"
		"xpos"		"513"
		"ypos"		"58"
		"wide"		"32"
		"tall"		"24"
		//		"0"
		//		"0"
		"visible"		"1"
		//		"0"
		"labelText"		">>"
	}
	"DemoFastBackward"
	{
		"ControlName"		"Button"
		"fieldName"		"DemoFastBackward"
		"xpos"		"352"
		"ypos"		"58"
		"wide"		"32"
		"tall"		"24"
		//		"0"
		//		"0"
		"visible"		"1"
		//		"0"
		"labelText"		"<<"
	}
	"DemoPrevFrame"
	{
		"ControlName"		"Button"
		"fieldName"		"DemoPrevFrame"
		"xpos"		"390"
		"ypos"		"58"
		"wide"		"24"
		"tall"		"24"
		//		"0"
		//		"0"
		"visible"		"1"
		//		"0"
		"labelText"		"<"
		"Command"		"prevframe"
	}
	"DemoNextFrame"
	{
		"ControlName"		"Button"
		"fieldName"		"DemoNextFrame"
		"xpos"		"483"
		"ypos"		"58"
		"wide"		"24"
		"tall"		"24"
		//		"0"
		//		"0"
		"visible"		"1"
		//		"0"
		"labelText"		">"
		"Command"		"nextframe"
	}
	"DemoProgress"
	{
		"ControlName"		"Slider"
		"fieldName"		"DemoProgress"
		"xpos"		"133"
		"ypos"		"32"
		"wide"		"450"
		"tall"		"25"
		//		"0"
		//		"0"
		"visible"		"1"
		"enabled"		"1"
		//		"0"
	}
	"DemoProgressLabelFrame"
	{
		"ControlName"		"Label"
		"fieldName"		"DemoProgressLabelFrame"
		"xpos"		"12"
		"ypos"		"31"
		"wide"		"116"
		"tall"		"24"
		//		"0"
		//		"0"
		"visible"		"1"
		"enabled"		"1"
		//		"0"
		"labelText"		"Tick: 0 / 0"
		"brighttext"		"1"
	}
	"DemoProgressLabelTime"
	{
		"ControlName"		"Label"
		"fieldName"		"DemoProgressLabelTime"
		"xpos"		"12"
		"ypos"		"58"
		"wide"		"116"
		"tall"		"24"
		//		"0"
		//		"0"
		"visible"		"1"
		"enabled"		"1"
		//		"0"
		"labelText"		"Time: 00:00 / 00:00"
		"brighttext"		"1"
	}
	"DemoSpeedScale"
	{
		"ControlName"		"Slider"
		"fieldName"		"DemoSpeedScale"
		"xpos"		"133"
		"ypos"		"58"
		"wide"		"98"
		"tall"		"24"
		//		"0"
		//		"0"
		"visible"		"1"
		"enabled"		"1"
		//		"0"
	}
	"SpeedScale"
	{
		"ControlName"		"Label"
		"fieldName"		"SpeedScale"
		"xpos"		"231"
		"ypos"		"58"
		"wide"		"54"
		"tall"		"24"
		//		"0"
		//		"0"
		"visible"		"1"
		"enabled"		"1"
		//		"0"
		"labelText"		"100.0 %"
	}
}
