"resource/entityreportpanel.res"
{
	"EntityReportPanel"
	{
		"ControlName"		"CEntityReportPanel"
		"fieldName"		"EntityReportPanel"
		"xpos"		"0"
		"ypos"		"14"
		"wide"		"510"
		"tall"		"522"
		//		"0"
		//		"0"
		"visible"		"1"
		"enabled"		"1"
		//		"0"
	}
	"Entities"
	{
		"ControlName"		"ListPanel"
		"fieldName"		"Entities"
		"xpos"		"10"
		"ypos"		"30"
		"wide"		"412"
		"tall"		"340"
		//		"3"
		//		"0"
		"visible"		"1"
		"enabled"		"1"
		//		"1"
	}
	"GotoButton"
	{
		"ControlName"		"Button"
		"fieldName"		"GotoButton"
		"xpos"		"432"
		"ypos"		"36"
		"wide"		"64"
		"tall"		"24"
		//		"0"
		//		"1"
		"visible"		"1"
		"enabled"		"1"
		//		"0"
		"labelText"		"Go To"
	}
	"DeleteButton"
	{
		"ControlName"		"Button"
		"fieldName"		"DeleteButton"
		"xpos"		"432"
		"ypos"		"70"
		"wide"		"64"
		"tall"		"24"
		//		"0"
		//		"1"
		"visible"		"1"
		"enabled"		"1"
		//		"0"
		"labelText"		"Delete"
		"command"		"Delete"
	}
	"PropertiesButton"
	{
		"ControlName"		"Button"
		"fieldName"		"PropertiesButton"
		"xpos"		"432"
		"ypos"		"104"
		"wide"		"64"
		"tall"		"24"
		//		"0"
		//		"1"
		"visible"		"1"
		"enabled"		"1"
		//		"0"
		"labelText"		"Properties"
		"Default"		"1"
		"command"		"ShowProperties"
	}
	"CloseButton"
	{
		"ControlName"		"Button"
		"fieldName"		"CloseButton"
		"xpos"		"432"
		"ypos"		"490"
		"wide"		"64"
		"tall"		"24"
		//		"0"
		//		"3"
		"visible"		"1"
		"enabled"		"1"
		//		"0"
		"labelText"		"Close"
	}
	"EntitiesLabel"
	{
		"ControlName"		"Label"
		"fieldName"		"EntitiesLabel"
		"xpos"		"10"
		"ypos"		"8"
		"wide"		"64"
		"tall"		"24"
		//		"0"
		//		"0"
		"visible"		"1"
		"enabled"		"1"
		//		"0"
		"labelText"		"Entities:"
	}
	"FilterLabel"
	{
		"ControlName"		"Label"
		"fieldName"		"FilterLabel"
		"xpos"		"10"
		"ypos"		"375"
		"wide"		"64"
		"tall"		"24"
		//		"0"
		//		"2"
		"visible"		"1"
		"enabled"		"1"
		//		"0"
		"labelText"		"Filter:"
	}
	"EverythingRadio"
	{
		"ControlName"		"RadioButton"
		"fieldName"		"EverythingRadio"
		"xpos"		"20"
		"ypos"		"400"
		"wide"		"100"
		"tall"		"24"
		//		"0"
		//		"2"
		"visible"		"1"
		"enabled"		"1"
		//		"0"
		"labelText"		"Everything"
		"SubTabPosition"		"1"
	}
	"PointRadio"
	{
		"ControlName"		"RadioButton"
		"fieldName"		"PointRadio"
		"xpos"		"20"
		"ypos"		"430"
		"wide"		"64"
		"tall"		"24"
		//		"0"
		//		"2"
		"visible"		"1"
		"enabled"		"1"
		//		"0"
		"labelText"		"Point"
		"SubTabPosition"		"2"
	}
	"BrushRadio"
	{
		"ControlName"		"RadioButton"
		"fieldName"		"BrushRadio"
		"xpos"		"20"
		"ypos"		"460"
		"wide"		"64"
		"tall"		"24"
		//		"0"
		//		"2"
		"visible"		"1"
		"enabled"		"1"
		//		"0"
		"labelText"		"Brush"
		"SubTabPosition"		"3"
	}
	"HiddenCheck"
	{
		"ControlName"		"CheckButton"
		"fieldName"		"HiddenCheck"
		"xpos"		"15"
		"ypos"		"490"
		"wide"		"160"
		"tall"		"24"
		//		"0"
		//		"2"
		"visible"		"1"
		"enabled"		"1"
		//		"0"
		"labelText"		"Include Hidden Objects"
	}
	"KeyvalueCheck"
	{
		"ControlName"		"CheckButton"
		"fieldName"		"KeyvalueCheck"
		"xpos"		"180"
		"ypos"		"400"
		"wide"		"100"
		"tall"		"24"
		//		"0"
		//		"2"
		"visible"		"1"
		"enabled"		"1"
		//		"0"
		"labelText"		"By Key/Value"
	}
	"KeyTextEntry"
	{
		"ControlName"		"TextEntry"
		"fieldName"		"KeyTextEntry"
		"xpos"		"197"
		"ypos"		"430"
		"wide"		"64"
		"tall"		"24"
		//		"0"
		//		"2"
		"visible"		"1"
		"enabled"		"1"
		//		"2"
		"editable"		"1"
		"maxchars"		"-1"
	}
	"EqualsLabel"
	{
		"ControlName"		"Label"
		"fieldName"		"EqualsLabel"
		"xpos"		"269"
		"ypos"		"430"
		"wide"		"12"
		"tall"		"24"
		//		"0"
		//		"2"
		"visible"		"1"
		"enabled"		"1"
		//		"0"
		"labelText"		"="
	}
	"ValueTextEntry"
	{
		"ControlName"		"TextEntry"
		"fieldName"		"ValueTextEntry"
		"xpos"		"288"
		"ypos"		"430"
		"wide"		"64"
		"tall"		"24"
		//		"0"
		//		"2"
		"visible"		"1"
		"enabled"		"1"
		//		"3"
		"editable"		"1"
		"maxchars"		"-1"
	}
	"ExactCheck"
	{
		"ControlName"		"CheckButton"
		"fieldName"		"ExactCheck"
		"xpos"		"280"
		"ypos"		"400"
		"wide"		"128"
		"tall"		"24"
		//		"0"
		//		"2"
		"visible"		"1"
		"enabled"		"1"
		//		"0"
		"labelText"		"Exact Matches Only"
	}
	"ClassnameCheck"
	{
		"ControlName"		"CheckButton"
		"fieldName"		"ClassnameCheck"
		"xpos"		"180"
		"ypos"		"460"
		"wide"		"128"
		"tall"		"24"
		//		"0"
		//		"2"
		"visible"		"1"
		"enabled"		"1"
		//		"0"
		"labelText"		"By Class Name"
	}
	"ClassNameComboBox"
	{
		"ControlName"		"ComboBox"
		"fieldName"		"ClassNameComboBox"
		"xpos"		"197"
		"ypos"		"490"
		"wide"		"155"
		"tall"		"24"
		//		"0"
		//		"2"
		"visible"		"1"
		"enabled"		"1"
		//		"4"
		"editable"		"1"
		"maxchars"		"-1"
	}
}
