"resource/KeyBindingHelpDialog.res"
{
	"KeyBindingHelpDialog"
	{
		"ControlName"		"CKeyBindingHelpDialog"
		"fieldName"		"KeyBindingHelpDialog"
		"xpos"		"440"
		"ypos"		"250"
		"wide"		"720"
		"tall"		"400"
		//		"0"
		//		"0"
		"visible"		"1"
		"enabled"		"1"
		//		"0"
		"settitlebarvisible"		"1"
		"title"		"#BxToolTimeline"
	}
	"keybindings"
	{
		"ControlName"		"SectionedListPanel"
		"fieldName"		"KeyBindings"
		"xpos"		"8"
		"ypos"		"19"
		"wide"		"705"
		"tall"		"340"
		//		"3"
		//		"0"
		"visible"		"1"
		"enabled"		"1"
		//		"0"
	}
	"Button1"
	{
		"ControlName"		"Button"
		"fieldName"		"Button1"
		"xpos"		"283"
		"ypos"		"368"
		"wide"		"64"
		"tall"		"24"
		//		"0"
		//		"2"
		"visible"		"1"
		"enabled"		"1"
		//		"0"
		"labelText"		"#vgui_close"
		"Command"		"close"
		"Default"		"1"
	}
	
	"Button2"
	{
		"ControlName"		"Button"
		"fieldName"		"Button2"
		"xpos"		"363"
		"ypos"		"368"
		"wide"		"64"
		"tall"		"24"
		//		"0"
		//		"2"
		"visible"		"1"
		"enabled"		"1"
		//		"0"
		"labelText"		"#KBHelpEditBindings"
		"Command"		"edit"
		"Default"		"1"
	}
}
