"Resource/LoadingDialogErrorLoggedInElsewhere.res"
{
	"LoadingDialog"
	{
		"ControlName"		"CLoadingDialog"
		"fieldName"		"LoadingDialog"
		"xpos"		"600"
		"ypos"		"360"
		"wide"		"400"
		"tall"		"180"
		//		"0"
		//		"0"
		"visible"		"1"
		"enabled"		"1"
		//		"0"
		"settitlebarvisible"		"1"
		"title"		"#VAC_LoggedInElsewhere_Title"
	}
	"progress"
	{
		"ControlName"		"ProgressBar"
		"fieldName"		"Progress"
		"xpos"		"20"
		"ypos"		"88"
		"wide"		"260"
		"tall"		"24"
		//		"0"
		//		"0"
		"visible"		"0"
		"enabled"		"1"
		//		"0"
		"progress"		"0.000000"
	}
	"Progress2"
	{
		"ControlName"		"ProgressBar"
		"fieldName"		"Progress2"
		"xpos"		"0"
		"ypos"		"0"
		"wide"		"64"
		"tall"		"24"
		//		"0"
		//		"0"
		"visible"		"0"
		"enabled"		"1"
		//		"0"
		"progress"		"0.000000"
	}
	"CancelButton"
	{
		"ControlName"		"Button"
		"fieldName"		"CancelButton"
		"xpos"		"300"
		"ypos"		"142"
		"wide"		"72"
		"tall"		"24"
		//		"0"
		//		"0"
		"visible"		"1"
		"enabled"		"1"
		//		"0"
		"labelText"		"#GameUI_RefreshLogin_Login"
		"Command"		"Login"
	}
	"TimeRemainingLabel"
	{
		"ControlName"		"Label"
		"fieldName"		"TimeRemainingLabel"
		"xpos"		"0"
		"ypos"		"0"
		"wide"		"64"
		"tall"		"24"
		//		"0"
		//		"0"
		"visible"		"0"
		"enabled"		"1"
		//		"0"
	}
	"InfoLabel"
	{
		"ControlName"		"Label"
		"fieldName"		"InfoLabel"
		"xpos"		"26"
		"ypos"		"34"
		"wide"		"340"
		"tall"		"88"
		//		"0"
		//		"0"
		"visible"		"1"
		"enabled"		"1"
		//		"0"
		"labelText"		"#VAC_LoggedInElsewhereReason"
		"wrap"		"1"
	}
	"BannerAd"
	{
		"ControlName"		"HTML"
		"fieldName"		"BannerAd"
		"xpos"		"20"
		"ypos"		"202"
		"wide"		"340"
		"tall"		"56"
		//		"0"
		//		"0"
		"visible"		"0"
		"enabled"		"1"
		//		"0"
	}
}
