"Resource\NewOperationDialog.res"
{
	"NewOperation"
	{
		"ControlName"		"CNewOperationDialog"
		"fieldName"		"NewOperation"
		"xpos"		"125"
		"ypos"		"108"
		"wide"		"256"
		"tall"		"136"
		//		"0"
		//		"0"
		"visible"		"1"
		"enabled"		"1"
		//		"0"
		"settitlebarvisible"		"1"
		"title"		"#Frame_Untitled"
	}
	"OperationType"
	{
		"ControlName"		"ComboBox"
		"fieldName"		"OperationType"
		"xpos"		"108"
		"ypos"		"32"
		"wide"		"128"
		"tall"		"24"
		//		"0"
		//		"0"
		"visible"		"1"
		"enabled"		"1"
		//		"0"
		"maxchars"		"-1"
	}
	"name"
	{
		"ControlName"		"TextEntry"
		"fieldName"		"Name"
		"xpos"		"108"
		"ypos"		"60"
		"wide"		"64"
		"tall"		"24"
		//		"0"
		//		"0"
		"visible"		"1"
		"enabled"		"1"
		//		"0"
		"editable"		"1"
		"maxchars"		"-1"
	}
	"Create"
	{
		"ControlName"		"Button"
		"fieldName"		"Create"
		"xpos"		"17"
		"ypos"		"92"
		"wide"		"64"
		"tall"		"24"
		//		"0"
		//		"0"
		"visible"		"1"
		"enabled"		"1"
		//		"0"
		"labelText"		"Create"
		"Command"		"Create"
	}
	"Cancel"
	{
		"ControlName"		"Button"
		"fieldName"		"Cancel"
		"xpos"		"87"
		"ypos"		"92"
		"wide"		"64"
		"tall"		"24"
		//		"0"
		//		"0"
		"visible"		"1"
		"enabled"		"1"
		//		"0"
		"labelText"		"Cancel"
		"Command"		"Cancel"
	}
	"Label1"
	{
		"ControlName"		"Label"
		"fieldName"		"Label1"
		"xpos"		"20"
		"ypos"		"32"
		"wide"		"64"
		"tall"		"24"
		//		"0"
		//		"0"
		"visible"		"1"
		"enabled"		"1"
		//		"0"
		"labelText"		"Operation:"
	}
	"Label2"
	{
		"ControlName"		"Label"
		"fieldName"		"Label2"
		"xpos"		"20"
		"ypos"		"60"
		"wide"		"64"
		"tall"		"24"
		//		"0"
		//		"0"
		"visible"		"1"
		"enabled"		"1"
		//		"0"
		"labelText"		"Name:"
	}
}
