"Resource\OptionsSubPortal.res"
{
	"PortalFunnel"
	{
		"ControlName"		"CCvarToggleCheckButton"
		"xpos"		"28"
		"ypos"		"28"
		"wide"		"148"
		"tall"		"28"
		//		"0"
		//		"0"
		//"RoundedCorners"		"15"
		//		"1"
		"labelText"		"#GameUI_PortalFunnel"
	}
	"PortalDepth"
	{
		"ControlName"		"ComboBox"
		"xpos"		"35"
		"ypos"		"106"
		"wide"		"175"
		"tall"		"24"
		//		"0"
		//		"0"
		//"RoundedCorners"		"15"
		//		"4"
		"maxchars"		"-1"
	}
	"Portal Funnel label"
	{
		"ControlName"		"Label"
		"xpos"		"159"
		"ypos"		"31"
		"wide"		"320"
		"tall"		"24"
		//		"0"
		//		"0"
		//"RoundedCorners"		"15"
		//		"0"
		"labelText"		"#GameUI_PortalFunnelLabel"
	}
	"PortalDepthLabel"
	{
		"ControlName"		"Label"
		"xpos"		"35"
		"ypos"		"82"
		"wide"		"179"
		"tall"		"24"
		//		"0"
		//		"0"
		//"RoundedCorners"		"15"
		//		"0"
		"labelText"		"#GameUI_PortalDepthLabel"
	}
	"BuildModeDialog"
	{
		"ControlName"		"BuildModeDialog"
		"xpos"		"362"
		"ypos"		"174"
		"wide"		"300"
		"tall"		"420"
		//		"0"
		//		"0"
		//"RoundedCorners"		"15"
		//		"0"
		"title"		"#Frame_Untitled"
	}
}
