"Resource\OptionsSubAudio.res"
{
	"SFXSlider"
	{
		"ControlName"		"CCvarSlider"
		"xpos"		"36"
		"ypos"		"43"
		"wide"		"175"
		"tall"		"50"
		//		"0"
		//		"0"
		//"RoundedCorners"		"15"
		//		"1"
		"leftText"		"#GameUI_Low"
		"rightText"		"#GameUI_High"
	}
	"MusicSlider"
	{
		"ControlName"		"CCvarSlider"
		"xpos"		"254"
		"ypos"		"43"
		"wide"		"175"
		"tall"		"50"
		//		"0"
		//		"0"
		//"RoundedCorners"		"15"
		//		"2"
		"leftText"		"#GameUI_Low"
		"rightText"		"#GameUI_High"
	}
	"CloseCaptionCheck"
	{
		"ControlName"		"ComboBox"
		"xpos"		"254"
		"ypos"		"179"
		"wide"		"175"
		"tall"		"24"
		//		"0"
		//		"0"
		//"RoundedCorners"		"15"
		//		"6"
		"maxchars"		"-1"
	}
	"SoundQuality"
	{
		"ControlName"		"ComboBox"
		"xpos"		"254"
		"ypos"		"116"
		"wide"		"175"
		"tall"		"24"
		//		"0"
		//		"0"
		//"RoundedCorners"		"15"
		//		"4"
		"maxchars"		"-1"
	}
	"SpeakerSetup"
	{
		"ControlName"		"ComboBox"
		"xpos"		"36"
		"ypos"		"116"
		"wide"		"175"
		"tall"		"24"
		//		"0"
		//		"0"
		//"RoundedCorners"		"15"
		//		"3"
		"maxchars"		"-1"
	}
	"AudioSpokenLanguage"
	{
		"ControlName"		"ComboBox"
		"xpos"		"36"
		"ypos"		"179"
		"wide"		"175"
		"tall"		"24"
		//		"0"
		//		"0"
		//"RoundedCorners"		"15"
		//		"7"
		"maxchars"		"-1"
	}
	"snd_mute_losefocus"
	{
		"ControlName"		"CCvarToggleCheckButton"
		"xpos"		"33"
		"ypos"		"230"
		"wide"		"430"
		"tall"		"28"
		//		"0"
		//		"0"
		//"RoundedCorners"		"15"
		//		"1"
		"labelText"		"#GameUI_SndMuteLoseFocus"
	}
	"ThirdPartySoundCredits"
	{
		"ControlName"		"URLButton"
		"xpos"		"254"
		"ypos"		"270"
		"wide"		"200"
		"tall"		"24"
		//		"0"
		//		"0"
		//"RoundedCorners"		"15"
		//		"8"
		"labelText"		"#GameUI_ThirdPartyTechCredits"
		"command"		"ShowThirdPartyAudioCredits"
		"Default"		"1"
	}
	"AudioSpokenLanguageLabel"
	{
		"ControlName"		"Label"
		"xpos"		"36"
		"ypos"		"155"
		"wide"		"175"
		"tall"		"24"
		//		"0"
		//		"0"
		//"RoundedCorners"		"15"
		//		"0"
		"labelText"		"#GAMEUI_AudioSpokenLanguage"
	}
	"RequiresRestartLabel"
	{
		"ControlName"		"Label"
		"xpos"		"36"
		"ypos"		"199"
		"wide"		"175"
		"tall"		"24"
		//		"0"
		//		"0"
		//"RoundedCorners"		"15"
		//		"0"
		"labelText"		"#GAMEUI_RequiresRestart"
	}
	"sfx label"
	{
		"ControlName"		"Label"
		"xpos"		"36"
		"ypos"		"19"
		"wide"		"160"
		"tall"		"24"
		//		"0"
		//		"0"
		//"RoundedCorners"		"15"
		//		"0"
		"labelText"		"#GameUI_SoundEffectVolume"
		"associate"		"SFXSlider"
	}
	"MusicVolumeLabel"
	{
		"ControlName"		"Label"
		"xpos"		"254"
		"ypos"		"19"
		"wide"		"160"
		"tall"		"24"
		//		"0"
		//		"0"
		//"RoundedCorners"		"15"
		//		"0"
		"labelText"		"#GameUI_MusicVolume"
		"associate"		"MusicSlider"
	}
	"SoundQualityLabel"
	{
		"ControlName"		"Label"
		"xpos"		"254"
		"ypos"		"92"
		"wide"		"179"
		"tall"		"24"
		//		"0"
		//		"0"
		//"RoundedCorners"		"15"
		//		"0"
		"labelText"		"#GameUI_SoundQuality"
		"associate"		"SoundQuality"
	}
	"SpeakerConfigLabel"
	{
		"ControlName"		"Label"
		"xpos"		"36"
		"ypos"		"92"
		"wide"		"184"
		"tall"		"24"
		//		"0"
		//		"0"
		//"RoundedCorners"		"15"
		//		"0"
		"labelText"		"#GameUI_SpeakerConfiguration"
		"associate"		"SpeakerSetup"
	}
	"TestSpeakersWarning"
	{
		"ControlName"		"Label"
		"xpos"		"36"
		"ypos"		"222"
		"wide"		"182"
		"tall"		"40"
		//		"0"
		//		"0"
		//"RoundedCorners"		"15"
		"visible"		"0"
		//		"0"
		"labelText"		"#GameUI_TestSpeakerSettingsWarning"
		"wrap"		"1"
	}
	"TestSpeakers"
	{
		"ControlName"		"Button"
		"xpos"		"36"
		"ypos"		"194"
		"wide"		"160"
		"tall"		"24"
		//		"0"
		//		"0"
		//"RoundedCorners"		"15"
		"visible"		"0"
		//		"5"
		"labelText"		"#GameUI_TestSpeakerSettings"
		"command"		"TestSpeakers"
		"Default"		"1"
	}
	"Label2"
	{
		"ControlName"		"Label"
		"xpos"		"254"
		"ypos"		"155"
		"wide"		"175"
		"tall"		"24"
		//		"0"
		//		"0"
		//"RoundedCorners"		"15"
		//		"0"
		"labelText"		"#GameUI_Captioning"
		"associate"		"CloseCaptionCheck"
	}
}
