"Resource\OptionsSubMouse.res"
{
	"ReverseMouse"
	{
		"ControlName"		"CCvarNegateCheckButton"
		"xpos"		"28"
		"ypos"		"9"
		"tooltiptext"		"#GameUI_ReverseMouseLabel"
		"wide"		"150"
		"tall"		"28"
		//		"0"
		//		"0"
		//"RoundedCorners"		"15"
		//		"1"
		"labelText"		"#GameUI_ReverseMouse"
	}
	"MouseFilter"
	{
		"ControlName"		"CCvarToggleCheckButton"
		"xpos"		"200"
		"ypos"		"10"
		"tooltiptext"		"#GameUI_MouseFilterLabel"
		"wide"		"150"
		"tall"		"28"
		//		"0"
		//		"0"
		//"RoundedCorners"		"15"
		//		"2"
		"labelText"		"#GameUI_MouseFilter"
	}
	"MouseRaw"
	{
		"ControlName"		"CCvarToggleCheckButton"
		"xpos"		"30"
		"ypos"		"70"
		"tooltiptext"		"#GameUI_MouseRaw_Hint"
		"wide"		"150"
		"tall"		"24"
		//		"0"
		//		"0"
		//"RoundedCorners"		"15"
		//		"0"
		"labelText"		"#GameUI_MouseRaw"
	}
	"MouseAccelerationCheckbox"
	{
		"ControlName"		"CheckButton"
		"xpos"		"30"
		"ypos"		"100"
		"tooltiptext"		"#GameUI_MouseAcceleration_Hint"
		"wide"		"150"
		"tall"		"24"
		//		"0"
		//		"0"
		//"RoundedCorners"		"15"
		//		"0"
		"labelText"		"#GameUI_MouseAcceleration"
	}
	"Joystick"
	{
		"ControlName"		"CCvarToggleCheckButton"
		"xpos"		"28"
		"ypos"		"148"
		"wide"		"226"
		"tall"		"28"
		//		"0"
		//		"0"
		//"RoundedCorners"		"15"
		//		"5"
		"labelText"		"#GameUI_JoystickLabel"
	}
	"JoystickSouthpaw"
	{
		"ControlName"		"CCvarToggleCheckButton"
		"xpos"		"62"
		"ypos"		"202"
		"wide"		"296"
		"tall"		"28"
		//		"0"
		//		"0"
		//"RoundedCorners"		"15"
		//		"6"
		"labelText"		"#GameUI_JoystickSouthpaw"
	}
	"ReverseJoystick"
	{
		"ControlName"		"CCvarToggleCheckButton"
		"xpos"		"62"
		"ypos"		"176"
		"wide"		"296"
		"tall"		"28"
		//		"0"
		//		"0"
		//"RoundedCorners"		"15"
		//		"1"
		"labelText"		"#GameUI_ReverseJoystick"
	}
	"HUDQuickInfo"
	{
		"ControlName"		"CCvarToggleCheckButton"
		"xpos"		"28"
		"ypos"		"167"
		"wide"		"148"
		"tall"		"24"
		//		"0"
		//		"0"
		//"RoundedCorners"		"15"
		"visible"		"0"
		//		"4"
		"labelText"		"#GameUI_HudQuickInfo"
	}
	"Slider"
	{
		"ControlName"		"CCvarSlider"
		"xpos"		"200"
		"ypos"		"40"
		"wide"		"200"
		"tall"		"40"
		//		"0"
		//		"0"
		//"RoundedCorners"		"15"
		//		"0"
		"leftText"		"#GameUI_Low"
		"rightText"		"#GameUI_High"
	}
	"SensitivityLabel"
	{
		"ControlName"		"TextEntry"
		"xpos"		"400"
		"ypos"		"40"
		"wide"		"50"
		"tall"		"24"
		//		"0"
		//		"0"
		//"RoundedCorners"		"15"
		//		"3"
		"editable"		"1"
		"maxchars"		"-1"
		"NumericInputOnly"		"1"
	}
	"MouseAccelerationSlider"
	{
		"ControlName"		"CCvarSlider"
		"xpos"		"200"
		"ypos"		"100"
		"tooltiptext"		"#GameUI_MouseAccelerationAmount_Hint"
		"wide"		"200"
		"tall"		"40"
		//		"0"
		//		"0"
		//"RoundedCorners"		"15"
		"enabled"		"1"	[!$OSX]
		"enabled"		"0" [$OSX]
		//		"0"
		"leftText"		"Low"
		"rightText"		"High"
	}
	"MouseAccelerationLabel"
	{
		"ControlName"		"TextEntry"
		"xpos"		"400"
		"ypos"		"100"
		"tooltiptext"		"#GameUI_MouseAccelerationAmount_Hint"
		"wide"		"50"
		"tall"		"24"
		//		"0"
		//		"0"
		//"RoundedCorners"		"15"
		"enabled"		"1"
		//		"0"
		"editable"		"1"
		"maxchars"		"-1"
	}
	"JoystickYawSlider"
	{
		"ControlName"		"CCvarSlider"
		"xpos"		"232"
		"ypos"		"237"
		"wide"		"186"
		"tall"		"40"
		//		"0"
		//		"0"
		//"RoundedCorners"		"15"
		//		"0"
		"leftText"		"#GameUI_Low"
		"rightText"		"#GameUI_High"
	}
	"JoystickYawSensitivityPreLabel"
	{
		"ControlName"		"Label"
		"xpos"		"70"
		"ypos"		"235"
		"wide"		"148"
		"tall"		"24"
		//		"0"
		//		"0"
		//"RoundedCorners"		"15"
		//		"0"
		"labelText"		"#GameUI_JoystickLookSpeedYaw"
	}
	"JoystickPitchSlider"
	{
		"ControlName"		"CCvarSlider"
		"xpos"		"232"
		"ypos"		"274"
		"wide"		"186"
		"tall"		"40"
		//		"0"
		//		"0"
		//"RoundedCorners"		"15"
		//		"0"
		"leftText"		"#GameUI_Low"
		"rightText"		"#GameUI_High"
	}
	"JoystickPitchSensitivityPreLabel"
	{
		"ControlName"		"Label"
		"xpos"		"70"
		"ypos"		"270"
		"wide"		"148"
		"tall"		"24"
		//		"0"
		//		"0"
		//"RoundedCorners"		"15"
		//		"0"
		"labelText"		"#GameUI_JoystickLookSpeedPitch"
	}
	"JoystickYawSensitivityLabel"
	{
		"ControlName"		"TextEntry"
		"xpos"		"500"
		"ypos"		"179"
		"wide"		"48"
		"tall"		"24"
		//		"0"
		//		"0"
		//"RoundedCorners"		"15"
		//		"3"
		"editable"		"1"
		"maxchars"		"-1"
		"NumericInputOnly"		"1"
	}
	"JoystickPitchSensitivityLabel"
	{
		"ControlName"		"TextEntry"
		"xpos"		"555"
		"ypos"		"256"
		"wide"		"48"
		"tall"		"24"
		//		"0"
		//		"0"
		//"RoundedCorners"		"15"
		//		"3"
		"editable"		"1"
		"maxchars"		"-1"
		"NumericInputOnly"		"1"
	}
	"Label3"
	{
		"ControlName"		"Label"
		"xpos"		"35"
		"ypos"		"40"
		"wide"		"148"
		"tall"		"24"
		//		"0"
		//		"0"
		//"RoundedCorners"		"15"
		//		"0"
		"labelText"		"#GameUI_MouseSensitivity"
	}
	"Label1"
	{
		"ControlName"		"Label"
		"xpos"		"182"
		"ypos"		"167"
		"wide"		"301"
		"tall"		"24"
		//		"0"
		//		"0"
		//"RoundedCorners"		"15"
		"visible"		"0"
		//		"0"
		"labelText"		"#GameUI_HudQuickInfo_Info"
	}
	"Divider1"
	{
		"ControlName"		"Divider"
		"xpos"		"35"
		"ypos"		"140"
		"wide"		"396"
		"tall"		"2"
		//		"0"
		//		"0"
		//"RoundedCorners"		"15"
		//		"0"
	}
	"BuildModeDialog"
	{
		"ControlName"		"BuildModeDialog"
		"xpos"		"1081"
		"ypos"		"390"
		"wide"		"300"
		"tall"		"420"
		//		"0"
		//		"0"
		//"RoundedCorners"		"15"
		//		"0"
		"title"		"#Frame_Untitled"
	}
}
