"Resource\OptionsSubVoice.res"
{
	"MicMeter"
	{
		"ControlName"		"ImagePanel"
		"fieldName"		"MicMeter"
		"xpos"			"40"
		"ypos"			"148"
		"wide"			"158"
		"tall"			"32"
		//		"0"
		//		"0"
		"visible"		"1"
		"enabled"		"1"
		//		"0"
		"image"			"resource/mic_meter_dead"
		"image2"		"resource/mic_meter_live"
		"barCount"		"19"
		"barSpacing"		"8"
	}
	"MicMeter2"
	{
		"ControlName"		"ImagePanel"
		"fieldName"		"MicMeter"
		"xpos"			"40"
		"ypos"			"148"
		"wide"			"158"
		"tall"			"32"
		//		"0"
		//		"0"
		"visible"		"1"
		"enabled"		"1"
		//		"0"
		"image"		"resource/mic_meter_live"
		"barCount"		"19"
		"barSpacing"		"8"
	}
	"VoiceReceive"
	{
		"ControlName"		"CCvarSlider"
		"fieldName"		"VoiceReceive"
		"xpos"		"246"
		"ypos"		"94"
		"wide"		"160"
		"tall"		"42"
		//		"0"
		//		"0"
		"visible"		"1"
		"enabled"		"1"
		//		"3"
		"leftText"		""
		"rightText"		""
	}
	"#GameUI_MicrophoneVolume"
	{
		"ControlName"		"Panel"
		"fieldName"		"#GameUI_MicrophoneVolume"
		"xpos"		"40"
		"ypos"		"94"
		"wide"		"160"
		"tall"		"26"
		//		"0"
		//		"0"
		"visible"		"1"
		"enabled"		"1"
		//		"2"
	}
	"voice_modenable"
	{
		"ControlName"		"CheckButton"
		"fieldName"		"voice_modenable"
		"xpos"		"33"
		"ypos"		"32"
		"wide"		"216"
		"tall"		"28"
		//		"0"
		//		"0"
		"visible"		"1"
		"enabled"		"1"
		//		"1"
		"labelText"		"#GameUI_EnableVoice"
	}
	"MicBoost"
	{
		"ControlName"		"CheckButton"
		"fieldName"		"MicBoost"
		"xpos"		"33"
		"ypos"		"212"
		"wide"		"216"
		"tall"		"28"
		//		"0"
		//		"0"
		"visible"		"1"
		"enabled"		"1"
		//		"5"
		"labelText"		"#GameUI_BoostMicrophone"
	}
	"Microphonelabel"
	{
		"ControlName"		"Label"
		"fieldName"		"Transmit label"
		"xpos"		"42"
		"ypos"		"70"
		"wide"		"180"
		"tall"		"24"
		//		"0"
		//		"0"
		"visible"		"1"
		"enabled"		"1"
		//		"0"
		"associate"		"#GameUI_MicrophoneVolume"
		"labelText"		"#GameUI_VoiceTransmitVolume"
	}
	"ReceiveLabel"
	{
		"ControlName"		"Label"
		"fieldName"		"Label1"
		"xpos"		"246"
		"ypos"		"70"
		"wide"		"180"
		"tall"		"24"
		//		"0"
		//		"0"
		"visible"		"1"
		"enabled"		"1"
		//		"0"
		"labelText"		"#GameUI_VoiceReceiveVolume"
		"associate"		"VoiceReceive"
	}
	"topHorizLeft"
	{
		"ControlName"		"Label"
		"fieldName"		"topHorizLeft"
		"xpos"		"13"
		"ypos"		"163"
		"wide"		"14"
		"tall"		"16"
		//		"0"
		//		"0"
		"visible"		"0"
		"enabled"		"1"
		//		"0"
		"labelText"		"40"
	}
	"topVertLeft"
	{
		"ControlName"		"Label"
		"fieldName"		"topVertLeft"
		"xpos"		"22"
		"ypos"		"80"
		"wide"		"21"
		"tall"		"16"
		//		"0"
		//		"0"
		"visible"		"0"
		"enabled"		"1"
		//		"0"
		"labelText"		"176"
	}
	"bottomHorizRight"
	{
		"ControlName"		"Label"
		"fieldName"		"bottomHorizRight"
		"xpos"		"321"
		"ypos"		"197"
		"wide"		"21"
		"tall"		"16"
		//		"0"
		//		"0"
		"visible"		"0"
		"enabled"		"1"
		//		"0"
		"labelText"		"176"
	}
	"bottomVertRight"
	{
		"ControlName"		"Label"
		"fieldName"		"bottomVertRight"
		"xpos"		"160"
		"ypos"		"248"
		"wide"		"21"
		"tall"		"16"
		//		"0"
		//		"0"
		"visible"		"0"
		"enabled"		"1"
		//		"0"
		"labelText"		"176"
	}
	"TestMicrophone"
	{
		"ControlName"		"Button"
		"fieldName"		"TestMicrophone"
		"xpos"		"40"
		"ypos"		"176"
		"wide"		"160"
		"tall"		"24"
		//		"0"
		//		"0"
		"visible"		"1"
		"enabled"		"1"
		//		"4"
		"labelText"		"#GameUI_TestMicrophone"
		"command"		"TestMicrophone"
	}
	"MilesVoiceLabel"
	{
		"ControlName"		"Label"
		"fieldName"		"MilesVoiceLabel"
		"xpos"			"43"
		"ypos"			"250"
		"wide"			"350"
		"tall"			"48"
		//		"0"
		//		"0"
		"visible"		"1"
		"enabled"		"1"
		//		"0"
		"labelText"		"#GameUI_Miles_Voice"
		"dulltext"		"1"
		"wrap"			"1"
	}
}
