"Resource/OptionsSubDifficulty.res"
{
	"Skill1Radio"
	{
		"ControlName"		"RadioButton"
		"xpos"		"34"
		"ypos"		"58"
		"wide"		"140"
		"tall"		"24"
		//		"0"
		//		"0"
		//		"1"
		"labelText"		"#GameUI_SkillEasy"
	}
	"Skill2Radio"
	{
		"ControlName"		"RadioButton"
		"xpos"		"34"
		"ypos"		"116"
		"wide"		"140"
		"tall"		"24"
		//		"0"
		//		"0"
		//		"1"
		"labelText"		"#GameUI_SkillNormal"
	}
	"Skill3Radio"
	{
		"ControlName"		"RadioButton"
		"xpos"		"34"
		"ypos"		"176"
		"wide"		"140"
		"tall"		"24"
		//		"0"
		//		"0"
		//		"1"
		"labelText"		"#GameUI_SkillHard"
	}
	"Label1"
	{
		"ControlName"		"Label"
		"xpos"		"36"
		"ypos"		"24"
		"wide"		"212"
		"tall"		"24"
		//		"0"
		//		"0"
		//		"0"
		"labelText"		"#GameUI_SelectDifficulty"
	}
	"Label2"
	{
		"ControlName"		"Label"
		"xpos"		"60"
		"ypos"		"80"
		"wide"		"380"
		"tall"		"36"
		//		"0"
		//		"0"
		//		"0"
		"labelText"		"#GameUI_EasyDescription"
		"wrap"		"1"
	}
	"Label3"
	{
		"ControlName"		"Label"
		"xpos"		"60"
		"ypos"		"138"
		"wide"		"380"
		"tall"		"36"
		//		"0"
		//		"0"
		//		"0"
		"labelText"		"#GameUI_NormalDescription"
		"wrap"		"1"
	}
	"Label4"
	{
		"ControlName"		"Label"
		"xpos"		"60"
		"ypos"		"198"
		"wide"		"380"
		"tall"		"36"
		//		"0"
		//		"0"
		//		"0"
		"labelText"		"#GameUI_HardDescription"
		"wrap"		"1"
	}
}
