"resource/OptionsSubVideoGammaDlg.res"
{
	"OptionsSubVideoGammaDlg"
	{
		"ControlName"		"CGammaDialog"
		"xpos"		"490"
		"ypos"		"312"
		"wide"		"290"
		"tall"		"396"
		//		"0"
		//		"0"
		//		"0"
		"title"		"#GameUI_AdjustGamma_Title"
	}
	"Gamma"
	{
		"ControlName"		"CCvarSlider"
		"xpos"		"17"
		"ypos"		"112"
		"wide"		"200"
		"tall"		"40"
		//		"0"
		//		"0"
		//		"1"
		"leftText"		"#GameUI_LIGHT"
		"rightText"		"#GameUI_DARK"
	}
	"Gamma label"
	{
		"ControlName"		"Label"
		"xpos"		"16"
		"ypos"		"88"
		"wide"		"108"
		"tall"		"24"
		//		"0"
		//		"0"
		//		"0"
		"labelText"		"#GameUI_Gamma"
	}
	"GammaEntry"
	{
		"ControlName"		"TextEntry"
		"xpos"		"228"
		"ypos"		"114"
		"wide"		"44"
		"tall"		"24"
		//		"0"
		//		"0"
		//		"2"
		"editable"		"1"
		"maxchars"		"-1"
		"NumericInputOnly"		"1"
	}
	"OKButton"
	{
		"ControlName"		"Button"
		"xpos"		"104"
		"ypos"		"356"
		"wide"		"80"
		"tall"		"24"
		//		"0"
		//		"0"
		//		"3"
		"labelText"		"#vgui_ok"
		"Default"		"1"
	}
	"ImagePanel1"
	{
		"ControlName"		"ImagePanel"
		"xpos"		"16"
		"ypos"		"156"
		"zpos"		"-1"
		"wide"		"256"
		"tall"		"192"
		//		"0"
		//		"0"
		//		"0"
		"image"		"gamma"
		"scaleImage"		"0"
	}
	"Button1"
	{
		"ControlName"		"Button"
		"xpos"		"192"
		"ypos"		"356"
		"wide"		"80"
		"tall"		"24"
		//		"0"
		//		"0"
		//		"4"
		"labelText"		"#vgui_Cancel"
		"Command"		"Close"
	}
	"Label1"
	{
		"ControlName"		"Label"
		"xpos"		"16"
		"ypos"		"36"
		"wide"		"264"
		"tall"		"53"
		//		"0"
		//		"0"
		//		"0"
		"labelText"		"#GameUI_GammaInfo"
		"wrap"		"1"
	}
}
