"resource/OptionsSubVideoAdvancedDlg.res"
{
	"OptionsSubVideoAdvancedDlg"
	{
		"ControlName"		"COptionsSubVideoAdvancedDlg"
		"xpos"		"719"
		"ypos"		"406"
		"wide"		"482"
		"tall"		"510" [!$OSX]
		"tall"		"358" [$OSX]
		//		"0"
		//		"0"
		//		"0"
		"title"		"#GameUI_VideoAdvanced_Title"
	}
	"frame_topGrip"
	{
		"ControlName"		"Panel"
		"xpos"		"8"
		"ypos"		"0"
		"wide"		"466"
		"tall"		"5"
		//		"0"
		//		"0"
		//		"0"
	}
	"frame_bottomGrip"
	{
		"ControlName"		"Panel"
		"xpos"		"8"
		"ypos"		"503"
		"wide"		"456"
		"tall"		"5"
		//		"0"
		//		"0"
		//		"0"
	}
	"frame_leftGrip"
	{
		"ControlName"		"Panel"
		"xpos"		"0"
		"ypos"		"8"
		"wide"		"5"
		"tall"		"492"
		//		"0"
		//		"0"
		//		"0"
	}
	"frame_rightGrip"
	{
		"ControlName"		"Panel"
		"xpos"		"477"
		"ypos"		"8"
		"wide"		"5"
		"tall"		"482"
		//		"0"
		//		"0"
		//		"0"
	}
	"frame_tlGrip"
	{
		"ControlName"		"Panel"
		"xpos"		"0"
		"ypos"		"0"
		"wide"		"8"
		"tall"		"8"
		//		"0"
		//		"0"
		//		"0"
	}
	"frame_trGrip"
	{
		"ControlName"		"Panel"
		"xpos"		"474"
		"ypos"		"0"
		"wide"		"8"
		"tall"		"8"
		//		"0"
		//		"0"
		//		"0"
	}
	"frame_blGrip"
	{
		"ControlName"		"Panel"
		"xpos"		"0"
		"ypos"		"500"
		"wide"		"8"
		"tall"		"8"
		//		"0"
		//		"0"
		//		"0"
	}
	"frame_brGrip"
	{
		"ControlName"		"Panel"
		"xpos"		"464"
		"ypos"		"490"
		"wide"		"18"
		"tall"		"18"
		//		"0"
		//		"0"
		//		"0"
	}
	"frame_caption"
	{
		"ControlName"		"Panel"
		"xpos"		"0"
		"ypos"		"0"
		"wide"		"472"
		"tall"		"23"
		//		"0"
		//		"0"
		//		"0"
	}
	"frame_minimize"
	{
		"ControlName"		"Button"
		"xpos"		"0"
		"ypos"		"0"
		"wide"		"18"
		"tall"		"18"
		//		"0"
		//		"0"
		"visible"		"0"
		//		"0"
		"labelText"		"0"
	}
	"frame_maximize"
	{
		"ControlName"		"Button"
		"xpos"		"0"
		"ypos"		"0"
		"wide"		"18"
		"tall"		"18"
		//		"0"
		//		"0"
		"visible"		"0"
		//		"0"
		"labelText"		"1"
	}
	"frame_mintosystray"
	{
		"ControlName"		"Button"
		"xpos"		"0"
		"ypos"		"0"
		"wide"		"18"
		"tall"		"18"
		//		"0"
		//		"0"
		"visible"		"0"
		//		"0"
		"labelText"		"o"
		"Command"		"MinimizeToSysTray"
	}
	"frame_close"
	{
		"ControlName"		"Button"
		"xpos"		"457"
		"ypos"		"8"
		"wide"		"18"
		"tall"		"18"
		//		"0"
		//		"0"
		//		"0"
		"labelText"		"r"
	}
	"frame_menu"
	{
		"ControlName"		"FrameSystemButton"
		"xpos"		"7"
		"ypos"		"8"
		"wide"		"18"
		"tall"		"18"
		//		"0"
		//		"0"
		//		"0"
	}
	"dxlabel"
	{
		"ControlName"		"ComboBox"
		"xpos"		"330"
		"ypos"		"385"
		"wide"		"132"
		"tall"		"24"
		//		"0"
		//		"0"
		//		"14"
		"maxchars"		"-1"
	}
	"ModelDetail"
	{
		"ControlName"		"ComboBox"
		"xpos"		"22"
		"ypos"		"58"
		"wide"		"132"
		"tall"		"24"
		//		"0"
		//		"0"
		//		"1"
		"maxchars"		"-1"
	}
	"TextureDetail"
	{
		"ControlName"		"ComboBox"
		"xpos"		"176"
		"ypos"		"58"
		"wide"		"132"
		"tall"		"24"
		//		"0"
		//		"0"
		//		"2"
		"maxchars"		"-1"
	}
	"FilteringMode"
	{
		"ControlName"		"ComboBox"
		"xpos"		"176"
		"ypos"		"196"
		"wide"		"132"
		"tall"		"24"
		//		"0"
		//		"0"
		//		"8"
		"maxchars"		"-1"
	}
	"ShadowDetail"
	{
		"ControlName"		"ComboBox"
		"xpos"		"176"
		"ypos"		"118"
		"wide"		"132"
		"tall"		"24"
		//		"0"
		//		"0"
		//		"5"
		"maxchars"		"-1"
	}
	"HDR"
	{
		"ControlName"		"ComboBox"
		"xpos"		"22"
		"ypos"		"316"
		"wide"		"132"
		"tall"		"24"
		//		"0"
		//		"0"
		"visible"		"1" 
		//		"12"
		"maxchars"		"-1"
	}
	"WaterDetail"
	{
		"ControlName"		"ComboBox"
		"xpos"		"22"
		"ypos"		"118"
		"wide"		"132"
		"tall"		"24"
		//		"0"
		//		"0"
		//		"4"
		"maxchars"		"-1"
	}
	"VSync"
	{
		"ControlName"		"ComboBox"
		"xpos"		"330"
		"ypos"		"196"
		"wide"		"132"
		"tall"		"24"
		//		"0"
		//		"0"
		//		"9"
		"maxchars"		"-1"
	}
	"ShaderDetail"
	{
		"ControlName"		"ComboBox"
		"xpos"		"330"
		"ypos"		"58"
		"wide"		"132"
		"tall"		"24"
		//		"0"
		//		"0"
		//		"3"
		"maxchars"		"-1"
	}
	"ColorCorrection"
	{
		"ControlName"		"ComboBox"
		"xpos"		"330"
		"ypos"		"118"
		"wide"		"132"
		"tall"		"24"
		//		"0"
		//		"0"
		//		"6"
		"maxchars"		"-1"
	}
	"MotionBlur"
	{
		"ControlName"		"ComboBox"
		"xpos"		"22"
		"ypos"		"258"
		"wide"		"132"
		"tall"		"24"
		//		"0"
		//		"0"
		//		"10"
		"maxchars"		"-1"
	}
	"Bloom"
	{
		"ControlName"		"CCvarToggleCheckButton"
		"xpos"		"170"
		"ypos"		"316"
		"wide"		"292"
		"tall"		"24"
		//		"0"
		//		"0"
		"visible"		"1" 
		//		"13"
		"labelText"		"#GameUI_Bloom"
	}
	"Motion Blur Label"
	{
		"ControlName"		"Label"
		"xpos"		"22"
		"ypos"		"232"
		"wide"		"138"
		"tall"		"24"
		//		"0"
		//		"0"
		//		"0"
		"labelText"		"#GameUI_MotionBlur"
		"associate"		"HDR"
	}
	"Button1"
	{
		"ControlName"		"Button"
		"xpos"		"290"
		"ypos"		"468" [!$OSX]
		"ypos"		"316" [$OSX]
		"wide"		"80"
		"tall"		"24"
		//		"0"
		//		"0"
		//		"16"
		"labelText"		"#GameUI_OK"
		"Command"		"OK"
		"Default"		"1"
	}
	"Button2"
	{
		"ControlName"		"Button"
		"xpos"		"382"
		"ypos"		"468" [!$OSX]
		"ypos"		"316" [$OSX]
		"wide"		"80"
		"tall"		"24"
		//		"0"
		//		"0"
		//		"17"
		"labelText"		"#GameUI_Cancel"
		"Command"		"Close"
	}
	"Label1"
	{
		"ControlName"		"Label"
		"xpos"		"22"
		"ypos"		"385"
		"wide"		"288"
		"tall"		"24"
		//		"0"
		//		"0"
		//		"0"
		"labelText"		"#GameUI_DX_Level"
		"textAlignment"		"east"
	}
	"Label2"
	{
		"ControlName"		"Label"
		"xpos"		"22"
		"ypos"		"360"
		"wide"		"288"
		"tall"		"24"
		//		"0"
		//		"0"
		//		"0"
		"labelText"		"#GameUI_DX_Installed"
		"textAlignment"		"east"
	}
	"Label3"
	{
		"ControlName"		"Label"
		"xpos"		"22"
		"ypos"		"34"
		"wide"		"112"
		"tall"		"24"
		//		"0"
		//		"0"
		//		"0"
		"labelText"		"#GameUI_Model_Detail"
		"associate"		"ModelDetail"
	}
	"Label4"
	{
		"ControlName"		"Label"
		"xpos"		"175"
		"ypos"		"34"
		"wide"		"124"
		"tall"		"24"
		//		"0"
		//		"0"
		//		"0"
		"labelText"		"#GameUI_Texture_Detail"
		"associate"		"TextureDetail"
	}
	"Label5"
	{
		"ControlName"		"Label"
		"xpos"		"22"
		"ypos"		"172"
		"wide"		"156"
		"tall"		"24"
		//		"0"
		//		"0"
		//		"0"
	}
	"Label6"
	{
		"ControlName"		"Label"
		"xpos"		"176"
		"ypos"		"172"
		"wide"		"152"
		"tall"		"24"
		//		"0"
		//		"0"
		//		"0"
		"labelText"		"#GameUI_Filtering_Mode"
		"associate"		"FilteringMode"
	}
	"dxinstalledlabel"
	{
		"ControlName"		"Label"
		"xpos"		"333"
		"ypos"		"360"
		"wide"		"130"
		"tall"		"24"
		//		"0"
		//		"0"
		//		"0"
		"labelText"		"DirectX v9.0"
	}
	"Divider1"
	{
		"ControlName"		"Divider"
		"xpos"		"22"
		"ypos"		"352"
		"wide"		"438"
		"tall"		"2"
		//		"0"
		//		"0"
		//		"0"
	}
	"Label7"
	{
		"ControlName"		"Label"
		"xpos"		"22"
		"ypos"		"94"
		"wide"		"132"
		"tall"		"24"
		//		"0"
		//		"0"
		//		"0"
		"labelText"		"#GameUI_Water_Detail"
		"associate"		"WaterDetail"
	}
	"Label8"
	{
		"ControlName"		"Label"
		"xpos"		"176"
		"ypos"		"94"
		"wide"		"132"
		"tall"		"24"
		//		"0"
		//		"0"
		//		"0"
		"labelText"		"#GameUI_Shadow_Detail"
		"associate"		"ShadowDetail"
	}
	"Label12"
	{
		"ControlName"		"Label"
		"xpos"		"330"
		"ypos"		"94"
		"wide"		"132"
		"tall"		"24"
		//		"0"
		//		"0"
		//		"0"
		"labelText"		"#GameUI_Color_Correction"
		"associate"		"ColorCorrection"
	}
	"Label10"
	{
		"ControlName"		"Label"
		"xpos"		"330"
		"ypos"		"172"
		"wide"		"154"
		"tall"		"24"
		//		"0"
		//		"0"
		//		"0"
		"labelText"		"#GameUI_Wait_For_VSync"
		"associate"		"VSync"
	}
	"Label9"
	{
		"ControlName"		"Label"
		"xpos"		"330"
		"ypos"		"34"
		"wide"		"132"
		"tall"		"24"
		//		"0"
		//		"0"
		//		"0"
		"labelText"		"#GameUI_Shader_Detail"
		"associate"		"ShaderDetail"
	}
	"Label11"
	{
		"ControlName"		"Label"
		"xpos"		"18"
		"ypos"		"442" [!$OSX]
		"ypos"		"310" [$OSX]
		"wide"		"280"
		"tall"		"24"
		//		"0"
		//		"0"
		//		"0"
		"labelText"		"#GameUI_RecommendedSettings"
	}
	"HDR Label"
	{
		"ControlName"		"Label"
		"xpos"		"22"
		"ypos"		"292"
		"wide"		"138"
		"tall"		"24"
		//		"0"
		//		"0"
		"visible"		"1" 
		//		"0"
		"labelText"		"#GameUI_HDR"
		"associate"		"HDR"
	}
	"Divider2"
	{
		"ControlName"		"Divider"
		"xpos"		"22"
		"ypos"		"160"
		"wide"		"438"
		"tall"		"2"
		//		"0"
		//		"0"
		//		"0"
	}
	"BuildModeDialog"
	{
		"ControlName"		"BuildModeDialog"
		"xpos"		"321"
		"ypos"		"648"
		"wide"		"300"
		"tall"		"420"
		//		"0"
		//		"0"
		//		"0"
		"title"		"#Frame_Untitled"
	}
	"FovSlider"
	{
		"ControlName"		"CCvarSlider"
		"xpos"		"176"
		"ypos"		"252"
		"wide"		"140"
		"tall"		"50"
		//		"0"
		//		"0"
		//		"11"
		"leftText"		"0.00"
		"rightText"		"1.00"
		"minvalue"		"75"
		"maxvalue"		"90"
		"cvar_name"		"fov_desired"
		"allowoutofrange"		"0"
	}
	"FOVLabel"
	{
		"ControlName"		"Label"
		"xpos"		"176"
		"ypos"		"232"
		"wide"		"168"
		"tall"		"24"
		//		"0"
		//		"0"
		//		"0"
		"labelText"		"#GameUI_FOV"
	}
	"MulticoreLabel"
	{
		"ControlName"		"Label"
		"xpos"		"330"
		"ypos"		"232"
		"wide"		"168"
		"tall"		"24"
		//		"0"
		//		"0"
		//		"0"
		"labelText"		"#GameUI_MulticoreRendering"
	}
	"Multicore"
	{
		"ControlName"		"ComboBox"
		"xpos"		"330"
		"ypos"		"258"
		"wide"		"132"
		"tall"		"24"
		//		"0"
		//		"0"
		//		"10"
		"maxchars"		"-1"
	}
}
