"Resource/OptionsSubKeyboard.res"
{
	"listpanel_keybindlist"
	{
		"ControlName"		"SectionedListPanel"
		"xpos"		"8"
		"ypos"		"10"
		"wide"		"480"
		"tall"		"258"
		//		"0"
		//		"0"
		//		"1"
	}
	"ChangeKeyButton"
	{
		"ControlName"		"Button"
		"xpos"		"272"
		"ypos"		"276"
		"wide"		"106"
		"tall"		"24"
		//		"0"
		//		"0"
		//		"4"
		"labelText"		"#GameUI_SetNewKey"
		"Command"		"ChangeKey"
	}
	"ClearKeyButton"
	{
		"ControlName"		"Button"
		"xpos"		"384"
		"ypos"		"276"
		"wide"		"105"
		"tall"		"24"
		//		"0"
		//		"0"
		//		"5"
		"labelText"		"#GameUI_ClearKey"
		"Command"		"ClearKey"
	}
	"Defaults"
	{
		"ControlName"		"Button"
		"xpos"		"8"
		"ypos"		"276"
		"wide"		"134"
		"tall"		"24"
		//		"0"
		//		"0"
		//		"2"
		"labelText"		"#GameUI_UseDefaults"
		"Command"		"Defaults"
	}
	"KeyAdvancedButton"
	{
		"ControlName"		"Button"
		"xpos"		"148"
		"ypos"		"276"
		"wide"		"111"
		"tall"		"24"
		//		"0"
		//		"0"
		//		"3"
		"labelText"		"#GameUI_AdvancedEllipsis"
		"Command"		"Advanced"
		"Default"		"1"
	}
}
