"Resource\SaveGameDialog.res"
{
	"SaveGameDialog"
	{
		"ControlName"		"CSaveGameDialog"
		"fieldName"		"SaveGameDialog"
		"xpos"		"512"
		"ypos"		"107"
		"wide"		"480"
		"tall"		"460"
		//		"0"
		//		"0"
		"visible"		"1"
		"enabled"		"1"
		//		"0"
		"settitlebarvisible"		"1"
		"title"		"#GameUI_SaveGame"
	}
	"listpanel_loadgame"
	{
		"ControlName"		"PanelListPanel"
		"fieldName"		"listpanel_loadgame"
		"xpos"		"20"
		"ypos"		"72"
		"wide"		"444"
		"tall"		"344"
		//		"3"
		//		"0"
		"visible"		"1"
		"enabled"		"1"
		//		"1"
	}
	"LoadSave"
	{
		"ControlName"		"Button"
		"fieldName"		"LoadSave"
		"xpos"		"282"
		"ypos"		"422"
		"wide"		"82"
		"tall"		"24"
		//		"0"
		//		"3"
		"visible"		"1"
		//		"2"
		"labelText"		"#GameUI_Save"
		"Command"		"loadsave"
		"Default"		"1"
	}
	"Cancel"
	{
		"ControlName"		"Button"
		"fieldName"		"Cancel"
		"xpos"		"376"
		"ypos"		"422"
		"wide"		"64"
		"tall"		"24"
		//		"0"
		//		"3"
		"visible"		"1"
		"enabled"		"1"
		//		"3"
		"labelText"		"#GameUI_Cancel"
		"Command"		"Close"
	}
	"HelpText"
	{
		"ControlName"		"Label"
		"fieldName"		"HelpText"
		"xpos"		"20"
		"ypos"		"28"
		"wide"		"426"
		"tall"		"44"
		//		"0"
		//		"0"
		"visible"		"1"
		"enabled"		"1"
		//		"0"
		"labelText"		"#GameUI_SaveGameHelp"
		"wrap"		"1"
	}
}
