"resource/setclipnamedialog.res"
{
	"SetClipNameDialog"
	{
		"ControlName"		"CSetClipNameDialog"
		"fieldName"		"SetClipNameDialog"
		"xpos"		"650"
		"ypos"		"390"
		"wide"		"450"
		"tall"		"180"
		//		"0"
		//		"0"
		"visible"		"1"
		"enabled"		"1"
		//		"0"
		"settitlebarvisible"		"1"
		"title"		"Set Clip Name"
	}
	"OkButton"
	{
		"ControlName"		"Button"
		"fieldName"		"OkButton"
		"xpos"		"88"
		"ypos"		"140"
		"wide"		"64"
		"tall"		"24"
		//		"0"
		//		"0"
		"visible"		"1"
		"enabled"		"1"
		//		"6"
		"labelText"		"#vgui_ok"
		"Command"		"Ok"
		"Default"		"1"
	}
	"CancelButton"
	{
		"ControlName"		"Button"
		"fieldName"		"CancelButton"
		"xpos"		"279"
		"ypos"		"140"
		"wide"		"64"
		"tall"		"24"
		//		"0"
		//		"0"
		"visible"		"1"
		"enabled"		"1"
		//		"7"
		"labelText"		"#vgui_Cancel"
		"Command"		"Cancel"
	}
	"ClipNameLabel"
	{
		"ControlName"		"Label"
		"fieldName"		"ClipNameLabel"
		"xpos"		"10"
		"ypos"		"43"
		"wide"		"90"
		"tall"		"24"
		//		"0"
		//		"0"
		"visible"		"1"
		"enabled"		"1"
		//		"0"
		"labelText"		"New Clip Name:"
		"textAlignment"		"east"
	}
	"ClipName"
	{
		"ControlName"		"TextEntry"
		"fieldName"		"ClipName"
		"xpos"		"107"
		"ypos"		"44"
		"wide"		"320"
		"tall"		"24"
		//		"0"
		//		"0"
		"visible"		"1"
		"enabled"		"1"
		//		"1"
		"editable"		"1"
		"maxchars"		"-1"
	}
	"RenumberClips"
	{
		"ControlName"		"CheckButton"
		"fieldName"		"RenumberClips"
		"xpos"		"99"
		"ypos"		"74"
		"wide"		"120"
		"tall"		"24"
		//		"0"
		//		"0"
		"visible"		"1"
		"enabled"		"1"
		"selected"		"1"
		//		"0"
		"labelText"		"Renumber Clips"
	}
	"FirstNumber"
	{
		"ControlName"		"TextEntry"
		"fieldName"		"FirstNumber"
		"xpos"		"54"
		"ypos"		"105"
		"wide"		"64"
		"tall"		"24"
		//		"0"
		//		"0"
		"visible"		"1"
		"enabled"		"1"
		//		"3"
		"editable"		"1"
		"maxchars"		"-1"
		"NumericInputOnly"		"1"
	}
	"Increment"
	{
		"ControlName"		"TextEntry"
		"fieldName"		"Increment"
		"xpos"		"198"
		"ypos"		"105"
		"wide"		"64"
		"tall"		"24"
		//		"0"
		//		"0"
		"visible"		"1"
		"enabled"		"1"
		//		"4"
		"editable"		"1"
		"maxchars"		"-1"
		"NumericInputOnly"		"1"
	}
	"NumDigits"
	{
		"ControlName"		"TextEntry"
		"fieldName"		"NumDigits"
		"xpos"		"344"
		"ypos"		"105"
		"wide"		"64"
		"tall"		"24"
		//		"0"
		//		"0"
		"visible"		"1"
		"enabled"		"1"
		//		"5"
		"editable"		"1"
		"maxchars"		"-1"
		"NumericInputOnly"		"1"
	}
	"FirstNumberLabel"
	{
		"ControlName"		"Label"
		"fieldName"		"FirstNumberLabel"
		"xpos"		"10"
		"ypos"		"105"
		"wide"		"40"
		"tall"		"24"
		//		"0"
		//		"0"
		"visible"		"1"
		"enabled"		"1"
		//		"0"
		"labelText"		"First:"
		"textAlignment"		"east"
	}
	"IncrementLabel"
	{
		"ControlName"		"Label"
		"fieldName"		"IncrementLabel"
		"xpos"		"124"
		"ypos"		"105"
		"wide"		"64"
		"tall"		"24"
		//		"0"
		//		"0"
		"visible"		"1"
		"enabled"		"1"
		//		"0"
		"labelText"		"Increment:"
		"textAlignment"		"east"
	}
	"NumDigitsLabel"
	{
		"ControlName"		"Label"
		"fieldName"		"NumDigitsLabel"
		"xpos"		"273"
		"ypos"		"105"
		"wide"		"64"
		"tall"		"24"
		//		"0"
		//		"0"
		"visible"		"1"
		"enabled"		"1"
		//		"0"
		"labelText"		"Num Digits:"
		"textAlignment"		"east"
	}
}
