"Resource\VProfPanel.res"
{
	"VProfPanel"
	{
		"ControlName"		"CVProfPanel"
		"fieldName"		"VProfPanel"
		"xpos"		"335"
		"ypos"		"18"
		"zpos"		"1002"
		"wide"		"1215"
		"tall"		"864"
		//		"0"
		//		"0"
		"visible"		"1"
		"enabled"		"1"
		//		"0"
		"settitlebarvisible"		"1"
		"title"		"VProf (running) --  8103 frames sampled"
	}
	"ProfileTree"
	{
		"ControlName"		"CProfileTree"
		"fieldName"		"ProfileTree"
		"xpos"		"1"
		"ypos"		"17"
		"wide"		"387"
		"tall"		"777"
		//		"0"
		//		"0"
		"visible"		"1"
		"enabled"		"1"
		//		"0"
	}
	"Hierarchy"
	{
		"ControlName"		"CProfileHierarchyPanel"
		"fieldName"		"Hierarchy"
		"xpos"		"10"
		"ypos"		"60"
		"wide"		"1195"
		"tall"		"794"
		//		"3"
		//		"0"
		"visible"		"1"
		"enabled"		"1"
		//		"0"
	}
	"CategoryCombo"
	{
		"ControlName"		"ComboBox"
		"fieldName"		"CategoryCombo"
		"xpos"		"100"
		"ypos"		"30"
		"wide"		"230"
		"tall"		"24"
		//		"0"
		//		"0"
		"visible"		"1"
		"enabled"		"1"
		//		"0"
		"maxchars"		"-1"
	}
	"SortCombo"
	{
		"ControlName"		"ComboBox"
		"fieldName"		"SortCombo"
		"xpos"		"737"
		"ypos"		"30"
		"wide"		"149"
		"tall"		"24"
		//		"0"
		//		"0"
		"visible"		"1"
		"enabled"		"1"
		//		"0"
		"maxchars"		"-1"
	}
	"HierarchicalViewSelection"
	{
		"ControlName"		"CheckButton"
		"fieldName"		"HierarchicalViewSelection"
		"xpos"		"475"
		"ypos"		"30"
		"wide"		"151"
		"tall"		"24"
		//		"0"
		//		"0"
		"visible"		"1"
		"enabled"		"1"
		//		"0"
		"labelText"		"Hierarchical View"
	}
	"RedoSorting"
	{
		"ControlName"		"Button"
		"fieldName"		"RedoSorting"
		"xpos"		"629"
		"ypos"		"30"
		"wide"		"105"
		"tall"		"24"
		//		"0"
		//		"0"
		"visible"		"1"
		"enabled"		"1"
		//		"0"
		"labelText"		"Redo Sorting"
		"Command"		"redosort"
		"Default"		"1"
	}
	"VerboseCheckbox"
	{
		"ControlName"		"CheckButton"
		"fieldName"		"VerboseCheckbox"
		"xpos"		"337"
		"ypos"		"30"
		"wide"		"135"
		"tall"		"24"
		//		"0"
		//		"0"
		"visible"		"1"
		"enabled"		"1"
		//		"0"
		"labelText"		"Verbose"
	}
	"PlaybackLabel"
	{
		"ControlName"		"Label"
		"fieldName"		"PlaybackLabel"
		"xpos"		"10"
		"ypos"		"65"
		"wide"		"200"
		"tall"		"24"
		//		"0"
		//		"0"
		"visible"		"0"
		"enabled"		"1"
		//		"0"
		"labelText"		"Playback (tick 0)"
	}
	"StepForward"
	{
		"ControlName"		"Button"
		"fieldName"		"StepForward"
		"xpos"		"220"
		"ypos"		"65"
		"wide"		"80"
		"tall"		"24"
		//		"0"
		//		"0"
		"visible"		"0"
		"enabled"		"1"
		//		"0"
		"labelText"		"Forward"
		"textAlignment"		"center"
		"Command"		"StepForward"
	}
	"StepBack"
	{
		"ControlName"		"Button"
		"fieldName"		"StepBack"
		"xpos"		"310"
		"ypos"		"65"
		"wide"		"80"
		"tall"		"24"
		//		"0"
		//		"0"
		"visible"		"0"
		"enabled"		"1"
		//		"0"
		"labelText"		"Back"
		"textAlignment"		"center"
		"Command"		"StepBack"
	}
	"GotoButton"
	{
		"ControlName"		"Button"
		"fieldName"		"GotoButton"
		"xpos"		"620"
		"ypos"		"65"
		"wide"		"80"
		"tall"		"24"
		//		"0"
		//		"0"
		"visible"		"0"
		"enabled"		"1"
		//		"0"
		"labelText"		"<-- goto"
		"textAlignment"		"center"
		"Command"		"GotoButton"
	}
	"PlaybackScroll"
	{
		"ControlName"		"ScrollBar"
		"fieldName"		"PlaybackScroll"
		"xpos"		"400"
		"ypos"		"65"
		"wide"		"200"
		"tall"		"24"
		//		"0"
		//		"0"
		"visible"		"0"
		"enabled"		"1"
		//		"0"
	}
	"CategoryLabel"
	{
		"ControlName"		"Label"
		"fieldName"		"CategoryLabel"
		"xpos"		"10"
		"ypos"		"30"
		"wide"		"80"
		"tall"		"24"
		//		"0"
		//		"0"
		"visible"		"1"
		"enabled"		"1"
		//		"0"
		"labelText"		"Category :"
		"textAlignment"		"east"
	}
}
