#base "../#uni_base/filesv1/button2/main.res"
#base "../#uni_base/filesv1/button2/wide_80.res"
#base "../#uni_base/filesv1/button2/tab/is-1.res"
#base "../#uni_base/filesv1/button2/label/gameui-close.res"
#base "../#uni_base/filesv1/button2/def/is-1.res"
#base "../#uni_base/filesv1/button2/def/command-close.res"