"Resource/baseaction_sys.res"
{
"ItemEffectMeterCount"
{
"ControlName""CExLabel"
"fieldName""ItemEffectMeterCount"
//"xpos""15"
//"ypos""14"
"zpos""2"
"wide""40"
"tall""20"
//"pinCorner""2"
"visible""1"
"enabled""1"
"tabPosition""0"
"labelText""%progresscount%"
"textAlignment""north"
"dulltext""0"
"brighttext""0"
"font""HudFontMedium"
}
}
