#base "confirmdialog_base.res"
"x" 	//new panel since ConfirmDialog cannot be moved.
{		
	"bgpanel2" 	//new panel since ConfirmDialog cannot be moved.
	{			//this meanwhile can be moved and everything tied to this
				
		"ControlName"	"EditablePanel"
		"fieldName"		"bgpanel2"
		"xpos"			"0"
		"ypos"			"100"
		"wide"			"p0.4"
		zpos 1000
		"tall"			"200"
		"autoResize"	"0"
		"pinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"0"
		"settitlebarvisible"	"0"
		"PaintBackgroundType"	"2"
		"paintbackground"		"1"
		"bgcolor_override"	"40 40 45 100"
		"keyboardinputenabled" "0"
		
		"top_line"
		{
			"ControlName"	"EditablePanel"
			"fieldname"		"top_line"
			"xpos"			"2"
			"ypos"			"0"
			"zpos"			"100"
			"wide"			"f3"
			"tall"			"1"
			"visible"		"1"	
			"PaintBackgroundType"	"0"
			"proportionaltoparent"	"1"
			"mouseinputenabled"	"0"
			"bgcolor_override"	"Orange"
		}
		
		"Settings_Label"
		{
			"ControlName"	"CExLabel"
			"fieldName"		"Settings_Label"
			"font"			"notobold10"
			"labelText"		"HUD:"
			"textAlignment"	"west"
			"xpos"			"7"
			"ypos"			"3"
			"zpos"			"115"
			"wide"			"300"
			"tall"			"12"
			"fgcolor"		"247 128 41 255"
			"auto_wide_tocontents" "1"
		}
		
		"PLHDR1"
		{
			"ControlName"	"CExButton"
			"fieldName"		"PLHDR1"
			"xpos"			"2"
			"ypos"			"0"
			"zpos"			"20"
			"wide"			"50"
			"tall"			"14"
			"autoResize"	"0"
			"pinCorner"		"0"
			"visible"		"1"
			"enabled"		"1"
			"tabPosition"	"0"
			"labelText"		"STREAM: OFF"
			"font"			"noto10"
			"textAlignment"	"center"
			"textinsetx"	"0"
			"dulltext"		"0"
			"brighttext"	"0"
			"Command"		"engine streamermodeoff"
			"actionsignallevel" "3"
			"sound_depressed"			"UI/buttonclick.wav"
			"sound_released"			"UI/buttonclickrelease.wav"
			"defaultFgColor_override" "244 232 198 255"
			"armedFgColor_override" "244 232 198 255"
			"depressedFgColor_override" "40 40 45 255"
			"armedBgColor_override"	"Orange"
			"pin_to_sibling" "Settings_Label"
			"pin_corner_to_sibling"					"PIN_TOPLEFT"
			"pin_to_sibling_corner"					"PIN_TOPRIGHT"					
			"image_drawcolor"	"235 226 202 255"
			"image_armedcolor"	"235 226 202 255"
		}
		"PLHDR2"
		{
			"ControlName"	"CExButton"
			"fieldName"		"PLHDR2"
			"xpos"			"2"
			"ypos"			"0"
			"zpos"			"20"
			"wide"			"50"
			"tall"			"14"
			"autoResize"	"0"
			"pinCorner"		"0"
			"visible"		"1"
			"enabled"		"1"
			"tabPosition"	"0"
			"labelText"		"STREAM: ON"
			"font"			"noto10"
			"textAlignment"	"center"
			"textinsetx"	"0"
			"dulltext"		"0"
			"brighttext"	"0"
			"Command"		"engine streamermodeon"
			"actionsignallevel" "3"
			"sound_depressed"			"UI/buttonclick.wav"
			"sound_released"			"UI/buttonclickrelease.wav"
			"defaultFgColor_override" "244 232 198 255"
			"armedFgColor_override" "244 232 198 255"
			"depressedFgColor_override" "40 40 45 255"
			"armedBgColor_override"	"Orange"
			"pin_to_sibling" "PLHDR1"
			"pin_corner_to_sibling"					"PIN_TOPLEFT"
			"pin_to_sibling_corner"					"PIN_TOPRIGHT"					
			"image_drawcolor"	"235 226 202 255"
			"image_armedcolor"	"235 226 202 255"
		}	
		"PLHDR3"
		{
			"ControlName"	"CExButton"
			"fieldName"		"PLHDR3"
			"xpos"			"2"
			"ypos"			"0"
			"zpos"			"20"
			"wide"			"80"
			"tall"			"14"
			"autoResize"	"0"
			"pinCorner"		"0"
			"visible"		"1"
			"enabled"		"1"
			"tabPosition"	"0"
			"labelText"		"Open QuickPlay Menu"
			"font"			"noto10"
			"textAlignment"	"center"
			"textinsetx"	"0"
			"dulltext"		"0"
			"brighttext"	"0"
			"Command"		"engine replay_reloadbrowser"
			"actionsignallevel" "3"
			"sound_depressed"			"UI/buttonclick.wav"
			"sound_released"			"UI/buttonclickrelease.wav"
			"defaultFgColor_override" "244 232 198 255"
			"armedFgColor_override" "244 232 198 255"
			"depressedFgColor_override" "40 40 45 255"
			"armedBgColor_override"	"Orange"
			"pin_to_sibling" "PLHDR2"
			"pin_corner_to_sibling"					"PIN_TOPLEFT"
			"pin_to_sibling_corner"					"PIN_TOPRIGHT"					
			"image_drawcolor"	"235 226 202 255"
			"image_armedcolor"	"235 226 202 255"
		}	        
		"reloadthisshit"
		{
			"ControlName"	"CExButton"
			"fieldName"		"reloadthisshit"
			"xpos"			"328"
			"ypos"			"0"
			"zpos"			"20"
			"wide"			"12"
			"tall"			"16"
			"visible"		"1"
			"enabled"		"1"
			"labelText"		"Ñ"
			"font"			"newicons12"
			"textAlignment"	"center"
			"textinsety" "5"
			"Command"		"engine dev_r"
			"actionsignallevel" "3"
			"sound_depressed"			"UI/buttonclick.wav"
			"sound_released"			"UI/buttonclickrelease.wav"
			"defaultFgColor_override" "244 232 198 255"
			"armedFgColor_override" "244 232 198 255"
			"depressedFgColor_override" "40 40 45 255"
			"armedBgColor_override"	"Orange"				
			"image_drawcolor"	"235 226 202 255"
			"image_armedcolor"	"235 226 202 255"
		}		
	}	
}	
