"Resource/EngineVGuiLayout.res"
{
"HowToUseCommentary"
{
"ControlName""Label"
"fieldName""HowToUseCommentary"
//"autoResize""0"
//"pinCorner""0"
"visible""1"
////"enabled""1"
"tabPosition""0"
"textAlignment""west"
//"dulltext""0"
//"brighttext""0"
"wrap""1"
}
}