#base "../base/filesv2/caratlabel/main.res"
#base "../base/filesv2/caratlabel/wide20.res"
#base "../base/filesv2/caratlabel/auto1.res"
#base "../base/filesv2/caratlabel/zpos1.res"
#base "../base/filesv2/caratlabel/xpos_c.res"
#base "../base/filesv2/caratlabel/ypos20.res"
#base "../base/filesv2/caratlabel/vis1.res"
#base "../base/filesv2/caratlabel/fgcolor_200.res"
#base "../base/filesv2/caratlabel/font/hudfontsmallest.res"

#base "../base/filesv2/classlabel/main.res"
#base "../base/filesv2/classlabel/cex.res"
#base "../base/filesv2/classlabel/font/mediumsmallbold.res"
#base "../base/filesv2/classlabel/text/west.res"
#base "../base/filesv2/classlabel/zpos1.res"
#base "../base/filesv2/classlabel/tall25.res"
#base "../base/filesv2/classlabel/content1.res"
#base "../base/filesv2/classlabel/vis1.res"

#base "../base/filesv1/backpack_panel/main.res"

#base "../base/filesv2/showexplanationbtn/main.res"
#base "../base/filesv2/showexplanationbtn/def0.res"
#base "../base/filesv2/showexplanationbtn/hudfontsmallbold.res"
#base "../base/filesv2/showexplanationbtn/zpos100.res"
#base "../base/filesv2/showexplanationbtn/wt20.res"