#base "base/mouseoveritem/content1.res"
#base "../../../#uni_base/filesv1/okbutton/ctrl/cex.res"
#base "../../../#uni_base/filesv1/okbutton/main.res"
#base "../../../#uni_base/filesv1/okbutton/position/wide130.res"
#base "../../../#uni_base/filesv1/okbutton/position/tall25.res"
#base "../../../#uni_base/filesv1/okbutton/auto.res"
#base "../../../#uni_base/filesv1/okbutton/zpos1.res"
#base "../../../#uni_base/filesv1/okbutton/vis1.res"
#base "../../../#uni_base/filesv1/okbutton/enabled.res"
#base "../../../#uni_base/filesv1/okbutton/tab0.res"
#base "../../../#uni_base/filesv1/okbutton/cmd/apply.res"
#base "../../../#uni_base/filesv1/okbutton/text/center.res"
#base "../../../#uni_base/filesv1/okbutton/label/craftnameconfirm.res"
#base "../../../#uni_base/filesv1/okbutton/def1.res"
#base "../../../#uni_base/filesv1/okbutton/dull0.res"
#base "../../../#uni_base/filesv1/okbutton/bright0.res"
#base "../../../#uni_base/filesv1/okbutton/sound.res"

#base "../../../#uni_base/filesv1/okbutton/font/hudfontsmallbold.res"
#base "../../../#uni_base/filesv1/okbutton/position/xpos220.res"
#base "../../../#uni_base/filesv1/okbutton/position/ypos200.res"

#base "../base/filesv1/confirmlabel/main.res"
#base "../base/filesv1/confirmlabel/position/tall20.res"
#base "../base/filesv1/confirmlabel/position/ypos80.res"


#base "base/subject_bg_icon/main.res"

#base "../../../#uni_base/filesv1/cancelbutton/ctrl/cex.res"
#base "../../../#uni_base/filesv1/cancelbutton/main.res"
#base "../../../#uni_base/filesv1/cancelbutton/position/x50.res"
#base "../../../#uni_base/filesv1/cancelbutton/position/ypos200.res"
#base "../../../#uni_base/filesv1/cancelbutton/position/zpos1.res"
#base "../../../#uni_base/filesv1/cancelbutton/position/w130.res"
#base "../../../#uni_base/filesv1/cancelbutton/position/t25.res"
#base "../../../#uni_base/filesv1/cancelbutton/pin3.res"
#base "../../../#uni_base/filesv1/cancelbutton/auto.res"
#base "../../../#uni_base/filesv1/cancelbutton/vis1.res"
#base "../../../#uni_base/filesv1/cancelbutton/enabled.res"
#base "../../../#uni_base/filesv1/cancelbutton/tab0.res"
#base "../../../#uni_base/filesv1/cancelbutton/label/cancel.res"
#base "../../../#uni_base/filesv1/cancelbutton/text/center.res"
#base "../../../#uni_base/filesv1/cancelbutton/dull0.res"
#base "../../../#uni_base/filesv1/cancelbutton/bright0.res"
#base "../../../#uni_base/filesv1/cancelbutton/def0.res"
#base "../../../#uni_base/filesv1/cancelbutton/cmd/cancel.res"
#base "../../../#uni_base/filesv1/cancelbutton/sound.res"
#base "../../../#uni_base/filesv1/cancelbutton/font/hudfontsmallbold.res"