#base "base/mouseoveritem/content1.res"
#base "../../../#uni_base/filesv1/okbutton/ctrl/cex.res"
#base "../../../#uni_base/filesv1/okbutton/main.res"
#base "../../../#uni_base/filesv1/okbutton/position/wide130.res"
#base "../../../#uni_base/filesv1/okbutton/position/tall25.res"
#base "../../../#uni_base/filesv1/okbutton/auto.res"
#base "../../../#uni_base/filesv1/okbutton/zpos1.res"
#base "../../../#uni_base/filesv1/okbutton/vis1.res"
#base "../../../#uni_base/filesv1/okbutton/enabled.res"
#base "../../../#uni_base/filesv1/okbutton/tab0.res"
#base "../../../#uni_base/filesv1/okbutton/cmd/apply.res"
#base "../../../#uni_base/filesv1/okbutton/text/center.res"
#base "../../../#uni_base/filesv1/okbutton/label/craftnameconfirm.res"
#base "../../../#uni_base/filesv1/okbutton/def1.res"
#base "../../../#uni_base/filesv1/okbutton/dull0.res"
#base "../../../#uni_base/filesv1/okbutton/bright0.res"
#base "../../../#uni_base/filesv1/okbutton/sound.res"

#base "../../../#uni_base/filesv1/okbutton/font/hudfontsmallbold.res"
#base "../../../#uni_base/filesv1/okbutton/position/xpos220.res"
#base "../../../#uni_base/filesv1/okbutton/position/ypos200.res"

#base "../base/filesv1/confirmlabel/main.res"
#base "../base/filesv1/confirmlabel/position/tall120.res"
#base "../base/filesv1/confirmlabel/position/ypos80.res"