#base "../base/filesv1/notifipresentpanel/main.res"
#base "../base/filesv1/notifipresentpanel/content1.res"
#base "../../../#uni_base/filesv3/acceptbutton/main.res"
#base "../../../#uni_base/filesv3/acceptbutton/font.res"
#base "../../../#uni_base/filesv3/acceptbutton/center.res"
#base "../../../#uni_base/filesv3/acceptbutton/sound.res"