#base "../../../#uni_base/filesv1/hudchathistory/main.res"
#base "../base/filesv1/armory_panel/main.res"

#base "../base/filesv2/headerline/main.res"
#base "../base/filesv2/headerline/zpos_5.res"
#base "../base/filesv2/headerline/image1.res"

#base "../base/filesv2/caratlabel/main.res"
#base "../base/filesv2/caratlabel/wide20.res"
#base "../base/filesv2/caratlabel/auto1.res"
#base "../base/filesv2/caratlabel/zpos1.res"
#base "../base/filesv2/caratlabel/xpos_c.res"
#base "../base/filesv2/caratlabel/ypos20.res"
#base "../base/filesv2/caratlabel/vis1.res"
#base "../base/filesv2/caratlabel/fgcolor_200.res"

	#base "../base/filesv1/backbutton/main.res"
	#base "../base/filesv1/backbutton/def1.res"
	#base "../base/filesv1/backbutton/content1.res"
	#base "../base/filesv1/backbutton/main.res"
	#base "../base/filesv1/backbutton/pin0.res"


#base "../../../#uni_base/filesv1/titlelabel/controlname/cex.res"
#base "../../../#uni_base/filesv1/titlelabel/main.res"
#base "../../../#uni_base/filesv1/titlelabel/text/west.res"
#base "../../../#uni_base/filesv1/titlelabel/auto.res"
#base "../../../#uni_base/filesv1/titlelabel/pin.res"
#base "../../../#uni_base/filesv1/titlelabel/vis1.res"
#base "../../../#uni_base/filesv1/titlelabel/enabled.res"

#base "../../../#uni_base/filesv3/confirmbutton/ctrl/cex.res"
#base "../../../#uni_base/filesv3/confirmbutton/main.res"
#base "../../../#uni_base/filesv3/confirmbutton/position/tall40.res"
#base "../../../#uni_base/filesv3/confirmbutton/auto.res"
#base "../../../#uni_base/filesv3/confirmbutton/pin.res"
#base "../../../#uni_base/filesv3/confirmbutton/vis1.res"
#base "../../../#uni_base/filesv3/confirmbutton/enabled0.res"
#base "../../../#uni_base/filesv3/confirmbutton/tab.res"
#base "../../../#uni_base/filesv3/confirmbutton/text/center.res"
#base "../../../#uni_base/filesv3/confirmbutton/dull0.res"
#base "../../../#uni_base/filesv3/confirmbutton/bright0.res"
#base "../../../#uni_base/filesv3/confirmbutton/sound.res"