#base "../base/filesv1/playerlistscroller/main.res"
#base "../base/filesv1/playerlistscroller/yp_80.res"

#base "../res_base/selectplayer/cancelbtn/content_a.res"

#base "../../../#uni_base/filesv1/titlelabel/controlname/cex.res"
#base "../../../#uni_base/filesv1/titlelabel/main.res"
#base "../../../#uni_base/filesv1/titlelabel/text/north.res"
#base "../../../#uni_base/filesv1/titlelabel/auto.res"
#base "../../../#uni_base/filesv1/titlelabel/pin.res"
#base "../../../#uni_base/filesv1/titlelabel/vis1.res"
#base "../../../#uni_base/filesv1/titlelabel/enabled.res"

#base "../../../#uni_base/filesv1/cancelbutton/ctrl/cex.res"
#base "../../../#uni_base/filesv1/cancelbutton/main.res"
#base "../../../#uni_base/filesv1/cancelbutton/position/x150.res"
#base "../../../#uni_base/filesv1/cancelbutton/position/y250.res"
#base "../../../#uni_base/filesv1/cancelbutton/position/zpos1.res"
#base "../../../#uni_base/filesv1/cancelbutton/position/w100.res"
#base "../../../#uni_base/filesv1/cancelbutton/position/t25.res"
#base "../../../#uni_base/filesv1/cancelbutton/pin3.res"
#base "../../../#uni_base/filesv1/cancelbutton/auto.res"
#base "../../../#uni_base/filesv1/cancelbutton/vis1.res"
#base "../../../#uni_base/filesv1/cancelbutton/enabled.res"
#base "../../../#uni_base/filesv1/cancelbutton/tab0.res"
#base "../../../#uni_base/filesv1/cancelbutton/text/center.res"
#base "../../../#uni_base/filesv1/cancelbutton/dull0.res"
#base "../../../#uni_base/filesv1/cancelbutton/bright0.res"
#base "../../../#uni_base/filesv1/cancelbutton/def1.res"
#base "../../../#uni_base/filesv1/cancelbutton/cmd/cancel.res"
#base "../../../#uni_base/filesv1/cancelbutton/sound.res"
#base "../../../#uni_base/filesv1/cancelbutton/font/hudfontsmallbold.res"
#base "../../../#uni_base/filesv1/cancelbutton/label/cancel.res"
